### ISSUE TITLE
Max request time shown is 10s

### ISSUE THREAD

**Issue by jaygorrell** [kiali/kiali#1021]
**Describe the bug**
Out of the box, Kiali shows 10s for all requests over 10s on both the service/workload graphs as well as the edge labels.

**Versions used**
Kiali: v0.14
Istio: 1.1.3
Kubernetes flavour and version: AWS/Kops 1.11.8

**To Reproduce**
1. Deploy a service that takes 15s or longer to respond
2. Make requests to that service
3. See that Kiali shows exactly 10s as the maximum request time

**Expected behavior**
Kiali shows accurate timeouts by default for slow responding services.

**Comment by jaygorrell** [comment]
Related issue https://github.com/istio/istio/issues/13421

**Comment by jmazzitelli** [comment]
@jaygorrell we'll probably need to see the telemetry data in your Prometheus. Kiali's graph shows what is in your telemetry, so we need to see what the telemetry says.

I assume these are http requests - so capture the **istio_requests_total** timeseries data in Promtheus - [see this doc page for details](https://istio.io/docs/tasks/telemetry/metrics/querying-metrics/).

@jshaughn will probably ask you to run some Prom queries on this data - he knows what's going on under the covers when the response times are reported in the graph and what Prom queries Kiali performs to calculate them.

**Comment by jaygorrell** [comment]
Thanks @jmazzitelli -- apologies for my ignorance but I haven't played with Prometheus enough to know my way around the queries. I did some searches on `istio_requests_total` but I don't see anything in the data that indicates a duration of any kind... just response codes.

I'm not sure if it's the right thing but if I do `istio_request_duration_seconds_count` on a service I know takes a while, I get 6 results (calling pods) with these values, which looks like what I'd expect for the durations. 
![image](https://user-images.githubusercontent.com/12174604/56429051-856efe80-628f-11e9-9f1e-e3d6f81ebed6.png)

**Comment by jshaughn** [comment]
@jaygorrell You are on the right track.  Response time information does not come from istio_requests_total but rather istio_request_duration_seconds_bucket.  @jmazzitelli Is right, though, in that Kiali is basically reporting on the telemetry supplied by Istio, so if the response times don't look right then it could be a problem in Kiali or in the original telemetry.   Note that when you select response time as your edge label we are showing 95th percentile (95% of the requests fall at or below this response time for the current time period selected).  Note that to see more response time percentiles you can select the edge and then look at the side panel.  There you can find a chart offering more information.  Let us know if you think the values are wrong, or if perhaps confusion about the percentile values.

This is the sort of query we perform to get the 95th percentile (i.e. quantile).  Note that below I use a 60s duration (i.e. time period last minute) and we only use successful responses when calculating response times. You need to replace YOUR_NAMESPACE with the relevant namespace/project:

histogram_quantile(0.95, sum(rate( istio_request_duration_seconds_bucket{reporter="source",source_workload_namespace="YOUR_NAMESPACE",response_code=~"2[0-9]{2}|^0$"}[60s])) by (le,source_workload_namespace,source_workload,source_app,source_version,destination_service_namespace,destination_service_name,destination_workload_namespace,destination_workload,destination_app,destination_version))

**Comment by jaygorrell** [comment]
Thanks @jshaughn -- that definitely replicates the issue. Also see my edit above.

Here are the results with that query:
![image](https://user-images.githubusercontent.com/12174604/56430679-1694a400-6295-11e9-9d7c-40c9cb80f297.png)

It seems the `le` bucket caps out at 10s too, even though `istio_request_duration_seconds_count` goes up to 60+ seconds.

**Comment by jmazzitelli** [comment]
> It seems the `le` bucket caps out at 10s too, even though `istio_request_duration_seconds_count` goes up to 60+ seconds.

It's been a while since I looked at the histrogram stuff, but I think "le" are the buckets (data less than 1.0 is in the "le=1.0" timeseries, etc). See where the "le" attribute is discussed in this page: https://prometheus.io/docs/practices/histograms

Some of this is coming back to me - IIRC, depending on how the metrics are collected (what the buckets are), you won't know the actual values past some "high water mark". I suspect this all is correct - Kiali, Istio, and Prometheus. Need to research again how histograms are collected, stored, and reported... but this all is starting to sound familiar to me. Look at the historgram data - if the largest value in the "le" attribute is "10" then I believe that means Prometheus won't know about any data larger than 10. I think the point is, if its larger than 10 (the high water mark for this timeseries), then it really doesn't matter if its 11, 15, 20 or 100 - its "abnormally big" for the context of this timeseries (http requests) and should be alerted on or considered out of bounds.

**Comment by jaygorrell** [comment]
Here's one more screenshot if it helps clarify things
![image](https://user-images.githubusercontent.com/12174604/56432669-45624880-629c-11e9-9508-814e26239182.png)

If this is intended I may look into a differently scoped issue on Prometheus. 10s ceilings isn't a one-size-fits-all good value... I agree it's great in most cases, but there are plenty of situations where 30+ seconds is normal but you still want to know if things go over 120 seconds for example.

**Comment by jmazzitelli** [comment]
> 10s ceilings isn't a one-size-fits-all good value... I agree it's great in most cases, but there are plenty of situations where 30+ seconds is normal but you still want to know if things go over 120 seconds for example.

This was exactly my thoughts when I first learned of the way histograms are stored in Prometheus. The beef here isn't with Kiali or Prometheus - its with the Istio reporting of its telemetry where it only buckets things up to 10s. But I suspect they set it up this way because, as you say, its great in most use-cases.

**Comment by jmazzitelli** [comment]
I knew I remembered this conversation :) From last october on kiali-dev - read this:

https://groups.google.com/d/msg/kiali-dev/Icw96t4AMV8/MZB1x-LPBgAJ

Particularly these parts:

```
I would definitely recommend histograms. Summaries have a fixed 
observation window (by default it's 10 minutes [1]) so your percentile 
value is only relevant for this window (you can't get the 99.9 
percentile for an arbitrary interval). They are also more resource 
intensive for the client. 
The counterpart with histograms is that you have to define the buckets 
in advance (the default is [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 
1, 2.5, 5, 10] is usually suitable for storing response times). 
```

I then confirm what the implications of this is:

```
OK, let me make sure I understand the implications of this. ... 
If I switch to histograms, I would need to know about what the observation values
are going to be. ... I need to know what I should be expecting in order to create
this historgram buckets....
```

So here you can see Simon (he is a Prom committer, he knows Prom) confirms that when something wants to have its histogram scraped by Prometheus, it needs to define the buckets. Simon shows the recommended buckets for http response times - I bet Istio defines their buckets using this mechanism. Note that if Istio defines this metric as a Summary and not a Historgram that would also explain the 10s - because Summary metrics are maxed out at 10s by default.

So, this shows, again, that the beef here is the way the Istio metrics are "bucket-ized". Prometheus is storing what Istio tells it to store, and Kiali is displaying what Prometheus has stored.

@jaygorrell do a Prom query that shows you all the "le" attribute values... what are they? I suspect the largest value is "10". That would mean Istio is exposing its metric with a largest value being 10. Anything larger than 10 will go in the last bucket that indicate "anything over 10"... so you can't discern if it was 11, 20, 100, or whatever.

**Comment by jaygorrell** [comment]
Yep, it sounds like you got it -- 10 is the largest bucket. The odd part is that Istio's default timeout is supposed to be 15s so it's an odd choice anyway. The default timeout is wrong anyway but that's another issue.

I'll go ahead and close this then, and open another with Istio after some more digging. I appreciate all the quick support... thanks so much!

**Comment by jaygorrell** [comment]
Ah! Just found the `kind: handler` "prometheus" in the Istio manifests. It has a reference to `request_duration_seconds` with:
```
buckets:
  explicit_buckets:
    bounds: [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10]
```

**Comment by harsha070** [comment]
How to add bucket in prometheus? I added 25, 50 and 100 in prometheus handler
```
buckets:
  explicit_buckets:
    bounds: [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 25, 50, 100]
```
But I my histogram percentile is still capped at 10s?

**Comment by jshaughn** [comment]
@harsha070 I would have thought that was what you needed to do, but perhaps this is good question for the Istio policies-telemetries channel on [Istio slack](istio.slack.com), or [forum](https://discuss.istio.io/).  Maybe it takes a change in more than one place.
