### ISSUE TITLE
Make readonly & admin access possible together

### ISSUE THREAD

**Issue by hdimitriou** [kiali/kiali#1139]
I have read that you are working on supporting RBAC ( https://github.com/kiali/kiali/issues/671#issuecomment-440564792 ) which is what I really want.

However, until that is in place, a workaround would be to allow the typical admin user, but also allow a readonly user as well. 
This way, we can let people use a readonly account to view stuff in Kiali and provide only a few people with the admin account. 

Right now, I see you can turn Kiali to readonly globally, which is not what I want because we need some people to have admin access

**Comment by israel-hdez** [comment]
@hdimitriou If you are using an OpenShift based cluster, you can have this possibility by enabling authentication through cluster credentials.

If you are using Kubernetes or a cluster flavor similar to it, then, as you say, it's not possible yet. I guess that the very minimum would be that Kiali supports more users that just an "admin" one.

For RBAC, as pointed in the comment you are referring, we are trying to delegate to the cluster RBAC. Here, the goal is to login into Kiali turhoug the cluster auth mechanisms. I'm curious to know if you would use any of the authentication mechanisms described here: https://kubernetes.io/docs/reference/access-authn-authz/authentication/ Your feedback about this help us to prioritize work.

**Comment by hdimitriou** [comment]
> I'm curious to know if you would use any of the authentication mechanisms described here: https://kubernetes.io/docs/reference/access-authn-authz/authentication/ 
I have gone through those, I would be more keen on service account token for groups of users. 
At the moment I am reluctant of giving non admin person access to people. 

Let's say that in terms of priority it makes more sense to be able to give groups of users some specific access levels. If you wanted you could even make personal service account tokens.

**Comment by israel-hdez** [comment]
Hi @hdimitriou 
I'm working into making it easier to integrate other auth mechanisms into Kiali, so that people can collaborate and include their wanted mechanisms.

As part of that, I may impement a "Token login", similar to the [login mechanism of the kubernetes dashboard](https://github.com/kubernetes/dashboard/wiki/Access-control#login-view) which seems to be "compatible" with current Kiali's RBAC Openshift mechanisms, thus probably making kubernetes RBAC support doable with small changes to Kiali. I hope this may cover your needs.

I'll update you with that progress.

**Comment by lucasponce** [comment]
@israel-hdez any update on this issue ?

**Comment by israel-hdez** [comment]
@lucasponce My plan is to do some changes to the auth mechanism.
This should be scheduled for Sprint 29, because I won't have the time to work on this in the current sprint.

**Comment by cfcosta** [comment]
I did some investigation on this, and found some things:

1 - When you set the installation to be view-only, we create a different service account that the pod uses to do the API requests. The solution here, and that's what I'm pursuing, is to create both service accounts and expose one via `ServiceAccountToken` kind of secret. I'm still investigating what needs to change for this to be possible, but it seems like a good way to go.
2 - Supporting creating multiple users for the `login` strategy is doable and relatively easy, so I'm doing it on a different PR.
3 - For Openshift, we do not respect global read-only at all. If the user has permissions to do something it will be possible, because we use the token from the user instead of our own service account. This is a bug, so I'll create another PR for this.

**Comment by jshaughn** [comment]
@cfcosta , @israel-hdez , Any update on this.  I'm not sure I see how https://github.com/kiali/kiali/issues/1848 relates to this request.  It seems more about being able to have admin view w/o editing abilities.  The first question is whether this is really something we want to to, and if so, should it apply at all on OpenShift.  @jmazzitelli , any thoughts?

**Comment by israel-hdez** [comment]
@jshaughn My idea with #1848 is that, since you can enable both "login" and "anonymous", somebody that properly logs-in would  have admin privileges, while somebody that proceeds as anonymous would be using the kiali-viewer SA.

Although, I'm not sure if that's the ideal implementation that @hdimitriou would like to see.

**Comment by israel-hdez** [comment]
@jshaughn BTW, on OpenShift I think it's already solved. Isn't it?
I though Kiali would take the privileges the logged in user via the token that it's returned by the OpenShift login. So, I understand this issue is specific for other k8s flavors.

**Comment by hdimitriou** [comment]
I would say that ideally your RBAC access should also define your Kiali access to those resources when you login. 

Lately however we have been using readonly mode and that is fine for all users but admins who want to test quickly, so your approach would be a good upgrade for me. 
I recognize that making changes on Kiali side can diverge Helm configuration files from reality and i find that a bit dangerous now.

**Comment by MarkDeckert** [comment]
Would be nice to have native RBAC support on an equal level with the openshift login method.

We have soft-multitenant non-openshift clusters using OIDC tokens for RBAC allowing access to team-based namespaces.

Using a token for login similar to the k8s dashboard would suit our purposes.

**Comment by israel-hdez** [comment]
@hdimitriou @MarkDeckert This is moving forward. See these pull requests: https://github.com/kiali/kiali/pull/1996 and https://github.com/kiali/kiali-ui/pull/1572.

Hopefully, that will cover this issue. If you can try the PRs and provide feedback, it will great. Otherwise, you could provide feedback after changes are released.

**Comment by hdimitriou** [comment]
The token and RBAC logic looks very good to me, thank you

**Comment by israel-hdez** [comment]
This is now merged and will be available in Kiali v1.11.0.

Right now, it's a new "secondary" login strategy. If you think this should be promoted as the default login strategy for Kubernetes, feel free to open a new issue.

Also, please report any issue you find.

**Comment by MarkDeckert** [comment]
@israel-hdez Sorry it's taken me so long to provide feedback on the token-based login.  I've finally had some time to do more testing after the holidays.  First of all, thank you for adding this feature so quickly!  Unfortunately I have discovered some issues that prevent me from using token-based auth.  In fact I believe current implementation will only work in a certain small subset of cases.  This may not be Kiali's fault since the rbac api is on the k8s side, but there may be workarounds.

- All users must have at a minimum list and get permissions on all namespaces in the cluster.  Otherwise login fails.  Ideally only the minimum necessary should be required. This is not really an issue for me - but perhaps should be documented.
- Once on the "Overview" page, all namespaces are shown, but errors pop up on the screen repeatedly as kiali refreshes underlying objects that the user doesn't necessarily have access to.
- When navigating to any other screen, the visible errors in UI mostly go away, although kiali still outputs the same errors to log as it apparently still repeatedly refreshes objects from all namespaces in the background, even though the view in UI may be scoped to a single namespace.

So it appears that to eliminate the errors, the token would need get and list to quite a few objects in every namespace in the cluster.  To work around this, additional logic would need to be introduced so that kiali can somehow identify and then ignore objects the token owner doesn't have permission to access. 

Obviously we could deploy separate kialis and limit kiali's permissions, etc. but then it still gives itself istio-system permission by default, so users would at least need that perm.  Also at this point you could just use ldap or login method instead and have a similar result.   Although without token-based access we lose one of the biggest advantages to using token based access - which is the ability to seamlessly hook into the existing k8s rbac's fine grained permissions.

**Comment by israel-hdez** [comment]
@MarkDeckert No problem in providing feedback after some time. Indeed, I appreciate your feedback. This is what we need a lot from community/users to make improvements that make sense to people.

Trying to reply while quoting:
> * All users must have at a minimum list and get permissions on all namespaces in the cluster [...]

This is documented in https://kiali.io/documentation/getting-started/#_login_options (third paragraph after the list of login methods). I know that docs may be somewhat distributed (some things in README.md of the repo, some others directly in sample YAMLs, some other in the website). We try to place docs where makes sense to have them at hand. But if you think that it's better to relocate some docs or have all docs in a single place, that's feedback we need and you may want to open an issue to discuss this. We think the current structure is OK, but we are biased because we know where to find the docs :)

> * Once on the "Overview" page, all namespaces are shown, but errors pop up [...]

I remember that when I tested this, I used the viewer role (see https://github.com/kiali/kiali/blob/master/operator/roles/kiali-deploy/templates/kubernetes/role-viewer.yaml) and I had no issues. But my memory may fail. Can you share the error message so that I can check?

> * When navigating to any other screen, the visible errors in UI mostly go away, although kiali still outputs the same errors [...]

Again, sharing with us the error messages will help a lot to diagnose.

**Comment by MarkDeckert** [comment]
@israel-hdez Thank you for the extensive response.  Next week I will dedicate some time to capture the error messages and provide some more info.

I believe this is the relevant line in the documentation you're referring to.
> Thus, for Kiali to work correctly the Service Account used to log in must have, at least, read privileges in all accessible namespaces

Would you mind if I submit a minor PR to change this to be more specific (changes in italic below)? 

> Thus, for Kiali to work correctly the Service Account used to log in must have, at least, **_get and list_** privileges in all **_namespaces accessible to kiali_**.

I don't mean to be critical of the documentation.  It is very good and much appreciated.  However, I believe this wording change may help some users like me in the future.  Just as some background to why I encountered this problem: Kubernetes Dashboard token login -- which inspired this change -- only requires the token to have "list" to namespaces so that the side namespaces pull-down menu doesn't fail, so I had no need until now to also allow "get".

All authentication to our clusters is via OIDC to AD which generates the tokens.  We use a soft-multitenancy model where different teams may share access to a single cluster, but are limited to their own "team" namespaces - where they have highly elevated permissions, but have no access at all to anything in namespaces they don't belong to via namespace scoped rolebindings.  When I get a chance next week I'll capture the error messages and provide an update - they're all related to trying to get/list objects like VirtualServices etc inside namespaces inaccessible to the token.

**Comment by MarkDeckert** [comment]
Just some of the errors:
On the Overview screen:
![image](https://user-images.githubusercontent.com/4957225/73705140-f01bea00-46a9-11ea-87d5-deb14036ef96.png)

The messages are accurate.  My test account doesn't have access to those objects in those namespaces.  The messages repeatedly pop up about a number of objects in namespaces I don't have access to (I only have list and get to the namespace itself, which I feel is fairly innocuous from a security standpoint in soft multinenancy with trusted users. But any further access to see objects inside is not allowed)

In Kiali logs I see errors like this below.  Also in graph mode I was getting panics (see further below).

> E0204 01:15:39.629466       1 apps.go:182] Error fetching Workload per namespace istio-system: pods is forbidden: User "oidc:marktest" cannot list resource "pods" in API group "" in the namespace "istio-system"
E0204 01:15:39.629546       1 errors.go:21] Error while fetching app health: services is forbidden: User "oidc:marktest" cannot list resource "services" in API group "" in the namespace "istio-system"
E0204 01:15:39.648898       1 apps.go:172] Error fetching Services per namespace jenkins: services is forbidden: User "oidc:marktest" cannot list resource "services" in API group "" in the namespace "jenkins"
E0204 01:15:39.765983       1 workloads.go:206] Error fetching Deployments per namespace jenkins: deployments.apps is forbidden: User "oidc:marktest" cannot list resource "deployments" in API group "apps" in the namespace "jenkins"
E0204 01:15:39.771546       1 workloads.go:222] Error fetching ReplicaSets per namespace jenkins: replicasets.apps is forbidden: User "oidc:marktest" cannot list resource "replicasets" in API group "apps" in the namespace "jenkins"
E0204 01:15:39.777568       1 workloads.go:190] Error fetching Pods per namespace jenkins: pods is forbidden: User "oidc:marktest" cannot list resource "pods" in API group "" in the namespace "jenkins"
E0204 01:15:39.777639       1 apps.go:182] Error fetching Workload per namespace jenkins: deployments.apps is forbidden: User "oidc:marktest" cannot list resource "deployments" in API group "apps" in the namespace "jenkins"
E0204 01:15:39.777677       1 errors.go:21] Error while fetching app health: services is forbidden: User "oidc:marktest" cannot list resource "services" in API group "" in the namespace "jenkins"
E0204 01:15:39.791744       1 tls.go:26] policies.authentication.istio.io is forbidden: User "oidc:marktest" cannot list resource "policies" in API group "authentication.istio.io" in the namespace "mdeckert"
E0204 01:15:39.817354       1 apps.go:172] Error fetching Services per namespace monitoring-etcd: services is forbidden: User "oidc:marktest" cannot list resource "services" in API group "" in the namespace "monitoring-etcd"
E0204 01:15:39.895722       1 tls.go:26] policies.authentication.istio.io is forbidden: User "oidc:marktest" cannot list resource "policies" in API group "authentication.istio.io" in the namespace "monitoring-etcd"
E0204 01:15:39.931805       1 workloads.go:190] Error fetching Pods per namespace monitoring-etcd: pods is forbidden: User "oidc:marktest" cannot list resource "pods" in API group "" in the namespace "monitoring-etcd"
E0204 01:15:39.937524       1 workloads.go:206] Error fetching Deployments per namespace monitoring-etcd: deployments.apps is forbidden: User "oidc:marktest" cannot list resource "deployments" in API group "apps" in the namespace "monitoring-etcd"
E0204 01:15:39.943159       1 workloads.go:222] Error fetching ReplicaSets per namespace monitoring-etcd: replicasets.apps is forbidden: User "oidc:marktest" cannot list resource "replicasets" in API group "apps" in the namespace "monitoring-etcd"
E0204 01:15:39.943187       1 apps.go:182] Error fetching Workload per namespace monitoring-etcd: pods is forbidden: User "oidc:marktest" cannot list resource "pods" in API group "" in the namespace "monitoring-etcd"
E0204 01:15:39.943220       1 errors.go:21] Error while fetching app health: services is forbidden: User "oidc:marktest" cannot list resource "services" in API group "" in the namespace "monitoring-etcd"
E0204 01:15:39.979612       1 tls.go:26] policies.authentication.istio.io is forbidden: User "oidc:marktest" cannot list resource "policies" in API group "authentication.istio.io" in the namespace "istio-system"
E0204 01:15:40.026309       1 tls.go:26] policies.authentication.istio.io is forbidden: User "oidc:marktest" cannot list resource "policies" in API group "authentication.istio.io" in the namespace "jenkins"
E0204 01:15:40.143594       1 tls.go:26] policies.authentication.istio.io is forbidden: User "oidc:marktest" cannot list resource "policies" in API group "authentication.istio.io" in the namespace "monitoring"



In graph mode I was actually getting panic errors like this:

> E0204 01:27:00.077079       1 graph.go:87] serviceentries.networking.istio.io is forbidden: User "oidc:marktest" cannot list resource "serviceentries" in API group "networking.istio.io" in the namespace "default": goroutine 350530 [runni
:
runtime/debug.Stack(0xc0142f4160, 0xa9, 0xc0006596e0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/kiali/kiali/handlers.handlePanic(0x16d6da0, 0xc009c27110)
        /home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/handlers/graph.go:86 +0x155
panic(0x12795a0, 0xc0006596e0)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/kiali/kiali/graph.CheckError(0x169ee60, 0xc00bb70240)
        /home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/util.go:38 +0x9c
github.com/kiali/kiali/graph/telemetry/istio/appender.ServiceEntryAppender.getServiceEntry(0xc00893f770, 0xc00901bbf9, 0xc, 0xc0189f18e0, 0xc, 0xc000aa6580, 0x0, 0xc01526e200)
        /home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/telemetry/istio/appender/service_entry.go:179 +0x4a2
github.com/kiali/kiali/graph/telemetry/istio/appender.ServiceEntryAppender.applyServiceEntries(0xc00893f770, 0xc00901bbf9, 0xc, 0xc00893f8c0, 0xc000aa6580, 0xc000658e00)
        /home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/telemetry/istio/appender/service_entry.go:108 +0x1da
github.com/kiali/kiali/graph/telemetry/istio/appender.ServiceEntryAppender.AppendGraph(...)
        /home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/telemetry/istio/appender/service_entry.go:56
github.com/kiali/kiali/graph/telemetry/istio.BuildNamespacesTrafficMap(0xc00893f770, 0x0, 0xc01526e200, 0x4, 0x4, 0x1, 0xc008c8b3e0, 0x1a3185c5000, 0xc00901bbf9, 0xc, ...)
        /home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/telemetry/istio/istio.go:49 +0x283
github.com/kiali/kiali/graph/api.graphNamespacesIstio(0xc013594480, 0xc00893f830, 0x149ac49, 0x9, 0x149841b, 0x5, 0xc00901bc26, 0x3, 0x1a3185c5000, 0xc00901bbf9, ...)
        /home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/api/api.go:44 +0xb8
github.com/kiali/kiali/graph/api.GraphNamespaces(0xc013594480, 0x149ac49, 0x9, 0x149841b, 0x5, 0xc00901bc26, 0x3, 0x1a3185c5000, 0xc00901bbf9, 0xc, ...)
        /home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/graph/api/api.go:26 +0x17c
github.com/kiali/kiali/handlers.GraphNamespaces(0x16d6da0, 0xc009c27110, 0xc002b6eb00)
        /home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/handlers/graph.go:51 +0x137
net/http.HandlerFunc.ServeHTTP(0x1533310, 0x16d6da0, 0xc009c27110, 0xc002b6eb00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/kiali/kiali/handlers.AuthenticationHandler.Handle.func1(0x16d6da0, 0xc009c27110, 0xc001eead00)
        /home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/handlers/authentication.go:492 +0x225
net/http.HandlerFunc.ServeHTTP(0xc000414360, 0x16d6da0, 0xc009c27110, 0xc001eead00)
        /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/kiali/kiali/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc000340300, 0x16d6da0, 0xc009c27110, 0xc000b33600)
        /home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/kiali/kiali/vendor/github.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1(0x16d69e0, 0xc014ca2fc0, 0xc000b33600)
        /home/jenkins/agent/workspace/kiali-workflow/kiali-release/src/github.com/kiali/kiali/vendor/github.com/NYTimes/gziphandler/gzip.go:336 +0x23f
net/http.HandlerFunc.ServeHTTP(0xc0002a8270, 0x16d69e0, 0xc014ca2fc0, 0xc000b33600)
        /usr/local/go/src/net/http/server.go:2007 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0002ae040, 0x16d69e0, 0xc014ca2fc0, 0xc000b33600)
        /usr/local/go/src/net/http/server.go:2387 +0x1bd
net/http.serverHandler.ServeHTTP(0xc000486000, 0x16d69e0, 0xc014ca2fc0, 0xc000b33600)
        /usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc004c861e0, 0x16dd220, 0xc0112c5ec0)
        /usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2927 +0x38e

**Comment by israel-hdez** [comment]
@MarkDeckert Your PR to improve the documentation at kiali.io is very welcome! Please, go ahead.

Regarding the errors you see, yes those are expected and go inline with the documented limitation. What the docs at kiali.io are trying to say is that the oidc:marktest ServiceAccount should have the kiali-viewer role in all namespaces (see https://github.com/kiali/kiali/blob/master/operator/roles/kiali-deploy/templates/kubernetes/role-viewer.yaml)

If this is not desirable (and I bet don't), please go ahead and open a new issue requesting this enhancement (or fix)
