### ISSUE TITLE
Is "No traffic logged" edge normal?

### ISSUE THREAD

**Issue by sniperking1234** [kiali/kiali#1159]
![image](https://user-images.githubusercontent.com/7834655/59747600-c3969780-92ab-11e9-8232-2d530ea3411f.png)
The information about the edge can find in Prometheus, although the value is 0
![image](https://user-images.githubusercontent.com/7834655/59747724-0b1d2380-92ac-11e9-8a2c-f35dc2c43f55.png)
Why did Kiali not record the information on this edge? Is it because the traffic is too small?
**Versions used**
Kiali: 0.21
Istio: 1.1.2
Kubernetes version: 1.11

**Comment by abonas** [comment]
@jshaughn

**Comment by jshaughn** [comment]
> Why did Kiali not record the information on this edge?

Kiali does not actually record any telemetry, Istio generates the telemetry from the proxies.  Kiali takes the telemetry and visualizes it in the graph.  When you see an edge with no traffic it means there was, at some point in the past, request traffic on that edge.  But for the time period being queried there were no requests.

In your example it looks like you are querying for 6h, so that means there were no requests for that edge in the last 6 hours.  But at some point in the past there must have been traffic, and that is why the time-series for that edge exists in Prometheus.   If you expected traffic on that edge the you need to investigate why there is no telemetry being reported.  That would likely have something to do with the Istio definitions.

**Comment by sniperking1234** [comment]
@jshaughn I got it. I thought the '0' in Prometheus is close to 0. In fact, ‘0’ is 0.

**Comment by jshaughn** [comment]
@sniperking1234 Ok, glad that makes sense.  One last note, sometimes the no-traffic edges can get in the way.  If you want to easily hide them try entering '! traffic" in the Graph Hide input box.
