### ISSUE TITLE
Service Entry is not displayed when egress gateway is configured

### ISSUE THREAD

**Issue by dwctua** [kiali/kiali#1194]
**Describe the bug**
  Service Entry is not displayed when egress gateway is configured
For UI issues please also add a screenshot that shows the issue.

**Versions used**
Kiali-ui
0.20.0 (87ca7062921e2aa857c6322e9ed3f0882f089922)
Kiali
v0.20.0 (140969bc2ef1a77ca7387b47f8b23dcbd4818bd0)
Components
Istio
1.2.0
Prometheus
2.8.0
Kubernetes
v1.14.0

**To Reproduce**
follow the link to set up Service Entry and engress gateway
https://istio.io/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/

**Expected behavior**
when there is SE only, it shows as expected, SE is pointing to external service.
However, after egress gateway is configured, SE disappeared. I only see telemetry flow for egress gateway, I would expect it also show the SE and the external service.
![image](https://user-images.githubusercontent.com/46290157/60213765-28b13680-9832-11e9-9e0f-38c224f45867.png)

**Comment by josejulio** [comment]
Hello @dwctua 
I was just checking this today. I think this is a problem with Istio telemetry, I left some comments in Istio chat.

Could you please help me confirm that you don't have any change `istio_requests_total` and `istio_tcp_sent_bytes_total` time-series that has any destination service = `edition.cnn.com` ?

The queries should look like this:
`istio_tcp_sent_bytes_total{destination_service="edition.cnn.com"}` and `istio_requests_total{destination_service="edition.cnn.com"}`

You should see the remains of your previous tries, but notice that they don't change after adding the Gateway, this is because the telemetry is not being reported with that setup. 
Kiali builds up the graph from this information.

I'll create an Istio issue to ask them if this is expected.

Thanks.

**Comment by dwctua** [comment]
can you show me how to confirm the change for istio_requests_total ? I included mixer log belwo for your reference.

{"level":"info","time":"2019-06-26T23:31:23.335745Z","instance":"accesslog.instance.istio-system","apiClaims":"","apiKey":"","clientTraceId":"","connection_security_policy":"unknown","destinationApp":"istio-egressgateway","destinationIp":"172.17.0.12","destinationName":"istio-egressgateway-687f8559cb-xvk89","destinationNamespace":"istio-system","destinationOwner":"kubernetes://apis/apps/v1/namespaces/istio-system/deployments/istio-egressgateway","destinationPrincipal":"","destinationServiceHost":"istio-egressgateway.istio-system.svc.cluster.local","destinationWorkload":"istio-egressgateway","grpcMessage":"","grpcStatus":"","httpAuthority":"edition.cnn.com","latency":"2.0363044s","method":"GET","permissiveResponseCode":"none","permissiveResponsePolicyID":"none","protocol":"http","receivedBytes":276,"referer":"","reporter":"source","requestId":"2cd9895c-f54b-9ca3-af3a-e535e41b241a","requestSize":0,"requestedServerName":"","responseCode":200,"responseFlags":"-","responseSize":1105085,"responseTimestamp":"2019-06-26T23:31:25.371994Z","sentBytes":1106685,"sourceApp":"sleep","sourceIp":"172.17.0.18","sourceName":"sleep-5fb55468cb-2h5tz","sourceNamespace":"poc","sourceOwner":"kubernetes://apis/apps/v1/namespaces/poc/deployments/sleep","sourcePrincipal":"","sourceWorkload":"sleep","url":"/politics","userAgent":"curl/7.60.0","xForwardedFor":"172.17.0.18"},
{"level":"info","time":"2019-06-26T23:31:23.336910Z","instance":"accesslog.instance.istio-system","apiClaims":"","apiKey":"","clientTraceId":"","connection_security_policy":"unknown","destinationApp":"","destinationIp":"151.101.65.67","destinationName":"unknown","destinationNamespace":"default","destinationOwner":"unknown","destinationPrincipal":"","destinationServiceHost":"istio-egressgateway.istio-system.svc.cluster.local","destinationWorkload":"unknown","grpcMessage":"","grpcStatus":"","httpAuthority":"edition.cnn.com","latency":"2.03515s","method":"GET","permissiveResponseCode":"none","permissiveResponsePolicyID":"none","protocol":"http","receivedBytes":810,"referer":"","reporter":"source","requestId":"5b3c75d8-d32a-9615-b992-236c3951c935","requestSize":0,"requestedServerName":"","responseCode":200,"responseFlags":"-","responseSize":1105085,"responseTimestamp":"2019-06-26T23:31:25.371868Z","sentBytes":1106691,"sourceApp":"sleep","sourceIp":"172.17.0.18","sourceName":"sleep-5fb55468cb-2h5tz","sourceNamespace":"istio-system","sourceOwner":"kubernetes://apis/apps/v1/namespaces/poc/deployments/sleep","sourcePrincipal":"","sourceWorkload":"sleep","url":"/politics","userAgent":"curl/7.60.0","xForwardedFor":"172.17.0.18,172.17.0.18"}

**Comment by dwctua** [comment]
I found the doc to run the query, but didn't find any when egress gateway is running. https://istio.io/docs/tasks/telemetry/metrics/querying-metrics/

**Comment by pilhuhn** [comment]
It sounds like this is what #1193 / #1172 is talking about? At least yesterday in the sprint demo, @jshaughn showed data flowing via SE to the egress.
The recording of the sprint demo should soon show up on https://www.youtube.com/channel/UCcm2NzDN_UCZKk2yYmOpc5w

**Comment by dwctua** [comment]
Cool! can't wait to see the demo. However, from the query above, seems there is no data when using egress gateway, not sure how this can be addressed.

**Comment by jshaughn** [comment]
@dwctua there may be two relevant things here.  First, as @josejulio mentioned above, we think there may be a telemetry issue in Istio because we would expect to see time-series in prometheus for traffic to the serviceEntry, and then from the serviceEntry to the egressgateway.  With that you would see a service node between policy-v1 and istio-egressgateway in the graph.  @josejulio is asking about that in Istio slack.

The second issue has to do with the fixes presented in yesterday's Kiali sprint demo.  Current releases of Kiali would render a service node (triangle shape) instead of the proper serviceEntry node (tag shape).  With the very latest changes in Kiali a proper serviceEntry node should get rendered.   Note that the Kiali issue is moot because with the apparent Istio issue you don't even get the incorrect service node.

**Comment by josejulio** [comment]
I just created an issue in istio: https://github.com/istio/istio/issues/15188 to follow up this possible bug.

**Comment by lucasponce** [comment]
This still depends on https://github.com/istio/istio/issues/15188

**Comment by lucasponce** [comment]
According to https://github.com/istio/istio/issues/15188 it seems Istio will update this related topic on 1.4

**Comment by israel-hdez** [comment]
Using Istio 1.4-beta.2 and Kiali `master`, I see this graph:

![image](https://user-images.githubusercontent.com/23639005/68244483-87ee3700-ffda-11e9-9e08-59b43efbd00d.png)

Although issue istio/istio#15188 is not yet closed and moved to 1.5 milestone, looks like the partial fixes they made are enough for the stated usecase.

I'll close this issue once Istio 1.4 is released.

**Comment by israel-hdez** [comment]
I have re-tested the scenario and I see the graph correctly.
Tested using a clean minikube cluster and installing Istio 1.4 using the demo profile, then doing the steps available at https://istio.io/docs/tasks/traffic-management/egress/egress-gateway-tls-origination/

Additionally, istio/istio#15188 was closed. I'm closing because this should be good.
