### ISSUE TITLE
crc Hack script shows 'unknown option -U'

### ISSUE THREAD

**Issue by pilhuhn** [kiali/kiali#1219]
RHEL 7.6

qemu-img info -U ~hrupp/.crc/machines/crc/crc
info: invalid option -- 'U'
qemu-img version 1.5.3, Copyright (c) 2004-2008 Fabrice Bellard

```
INFO Login to the console with user: kubeadmin, password: ****
CodeReady Containers instance is running
[sudo] Passwort für hrupp:
HACK: Will attempt to get shared write lock to obtain disk size
[sudo] Passwort für hrupp:
info: invalid option -- 'U'
HACK: Cannnot determine current disk size of VM - will assume there is enough
HACK: Creating users 'kiali' and 'johndoe'
Logged into "https://api.crc.testing:6443" as "system:admin" using existing credentials.

```

**Comment by jmazzitelli** [comment]
This was something that was just added recently to support Fedora. You should not even get to this if you are on RHEL :) Here's the PR: https://github.com/kiali/kiali/pull/1209/files

So you see if this command fails initially:

```
  _QEMU_IMG_STDOUT="$(sudo qemu-img info ${CRC_MACHINE_IMAGE})"
```

But on Fedora this will fail because it won't allow you to get image info in a running VM without asking for a write-lock (on my RHEL 7.6 box, this does not fail). So if that fails (e.g. on Fedora 30) only then does it try to run with the `-U` option:

```
  _QEMU_IMG_STDOUT="$(sudo qemu-img info -U ${CRC_MACHINE_IMAGE})"
```

So, @pilhuhn , confirm you at least have the "qemu-img" command and with the CRC VM running execute `sudo qemu-img info ~/.crc/machines/crc/crc` - what do you get?

**Comment by pilhuhn** [comment]
Yes I have `quemu-img`. See version info above.

```
$ sudo qemu-img info ~/.crc/machines/crc/crc
[sudo] Passwort für hrupp:
image: /home/hrupp/.crc/machines/crc/crc
file format: qcow2
virtual size: 31G (33285996544 bytes)
disk size: 9.1G
cluster_size: 65536
Format specific information:
    compat: 1.1
    lazy refcounts: true
```

```
$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.6 (Maipo)
[hrupp@pintsize hack]$ uname -a
Linux pintsize.home.pilhuhn.de 3.10.0-957.21.3.el7.x86_64 #1 SMP Fri Jun 14 02:54:29 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by pilhuhn** [comment]
[14:45:54]  <pilhuhn>	mazz I fear this was just a blip . This time it passes (again). This morning I also had those segvs that others have reported. Now it is good again.

I will keep an eye on this.
