### ISSUE TITLE
Missing roles when installing operator from the hub

### ISSUE THREAD

**Issue by omerlh** [kiali/kiali#1252]
**General remarks**
I installed the operator from the [OpratorHub](https://operatorhub.io/operator/kiali). After installing the operator, I noticed errors in the logs - complaining about missing roles. After editing the role and adding permissions to list `roles` and `clusterroles` in API group `rbac.authorization.k8s.io`. Patching the role fixed the issue and Kiali was installed successfully after creating the CRD.

BTW I noticed the role is very wide, and I'm not sure it needs all the permissions it requested - but I have nothing to base it on.

**Comment by jmazzitelli** [comment]
Darn! Yeah, some roles seem to be missing both in the [upstream](https://github.com/operator-framework/community-operators/blob/master/upstream-community-operators/kiali/kiali.v1.1.0.clusterserviceversion.yaml#L326-L327) and the [community](https://github.com/operator-framework/community-operators/blob/master/community-operators/kiali/1.1.0/kiali.v1.1.0.clusterserviceversion.yaml#L321-L322) repos. (Note, the missing ones are the roles and rolebindings).

If you install the Operator using the kiali operator deploy script you will get these since they are in the [template used by that script here](https://github.com/kiali/kiali/blob/v1.1.0/operator/deploy/role.yaml#L71-L84)

I created two PRs to fix this:

* https://github.com/operator-framework/community-operators/pull/524
* https://github.com/operator-framework/community-operators/pull/525

Note that the clusterrole and clusterrolebinding permissions are OPTIONAL and are only needed by the operator. Kiali itself will never get these permissions, this is only for the operator (and again, its optional). If you want to set the Kiali CR setting `deployment.accessible_namespaces` to the value of `[**]` (that is, if you want to grant to Kiali a view of the entire cluster) then these clusterroles/bindings is needed. If you feel uncomfortable granting clusterroles and clusterrolebindings permissions to the operator, you can remove them from the operator role, but when you do this, realize you must either specify a list of namespaces for Kiali to access (`deployment.accessible_namespaces`) or leave that setting unset, which by default gives access to Kiali to all namespaces currently existing in the cluster (but not namespaces created in the future). See https://www.kiali.io/documentation/getting-started/#_accessible_namespaces for additional information. 

> I noticed the role is very wide, and I'm not sure it needs all the permissions it requested - but I have nothing to base it on.

It does need all of these permissions (though perhaps not all of the verbs). The operator needs a set of permissions to be able to do what it needs to do, and then it needs the additional permissions that Kiali requires (since the operator must have the same permissions that it needs to grant to the resources it creates). Put these two together and the operator role is wide. But all of the permissions have a purpose. If you find a permission in this role that it does not need, let us know and we will look into it. There is one thing that might be able to be stripped down, and that is the verbs.Traditionally, the operators are given the verb of "*" to its resource rules (meaning all verbs) - in the roles you see here, the Kiali team simply explicitly lists virtually all the verbs that make up "*" rather than specify "*" directly. This was done because in the future if we find we do not need some verbs (such as 'patch' or 'watch') then we could just delete that specific unneeded verb and leave the others intact. But the groups/resources themselves are all needed. Kiali is able to manage lots of resources within your cluster and that's why these are needed.

**Comment by jmazzitelli** [comment]
Those two PRs have been merged. So this should be fixed.

**Comment by omerlh** [comment]
Thanks for the quick response! I'll test and update if I'll encounter further issues.

**Comment by israel-hdez** [comment]
I'm closing. Please, reopen if you find that this is still a problem.
