### ISSUE TITLE
operator: Kilai resource is namespace but doesn't work like a normal CRD

### ISSUE THREAD

**Issue by mikebryant** [kiali/kiali#1261]
**Describe the bug**
The Kiali resource is namespaced, but can only go in the same namespace as the kiali-operator

In addition the resources it creates are not correctly configure with an ownerReference, so garbage collection doesn't work.

**Versions used**
Kiali: 1.1.0
Istio: 1.1.9
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9) EKS 1.11

**To Reproduce**

**Expected behavior**
One of:

#### Keep it namespaced
- I would expect the `deployment.namespace` field to be removed
- I would expect all created resources to be deployed in the same namespace as the CR
- I would expect ownerReferences on all created resources
- I would expect the operator to watch all namespaces for CRs

#### Change it to Cluster scope
- I would expect ownerReferences on all created resources

**Comment by jmazzitelli** [comment]
I don't follow some of what is in the description. The steps to reproduce are missing, so I'm confused. But I'll add comments here based on what I am reading here.

* The Kiali resource is namespaced, but can only go in the same namespace as the kiali-operator

The Kiali CR (aka the "Kiali resource") does not have to be in the same namespace as the kiali-operator. The operator supports the InstallModeType of SingleNamespace as well as OwnNamespace and AllNamespaces. You can set the watch namespace to any namespace you want. If you are installing via the deploy script (as documented at https://www.kiali.io/documentation/getting-started) you can pass in the namespace you want the operator to watch via the `--operator-watch-namespace` option. If installing the operator via OLM, you can tell it which namespace to watch. 

* I would expect the deployment.namespace field to be removed

I don't know what this means. Where is this to be removed from and what is this actually referring to?

* I would expect all created resources to be deployed in the same namespace as the CR

This isn't always the case. The Kiali resources are for the most part created in the declared deployment.namespace as defined in the Kiali CR (this allows one to, for example, install the Kiali Operator in its own namespace, watch for a Kiali CR in its own namespace (or some other namespace), but yet be able to install Kiali in the istio-system namespace with the rest of the Istio components). So this namespace where Kiali is installed may or may not be in the same namespace as where the Kiali CR is found. Note that depending on configuration (see accessible_namespaces) roles and role bindings will be created in those accessible namespaces as well - so not all resources are created in that one namespace - the operator is responsible for managing some additional resources elsewhere.

* I would expect ownerReferences on all created resources

The Kiali operator does not modify ownerReferences - owner reference creation are left as a job for the underlying operator-sdk. Because the Kiali Operator is implemented with the ansible operator-sdk, that SDK should be handling this and cleaning things up properly. If there is a problem with cleanup, we'd need replication procedures to see the issue.

* I would expect the operator to watch all namespaces for CRs

This can be configured by setting the watch namespace properly. If you are installing the Operator using OLM/OperatorHub, then you can tell the operator to watch all namespaces. If you are installing via the kiali deploy script (as documented at https://www.kiali.io/documentation/getting-started) then you can pass the `--operator-watch-namespace` with a value of "**". This puts the operator in InstallModeType of "AllNamespaces". Note that regardless of the watch namespace or which namespace the Kiali CR is found, Kiali resources are installed in the deployment.namespace setting (which does not necessarily mean the same namespace where the CR is found).

Those are just some of my thoughts.

**Comment by israel-hdez** [comment]
@mikebryant do you have any feedback to the previous reply?

**Comment by mikebryant** [comment]
Sorry, I missed the notification for your reply. Thanks for the detail!

> The Kiali CR (aka the "Kiali resource") does not have to be in the same namespace as the kiali-operator. The operator supports the InstallModeType of SingleNamespace as well as OwnNamespace and AllNamespaces. You can set the watch namespace to any namespace you want. If you are installing via the deploy script (as documented at https://www.kiali.io/documentation/getting-started) you can pass in the namespace you want the operator to watch via the --operator-watch-namespace option. If installing the operator via OLM, you can tell it which namespace to watch.

Ah, this is useful, and satisfies what I need there. I'm somewhat confused by this not being the default (since the CRD is defined cluster-wide, it makes sense to me for the operator to default to working cluster-wide), but no matter. Thanks for the heads up

> I don't know what this means. Where is this to be removed from and what is this actually referring to?

This was a subset of one of the options, which is if the CR is namespaced, all objects should be created within that namespace, or `ownerReferences` don't work.

> The Kiali operator does not modify ownerReferences - owner reference creation are left as a job for the underlying operator-sdk. Because the Kiali Operator is implemented with the ansible operator-sdk, that SDK should be handling this and cleaning things up properly. If there is a problem with cleanup, we'd need replication procedures to see the issue.

As above, I didn't know it was possible to set the watch namespace, so I had the Kiali CR in the same namespace as the operator, which was different to where I needed kiali installed. ownerReferences on a Namespace-scoped object cannot cross a namespace, so all of the resources created are orphans and will not be cleaned up. The operator-sdk can't set the ownerReferences properly because the resources created aren't within the right scope for them.

From https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/
`Note: Cross-namespace owner references are disallowed by design. This means: 1) Namespace-scoped dependents can only specify owners in the same namespace, and owners that are cluster-scoped. 2) Cluster-scoped dependents can only specify cluster-scoped owners, but not namespace-scoped owners.`

This was the gist of my second option under expected behaviour - if the Kiali CR is going to modify objects across multiple namespaces, it should be Cluster-scoped, not Namespace-scoped, to keep the contract about how controllers and the objects they control work.

> Note that regardless of the watch namespace or which namespace the Kiali CR is found, Kiali resources are installed in the deployment.namespace setting (which does not necessarily mean the same namespace where the CR is found).

This is where I have a bit of an issue. If I want to install the kiali-operator in a multi-tenant cluster, it provides an avenue for a big security hole. The Kiali CR is namespaced, so as is normal, for a Namespace-scoped resource you can allow users to create it within their Namespace. But the kiali-operator is vulnerable to a confused deputy attack. The attacker can create a Namespace-scoped object in their own Namespace that interferes with objects in another user's Namespace.

If the Kiali CR is cluster-scoped, it's obvious to a cluster administrator that it can affect things cluster-wide and is therefore not suitable to be given to users.

If it's namespace-scoped, it should only cause creation/modification of objects within the Namespace it's defined.

**Comment by jmazzitelli** [comment]
> If I want to install the kiali-operator in a multi-tenant cluster, it provides an avenue for a big security hole. The Kiali CR is namespaced, so as is normal, for a Namespace-scoped resource you can allow users to create it within their Namespace. But the kiali-operator is vulnerable to a confused deputy attack. The attacker can create a Namespace-scoped object in their own Namespace that interferes with objects in another user's Namespace.

For details on the current state of affairs of how Kiali does namespace management, see https://www.kiali.io/documentation/getting-started/#_namespace_management

But I can say that Maistra addresses this issue you bring up (Maistra is a multi-tenant Istio implementation). Today, Maistra provides additional security such that users won't be able to add namespaces to Kiali's deployment.accessible_namespaces list unless that user has access to those namespaces. Outside of a Maistra environment, the plan is for the Kiali operator to provide this security check itself, but we need this first from the ansible operator SDK: https://github.com/operator-framework/operator-sdk/issues/1658

So for people with interest in multi-tenant scenarios, we recommend people look at Maistra and Kiali's integration with it.

**Comment by mikebryant** [comment]
That's really good to hear, thanks for the information.

I think that addresses all the comments I had, thanks for taking the time to respond in such detail :)
