### ISSUE TITLE
Global labels filters to reduce the search space

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#1269]
Much like global namespace(s) selection, we could have some global custom labels filters in order to help reduce the search space while troubleshooting.

Currently Kiali only offers navigation through namespace filtering, but users may have some custom usage of labels to partition their workspaces and Kiali could use that to help the users to narrow down the different views (both graph and *-list)

You can upvote/downvote/comment this feature request.

**Comment by lucasponce** [comment]
Related:
#1522 
#1511

**Comment by jotak** [comment]
Some status update:
- This "labels filtering" already exists in Services list, Applications list and Workloads list pages. Filters are preserved while navigating through these pages
- Navigating to the Istio objects page would break/loose these filters
- Navigating to the Graph page doesn't break them however they are not used here (ignored)
- For Overview page labels are checked against namespaces and not underlying objects ; see #2559 ; it's useful but doesn't provide the "global filtering" experience.

**Comment by aljesusg** [comment]
My idea was add this label Filter globally (like namespace dropdown) at least in workloads, services and apps list.

![Screenshot from 2020-05-05 11-57-02](https://user-images.githubusercontent.com/3019213/81054691-8dfc9c00-8ec7-11ea-8431-12bb266e5bea.png)

About how to apply them in the Graph require more research

**Comment by lucasponce** [comment]
As this task is a research, and there is no any expectation to implement a change, I'd like also to see investigation in the graph, rather than a change on the UI of the labels.

To me, or at least how I understood this task, was more thinking in how we can apply a label, that may reduce all space (graph included).

In a way that i.e. if I have an additional label as stage:env2, I can completely filter everything on Kiali (perhaps from backend too) with that label.

And Graph and List would be reduced.

Where to place the label control would be more a secondary task rather than primary task for it.

I know that perhaps this may require more discussion and it may introduced some noise on the epic, but I'm ok to remove this task from the EPIC (I understand it's big and it would require both teams thinking on it).

Just let me know, and we can remove it from the Sprint, and add it back the "discussion needed" label.

Changing the label filter at namespace label without applying the whole kiali is not something I like, I think. For that I prefer to keep the current design, as this is just an UI change without really impact on the feature.

**Comment by jshaughn** [comment]
To include the graph in a globally set label-filter would be best done in the backend, perhaps with an additional appender, or maybe built into the dead-node appender.   We don't have label information client-side in the graph and so it's not suitable for the graph-hide feature, or a new client-side filtering.

That's just a technical note for feasibility, as for the feature itself, it seems like it could be useful and if globally set it probably should be applied to the graph, at least by default.

**Comment by jshaughn** [comment]
It may be useful to start thinking about "global filters" as the "observabiility scope".  Namespace selection, label include/exclude, and maybe something more downline (cluster selection?).   The reason being that "filters" may be something we apply client-side.  For example, I could imagine a scope that limits to label=mylabel, and then in the client still filtering on label=v1.  I don't know, just a passing thought...

**Comment by lucasponce** [comment]
I think for labels we have started the problem from a more technical view rather than a high level scenario.

As this is a research, I'd like to use this one to define a target of what we want to address.

For example, how I see this feature is:
- Some persona like a cluster admin is going to have visibility of a massive number of namespaces. This is important, because, for example, other scenarios like the Developer Console are focus on a single namespace with a single app with few components. Then, I think this kind of filtering applies for those highly populated use cases. (i.e. this is not artificial, just think of those scenarios where there are hundres of namespaces, one per user).
- Ok, when we setup that high level target, in an organizacion can be some label conventions (i.e. environment={dev,testing} or any other custom way use to categorize workloads and services - and applications -).
- Then, my use case would be to apply a filter on that (i.e. environment=dev) that can limit the visualization of those elements that match the filter conditions in all places: graph and lists (no need to apply this on details).

Once that we build our high level goal, perhaps we can then enter in the technical space and discuss (what labels are available and where), what we would need to provide this high level result.
What could be the best strategy ? (i.e. to filter in backend, to fetch and filter in client side).
How to resolve ambiguities (i.e. querying expressions may open a lot of tricky corner cases that are complex to solve and probably it may introduce penalties on all layers, etc).

Anyway, from this particular issue I don't expect any PoC yet, but perhaps a better description of those aspects.

**Comment by jshaughn** [comment]
@lucasponce I agree with the feature statement you made above and I continue to think of this idea as establishing a global [observability] scope.  Today that is limited to namespaces, but going forward could include label filters.  The scope could be passed around both client-side and in the API.

**Comment by lucasponce** [comment]
Related to https://github.com/kiali/kiali/discussions/4080

**Comment by lucasponce** [comment]
I'm going to close this after #4605.
Using workload labels have been prioritized first in the Graph component.
