### ISSUE TITLE
Kiali Operator to support Pop Security Policy

### ISSUE THREAD

**Issue by Sallyan** [kiali/kiali#1294]
**Issue**: 
Our GCP cluster is enabled Pod Security Policy. After run the kiali-operator deploy script, the containers are not started. 
Pod status: CreateContainerConfigError
Error: container has runAsNonRoot and image will run as root

**Solution**: 
Need to add PSP for kiali-operator and update the role spec, deploy/merge scripts.

**Comment by jmazzitelli** [comment]
This issue needs more details. Please fill in the "new issue" template so it is more clear what you are asking for. I am including the template below so you don't have to press the "new issue" button again:

----

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here. If it is about a new design, please attach a drawing of a potential solution.
For backend changes also describe how one could test the new feature and how it impacts display on the UI.

**Comment by jshaughn** [comment]
@Sallyan @jmazzitelli I'm adding the Stale label here.  Should this be closed?

**Comment by lucasponce** [comment]
No new info from this issue.
I'm going to close it, please, if it's still open, add an update and we can re-open and plan an action on it.

**Comment by jmazzitelli** [comment]
FYI, PSP (PodSecurityPolicy) will soon be deprecated in Kubernetes. So we won't be doing anything wrt PSPs since it is going away soon. See: https://github.com/kubernetes/kubernetes/pull/97171

`The PodSecurityPolicy API is deprecated in 1.21, and will no longer be served starting in 1.25.`
