### ISSUE TITLE
Add insights from CI/CD

### ISSUE THREAD

**Issue by omerlh** [kiali/kiali#1299]
Add information like:
 - Git commit message
 - CI build link
 - Last publish date

Can be implemented maybe with labels or via plugins?

**Comment by israel-hdez** [comment]
I need more info. I don't understand clearly. 
Where this info should go? Is this for the [README](https://github.com/kiali/kiali/blob/master/README.adoc) file of the repo? Or is this something that you want to be visible in Kiali?

**Comment by jotak** [comment]
I guess this is extra workload information that we would like to see in workload details, right?
Maybe we can have a generic setup in Kiali to tell which annotations we want to display on the UI per workload, hence then it would be up to the user to fill these annotations.

What do you think, @omerlh , would it meet the requirement?

**Comment by omerlh** [comment]
Yeah, that actually sounds like a good solution.

**Comment by abonas** [comment]
To extend @jotak and @omerlh thoughts, perhaps this should be extended into "which annotations we want to display in the UI per all entities in Kiali", not only workloads? (but also services, for example)
At the moment the labels are displayed but indeed not annotations.

**Comment by omerlh** [comment]
yep, that sounds like a good suggestion

**Comment by abonas** [comment]
also tracked here https://issues.jboss.org/browse/KIALI-3192

**Comment by brianredbeard** [comment]
We should make sure when documenting this we are clear in what the goal is, are we surfacing information on [annotations][1], [labels][2], or both?

Fortunately labels have strict character limits which make them _less_ likely to break UI components.  

The guidance I've been given in the past is basically:

  - if you need to use the data to find or mutate a resource, use a label
  - if it's strictly informational, use an annotation

Regardless of the combination of [labels][2] and/or [annotations][2] we should make it clear which it is in the UI so that we can correctly set expectations (e.g. Oh, this datum is _clearly_ a label so I can make a query based on it). 

[1]: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
[2]: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/

**Comment by abonas** [comment]
@brianredbeard  this is how this is presented in okd, just 2 separate sections, I was leaning towards something similar:
http://openshift.github.io/openshift-origin-design/web-console/future-openshift/contextual-help/img/hint-next-step.png

**Comment by brianredbeard** [comment]
Works for me.

Ship it.

![shipit](https://media.giphy.com/media/dWM8tQEMJwdNu/giphy-downsized.gif)

**Comment by jotak** [comment]
I'm closing this one as the configurable annotations has been implemented ( https://github.com/kiali/kiali/issues/1564 ) ; please re-open if you think more can be done.
