### ISSUE TITLE
Graph filtered by single namespace shows other namespaces

### ISSUE THREAD

**Issue by ceastman-ibm** [kiali/kiali#1340]
**General remarks**
I have istio enabled in 5 namespaces, with microservices in each.

**Describe the bug**
Graph of a single namespace is showing things from other namespaces.

For UI issues please also add a screenshot that shows the issue.
<img width="1330" alt="Screen Shot 2019-08-14 at 10 01 45 AM" src="https://user-images.githubusercontent.com/25593207/63031970-92d17980-be7a-11e9-815e-05a90733b86f.png">

**Versions used**
Kiali: v0.20.0
Istio: 1.2.2
Kubernetes flavour and version: IBM Cloud 1.13

**To Reproduce**
1. Go to 'graph'
2. Click on 'namespace'
3. Select a single namespace

**Expected behavior**
To only see things in that namespace

**Comment by pilhuhn** [comment]
I think it is working as intended, but not as expected :-)
What I am trying to say is that we recognise that a mesh can span multiple namespaces. Now when you only select one namespace, as you did, we decided that if the mesh spans multiple, we restrict the view to the selected namespace, but also show that there are connections to other namespaces (nodes with the little mesh in them).

We should perhaps introduce a flag to "hard limit to 1 namespace", which would have the implication that a component like the central one your screenshot shows, may show metrics in the details views which can not be reproduced on the graph, because those edges are coming from other namespaces and which would then be removed by that option.

**Comment by jmazzitelli** [comment]
What @pilhuhn said. If you don't show those outgoing connections to external namespaces, you will have no idea where the outbound connections are going to... and, in fact, it will be worse because you will have no idea that a node is sending ANY outbound messages - it would look like the nodes are only receiving incoming connections but not sending anything. So that would then be the confusing thing if kiali didn't do what it is doing.

**Comment by mtho11** [comment]
A workaround could be to use the 'hide' feature.

**Comment by josejulio** [comment]
> A workaround could be to use the 'hide' feature.

Something like `namespace!=istio-system` would work.

**Comment by ceastman-ibm** [comment]
can i string namespaces in the hide field? like namespace!=istio-system,red,live ?

**Comment by ceastman-ibm** [comment]
thank you for the clarification.

**Comment by mtho11** [comment]
> can i string namespaces in the hide field? like namespace!=istio-system,red,live ?

Not sure if you got your question answered.
You can use `and` in the find field. If you click on the `?` help icon you can find more info and examples. For instance: `namespace != istio-system and namespace != red and namespace != live`

**Comment by abonas** [comment]
I'm in favor of adding an option in the Display drop down menu - a checkbox of something like "show connections to other namespaces". Similar to the "show service nodes" and "show unused"

**Comment by jshaughn** [comment]
@ceastman-ibm , As mentioned above you can use AND.   If you want to hide all of the outside namespaces just type 'outside' in the hide box.
