### ISSUE TITLE
Support the new Istio AuthorizationPolicy CRD

### ISSUE THREAD

**Issue by yangminzhu** [kiali/kiali#1344]
**Is your feature request related to a problem? Please describe.**
Per request in https://github.com/istio/installer/pull/333#issuecomment-521764522

Note, the AuthorizationPolicy is the new approved access control policy in Istio that is going to replace the previous RBAC policy.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
The CRD is added to Istio in https://github.com/istio/istio/pull/16187

**Comment by yangminzhu** [comment]
cc @jmazzitelli

**Comment by jmazzitelli** [comment]
@yangminzhu can you confirm - all that we need in Kiali is the additional permissions - is that correct? I'm speaking of these: https://github.com/istio/istio/pull/16187/files#diff-12c9c53058b0643bb179e26064592c09R134

So we just need to make sure kiali has those permissions?

**Comment by jmazzitelli** [comment]
For now, it seems we just need to do the following:

Three main places to change these (ignoring all the OLM/operatorhub manifests):

For both kubernetes and openshift templates, in role.yaml, we need to add the ones with the read/write permissions and in role-viewer.yaml just the read-only permissions:

https://github.com/kiali/kiali/tree/master/operator/roles/kiali-deploy/templates/kubernetes
https://github.com/kiali/kiali/tree/master/operator/roles/kiali-deploy/templates/openshift

And then the operator needs the read/write permissions because it has to be able to give kiali those perms - so we need to add them here too:

https://github.com/kiali/kiali/blob/master/operator/deploy/role.yaml

**Comment by jshaughn** [comment]
From what I can tell this won't be in upstream until the 1.4 release.

**Comment by lucasponce** [comment]
Yeah, probably we want to add in the kiali version (TBD) what will be target for Istio 1.4

**Comment by xeviknal** [comment]
Closing per https://github.com/kiali/kiali/pull/2028
@yangminzhu let us know if the outcome of that PR is aligned with your expectations. Thanks.
