### ISSUE TITLE
Multi-cluster: App graph support with virtual service routing (multiple control plane)

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#1365]
In a multi-cluster setup with multiple control planes, it is possible to load balance traffic using virtual services. Load-balancing can route traffic to local and remote services using a VS (see yaml example in #1364).

Currently, under this setup, the "app graph" is generating wrong connections:

![image](https://user-images.githubusercontent.com/23639005/63559818-147b7400-c519-11e9-93c5-446b87c42992.png)

The graph is generating a connection between the _details-small_ ServiceEntry to the _details_ workload and the same happens for the _reviews_ case. This is not true, because the _details-small_ and the _reviews-small_ services are in a remote cluster.

What is happening is that the productpage workload is making calls to the _details-small_ and _reviews-small_ remote services, and also to the local _details_ and _reviews_ services. 

_The issue is present only when Service nodes are displayed._

The goal is to adequately and consistently resolve traffic to, both, local and remote services when a VirtualService is involved.

**Comment by jshaughn** [comment]
OK, so as you explained to me in chat, the ability for a service in clusterA to requests a service in clusterB is done via ServiceEntry definitions that sort-of "forward" the request out of clusterA and into clusterB.  The ServiceEntry definitions are MESH_INTERNAL because, I assume, we're still talking about mesh-managed services.

My gut feeling is that the root problem here, and probably in the other graphs as well, is that we're not properly identifying the service node (actually, serviceEntry) because most likely the namespace is not "unknown".  Looking at the telemetry will help.
