### ISSUE TITLE
Indicating in UI that a pod has been ejected in outlier detection situations

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1399]
I think this should be a research task to see if an indication on ejected pod is available.
https://istio.io/docs/reference/config/istio.networking.v1alpha3/#OutlierDetection

Pods can be ejected from load balancing in certain conditions, as defined in outlier detection.
If Istio/Envoy can provide an indication on that, then Kiali should visually indicate that on the relevant service/workload, graph, etc.

JIRA:
https://issues.jboss.org/browse/KIALI-2084

**Comment by jshaughn** [comment]
@lucasponce, @abonas, When outlier detection opens a circuit breaker the destination become unreachable as client proxies are told it's unavailable.  **If that is what this issue is about** then I think we already have this, or at least partially.  Open CBs cause request failures, and with the response flags now available in the side panel, a user can click an edge and see the response codes indicating that failures are related to an open CB.

If we want to make it even more explicit we'd need to discuss how it should be done, perhaps badging on the affected edge, I'm not sure.

But, **if this issue is about evicted pods** that's different, and I think very valuable.  That is a k8s thing as opposed to Istio.  I think we may want to add pod eviction to Health calculation.  It is probably too heavy for the core graph as we avoid pulling the complete service information.  But the async Health calc already pull the Service pods, and presumably the pod status.

So, let's figure out what this issue is about, and also whether we may want to add one for evicted pods.

**Comment by lucasponce** [comment]
I think that the info brought from Istio as @jshaughn comments is defined in the Graph.

From Workload health, Kiali fetches the desired/current/available replicas which in practice gives information about this problem (i.e. I want 5 pods but there are only 3).

Also, the Pods are listed in the workload with details about the Phase.

One thing that perhaps we can improve is to mark better when a Pod has been "evicted".
Kiali fetches the Phase but that's not enough, probably we need to dig into the PodConditions, or the Message/Reason, as evicted messages are marked there.

But I only envision to extend the Workload Details to have a better details of the Pod list.

**Comment by jshaughn** [comment]
@lucasponce I am +1 to anything that would indicate pod "eviction".  This seems to me a very tricky thing for ops guys as it can explain problems that are related not the app but to the resources available in the cluster.

**Comment by cfcosta** [comment]
So, after lots of investigation and testing on this, I think we can either close it or if someone can take a look at it with a fresh mind and find something new to test.

CB failures are already shown on Kiali, so the main idea is to show when/if the pods have been evicted for some reason, and the problem here is that both on PodConditions and on kube events, evicted pods inside the cluster always show as HorizontalAutoScaler events, without more information that can actually be used.

What I've tried:
- Forceful quit from inside the container.
- CPU Leak without limits on the deployment
- Memory leak without limits on the deployment
- Memory and CPU leak with limits on the deployment

All of them didn't return any kind of information that I could reliably use, unfortunately, and the events are shown as if the pod/deployment has been rescheduled, not dropped.

**Comment by lucasponce** [comment]
As a user perhaps I don't want to go deep.
But one thing that can improve a lot is to collect the # of restarts and make that info available in the current health.
Today we collect the current/desire # of Pods and health react to that.

One thing that would add value is to also indicate if some workload has an unusual # of restarts.

I'm fine if we change the scope of this issue to that.

Out of the scope would be to integrate this with the current health config logic (that can be a separated task) but adding support fo restarts is something we definetely would like to pursue.

**Comment by jshaughn** [comment]
I'm going to try and do something simple to see if we can make some progress on this.  At first it will just be for display and we'll go from there.
