### ISSUE TITLE
Research alerting options

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1416]
We probably need to research a bit into what our options could be around Kiali and alerting.

I suspect this likely means integrating with the p8s alert manager, but there could be other things to consider.

We also need to figure out the story of what Kiali could be doing with alerts.

Do we want Kiali to receive alerts and show a pop up?
Do we want Kiali to be able to configure when an alert is triggered and where it goes?
Do we want Kiali data to be a trigger for events (eg have Kiali health checks be stored as metrics in p8s and have an alert go out if the health checks are failing)
Or are there completely other things we should be considering here
The goal of this research spike is to figure out potential options, record those options in a document and facilitate a meeting/discussion around what we might want to be doing here.

JIRA:
https://issues.jboss.org/browse/KIALI-2720

**Comment by lucasponce** [comment]
I think we are in an agreement that Kiali may read additional signals (alerting) in the high level correlation context.

But it is also clear that alert management is out of the scope.

**Comment by lucasponce** [comment]
@jshaughn perhaps I'd like to bring this one to our next grooming.

**Comment by jshaughn** [comment]
It's been a long time since we thought much about this issue, but I think it's still relevant.  Looking back at the description I think it's still true that we defer to Prometheus Alerting as an actual alerting system to be used with the Istio service mesh.   But I'm thinking maybe we want to revisit, "Do we want Kiali data to be a trigger for events (eg have Kiali health checks be stored as metrics in p8s".    Kiali detects a variety of things and could feasibly generate useful metrics for users to trigger off of.  One issue, though, is that Kiali is a UI and as such is not really doing any monitoring unless initiated by a user. Furthermore, users could be doing any variety of things.  I don't think anyone is interseted in alerting based on the ad hoc interactions of the UI.   I'm not sure what the answer is but I'm wondering if we should consider a Kiali monitor process that could "crawl" the mesh and perform our various validations, checks, etc, and potentially generate telemetry.

**Comment by lucasponce** [comment]
I don't think that the direction of Kiali should be to provide another signal but consume existing signals.
The trend in Istio was to eliminate the bottleneck of the telemetry, let the prometheus to collect information from the workloads.

A Kiali monitor to crawl information changes the direction about what Kiali is designed.

Another discussion is if to compute those signals Kiali can use some level of cache mechanism that may help to scale.

**Comment by jshaughn** [comment]
I agree that Kiali's purpose is not to provide signals or to perform alerting, but I'm not sure generating metrics is outside of our scope.  We are trying to help mesh users configure and validate their mesh, then help locate/detect and debug issues.  Our configurable health detection and "interesting" trace identification are value-added detection capabilities that are designed to surface issued in the UI, but not necessarily only useful in that fashion.  Minimally, though, we could even [optionally] generate metrics solely based on UI-based requests.

**Comment by lucasponce** [comment]
> Minimally, though, we could even [optionally] generate metrics solely based on UI-based requests.

I don't think so.

OpenTelemetry and other projects are working in that space, to collect these signals and provide better insights, and potentially to combine with other domains (infrastructure and application domains).

I doubt that a Mesh health can work without those spaces, so what is in the scope of Kiali is to use better the signals that are currently available rather than generate new ones.

And let users to understand and use efficiently the Mesh. But Mesh can't work isolated from infrastructure and application layers, so instead to be a player in those space we should prioritize a better integration.

Otherwise, as soon as you try to move in that space you will find that there is a better project working in that direction.

**Comment by jshaughn** [comment]
@lucasponce At this point I don't see anything here for us, shall we close it?

**Comment by lucasponce** [comment]
> At this point I don't see anything here for us, shall we close it?

+1
