### ISSUE TITLE
Have a Kiali instance available to the public

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1432]
It would be nice if we had a Kiali instance available to the public internet so people can play with Kiali by simply pointing their browser to some public URL.

We have people ask for this already.

JIRA:
https://issues.jboss.org/browse/KIALI-1545

**Comment by israel-hdez** [comment]
I will close this one as stale.

This has been around for a little more than a year.

The blocker is to find a place to host the public instance. Since this was initially proposed, I've tried several times a search on the web and I couldn't find a free place to host this. If it will cost, it's probably not worth it.

Also, I haven't heard people asking for this after it was initially proposed. Please, consider re-opening once we have a place to host the public instance.
