### ISSUE TITLE
Istio supports multiple app/version labels - kiali needs to support these also

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1458]
"As a Kiali user, I want the new app label changes to be supported in Kiali so that my grouping works as expected"

see https://github.com/istio/istio/issues/10724

There are multiple app and version labels that Istio supports in 1.1. Kiali needs to support these, too.

The app label can be named one of these three, in this order of precedence (as mentioned in the above github issue):

1. app
2. app.kubernetes.io/instance
3. app.kubernetes.io/name

The version label can be named one of these two, in this order of precedence:

1. version
2. app.kubernetes.io/version

JIRA:
https://issues.jboss.org/browse/KIALI-2211

**Comment by Starefossen** [comment]
Anything we can do to move this forward?

**Comment by abonas** [comment]
> Anything we can do to move this forward? These labels are now the default for any new Helm Charts.

@Starefossen is this supported already in upstream Istio? I saw some discussions and an open issue, but didn't find anything merged there.

**Comment by mtho11** [comment]
@jmazzitelli @jshaughn is this supported yet? Should it get added to the sprint?

**Comment by jmazzitelli** [comment]
We can support one set of app/version labels - and they can be whatever you want them to be. That is supported.

What is NOT supported is supporting MULTIPLE label pairs. So today Kiali cannot support app labels  of EITHER "app" OR "app.kubernetes.io/name" OR "app.kubernetes.io/instance". It has to be just one - take your pick and whatever you want you set it in the Kiali CR (default is "app"). Same for "version".

At one point I tried to code up support for this and it was really ugly because Kubernetes itself doesn't let you query for multiple label names like we would need, so it would mean Kiali needs to perform multiple queries, which would end up causing a lot of extra queries being done (and thus causing a performance hit).

**Comment by jshaughn** [comment]
Related to https://github.com/kiali/kiali/issues/2276 which is about the new canonical_service metric labels.  Those labels should be used in graph gen but it's not really clear how we use that value to tie to istio config objects.

**Comment by jotak** [comment]
Is this still an issue? (In the light of what @jmazzitelli said: custom labels are already supported, what is not is having several names used *at the same time* per instance of kiali)

If it is, perhaps we can have a different approach now that cache is enabled. Like fetching all workloads / objects in the namespace, then doing our own filtering with multiple label names. With cache enabled, the performance impact would probably be minor.

**Comment by jshaughn** [comment]
@jotak I'm thinking we can close this issue and re-open a new issue if and when a specific problem case appears.  From the metrics side we can use the canonical fields.  For object query I think we can assume users use a single scheme, either app/version or the standard k8s labels, and can set that in our config as needed.   I'm not sure app/version will serve as the best default going forward but for backward compatibility we probably don't want to change our defaults.
