### ISSUE TITLE
Make expired/unauthorised dialogs more user friendly

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1470]
Currently, we show messages like "backend returned code 401" or "Has your session expired? Try logging again". 
The 1st one is a technical code that should not be shown to the user. The 2nd one is better, but still "Try logging again" does not help the user.

JIRA:
https://issues.jboss.org/browse/KIALI-2489

**Comment by israel-hdez** [comment]
Closing this as outdated and no longer valid, because the "Has your session expired?" message is no longer shown.

As commented in the JIRA, currently the user is being redirected to the login screen with a better message.

In the Jira, a "dashboard" mode has been suggested. If that mode is desirable, a new issue should be opened.
