### ISSUE TITLE
Investigate Istio telemetry 1.3.x support

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1569]
We need to have someone look into the changes happening in Istio 1.3.x and create issues for things which may need to be changed in Kiali, or new features that we might want to incorporate.

JIRA:
https://issues.jboss.org/browse/KIALI-3219

**Comment by jshaughn** [comment]
With RC1 the number of CRDs seems to have increased to 24.  Upping the helm installer again: 

https://github.com/kiali/kiali/pull/1636

**Comment by jshaughn** [comment]
Some more investigation around PassthroughCluster.   I was able to see the requested endpoints of requests leaving the mesh (For example, www.google.com).  When I say "see" I mean it's in the telemetry, it is not shown by Kiali.  I am thinking that we may want to try and capture this info if users do the necessary Istio configuration.  

To get the additional information you need to add the "request_host" label to the istio_requests_total metric.  I did that by  editing install/kubernetes/helm/istio/charts/mixer/templates/config.yaml and adding it in the requestcount instance and also in the prometheus handler, and then re-running the helm template.

We may want to try and support the information in request_host, if it is configured, because users may want to know what endpoints are being requested.

**Comment by jshaughn** [comment]
RC3 CRD count now 25: https://github.com/kiali/kiali/pull/1659

**Comment by jshaughn** [comment]
GA CRD count now 23: https://github.com/kiali/kiali/pull/1671

**Comment by jshaughn** [comment]
OK, I'm going to close this.  1.3.0 is released.  The current version of Kiali should work against it and the next version of Kiali 1.5.0 will have some added support.

I am following up with https://github.com/kiali/kiali/issues/1694 to investigate the experimental mixer-less telemetry.
