### ISSUE TITLE
Add indication if certificates are managed by Citadel or external tool

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1577]
Add indication in UI if certificates are managed by Citadel or external tool

JIRA:
https://issues.jboss.org/browse/KIALI-3226

**Comment by xeviknal** [comment]
I've done some research wrt to certificate management on Istio. I came up with this.
I am not sure which of the following scenarios covers the description of the issue.
cc @abonas 

## Certificate Management

AFAIK, there are multiple certificates involved around the whole security features in Istio.
1. Automatic certification management for each workload in the mesh.
2. Certification of ingress gateway.

For the **first option**, SDS and Citadel (Istiod) are in charge of the certification life-cycle[1]. Customization available in this area are:

1. Allow Chiron and K8s API to be responsible for certs provisioning and management. [2] [3]
2. Plug-in CA certificates. [4] [5]
3. Workload Certificate TTL - default to 90 days (security.workloadCertTtl variable) [5] [13]
4. Root Certificate expiration date [6] [7]

For the **second option**, the ingress gateway may be using three types of certificates:

1. Managed by a cert-manager (e.g. Let’s Encrypt) with k8s Ingress [8]
2. Own certificates mounted into the ingress pod filesystem [9]
3. Own certificates sent to envoy directly (avoid filesystem) through SDS [10]
4. No certificate enabled.

Most of the options mentioned above might be included into the console. However, they might require certificate manipulation. GoLang has the [x509 library](https://golang.org/pkg/crypto/x509/#Certificate) that ease this task.

## Implementation

Steps to fetch the solution of **first option** scenarios and show it into Kiali:

### Allow Chiron and K8s API to be responsible for certs provisioning and management

1. Fetch Istio ConfigMap
2. Detect the field `mesh.certificates`

```
   certificates:
      - dnsNames:
        - example1.istio-system.svc
        - example1.istio-system
        secretName: dns.example1-service-account
      - dnsNames:
        - example2.istio-system.svc
        - example2.istio-system
        secretName: dns.example2-service-account
```
3. Make sure certificates are present into istio-system (as a secret)
3.1 kubectl get secret dns.example1-service-account -n istio-system

4. **In Kiali show**:
4.1 List of DNS certificates managed by Chiron and K8S
4.2 Show a warning if the secret is not found into istio-system
4.3 read the certificate and show related information ([Golang package](https://golang.org/pkg/crypto/x509/#Certificate)) and display metadata like Issuer, Not before, Not after dates and location (for multi clustering [12]).

refs:[2] [3]

### Plug-in CA certificates

In order to Plug-in the CA certificates, the user needs to add the `cacerts` secrets into CP namespace (e.g. istio-system). The secret has to have this specific name and has the specific files within it. If the following conditions are matched, then the CA is plugged into Istio CP.
1. Secret named `cacerts` and has to contain the following files:
2. Has the `ca-cert.pem` file
3. Has the `ca-key.pem` file, 
4. Has the `root-cert.pem` file,
5. Has the `cert-chain.pem` file

If the conditions aren’t matched, then istio creates its own CA secrets file names `istio-ca-secret`.

However, and similarly to the previous section, there is the option to display the Issuer, Expiration date, and other certificate-related information. Likewise, it would require certificate manipulations ([openssl](https://golang.org/pkg/crypto/x509/)) to process that information.

**In Kiali show**: 
Show the Root CA certificate metadata (of course, not revealing the cert itself):
- Issuer
- Location (important for multi clustering)[12]
- Validity timestamp (not before, not after)

Also Kiali might show a warning if both secrets are found. I’d mean that Istio didn’t find the self-signed CA certificates and citadel (istiod) creates it during the installation process.

Refs: [4] [5]

### Workload Certificate TTL - default to 90 days (security.workloadCertTtl variable)

Istio allows its users to specify the lifetime of their workload certificates (TTL)[13]. Two parameters are needed for this: `max-workload-cert-ttl` and `workload-cert-ttl`. The wrong definition of these parameters might lead to issues because of too much rotation in the control plane.

- Fetch the istiod deployment
- Look for both parameters into the `args` list.
- Show it in the UI.
  - It might be useful to show some warnings if `workload-cert-ttl` is greater than `max-workload-cert-ttl`.

refs: [5][13]

### Root Certificate expiration date 

It is covered in the first option, second scenario.
1. Fetch cacerts secrets from istio control plane.
2. Read the root CA from that secret and present the metadata around it.
3. Kiali could show a warning if the certificate is close to expiration date or it has already expired.

Refs: [6] [7]

## Proposal
Create a section into Kiali (around the masthead, perhaps into the dropdown) where Kiali will show:
1. Root CA certificate metadata (Issuer, Location Validity timestamps) from either istio-ca-certs or cacerts secret placed into CP namespace.
2. If Chiron is enabled, show the list of dnsNames and secrets created. For each one, show the certificate metadata.
3. Show the WorkloadTtl and maxWorkloadTtl params from Istiod.

Ingress certificate management might be researched in the future. Unless this issue also target this scenario.

[1] https://istio.io/docs/concepts/security/#pki

[2] https://istio.io/docs/tasks/security/dns-cert/
[3] https://istio.io/blog/2019/dns-cert/

[4] https://istio.io/docs/tasks/security/plugin-ca-cert/
[5] https://istio.io/docs/reference/config/installation-options/#security-options

[6] https://istio.io/docs/ops/configuration/security/root-transition/
[7] https://istio.io/docs/reference/commands/istio_ca/#envvars

[8] https://istio.io/docs/tasks/traffic-management/ingress/ingress-certmgr/
[9] https://istio.io/docs/tasks/traffic-management/ingress/secure-ingress-mount/
[10] https://istio.io/docs/tasks/traffic-management/ingress/secure-ingress-sds/
[11] https://istio.io/docs/ops/diagnostic-tools/controlz/
[12] https://github.com/istio/istio/tree/master/samples/certs#generating-certificates-for-bootstrapping-multicluster-chain-of-trust
[13] https://istio.io/faq/security/#cert-lifetime-config

**Comment by sandeep1699** [comment]
Hi @xeviknal 

Sorry i'm new to istio, could you please let me know, can we use k8s CA as a signing authority for workload proxies using chiron?

**Comment by xeviknal** [comment]
Hi @sandeep1699, from Kiali perspective, I am not sure how to support you so far. We haven't supported any integration with regards to certificate management yet. Nevertheless, when researching for this issue I found the following task [1] in istio website.

For further information, I'd recommend you to address this question in discuss.istio.io, the istio community discussion forum.

[1] https://istio.io/latest/docs/tasks/security/cert-management/dns-cert/

**Comment by lucasponce** [comment]
This issue is still valid.

The scope as commented by @xeviknal should be reduced to:

```
Create a section into Kiali (around the masthead, perhaps into the dropdown) where Kiali will show:

Root CA certificate metadata (Issuer, Location Validity timestamps) from either istio-ca-certs or cacerts secret placed into CP namespace.
If Chiron is enabled, show the list of dnsNames and secrets created. For each one, show the certificate metadata.
Show the WorkloadTtl and maxWorkloadTtl params from Istiod.
```

**Comment by lucasponce** [comment]
I think it could be good if @leandroberetta gets familiar with this area as well.
@xeviknal can review or update the scope of the issue if this comment https://github.com/kiali/kiali/issues/1577#issuecomment-779206144 is outdated.

**Comment by jmazzitelli** [comment]
If, in order to implement this "show details of the secret in the masthead" requires Kiali and the operator to be granted cluster-wide "read secret" permission, I'm going to have to stamp a "-1" on this.

We specifically have been avoiding adding this "read any secret" permission because of the huge security implications. People do not like it (we recently had a community member complain about our current ability to read secrets in the control plane namepace). This is a very, very bad (potential) security hold that kiali would be opening up.

We need to avoid this permission. If you need to read a specific secret, we can do so by name as we do here: https://github.com/kiali/helm-charts/blob/master/kiali-operator/templates/clusterrole.yaml#L41-L52

But do NOT add a blanket "read any and all secrets in the entire cluster" permission - especially if we only need it to show details in the masthead. The benefits in that case do not outweigh the risks.

**Comment by leandroberetta** [comment]
> We need to avoid this permission. If you need to read a specific secret, we can do so by name as we do here: https://github.com/kiali/helm-charts/blob/master/kiali-operator/templates/clusterrole.yaml#L41-L52

I understand, reading specific secrets by name would work for some cases of this feature set, but there is one case (when using Chiron) that we need to read secrets configured in istio configmap and we wouldn't know the names in advance.

> But do NOT add a blanket "read any and all secrets in the entire cluster" permission - especially if we only need it to show details in the masthead. The benefits in that case do not outweigh the risks.

+1 for an open discussion.

**Comment by xeviknal** [comment]
@jmazzitelli you are right. Could there be a dynamic role? Like the operator creating a role for the files specified in the configuration? Just giving permissions to secrets A, B, and C specified in the CR/CM.

**Comment by jmazzitelli** [comment]
> Could there be a dynamic role? Like the operator creating a role for the files specified in the configuration? Just giving permissions to secrets A, B, and C specified in the CR/CM.

Let's think about that. In the end, I think there is still an issue we need to resolve and get the community to comment on, but this is something to consider.

First, we already have the ability to "list" secrets in the control plane (e.g. `istio-system`) (this is "list" not "get" - so today we can't read them - we can just get their names) - see the [kiali "control plane role"](https://github.com/kiali/helm-charts/blob/v1.37.0/kiali-server/templates/role-controlplane.yaml) that the server is granted. 

In order to be able to grant this permission - the operator itself also has this permission (and the operator has this permission cluster-wide, too - because the operator needs to be able to create Kiali servers in any namespace). The operator also has the permission (cluster-wide) to watch and create secrets (it needs this because it may need to create the kiali-signing-key -- see: https://github.com/kiali/helm-charts/blob/v1.37.0/kiali-operator/templates/clusterrole.yaml#L34-L40) But the operator does NOT have the permission to "get" secrets cluster-wide - so it can't ready them.

Let's say we add this new feature to the Kiali CR - something like:

```
deployment:
  accessible_secrets: ['A', 'B']
```

Just like our "accessible_namespaces", here we list secrets we want Kiali to access. The operator could add permissions to this [control plane role](https://github.com/kiali/helm-charts/blob/v1.37.0/kiali-server/templates/role-controlplane.yaml) (the thing I mentioned above) so the kiali server can get the content of those named secrets. Now, this is only good to read secrets IN THE control plane. Which I think is good - that's where we expect these secrets to be right? No need to grant cluster-wide "read secret" if the secrets we care about are in the control plane namespace only.

We *could* expand this feature to allow a role to be created in other namespaces to read other secrets in those namespaces, but that would be more complicated to code. It is doable, but tricky and we have to be careful that the operator removes these roles when someone removes them from the Kiali CR (or deletes the CR entirely). We have to be very careful as any bug in this area could expose secrets. We also need to code this up in the server helm chart - it is much easier to do if we just support control-plane-namespace-only secrets.

There are 2 things:

1) Is it OK to restrict this feature to read secrets ONLY found in the control plane? If so, that is must easier to code up and would introduce less of these security issues I'm worried about.

2) This STILL has the problem of requiring a "read-any-secret-cluster-wide" permission to be granted to the operator service account - the operator needs that because it will have to be able to grant "read-secret" in any namespace (because a Kiali can be installed in any control plane namespace which can be anywhere in the cluster and can ask to read any secret via this new accessible_secrets setting). So we still have to answer the question, "Are we ok introducing a kiali cluster role to get secrets?" I'm still not convinced this is a good idea. Again, we need this discussed more out in the open so we have full community participation to answer that question.

**Comment by leandroberetta** [comment]
@jmazzitelli (1) it is OK to restrict this feature to read secrets ONLY in the control plane namespace.

Regarding (2), I understand that will be users that don't like this, but others maybe want this feature, so a feature flag could be a solution letting the users choose to active this or not. 

Anyway, for the users that activate this feature, we will still have the operator with the read secrets permission in their clusters.

I'm thinking possibilities to see this feature viable.

**Comment by jmazzitelli** [comment]
We have something similar in the operator - you can tell the operator NOT to be given create-cluster-role permissions via a helm chart setting. If you take away that permission, the operator cannot support accessible_namespaces="**" (in fact, that "can-i" PR using self-subject-access-review you just tested/approved is the thing that checks for this and aborts with a human-readable error message when the permission is not granted). We could do the same for this read-all-secrets, too, if we want.

That doesn't help OLM installed operators - there is no way today for users to give/take permissions from operators via OLM

**Comment by xeviknal** [comment]
@leandroberetta is the feature still interesting if we only have access to control plane secrets? Which scenarios couldn't progress because of this limitation?

**Comment by leandroberetta** [comment]
@xeviknal I guess that yes, but we still have the issue where the operator service account has cluster wide read secrets permissions.

As far as I can see and investigate, all these secrets will be in the control plane namespace

- cacerts
- isio-ca-secret
- other secrets name for canaries
- chiron secrets (that are called according the mesh configuration in istio configmap)

I couldn't find a way to declare that these secrets belong to other namespaces, so pretty sure they will be in the control plane namespace.
