### ISSUE TITLE
Quarkus runtime metrics are outdated 

### ISSUE THREAD

**Issue by pavolloffay** [kiali/kiali#1622]
Quarkus runtime metrics are outdated. https://github.com/kiali/kiali/blob/master/operator/roles/kiali-deploy/templates/dashboards/quarkus.yaml does not work with Quarkus 0.19.0 (MP metrics 1.x) nor Quarkus 0.20.0 (MP metrics 2.x).

It would be also great to provide MP metrics 2.x template.

**Comment by jshaughn** [comment]
@jotak Is this issue still relevant?

**Comment by jotak** [comment]
It depends on what we want to do. Yes, the dashboard is still outdated, but, who's going to maintain it in the long run?
There's currently 20 dashboards out there: https://github.com/kiali/kiali-operator/tree/master/roles/default/kiali-deploy/templates/dashboards

Perhaps we could try to call for help on maintaining them? (maintainers who have expertise on the appropriate runtime).
Else, we can also consider reducing the scope of supported runtimes.

We have so far:
- quarkus: find maintainer?
- several springboot dashboards: find maintainer?
- several vert.x dashboards: I can maintain them since I'm also maintainer of vertx-micrometer-metrics module
- thorntail: find maintainer?
- node.js: find maintainer?
- envoy: this one should be maintained by the team; some problems though, needs investigation, cf https://github.com/kiali/kiali/issues/2582
- go and kiali: I guess it is fair to continue to support them, it's dogfooding and has proved to be useful a couple of times

**Comment by lucasponce** [comment]
> It depends on what we want to do. Yes, the dashboard is still outdated, but, who's going to maintain it in the long run?

I think goal here would be to check if there is any gap in the documentation, in a way that someone from the community may update the dashboards without knowledge about Kiali development.

Probably, Kiali team may focus in the Envoy one as being discussed in the #2582 but let the runtimes as a community effort.

**Comment by lucasponce** [comment]
I think is reasonable to close this one.
To me, runtime dashboards should be maintained by users, Kiali has improved the way to personalize the dashboards using annotations in https://github.com/kiali/kiali/issues/4145.

So, these dashboards will be outdated soon, so, they can be used as examples that user can update, and at some point the defaults could be updated.
