### ISSUE TITLE
Have an interactive legend on metrics charts (k-charted)

### ISSUE THREAD

**Issue by pavolloffay** [kiali/kiali#1648]
When a chart is showing multiple metrics at the same time it's very hard to match the legend with values. 

Some thoughts: 
* hovering on line could highline line and value in the legend
* use more distinctive colors - the chart is showing 4 types of blue color

![Screenshot of Kiali  istio-system  (2)](https://user-images.githubusercontent.com/5618424/64531641-41e56180-d310-11e9-8b50-f09666c86b58.png)

**Comment by jotak** [comment]
Hi @pavolloffay ,
Kiali has switched now to a different charting library so this is different.
See how it looks:

![Imgur](https://imgur.com/RU8A5a4)

As you can see, tooltips now show only datapoints hovered and not all datapoints on timestamp. Also, the colors cycle is better / more diverse.

There's also some drawbacks compared to the previous lib, e.g. legend is not interactive. Feel free to continue to give feedback :)

**Comment by pavolloffay** [comment]
* The hovered box could contain the color next to the text.
* It could highlight also the hole line.

**Comment by lucasponce** [comment]
@jotak any action for this one with latest comments from @pavolloffay ?
(Just if we can move this issue to backlog or it's not clear what changes we can implement on it).

**Comment by jotak** [comment]
I'm going to put it under backlog. Maybe I'll split in two different tasks: one about legend and one about tooltip.
For the legend we've already improved some charts, but not k-charted yet, so that's something to do that can go to the backlog.
For the tooltip the current one is not fully satisfying, as @pavolloffay says it'd be nice to get colored indication next to the text. But it's a field of investigation with patternfly too.

**Comment by jotak** [comment]
@lucasponce @pavolloffay I've split the tooltip related one: https://github.com/kiali/kiali/issues/1792
