### ISSUE TITLE
LDAP issue regarding bind user

### ISSUE THREAD

**Issue by lpereiraa** [kiali/kiali#1655]
Good morning, good people @Kiali,

First of all, congrats on the awesome work developed on this project.

We are having an issue when attempting to configure Kiali's newly implemented LDAP service. Since there's no way to specify a bind user (with it's own bind user password), we have no way to recursivelly search through the AD tree, so we are stuck in searching on only one OU, and the user can only be searched using it's CN, and not other object attribute (like sAMAccountName). 

Thanks in advance for your attention.

**Comment by lucasponce** [comment]
cc @israel-hdez

**Comment by jmazzitelli** [comment]
switching label to "enhancement" as this is asking for a feature to allow for specifying another user to perform the search

**Comment by jshaughn** [comment]
The LDAP support is a feature contributed by the community and we'd like to see enhancements also contributed.  Perhaps the original LDAP contributor would be interested in the enhancement: @Maneshme, what do you think?

**Comment by israel-hdez** [comment]
@lpereiraa about the CN constraint, I think you can use the available lap options documented in https://www.kiali.io/documentation/getting-started/#_ldap. I haven't tried, but perhaps you could use the ldap_user_filter option. Mosty likely, you can search recursively (I guess that's the use of ldap_base and ldap_user_filter options); but since the ldap_bind_dn has a fixed depth, that probably means that, at the end, you cannot authenticate against users in different OUs.

Perhaps @Maneshme could comment better.

**Comment by israel-hdez** [comment]
Hi!
Unfortunately, the LDAP implementation in Kiali has been deprecated and will no longer be maintained. So, I'm clossing this ticket -- sorry for the inconvenience.

In Kiali v1.19 a new _openid_ authentication strategy has been implemented. Our recommendation is that you use an OpenID connect provider that has support for LDAP (like [Keycloak](https://www.keycloak.org/) or [Dex](https://github.com/dexidp/dex), which will offer much more robust LDAP implementation than what we could offer in Kiali)
