### ISSUE TITLE
Kiali restarts when bookinfo project is deleted and created again

### ISSUE THREAD

**Issue by pavolloffay** [kiali/kiali#1660]
Kiali pod restarts when bookinfo namespace is created.

Steps to reproduce:
1. create bookinfo project
2. delete bookinfo project

Kiali always restarts in step 2. however in the previous workflows I have deployed full bookinfo app in the project - not sure if that affects the restart. I have been seeing this behavior when preparing for the red hat forum.

```
Kiali-ui
1.0.3
Kiali
v1.0.5.redhat1
Components
OpenShift Service Mesh
1.0.0
Prometheus
2.7.2
Kubernetes
v1.13.4+df9cebc
GrafanaURL
https://grafana-istio-system.apps.ploffay.crossproduct.rhmw.io
JaegerURL
https://jaeger-istio-system.apps.ploffay.crossproduct.rhmw.io

```

**Comment by gbaufake** [comment]
That is expected because kiali receives a new list of accessible list
though the service mesh member roll if I am not mistaken.

@John Mazzitelli <mazz@redhat.com> @mazz can give more details on it

**Comment by jmazzitelli** [comment]
I don't see why Kiali would ever have to restart (or even care) that bookinfo namespace is deleted unless maybe this is in the context of Maistra/ServiceMesh? If so, then yeah, its probably due to the change Maistra is making ultimately in the kiali accessible namespaces list in the Kiali CR. We have changed this behavior in the latest code - Kiali will do a rolling re-deployment so the downtime is minimal and hopefully not very noticeable by the user.

See: https://github.com/kiali/kiali/pull/1348

**Comment by pavolloffay** [comment]
It was in the context of maistra/serviceMesh. I have deployed https://gitlab.cee.redhat.com/istio/install-rhossm/tree/master and this SMCP CR https://github.com/pavolloffay/istio-bookinfo-redhat-forum-zurich-2019/blob/master/manifests/smcp.yaml.

After the service mesh deployment I didn't edit any CRs, just created and deleted namespace. The restart of Kiali was noticeable in my case.

**Comment by jmazzitelli** [comment]
> The restart of Kiali was noticeable in my case.

It won't be noticeable in the next productization release based on the current kiali codebase thanks to PR #1348
