### ISSUE TITLE
Session expired dialog - Logout fails

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#1662]
When Kiali session is expired, it shows a dialog box, which has an option to Log Out.
But in fact Logout fails with a loop of error notifications:

![Screenshot from 2019-09-11 09-45-50](https://user-images.githubusercontent.com/604313/64678148-48dbb380-d479-11e9-987e-ba5038935fdd.png)

**Comment by lucasponce** [comment]
In which Kiali version this problem happens ?

**Comment by hhovsepy** [comment]
Kiali-ui 1.5.0 (79f36a929f854e3d20fa54ad73b0f4b30d6c7594)
Kiali v1.5.0-SNAPSHOT (20300260cce93481c9f28f4a75d0dd69875f6ecb)

**Comment by jotak** [comment]
In a first attempt, I didn't reproduce. I've set expiration to 60 seconds, and it works as expected on logout.
@hhovsepy can you tell what is the whole error message? (it's truncated on the screenshot)
Also, is there any more information in backend logs?

**Comment by jotak** [comment]
Also, which authentication strategy are you using? Openshift? Basic auth?

**Comment by hhovsepy** [comment]
It is using OAuth. The error message is "Token is invalid: token contains an invalid number of segments", the same in UI ans logs.

**Comment by jotak** [comment]
ok, i was trying with basic auth, that certainly explains the difference

**Comment by lucasponce** [comment]
@hhovsepy just to confirm, this issue has been fixed in master, but it affect to v1.0.5 ?
Has @jotak to backport the PR merged into the v1.0 branch ?

I put the label but not sure if I misunderstood it.

**Comment by hhovsepy** [comment]
@lucasponce yes it should be backported to v1.0 branch

**Comment by jotak** [comment]
@lucasponce @hhovsepy while cherry-picking the patch & resolving conflicts I'm seeing that the bug was certainly not present in v1.0 branch, because we were silently ignoring the error on logout hence it wouldn't have triggered what Hayk saw on the frontend.

See incriminated code, just before my patch: https://github.com/kiali/kiali/blob/2a287358e12d74968fa3ee1b3f973b3bb3b5b072/handlers/authentication.go#L493-L499

And in v1: https://github.com/kiali/kiali/blob/828e31e1cfec6424b8844056689965fc25777f29/handlers/authentication.go#L422-L426 
=> no InternalServerError returned in case of failure in v1

So, I think it's not necessary to backport the patch.
