### ISSUE TITLE
Log all routes for all the non 2xx requests made to istio gateway

### ISSUE THREAD

**Issue by Ghost---Shadow** [kiali/kiali#1670]
**Is your feature request related to a problem? Please describe.**
I am getting a lot of 404 traffic from my istio ingress gateway. In order to debug I want to know what broken URLs/misconfigured virtual services my microservices have.

**Describe the solution you'd like**
Just log it over here maybe

something like

|Code| Route| Flags| percentage|
|--|--|--|--|
|404| /api/foo| NR| 100% |
|503 |/api/bar| NR| 50% |

![Screen Shot 2019-09-13 at 3 01 56 PM](https://user-images.githubusercontent.com/7743925/64852889-e41a8780-d637-11e9-919c-ac09ce47fed5.png)

**Describe alternatives you've considered**
Meanwhile is there any command line way of getting the logs?

**Comment by lucasponce** [comment]
Side comment: If you go to the specific detail service/workload, you have advanced options to group by sender.

I wonder if that helps, or probably we need also to extend this feature there, too.

**Comment by Ghost---Shadow** [comment]
The sender is `istio-gateway`. I want the URI `/api/whatever`

**Comment by jshaughn** [comment]
I agree that knowing which requested routes can not be reached is important information.  Right now that information isn't available in the standard telemetry.  But, it is a topic being discussed actively as Istio telemetry evolves.  A concern with capturing this information is the potential for cardinality explosion in the time-series.  Capturing URI information means potentially multiple time-series for each URI, and if there are many URIs...  Also, it comes with more aggregation when the URI is not important.  We're looking for ways to provide more information for understanding errors, while still maintaining perf.

I'm going to label this as Future because it depends on potential changes being discussed now for upcoming versions of Istio.

Also, this is a potentially related issue: https://github.com/kiali/kiali/issues/1405

**Comment by jmazzitelli** [comment]
To be clear and to follow up on what @jshaughn said, Kiali cannot do anything wrt to this enhancement request unless and until Istio includes that URI information in the telemetry that Istio collects. So if there isn't one already, you should submit an enhancement request to Istio requesting that Istio capture and store this URI information in the telemetry (I seem to remember there was an issue already)

**Comment by Ghost---Shadow** [comment]
Do you know any other tool in the istio ecosystem which is tailored for this?

**Comment by jmazzitelli** [comment]
Did you look at Jaeger tracing? Kiali has the Jaeger integration built in, and it is more tailored toward individual URL tracing. @objectiser or the rest of the Jaeger team could be able to give more insight - see this for how to communicate with that team and project: https://github.com/jaegertracing/jaeger#questions-discussions-bug-reports

**Comment by jshaughn** [comment]
I agree with thew tracing comment.  Also, for recently released versions of Istio you can add to the standard telemetry.  If you add request.host you may be able to see what you want by querying prometheus directly.  To add request.host you basically need to (via helm);

Edit  install/kubernetes/helm/istio/charts/mixer/templates/config.yaml and add it (request.host/request_host) in the requestcount instance and also in the prometheus handler, and then re-run the helm template.

**Comment by jshaughn** [comment]
@Ghost---Shadow , Starting with Istio 1.3.1 they are more conveniently reporting the request.host as the destination_service for egress traffic (in some scenarios).  And in Kiali's next release (currently in master so available as "latest")  there is a new "Hosts" tab in the side panel for edges.  When you can please give these versions a try and see if helps you identify what you're looking for, and report back.  Thanks, -Jay

**Comment by abonas** [comment]
can this be issue closed?

**Comment by jshaughn** [comment]
I think we have satisfied this one, if not please follow up with a new feature request.
