### ISSUE TITLE
Show virtual service in graph

### ISSUE THREAD

**Issue by roodkcab** [kiali/kiali#1681]
We are currently using Istio for ABTest, and there are mainly two types of or ABTest workload based on the git flow the project using, i.e. Master and Branch respectively. For those using Branch flow, we deploy each branch as a separate workload, and Kiali draw them like a charm, we can clearly distinguish the flow using versioned app in graph panel. While for the Master flow project, developers want to handle ABTest using code `if () {case A} else {case B}`, so there will be only one workload, since there's no virtual service in Kiali graph, we can't get any information on such flow. I think it's better to add versioned virtual service between service and app like this. 

![image](https://user-images.githubusercontent.com/1700820/65015365-ea6c7480-d953-11e9-8cd8-c1587a5aeea2.png)

what do u guys think?

**Comment by jotak** [comment]
Hi @roodkcab thanks for your feedback,

Currently any virtual service is only represented by the small branching icon that we can see in your screenshot above. I can see how we could improve a little bit that display by showing the name of the virtual service(s) in play (+ eventually some additional information about that VS, like a summary of its definition maybe within a tooltip?).

However I fear we'll be limited by the information available from Istio telemetry, and we won't be able to represent the traffic flowing through different VS, as you're suggesting, because that information is not provided in telemetry as far as I know. Or that would be a feature request to the istio telemetry components, too.

**Comment by roodkcab** [comment]
@jotak thanks for telling me how to add such feature, I'll have a check on Istio telemetry.

**Comment by jotak** [comment]
No problem - but let's keep this issue opened and I'd like to hear from others too (ping @jshaughn @jmazzitelli & all)

**Comment by jmazzitelli** [comment]
> we'll be limited by the information available from Istio telemetry, and we won't be able to represent the traffic flowing through different VS, as you're suggesting, because that information is not provided in telemetry as far as I know. Or that would be a feature request to the istio telemetry components, too.

If I understand what is being reported here, I believe this is something currently being discussed with the Istio folks - how to make the Istio telemetry better to distinguish virtual services in the graph. @jshaughn has a proposal document he's writing up to talk about this. I'll let him chime in with the ideas being proposed.

**Comment by jshaughn** [comment]
As @jotak said, the telemetry information necessary to inject virtual service nodes into the graph is not reliably available at this time.  And as @jmazzitelli said, the topic is actively being discussed to see whether Istio can supply more information, in a performant way.  In general we'd like to be able better visualize how the requested service gets routed to the destination service(s) via virtual service definitions.  

I think this issue is probably covered by https://github.com/kiali/kiali/issues/1602.

**Comment by roodkcab** [comment]
I did some study, here's what I found now
![image](https://user-images.githubusercontent.com/1700820/65055130-3abdf380-d9a1-11e9-9927-8deadd4b1b86.png)
it seems source envovy proxy only report on service it tried to connect to, without any virtual service information, I don't know whether it possible to add such information within that report, will continue searching.

**Comment by jshaughn** [comment]
@roodkcab I'm going to close this in favor of continuing discussion in https://github.com/kiali/kiali/issues/1602.   Thanks, and look forward to any input you may have for that issue.
