### ISSUE TITLE
Add service link to Virtual Service detail page

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#1703]
In Destination Rule Detail page, we have a link in the host field pointing to the service detail page. One small improvement would be to add same link into the VirtualService Detail page, in the host list section.

Besides that, I would be less restrictive in terms of when we show the link and when we don't. Instead of render a plain text when there are any kind of checks. I would render plain if and only if there isn't a checker for that specific host.
Meaning that, if the VS/DR has a checker in the subsets, we still can render the link to the service. Right now, that is not behaving like that.

**Comment by lucasponce** [comment]
> In Destination Rule Detail page, we have a link in the host field pointing to the service detail page. One small improvement would be to add same link into the VirtualService Detail page, in the host list section.

We have that in the VS route, right ?

https://istio.io/docs/reference/config/networking/v1alpha3/destination-rule/
https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/#VirtualService

One of the main reasons we didn't add it in the VS is that "hosts" can be any alias in the way of a DNS. So Kiali should also check and validate if that hosts is valid and can be rendered.

Meanwhile in the DR this is more restricted to a Service within the mesh (or ServiceEntry).

So, that's reason we added the link in the DR/host and in the VS/routes.

This links can be also improved, but it also adds complexity in the validation, so that's why we didn't implement it in first iteration.

**Comment by xeviknal** [comment]
Thank you for approaching this. It make sense. I missed the nuances of that service in the host list in the VS.

Closing this issue.
