### ISSUE TITLE
Can't open service details

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#1786]
Hi can't open any service details, here's what I'm getting:

![Capture d’écran de 2019-10-11 12-04-22](https://user-images.githubusercontent.com/2153442/66644037-414a2e80-ec20-11e9-8e77-a92ef285c537.png)

I first imagined it was something wrong in my environment but doesn't seem so.
On the REST query for service details, an empty object is returned for `validations`.

Also there's some code smell UI-side regarding this, in several place I'm seeing this type cast: `{} as ObjectValidation` which looks quite wrong, especially in `ServiceInfoDescription`, as straight after the validation object is accessed as `this.getValidations().checks` which results in the error I'm seeing.

I'm setting this issue as a blocker as I can't see any service details.

**Comment by xeviknal** [comment]
It might be related to https://github.com/kiali/kiali-ui/pull/1440 @aljesusg wdyt?

**Comment by lucasponce** [comment]
Mmm I don't get it.

I'm using a fresh master with kiali backend:

commit a52035c7c801c70ae76e616535cd0414ad4804b4 (HEAD -> master, upstream/master, origin/master, origin/HEAD)
Merge: 7e0e54a2 1ad19f43
Author: Guilherme Baufaker Rêgo <gbaufake@redhat.com>
Date:   Thu Oct 10 22:15:30 2019 -0300


and kiali-ui:

commit d490082f8c3b58bbd060ed0598e9ef065c11ffd2 (HEAD -> master, upstream/master, origin/master, origin/HEAD)
Merge: 19c7c2db 12519199
Author: Joel Takvorian <jtakvori@redhat.com>
Date:   Fri Oct 11 12:21:00 2019 +0200

    Merge pull request #1474 from jotak/pf4-metrics-settings
    
    Move metrics settings to PF4

And I have a bogus Service:

![image](https://user-images.githubusercontent.com/1662329/66647073-35626a80-ec28-11e9-9b7b-b5ba8fce223e.png)

![image](https://user-images.githubusercontent.com/1662329/66647085-3d220f00-ec28-11e9-851d-00f7e1e711a2.png)

![image](https://user-images.githubusercontent.com/1662329/66647111-48753a80-ec28-11e9-997c-025c2a7a4b67.png)

I'm using a localhost mode, but if the problem is between backend/fronend I guess I should reproduce it here as well.

**Comment by xeviknal** [comment]
Tried to reproduce the bug but I couldn't. I am using the same version as mentioned right below.

I also explicitly tried the validation where the log points to:

![Screenshot of Kiali Console (72)](https://user-images.githubusercontent.com/613814/66648521-04843480-ec2c-11e9-8097-0bb4490c0960.jpg)

**Comment by lucasponce** [comment]
I'm going to re-open this one.
UI should be protected, but it seems that validations service can send an invalid/unexpected empty format which needs to be investigated.

cc @xeviknal

**Comment by jotak** [comment]
Yes +1, it needs further investigations

**Comment by lucasponce** [comment]
(Re-opened, for some reason it closed when pushing in a different branch, I need to check this)
