### ISSUE TITLE
Missing sidecar - Bookinfo example

### ISSUE THREAD

**Issue by DhruvM1994** [kiali/kiali#1858]
**Describe the bug**
I am trying to deploy the bookinfo example from https://docs.openshift.com/container-platform/4.1/service_mesh/service_mesh_day_two/ossm-example-bookinfo.html using the CodeReady Containter-VM hosting OpenShift 4.
After installing all necessary pods the kiali dashboard is accesible.

Overview:
![image](https://user-images.githubusercontent.com/56864563/67941572-3444ad80-fbd6-11e9-92cd-c8f2d6cb7ac7.png)

Graph:
![image](https://user-images.githubusercontent.com/56864563/67941618-51797c00-fbd6-11e9-914e-f184aa2dd24d.png)

Graph unused nodes:
![image](https://user-images.githubusercontent.com/56864563/67941766-aa491480-fbd6-11e9-9d56-e0b1217ea7d9.png)

List of services:
![image](https://user-images.githubusercontent.com/56864563/67941720-8c7baf80-fbd6-11e9-8cba-d7807ce6ec96.png)

**Versions used**
```
crc version: 1.0.0+575079b
OpenShift version: 4.2.0 (embedded in binary)
```

**To Reproduce**
1. Go to https://docs.openshift.com/container-platform/4.2/service_mesh/service_mesh_install/installing-ossm.html to setup service mesh for OpenShift 4
2. Install the bookinfo-example from https://docs.openshift.com/container-platform/4.2/service_mesh/service_mesh_day_two/ossm-example-bookinfo.html
3. Access the kiali dashboard via OpenShift "Web Console" under Networking->Routes
4. See error from above

**Expected behavior**
A graph of the called services should be shown.

**Comment by jmazzitelli** [comment]
Side note: I'm impressed you even got this to run on CRC VM - I have tried for weeks and I simply can't give the CRC VM enough resources to even deploy all the pods successfully. How much RAM memory and how many CPUs did you give to the CRC VM?

As for your issue here - first check to make sure all the istio-system pods are up and running (`oc get pods -n istio-system`) - make sure there are no pods that are down or failing to start.

**Comment by DhruvM1994** [comment]
Currently I am assigning about 12 GB and 4 virtual processors to the VM.

The weird thing is that if I configure all pods (istio-related and the ones from the example) in a single namespace, then all pods are running. Though, the Kiali dashboard looks like above.

However, if I use two separate namespaces (istio-system and bookinfo) then some bookinfo-related pods are "pending" as described above. According to the OpenShift "Web Console" the pods in the istio-system namespace are running, so far.

**Comment by jshaughn** [comment]
@DhruvM1994 , If you are getting all unused nodes for the services then it is likely that you are not getting any telemetry for your service traffic.  That is consistent with not having any sidecars.  I think @jmazzitelli mentioned just yesterday that you need CNI with 1.4 to get the sidecars, mazz, any comment?

**Comment by jmazzitelli** [comment]
You need CNI for sure - but Service Mesh should have that all configured for you.

Note that if you are installing bookinfo directly inside the istio-system NS, that isn't going to work because IIRC sidecar injection is NOT enabled for the istio-system control plane namespace. So what you are seeing is what I would expect and Kiali is detecting things normally. You need to install bookinfo in its own namespace.

This would be a question for the service mesh guys - "if I install bookinfo directly inside istio-system, how do I get bookinfo pods to have sidecars injected?"

Or try to install bookinfo in its own namespace, which is how it really should be done. Applications should not be inside the control plane namespace itself.

**Comment by DhruvM1994** [comment]
Now, I am running the control plane in the "istio-system" namespace and the example in the "bookinfo" namespace. 

Accroding to https://docs.openshift.com/container-platform/4.2/service_mesh/service_mesh_install/installing-ossm.html I inserted "bookinfo" as a member in the "Istio Service Mesh Member Roll" in the "istio-system" namespace.

The istio-related pods are running so far. However, some bookinfo-related pods are "pending" and "Unschedulable", due to "Insufficient cpu", accroding to the OpenShift "Web Console".

Though, I cannot assign more resources to the VM.

**Comment by jmazzitelli** [comment]
> The istio-related pods are running so far. However, some bookinfo-related pods are "pending" and "Unschedulable", due to "Insufficient cpu", accroding to the OpenShift "Web Console".
> 
> Though, I cannot assign more resources to the VM.

Yup - this is exactly the problem I have and why I abandoned using CRC for Service Mesh deployments - simply can't give CRC enough resources to run ServiceMesh, Kiali, Jaeger, and a demo like bookinfo. This isn't a CRC issue - its an OpenShift issue - it requires too much resources.

This has been an ongoing thing and has been discussed with the CRC team - but like I say, nothing they can do about it as it is a resource-limitation thing within OpenShift itself.

FWIW: I have been using an OpenShift cluster on AWS with 4 worker nodes and Service Mesh + bookinfo works for me.

**Comment by DhruvM1994** [comment]
Thanks for the information.

**Comment by jshaughn** [comment]
@DhruvM1994 It seems this issue can be closed.  Please let us know if you'd like it re-opened. Thanks!
