### ISSUE TITLE
2 Different sized icons in Services Detail Health Overview

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#1869]
**General remarks**
In the services detail page in the health overview section there are two '?' icons that are different sizes.

![Screenshot from 2019-11-01 13-24-32](https://user-images.githubusercontent.com/1312165/68054399-6d028680-fcab-11e9-9252-1ccbd29f9c2c.png)

**Comment by abonas** [comment]
@aljesusg is this related to PF4 migration?
the text seems to be different size too, so perhaps different sized icons are expected?

**Comment by jshaughn** [comment]
@abonas, this has to do with the change to consolidating our Icon use into KialiIcons, which defaults to width 10px, which is smaller than the default.  So in places where the default was used we are seeing icons unintentionally small.

**Comment by jotak** [comment]
In this particular example it can look a bit weird because health is computed from only 1 subpart.
But you see the global indicator (the wider one) and the details indicator (smaller one), which happens to be alone here.
The global health indicator is an aggregation of all subparts indicators which have each their own status.

**Comment by jotak** [comment]
When you look at a more complex example I think it makes more sense:

![Capture d’écran de 2019-11-04 11-53-11 (copie)](https://user-images.githubusercontent.com/2153442/68123727-092bc800-ff0e-11e9-92c4-003da6e42650.png)

**Comment by aljesusg** [comment]
About text @abonas we followed the mockup https://marvelapp.com/i9h9g7j/screen/59315420
where there is a "Health Overview" title an after that subsections, the problem is that the mockup is not aligned with our Health object

![Screenshot from 2019-11-04 14-18-33](https://user-images.githubusercontent.com/3019213/68123737-0fba3f80-ff0e-11e9-8a14-56dd2827ecc2.png)

**Comment by abonas** [comment]
so per @jotak comment perhaps this is not an issue?

**Comment by jshaughn** [comment]
@mtho11 is OK with this given the UX design is implemented.
