### ISSUE TITLE
Doc request: document minimal Operator RBAC permission for view_only_mode

### ISSUE THREAD

**Issue by jonmoter** [kiali/kiali#1873]
**Is your feature request related to a problem? Please describe.**

The instructions for deploying the Kiali Operator create a [kiali-operator cluster role](https://github.com/kiali/kiali/blob/master/operator/deploy/role.yaml) that has a lot of permissions. It can can execute CRUD operations on Pods, Services, and ServiceAccounts in any namespace.

I understand that is necessary in the case where Kiali will be used to configure and modify workloads in the cluster. The Operator needs sufficient permissions so it can grant the Kiali components the ability to do that.

I would like to run Kiali with the `view_only_mode` flag set to true in my production clusters. However, I still need to run the Operator will the ClusterRole with all those permissions. Following the principle of least privilege, I would rather not do that.

**Describe the solution you'd like**

Include an option or link to a minimal ClusterRole that would be sufficient for the Operator to work in view-only mode.

Ideally, the `getLatestKialiOperator` script would have an option allowing you to specify view-only mode which would use those minimal permissions.

But a simpler solution would be to have a YAML file with a minimal ClusterRole somewhere in the github repo, with a link to that explaining how you could swap out the minimal role.  Or maybe create both ClusterRoles, and add instructions on how to change the ClusterRoleBinding.

**Describe alternatives you've considered**

I could probably either read through the code or trial-and-error the existing ClusterRole, removing permissions and testing to see whether it still worked. But I'd far prefer that be a documented and supported option by the project.

**Comment by jmazzitelli** [comment]
> Ideally, the `getLatestKialiOperator` script would have an option allowing you to specify view-only mode which would use those minimal permissions.

This is how I would prefer it done, as well. We already do something similar with the accessible-namespaces setting (if ** we give the operator cluster roles, otherwise, we do not). For this case, we could have "--view-only-mode" setting that by default is false, but if explicitly set to true we could strip out the permissions given to the operator such that it has the minimum required to install a kiali that has view-only-mode turned on. 

This will have a side effect that if someone edits the Kiali CR to turn off view-only-mode, the operator will fail. But this is probably what you would want anyway (if you turned off the capability of the operator to turn it off during initial install, you probably don't want it to have that capability at all).

**Comment by lucasponce** [comment]
I didn't see your comment @jmazzitelli let me know if you want to work on this, in any case I can take it for next sprint as well.

**Comment by jmazzitelli** [comment]
> let me know if you want to work on this

I can work on this @lucasponce ... I will assign this to me.

**Comment by jmazzitelli** [comment]
review PR #2003 if you want to see how this is being implemented.
