### ISSUE TITLE
Validate Kiali against Telemetry v2 in Istio 1.5

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#1894]
*Telemetry V2 is aka Mixer-less telemetry*

Istio's P&T WG is asking to actively test Kiali on Telemetry v2 (and they may "broadcast" a similar message to other add-ons).

It's expected that Telemetry v2 will reach enough maturity to be enabled by default in a following release (after Istio v1.4). 

Telemetry v2 metrics for HTTP are almost at par with Telemetry v1. So, we must make sure that all Kiali features dealing with HTTP metrics are working successfully.

Telemetry v2 metrics for TCP aren't at par yet, but they said it's very close. Kiali should be validated and fixed, if needed.

Once Kiali is validated and fixed, since Telemetry v2 is close to become the default, testing Kaili in both Telemetry V1 and V2 should become the usual validation to ensure compatibility with the following release.

Related to previous #1694.

**Comment by jshaughn** [comment]
I've tried mixer-less (v2) telemetry with istio 1.4-beta4.   The [issue we reported against 1.3](https://github.com/istio/istio/issues/17231) is fixed and so v2 actually seems usable for HTTP traffic (TCP is still not available).  I do see two issues:
- In the prelim docs (https://preliminary.istio.io/docs/ops/telemetry/in-proxy-service-telemetry) the filter file locations are wrong.  You want:
  - install/kubernetes/operator/charts/istio-control/istio-discovery/metadata-exchange-v2.yaml
  - install/kubernetes/operator/charts/istio-control/istio-discovery/stats-filter-v2.yaml
 - Traffic to PassthroughCluster is being reported with destination 'unknown instead of 'PassthroughCluster'.   I haven't tested BlackHoleCluster, perhaps it has the same issue.

**Comment by jshaughn** [comment]
The Istio 1.4 offers TCP metrics as an experimental feature, HTTP has been upgraded to alpha.  We need to test the experimental TCP impl.

**Comment by jshaughn** [comment]
Although the [1.4 release doc](https://istio.io/news/releases/1.4.x/announcing-1.4/) states,  

> We’ve also added new experimental features that don’t require Mixer: TCP metrics and Stackdriver metrics.

In Slack I was told that mixer-less TCP support is actually coming in Istio 1.5.   I did validate that HTTP support (now Alpha) seems to still work fine in 1.4.  I think the intent is to make V2 Telemetry the default in 1.5, but considering the TCP support did not make 1.4, I'm not sure tyhe new V2 default will actually happen.

**Comment by jshaughn** [comment]
It looks like [this GRPC status PR](https://github.com/istio/istio/pull/20036) will be merged in 1.5.  We will need to make updates to make use of the change as the grpc status will be reported in a new field, not in the current response_code field.

**Comment by jshaughn** [comment]
Notes from P&T:

In Istio 1.5, the default HTTP telemetry is generated by the in-proxy Stats filter (i.e. Telem V2). This represents a 50% reduction in total CPU usage. Telemetry V2 in Istio 1.5 has the following major feature gaps and differences vis-a-vis Mixer Telemetry.
- Out of mesh telemetry
  - When the source or the destination of the traffic is not side-car injected, some telemetry information is missing.
- Egress Telemetry is not supported.
- Histogram bucketization in V2 telemetry is significantly different than Mixer.
  - WE Hanve already added backward compatible support.
- TCP telemetry is only supported with mTLS.
- Needs a larger Prometheus instance than Mixer V1 since all proxies must be scraped.

**Comment by lucasponce** [comment]
So, perhaps we need to put a note for Kiali 1.13 (the target for Istio 1.5) that would require Mixer Telemetry.

Isn't it ?

**Comment by jotak** [comment]
>     * TCP telemetry is only supported with mTLS.

this one in particular sounds really weird, do you know if there's an issue to track that?

**Comment by jshaughn** [comment]
@lucasponce No, we certainly don't require Mixer telemetry, we support Telemetry V2.  But of course any feature-gaps/telemetry-reporting-changes will be reflected in Kiali because the underlying reporting will have changed.  I think it would be helpful if we actually had release notes so that we could just pass on that fact to our users, and maybe reduce the number of Kiali issues reported.

@jotak That TCP note is significant, I guess, although I'm not sure if TCP is used in most cases and therefore impact will be small.  Maybe I'll ask that on Slack...

**Comment by jshaughn** [comment]
Filed this bug when testing 1.5: https://github.com/istio/istio/issues/21324

It does not affect Kiali because we don't yet use the canonical_service info.  Added https://github.com/kiali/kiali/issues/2276 for adding that support.

**Comment by jshaughn** [comment]
Closing, 1.5 is released and I think we will have finished addressing the upstream changes with the Kiali 1.15 release.  Although, Kiali 1.14 is packaged with 1.5 and is functional.

**Comment by kylegalea** [comment]
Using istio 1.5 with telmetry v2 and kiali 1.16, I am not getting the correct flow for external access. Is telemetry v2 still not working well with egress gateway traffic

![image](https://user-images.githubusercontent.com/53271472/80411606-be8f7500-88cc-11ea-8dd5-4e24e38e168c.png)

**Comment by jshaughn** [comment]
@kylegalea I would follow up with either Istio Slack (extension-telemetry channel), or Istio Discuss (policies and telemetry area).   I expect Kiali is displaying what istio is supplying to Prometheus.   If this used to work as expected using Mixer (V1) Telemetry then they may need to know there is a behavior gap with V2 or just that the telemetry is not intuitive.

If you have reason to think it's Kiali's issue, then go ahead and open a new issue in Kiali.
