### ISSUE TITLE
Add GDPR page to kiali.io

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#1914]
Kiali.io needs a GDPR page. This is specially important for compliance with EU.

**Comment by jotak** [comment]
About GDPR: here's what uMatrix shows:

![Capture d’écran de 2019-11-11 18-30-30](https://user-images.githubusercontent.com/2153442/68607751-a9a35e80-04b1-11ea-8ad2-6fe6444dc4ba.png)

I see youtube is trying to set no less than 14 third-party cookies which indeed I guess must require user agreement for GDPR. Or maybe switch to something less intrusive than youtube?

btw what's googletagmanager? a new google-analytics-like?

Also maybe we'd better embed our own scripts (like jquery) rather than fetching a remote one, that would be one less stuff to make gdpr-compliant? (if i understand correctly)

**Comment by xeviknal** [comment]
Good observation. However, I would open new issue for fixing this abuse.
google tag manager is a tool to manage all the scripts for tracking: analytics and so on. It is a way to avoid adding one script per service and preventing marketers to add services without changing the code.
Regarding to GDPR, we have asked support in writting the document.

**Comment by xeviknal** [comment]
Closing this per https://github.com/kiali/kiali.io/pull/189
