### ISSUE TITLE
[RFE] Lists: show total number of items

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#1923]
PF3 objects listing and pagination was showing total number of items.
Now with PF4 and scrolling, user does not have a clue how many objects are listed.

RFE show total number of items which will be shown after user scrolls down.

**Comment by lucasponce** [comment]
I'm not sure if this one is valid.
In PF4 and OpenShift Console virtual scrolling doesn't show number of items due potential dynamic of the data (not the case in Kiali as we know the # of items).

In any case, this would require some check with Kiali UX about it.

**Comment by lucasponce** [comment]
Oh, correction, in the "Projects" views there are not that number, but I can see that in the top of Workloads:
https://console-openshift-console.apps.lponce-dev.devcluster.openshift.com/k8s/ns/istio-system/pods?orderBy=asc&sortBy=Readiness

**Comment by cfcosta** [comment]
I did some investigation on it few sprints ago, the main takeaways are:
- There's no simple way to add it to the end of the list viewport, mostly because of the height calculation for the virtual lists.
- The current virtual list implementation does not respect the provided height (we do set it but it doesn't make any difference).
- The item count was part of PF3, but it is not anymore on PF4. If they wanted that they'd have implemented it already.

So my recommendation for this one is to either close it or keep it in the backlog until something changes. What do you guys think?

**Comment by lucasponce** [comment]
Closing, it's minor, we are reviewing priorities for next sprints.
