### ISSUE TITLE
KChart warnings

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#1928]
Several console warnings like this when navigating to metric details:
![image](https://user-images.githubusercontent.com/1662329/68764895-df645680-061b-11ea-968d-2f310c048737.png)

**Comment by lucasponce** [comment]
@jotak I've seen this issue by chance.
Let me know if it's duplicated or in your radar.
I can also take it to catch up with kcharts and fix it.

**Comment by jshaughn** [comment]
I've seen these but I think it's actually a Victory issue.  Maybe Joel can confirm.

**Comment by jotak** [comment]
Yes I've also seen it, and it's a bad proptypes definition somewhere but I haven't investigated enough to see if it lies in pf4 code or in victory. But afaict our code is correct.

**Comment by lucasponce** [comment]
Ok, I will take a look in any case, just as exercice to get familiar and see if it's something we can do in kiali side without depending of Victory library.

**Comment by mtho11** [comment]
@lucasponce perhaps this should be labeled `Waiting External` if you don't find a solution?

**Comment by cfcosta** [comment]
@lucasponce I can report the issue to Victory (or try to find an solution from our side), or did you manage to get progress on this?

**Comment by jotak** [comment]
To be more accurate, this faulty Proptype is defined in patternfly `ChartTooltip`, not in Victory. I don't know how it can *not* have a `x` value, this is probably something happening within `VictoryVoronoiContainer` (which comes from Victory, this time).
We could try to upgrade pf4, maybe they've already fixed it.

**Comment by cfcosta** [comment]
@jotak ok, I'll take a look at that and report back.

**Comment by lucasponce** [comment]
@cfcosta go ahead, I put this one in my todo list but it's fine if you want to work on it.
Next time, please, ask me in the IRC before to take it to coordinate.
Thanks.

**Comment by cfcosta** [comment]
No problem, I took it because it was not assigned to anyone and no update in a few days, but will coordinate with you next time :)

**Comment by jshaughn** [comment]
@cfcosta (and all) yes, definitely inquire before self-assigning, especially if it originated from, or is labeled for, the other sub-team.  There may be some relevant update, or just to make sure it's not in-progress but not updated.

**Comment by cfcosta** [comment]
Update:

This error is an one line fix:

![error1](https://user-images.githubusercontent.com/14752/70336303-ab99dc80-1827-11ea-8a74-9a23fae59900.png)

```diff
diff --git a/src/components/Charts/SparklineChart.tsx b/src/components/Charts/SparklineChart.tsx
index 60278520..268cad5e 100644
--- a/src/components/Charts/SparklineChart.tsx
+++ b/src/components/Charts/SparklineChart.tsx
@@ -35,7 +35,7 @@ export class SparklineChart extends React.Component<Props, State> {
     if (props.width === undefined) {
       this.containerRef = React.createRef<HTMLDivElement>();
     }
-    this.state = { width: props.width || 0, hiddenSeries: new Set() };
+    this.state = { width: props.width || 1, hiddenSeries: new Set() };
   }

   handleResize = () => {
```

What happens is that if you set the width to 0 then things break :)

The other takes more time, what happens is that, when you move the mouse on top of the sparkline graph (that does not happen on metric graphs because they are bigger), the tooltip is bigger than the area of the graph, so it tries to center the origin point of the tooltip and it gets messed up:

![error2](https://user-images.githubusercontent.com/14752/70336472-f3b8ff00-1827-11ea-9c00-1e98f18946e9.png)

I can replicate it consistently under Patternfly, but tried on Victory directly and everything was ok. Updating patternfly and victory did not change anything, so I'm investigating deeper to see if I can isolate the error.

One workaround would be to do the centering manually based on the mouse position, so I'm also investigating that.

**Comment by jotak** [comment]
waw good catch @cfcosta
