### ISSUE TITLE
What edit is required in the default cr file?

### ISSUE THREAD

**Issue by satyajituk** [kiali/kiali#1947]
What edit does this file need?
https://github.com/kiali/kiali/blob/master/operator/deploy/kiali/kiali_cr.yaml

It is mentioned in [this link](https://kiali.io/documentation/getting-started/#_create_or_edit_the_kiali_cr) to "edit". But I am not sure if the unedited file will also work fine.

**Comment by jmazzitelli** [comment]
It depends how you want to configure kiali. Read the comments in that link to the yaml file and you'll see what the settings do.

This issue is neither a bug or enhancement request - closing. If you want user help, you can talk to us in a few different places - see: the "Talk to us" section here: https://kiali.io/contribute/

We are on freenode IRC, kiali-users google group, and Istio Slack, room #kiali, to name a few.
