### ISSUE TITLE
Feature Request: Support for animated visual representation of traffic.

### ISSUE THREAD

**Issue by liamawhite** [kiali/kiali#198]
As discussed [here](https://twitter.com/pilhuhn/status/996719852596486146). It makes it much easier to see the amount of traffic vs line thickness.

Something in the vain of Visceral. It is possible with Visceral but is a lot of effort to make it Istio friendly. A Visceral demo can be found [here](https://youtu.be/0fKi3NeCsSE?t=19m33s).

I really like the idea of having a dashboard for all observability in the service mesh. Keep up the good work!

**Comment by mtho11** [comment]
@liamawhite Some WIP: https://github.com/kiali/kiali-ui/pull/356

**Comment by mtho11** [comment]
@liamawhite what do you think about this option: https://github.com/kiali/kiali-ui/pull/356

**Comment by liamawhite** [comment]
This is a very good start! I think to fully implement this Kiali needs to be a live view of whats happening rather than a point in time.

**Comment by jmazzitelli** [comment]
FWIW: A "live" view would always be limited to what Prometheus has stored since the data visualized by Kiali is coming from Prometheus and Prometheus only scrapes data every X seconds. So whatever X is (I can't remember what the Istio install sets it as the default) that is the minimum "point in time" delay we can expect.

If, by "live", you mean "auto-refreshed", yes, we should go back and re-introduce that feature. We used to have auto-refresh earlier on (we replaced that with the manual refresh button a couple sprints ago). But I think we should consider perhaps using a websocket approach rather than a polling approach (i.e. the client "refreshing" every X seconds).

**Comment by mtho11** [comment]
An auto-refresh would be an easy first step.

**Comment by liamawhite** [comment]
Understood. I believe promviz (Vizceral backed Prometheus) works on a ~15s delay.

**Comment by jmazzitelli** [comment]
This is done. Animation on the edges - number of dots and speed of dots indicate throughput and response times. Example: https://twitter.com/ScarletCapMazz/status/1009493932303142916

There is also auto-refresh that you can configure down to every 5s for a "live" view.

**Comment by djamaile** [comment]
So did this websocket approach bear any fruit? Also looking to implement this with a websocket.
