### ISSUE TITLE
Traces & metrics correlation: metrics analysis

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#1981]
An idea for more correlation (could be something like correlation v2): a user could right-click on a chart (e.g. on a span, or actually anywhere in a chart), which opens a menu with the option: "More correlation" (or a better name) which, based on the related timestamp, would start some analysis of *all* metrics in prometheus for the related service (or even other services in the same namespace) to find the ones that have "unusual" changes close to that timestamp. The goal would to help the user to locate "strange behaving" metrics among all the available ones - and possibly correlate things beyond a single service.

I think this analysis can be done by comparing the standard deviation close to that timestamp. I've tested that locally and it seems to give interesting results.

Goal of the RS would be to determine if the kind of analysis we can do would be promising to actually troubleshoot.

**Comment by lucasponce** [comment]
This feature is progressed in the traces tab, where users can check if a particular trace/span is "good/bad" compared with the standard deviation.

![image](https://user-images.githubusercontent.com/1662329/128191083-60cdbde3-38bd-4f8f-9eba-a72f86f7e527.png)

Also the charts give some level of correlation to identify suspected peaks that a user may want to zoom in to investigate better:

![image](https://user-images.githubusercontent.com/1662329/128191214-8931dc04-f691-4220-aab2-fb4ce58d5878.png)

Today spans are correlated with logs as well, so there is some good level of correlation support.

Probably, in the future, Kiali way want to integrate with more powerful analytics solutions and show them rather than compute from metrics itself.

So I think we can close this one in favor to future integration with other solutions for this particular space (metrics analysis).
