### ISSUE TITLE
Dev script podman+minikube

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#2005]
As discussed on mailing, and as podman is the new way to go, I suggested either to better document the deployment steps for a dev environment with podman+minikube, or to have some script helpers. This task is about scripting.

@jmazzitelli has a better idea of the existing scripts we can re-use, but just for the record, here's my current notes / steps:

```bash
# init; do it once ; probably not to be scripted
minikube config set vm-driver kvm2 # or whatever you want
minikube config set memory 8000 # or whatever you want
# start minikube
minikube start
minikube addons enable registry # not sure if it's necessary or enabled by default 
```

(Note, I also tried using cri-o (`minikube start --container-runtime=cri-o`) but didn't work ootb at a later step (ErrPullImage on my deployments), probably nothing serious, I guess some config is necessary to skip TLS verify.)

```bash
# Install istio, e.g. with istio-1.3.1 in `$HOME`
for i in ~/istio-1.3.1/install/kubernetes/helm/istio-init/files/crd*yaml; do kubectl apply -f $i; done
kubectl apply -f ~/istio-1.3.1/install/kubernetes/istio-demo.yaml
```

create/deploy operator:
```bash
OPERATOR_IMAGE_NAME="localhost:5000/kiali/kiali-operator" make operator-create
```

When the above command is waiting the operator to be ready, open a new terminal and run:

tag:
```bash
podman tag $(podman images | awk '$1$2~/localhost:5000\/kiali\/kiali-operatordev/{print $3}') $(minikube ip):5000/kiali/kiali-operator:dev
```

push:
```bash
podman push $(minikube ip):5000/kiali/kiali-operator:dev --tls-verify=false
```

build / deploy Kiali (with my local console!) :
```bash
DOCKER_NAME=localhost:5000/kiali/kiali CONSOLE_LOCAL_DIR=/work/swsui CONSOLE_VERSION=local make clean build docker-build

podman tag $(podman images | awk '$1$2~/localhost:5000\/kiali\/kialidev/{print $3}') $(minikube ip):5000/kiali/kiali:dev

podman push $(minikube ip):5000/kiali/kiali:dev --tls-verify=false

KIALI_CR_FILE=~/kiali_cr_jaeger.yaml AUTH_STRATEGY=login KIALI_IMAGE_NAME=localhost:5000/kiali/kiali make k8s-deploy
```

Port-forward
```bash
kubectl port-forward svc/kiali 20001:20001 -n istio-system
```

For yarn start, proxy has to be `"https://localhost:20001/kiali"`

**Comment by jotak** [comment]
Also I had to change two little things in Makefiles:

- In the main one, in target `docker-build-kiali`, `s/docker/podman`
- In the operator's one, target `operator-build`, add argument to the operator sdk: ` --image-builder=podman`

**Comment by jmazzitelli** [comment]
lemme see what magic i can put together in our makefiles and other scripts. i'll try to get it to work for both podman/docker combination as well as minikube/openshift-on-aws

**Comment by jotak** [comment]
Thanks @jmazzitelli !!

**Comment by jmazzitelli** [comment]
I'll add more info in PR #2013, but in short, here's what I got:

1. The `hack/k8s-minikube.sh` is now up to date - you can use this to start, stop, delete minikube, create your port-forward, etc. It will also prepare the necessary minikube addons for you. Pass in cmdline options to set how much mem, CPU, disk to give minikube, and what driver you want to use.

2. To install upstream Istio, you can pass the `istio` command to the `hack/k8s-minikube.sh` script. This uses `hack/istio/install-istio-via-istioctl.sh` under the covers - if you want to use that directly, pass `--help` for all the things you can pass to it.

So to bring up minikube with istio installed, you can run:

```
hack/k8s-minikube.sh start
hack/k8s-minikube.sh istio
```

3. The makefiles by default still assume `docker` and that you want to test on OpenShift. However, you can set the env var `IS_MINIKUBE=true` so make switches to using minikube. If you want to use `podman` instead of `docker`, pass in `DORP=podman` (where `DORP` stands for "Docker OR Podman"). So, to install Kiali into the minikube you started via the hack script (as described above) you first build like you always have (e.g. `CONSOLE_VERSION=local make clean build`) and then you can:

```
IS_MINIKUBE=true make cluster-push operator-create kiali-create
```

That will push all images to the cluster (in this case, minikube), it will create an operator by deploying the operator via the deploy script (the same script that users use via `git.io/getLatestKialiOperator`), and then creates a Kiali CR which causes the operator to deploy Kiali.

Look in the main Makefile for some settings you can set via env vars to control some kiali config (such as AUTH_STRATEGY, VERBOSE_MODE, ACCESSIBLE_NAMESPACES, etc).

4. To see Kiali within minikube, you can use `hack/k8s-minikube.sh port-forward` which will create a port-forward server to Kiali's port 20001. The output will tell you want URL to point to in order to access Kiali.

I have not tested podman (DORP=podman) because podman isn't working on my machine at the moment. I'll hope someone can test it and tweek that PR to get it to work.. It should be close, but I'm not sure if its 100%.

**Comment by jotak** [comment]
Thanks @jmazzitelli I'm going to test two scenarios:

- With the hack scripts and a couple of env vars (e.g. I use kvm2 not virtualbox)
- Without hack script but still building with podman & pushing to minikube
