### ISSUE TITLE
Fix incorrect description on Kiali CR

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#2050]
https://github.com/kiali/kiali/blob/master/operator/deploy/kiali/kiali_cr.yaml#L455

"# Caution: Kubernetes cache is not compatible with reduced permissions scenearios."

@jmazzitelli you mean cluster vs non cluster permissions or you mean here if you remove a WATCH verb for example ?

I guess the sentence in the yaml could be misleading and perhaps it needs more clarification.

Cache is designed to work without cluster permissions.

**Comment by jmazzitelli** [comment]
@lucasponce I don't know what that means. I don't think I originally authored that. I didn't work on the cache so I wouldn't know where it does or does not work :)

Should we take this out?

**Comment by jmazzitelli** [comment]
Looks like it originated in the old PoC PR for the cache implementation that we just copied over: https://github.com/kiali/kiali/pull/1263/files#diff-f8f6c9abc6c5969045b61451c949e922R137

I think we should remove it. It probably is outdated.

**Comment by jmazzitelli** [comment]
Yeah, and look here - some code was removed that had this comment in it, too:

https://github.com/kiali/kiali/pull/1749/files#diff-9c432430308ba075a6525635dd9a4ed9L137

https://github.com/kiali/kiali/pull/1749/files#diff-9c432430308ba075a6525635dd9a4ed9L204

So that comment in the Kiali CR probalby should have been removed as well.

I take it out and submit a PR.
