### ISSUE TITLE
Hover-Over Info On Traffic/Flags/Hosts Side-Graphs Not Correct

### ISSUE THREAD

**Issue by mattmahoneyrh** [kiali/kiali#2068]
Hover-over Traffic/Flags/Hosts side-graphs is not showing correct information .

In the Hosts "HTTP Request Traffic min / max:" graph screen-shot, it can be seen that when hovering over the graphed line does not fully display the information, as well as it appears the color is incorrect (Expected color is red, Actual color is blue):

![Selection_114](https://user-images.githubusercontent.com/7262987/71838462-dbd2d600-3086-11ea-96b6-2a18bdbeca70.jpg)

In the Hosts "HTTP Request Response Time (ms)" graph screen-shot, there are two time-stamps in the info, and the expected color is incorrect (Expected color is orange, Actual color is blue).

![Selection_113](https://user-images.githubusercontent.com/7262987/71838651-58fe4b00-3087-11ea-81ba-25a434a53aaa.jpg)

The same issues above can be seen on all Traffic, Flags, and Hosts graphs.

**Comment by jshaughn** [comment]
@mattmahoneyrh , @cfcosta No need to jump the usual process of getting on backlog, etc.   I'll add to the backlog and asking @jotak to comment as he's most familiar with the new Victory sparklines and the associated tooltip handling.

**Comment by jotak** [comment]
@mattmahoneyrh when you see this issue, isn't it because the datapoints of two series are coincident?
It's hard to read on your first screenshot, but I think this is the case on the second one: p95 and p99 are coincident. So, the actual bug is that we should display the 2 colors on the tooltip (but at the moment I've not been able to do this, due to victory not provide enough information ... might be something to fix in victory)

**Comment by jotak** [comment]
About tooltip being truncated, the issue is that it's all within a svg canvas so the tooltip cannot be displayed overlapping outside of that canvas. Among the possibilities we have, I see:

- Increasing chart height (but I remember that you prefer keeping it as small as possible to avoid side-panel scrolling)
- Increase chart height but reduce margin between charts
- Reduce tooltip padding
- Reduce font size

**Comment by jotak** [comment]
Could you split this in two different issues please? I've a fix for the clipped tooltip issue, but not yet for the missing color issue.

**Comment by cfcosta** [comment]
> * Reduce font size

+1 to that, the inconsistent text size loses us a lot of space.
