### ISSUE TITLE
In Kiali Service Graph view switching App Graph to Service graph loses Response Time Options

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2070]
**General remarks**
When in the App graph or versioned app graph mode in the Kiali service graph, the `Edge label` selections are lost when switching the `App Graph` to `Service Graph`. 
There is no warning that I will lose those edge labels, and they are still selected in the dropdown even though they are not visible now.

This video illustrates this behavior:
![response-time](https://user-images.githubusercontent.com/1312165/71943679-4878ce00-3176-11ea-9be5-eba9f9353441.gif)

**Comment by jshaughn** [comment]
@mtho11 Good observation.  The root cause is not  the switch of graph types but rather that response time is not a valid option for Service graphs.  You'll get no label even if you are working with a Service graph directly and select Response Time edge label.  This is because a Service graph is a "logical" of requests.  We can show request rates for services, but because services themselves don't process requests we don't show response time info.   Note that in the original app graph the edges leading into the service nodes also don't show response time.

So the question is whether we need to prevent this situation or maybe FAQ it.
