### ISSUE TITLE
Inbound Metrics tab in details pages shows console warnings

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2088]
**General remarks**
When going to the details page and selecting inbound metrics tab there are console warnings.
This is not a really bad error since it is only seen on the browser console,  just something that should be fixed.

![Kiali_Console](https://user-images.githubusercontent.com/1312165/72228428-4d18fa00-355b-11ea-9323-2d51e8a665e8.png)

Here are the details of the warning message:

Warning: Failed prop type: Invalid prop `events[2].target` of type `array` supplied to `VictorySharedEvents`, expected `string`.
    in VictorySharedEvents (created by VictoryChart)
    in VictoryChart (created by Chart)
    in Chart (created by ChartWithLegend)
    in div (created by ChartWithLegend)
    in ChartWithLegend (created by KChart)
    in KChart (created by Dashboard)
    in div (created by GridItem)
    in GridItem (created by Dashboard)
    in div (created by Grid)
    in Grid (created by Dashboard)
    in Dashboard (at IstioMetrics.tsx:220)
    in div (created by CardBody)
    in CardBody (at IstioMetrics.tsx:218)
    in article (created by Card)
    in Card (at IstioMetrics.tsx:217)
    in div (created by GridItem)
    in GridItem (at IstioMetrics.tsx:216)
    in div (created by Grid)
    in Grid (at IstioMetrics.tsx:215)
    in div (at RenderComponentScroll.tsx:24)
    in RenderComponentScroll (at IstioMetrics.tsx:214)
    in IstioMetrics (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in withRouter(Connect(IstioMetrics)) (at WorkloadDetailsPage.tsx:272)
    in section (created by TabContent0)
    in TabContent0 (created by ForwardRef)
    in ForwardRef (created by Tabs)
    in Tabs (created by Context.Consumer)
    in ComponentWithOuia (created by Context.Consumer)
    in Unknown (at Tabs.tsx:94)
    in ParameterizedTabs (at WorkloadDetailsPage.tsx:361)
    in WorkloadDetails (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route (at RenderPage.tsx:16)
    in Switch (at SwitchErrorBoundary.tsx:42)
    in SwitchErrorBoundary (at RenderPage.tsx:31)
    in div (at RenderPage.tsx:30)
    in div (at RenderPage.tsx:42)
    in RenderPage (at Navigation.tsx:116)
    in section (created by PageSection)
    in PageSection (at Navigation.tsx:115)
    in main (created by Page)
    in div (created by Page)
    in Page (at Navigation.tsx:113)
    in Navigation (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in withRouter(Connect(Navigation)) (at App.tsx:107)
    in Router (at App.tsx:106)
    in AuthenticationController (created by ConnectFunction)
    in ConnectFunction (at App.tsx:117)
    in PersistGate (at App.tsx:115)
    in Provider (at App.tsx:114)
    in App (at src/index.tsx:29)

**Comment by jotak** [comment]
I've opened a ticket on victory issues: https://github.com/FormidableLabs/victory/issues/1470

**Comment by jotak** [comment]
Ok, I'm not going to wait too long, going to fix that (which involves a bit of refactoring).
Note that it needs to be fixed both in metrics (k-charted) and sparkline charts of summary panel.

I have a question for saturn folks @jshaughn , @mtho11 , @israel-hdez  ...

Currently, the Sparkline charts code is in kiali-ui whereas most other victory-related code is in k-charted. We can consider it makes sense, because k-charted was primarily focused on the handling of "monitoring dashboards".

However, it leads to a lot of duplication and patches often need to be done in two places (like it's the case now).

So, what would you prefer: put SparklineChart component in k-charted or keep it under kiali-ui?
Pros & cons that I see if moving it:

pros:
- less duplication, less maintenance
- probably more consistency between the various chart usages
- k-charted uses storybooks which helps to quickly try changes & tweaks & debug

cons:
- introduces a dependency on k-charted when we hadn't before, in graph
- longer & less trivial delivery process for code changes in k-charted impacting kiali-ui

So tell me what you prefer...

**Comment by jshaughn** [comment]
@jotak I'm fine with having it centralized in k-charted. Note that we do now apply custom styling, so we'd need to maintain the look we have currently.  The good news is that just last Friday we merged an UX update to all of the side summary-panels, so I don't expect changes in the near-term.

**Comment by israel-hdez** [comment]
@jotak Sparklines changes are very sporadic. So, in practice, the "cons" list is negligible. I'm also fine if you move the SparklineChart component to k-charted.
