### ISSUE TITLE
multi tenant support

### ISSUE THREAD

**Issue by debianmaster** [kiali/kiali#212]
is there a plan to support multi-tenant features ? Also use openshift authentication proxy in future?

**Comment by abonas** [comment]
Hi, please provide more details and an example/use case of multi tenant features that you have in mind. thanks

**Comment by abonas** [comment]
you can also see some work on multi project support done in #214, so it will be good to know if that provides some of what you are looking for, or you have a completely different use case.

**Comment by debianmaster** [comment]
@abonas i'd like to see if this is possible

- As a cluster administrator i'd like to restrict my platform users to to see only traffic mesh data related to their respective name spaces (not everything)
- As a platform user i would like to login to kiali using inbuilt openshift [auth](https://github.com/openshift/oauth-proxy) mechanism.    (This will make it specific to openshift specific  , but it can be enabled only for openshift) 
- A simpler implementation would be in drop down selection of namespaces, please show only namespaces to which i'm owner of

**Comment by abonas** [comment]
@debianmaster thanks for the further explanation, we'll check. @mwringe @pilhuhn

**Comment by mwringe** [comment]
> As a cluster administrator i'd like to restrict my platform users to to see only traffic mesh data related to their respective name spaces (not everything)

There is a PR to add in support to restrict the Kiali service account to only the namespaces that you are interested in. This is for the service account, if you want to have different people access different things you could potentially run multiple Kiali's, so its probably not idea for your usecase.

This also only works on the kiali service account, and it doesn't affect the metrics that Kiali can access since those come from p8s. The UI wont show you the option to get the metrics, but if you know the URL you might be able to access them. Its a first start.

> As a platform user i would like to login to kiali using inbuilt openshift auth mechanism. (This will make it specific to openshift specific , but it can be enabled only for openshift) 

We have a jira created for this usecase: https://issues.jboss.org/browse/KIALI-566

> A simpler implementation would be in drop down selection of namespaces, please show only namespaces to which i'm owner of

With the PR mentioned above, we could potentially set things up so that the user logs in via OpenShift auth, and we then use their token instead of the service account one. This would then have the UI only show the namespace you have access to. That could give you a quasi multi-tenancy support. 

But, its not exactly as simple as this. There are a few other areas we need to figure out here a bit better  since going multi-tenancy has other concerns (eg how to handle user configurations)

**Comment by pilhuhn** [comment]
@debianmaster A general "yes"
