### ISSUE TITLE
[hack] install-istio-via-istioctl needs to change CNI options

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#2173]
The latest Istio slightly changed the CNI options. Our hack script needs to change to support this (this is required for the latest Istio, but I don't know how far back this change occurred - unsure if the 1.4 release requires this change).

See: https://github.com/istio/istio.io/pull/6371

**Comment by lucasponce** [comment]
I think hack scripts issues like this can have the "backlog" label.
That means that issue is "ready", it doesn't mean that is added to a Sprint, which is a different step.
@jmazzitelli feel free to add "backlog" label to similar issues like this.
To be honest, I can't check if your description is not right, to me it looks good.
