### ISSUE TITLE
[operator] Kiali resource type status 

### ISSUE THREAD

**Issue by OchiengEd** [kiali/kiali#2212]
**Is your feature request related to a problem? Please describe.**
The Kiali resource that is managed by the operator has its current status held under the field `.status.type`. This results in the status being reported as Unknown in openshift dashboard or any other monitoring system that will check `.status.phase` like is used in other native kubernetes resources such as pods

```
$ oc -n servicemesh get jaeger jaeger -o json | jq .status.phase
"Running"
$ oc -n servicemesh get kiali kiali -o json | jq .status.phase
null
$ oc -n servicemesh get kiali kiali -o json | jq .status.conditions[0].type
"Running"
$ 

```

**Describe the solution you'd like**
Report the status under `.status.phase`

**Describe alternatives you've considered**
N/A

**Additional context**
Add any other context or screenshots about the feature request here. If it is about a new design, please attach a drawing of a potential solution.
For backend changes also describe how one could test the new feature and how it impacts display on the UI.

**Comment by jmazzitelli** [comment]
This `status` field is dictated entirely by the ansible operator-sdk... if you feel this status field needs to change, the recommended approach is to report it to the operator-sdk folks:

https://github.com/operator-framework/operator-sdk/issues/new/choose

**Comment by OchiengEd** [comment]
Thanks. Let me look into that.

**Comment by OchiengEd** [comment]
@jmazzitelli It is possible to add custom status for an operand(or custom resource) managed by an ansible operator. Below are the resources used to arrive at this.

[1] https://github.com/operator-framework/operator-sdk/blob/e4d29c8ca1ff3ccc5ebef6f1695730b84cf8729e/pkg/ansible/controller/status/types.go#L153-L180
[2] https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/dev/developer_guide.md#custom-resource-status-management

**Comment by jmazzitelli** [comment]
AFAIK, we don't have access to the status that the operator-sdk is putting inside the conditions[0].type. IMO, If this truly is a problem that OS console and other things can't see the status then it is a problem across the board for all ansible operators and they (operator-sdk folks) should know about this and fix it within the ansible operator-sdk base image.

**Comment by OchiengEd** [comment]
The conditions are being handled as generic status. So am totally with you, operator-sdk handle those. However, nothing stops an operator developer from adding a `.status.phase` to hold the status of the operand.

It might be a challenge for operator-sdk to effectively have generic code to tell the status of all operands.

**Comment by jmazzitelli** [comment]
```
$ oc -n servicemesh get kiali kiali -o json | jq .status.conditions[0].type
"Running"
```

My question is - where is that coming from? The Kiali operator itself is not setting that. I was assuming the operator sdk framework is the one setting that (or perhaps some underlying kubernetes/openshift component?)

**Comment by OchiengEd** [comment]
That is part of the conditions. Which would indicate that the operator-sdk is responsible for that. A review of the permalink I included two posts back would show you how that is being handled. Operator SDK does not give you a way to alter that, however, you can add custom status which we can take advantage of and add `.status.phase`

**Comment by jmazzitelli** [comment]
> indicate that the operator-sdk is responsible for that.

OK. That's what I suspected. So the operator-sdk does know the condition for the operand since it is populating this status.conditions.type field. Assuming that is true, and considering this is true:

`This results in the status being reported as Unknown in openshift dashboard or any other monitoring system that will check .status.phase like is used in other native kubernetes resources such as pods`

then I think we should ask the operator-sdk guys to add to the ansible operator base framework so that when it creates this `.status.conditions[0].type` with the appropriate value that at the same time they also create this `status.phase` with the same value. They should want to do this to help all ansible operators since it appears that type.phase is something all  openshift dashboards/other kubernetes monitoring systems check. Or am I still missing something?

**Comment by jmazzitelli** [comment]
I just want to be clear about something - because I was originally thinking this was the status on the kiali pod ... but this conversation is all about the status field on the Kiali CR itself. My kiali and kiali operator pods have status.phase. Just not in the  Kiali CR itself - and yes, for sure the operator-sdk is the one originally populating that status.

**Comment by OchiengEd** [comment]
Let me try address the issues seperately. We seem to be going in circles.

1. The `.status.phase` status shown in the jaeger CR allows the jaeger status to be correctly reported in Openshift console or any other tool that will use that to tell the status of an operand. So, if we add it in the kiali status, a user can determine the status of the CR through the openshift console or any other tool that will be looking for this information.

2. The `.status.conditions[0].type` or `.status.conditions` as a whole are specific to the status of the ansible runs. So, to be clear, that is not the status of the CR or the operand. If you do not wish to see that information, it can be turned off by adding `manageStatus: false`  in the  `watches.yaml` file.

3. The `operator-sdk` team is responsible for the status of the ansible plays. I totally agree with you 100% on that. However, they allow the operator developer to create operand specific status through the custom status as outlined in https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/dev/developer_guide.md#custom-resource-status-management.

In addition, operator-sdk allows you to disable the ansible specific status shown in `.status.conditions` as explained in 2 above. As a result, it does not appear as though there is anything for the operator-sdk team to resolve.

**Comment by jmazzitelli** [comment]
> The .status.phase status shown in the jaeger CR allows the jaeger status to be correctly reported in Openshift console or any other tool that will use that to tell the status of an operand.

OK, I now see what this enhancement request is asking for. You want the status of the OPERAND (the Kiali server pod) to be stored in the Kiali CR's `status.phase`.

Note that the Kiali operator does not perform periodic reconciliation runs today - it only performs a reconciliation run when the user updates one of the Kiali CRs that the operator is watching. So it will not be able to provide you with what you are looking for. At best it will tell you the status of the pod at that point in time when the last Kiali CR update occurred. In other words, today the operator will not be able to give you a real-time, current status of the Kiali operand - for that you should go directly to the source and look at the Kiali pod's status directly (which does have status.phase).

It would only be possible to do this by introducing periodic reconciliation runs within the ansible operator, but we originally had this enabled very, very early in the development of the operator and having the ansible playbook run periodically caused problems. I'm not saying it can't be done, I'm just saying there will be problems that need to be overcome if this "status.phase" is to be periodically updated, say, every 1 second or 10 seconds or whatever. Perhaps the operator would need to periodically check to see if the Kiali CR changed and if not, then skip everything it normally does and just populate the status.phase with the Kiali pod's current status. This of course would introduce a different runtime paradigm within the operator (rather than only run whenever the user updates the CR, it would need to run periodically every X seconds and do things differently if nothing changed).

But in the end, that would just simply be duplicating the same information available in the pod's "status". I would see this as a "nice to have" since the information is still available (in the pod "status" block), just not within the CR.

**Comment by OchiengEd** [comment]
I will play around with this and get back to you once I validate the issues brought up.

**Comment by OchiengEd** [comment]
Just thinking even without having periodic reconciliation, we can set the `.status.phase` at the end of the plays. I will try to put something together to explore this

**Comment by lucasponce** [comment]
@jmazzitelli is this issue still relevant ?

**Comment by jmazzitelli** [comment]
we do now have our own status fields that track the progress of the Kiali Operator (status.progress). It will look something like:

```
  progress:
    duration: "0:02:53"
    message: 7. Finished all resource creation
```

But this is really just a little more detail than what you already get with the operator-sdk status details.

We do not have the ability to track the progress of the kiali pod because the ansible playbook is not periodically reconciled (there are issues with that if we enable that - we used to do periodic reconciliation a long time ago but disabled it).

We should close this - without periodic reconciliation, this is not possible to implement, and we are not going to enable periodic reconciliation for the sole purpose of populating a status.phase field in the CR. The user will be able to obtain this by looking at the pod status itself, so it is still possible to obtain the status of the pod, just not through the Kiali CR.
