### ISSUE TITLE
Add support for custom authentication using a reverse proxy setup

### ISSUE THREAD

**Issue by JorenZ** [kiali/kiali#2216]
**General remarks**
(EDIT: it turns out the JWT policy I mentioned before was not active. Hence, this simplifies to just "Kiali UI behind Ambassador OIDC".)

We have run into an issue with our Kiali UI. It may be a bug, but we may very well be missing some configuration somewhere, in which case we'd be very happy to hear where to look for said configuration!

*Our situation*
Kiali is being served on an internal url protected by Istio using the Ambassador OIDC plugin (https://github.com/ajmyyra/ambassador-auth-oidc), which is working correctly: you navigate to the url, get redirected to the OIDC login, you log in, you are redirected back to the Kiali UI. The browser then includes a `cookie: auth=aBcD...eFgH` with requests, and everything works.

However, after your initial token expires, the UI seems to be unable to perform API calls.

**Describe the bug**
* initial login via the browser succeeds: visit https://kiali.our.url; redirect to OIDC login page; log in; redirect to https://kiali.our.url
* UI performs all calls with the `cookie: auth=aBcD...eFgH` header and all is well. For example:
  * UI calls https://kiali.our.url/kiali/api/namespaces; includes the header; returns 200 and a bunch of namespaces
  * UI calls https://kiali.our.url/kiali/api/mesh/tls; includes the header; returns 200 and an mTLS status

<5 minutes pass, the validity period of our JWTs>

* API calls start failing: UI performs calls without the `cookie: auth=aBcD...eFgH` header and all is not well. For example:
  * UI calls https://kiali.our.url/kiali/api/namespaces; does not include the header; returns 302 redirect to https://our.oidc.url/
  * UI calls https://kiali.our.url/kiali/api/mesh/tls; does not include the header; returns 302 redirect to https://our.oidc.url/

This yields UI errors like 'Could not fetch namespace list:' and 'Could not fetch apps list:', and a range of other 'Could not's because the API calls in question no longer get through.

*Related*
The Istio Ambassador pod logs each of these failed API calls:
* `/kiali/api/namespaces Cookie not set, redirecting to login.`
* `/kiali/api/mesh/tls Cookie not set, redirecting to login.`

We have found two workarounds for this:
* hard-refresh the page with F5. This causes a JWT refresh, and so the calls start succeeding again for 5 minutes:
  * `/kiali/api/namespaces Authorized & accepted.`
  * `/kiali/api/mesh/tls Authorized & accepted.`
* add an exception in the Ambassador URLs for `/kiali/api`. This also works, but for obvious reasons we would like to keep the API behind authentication just as much as the UI:
  * `/kiali/api/namespaces URI is whitelisted. Accepted without authorization.`
  * `/kiali/api/mesh/tls URI is whitelisted. Accepted without authorization.`

**Versions used**
Kiali: v1.12.0
Kiali operator version: v1.12.0
Istio: 1.4.2
Kubernetes flavour and version: 
* client: v1.17.0
* server: v1.15.5

**To Reproduce**
I can paste all the relevant Istio, Ambassador, Kiali elements here, if needed. 

**Expected behavior**
The UI keeps the JWT current, and includes it on all requests even after its initial period expires.

**Comment by israel-hdez** [comment]
Hi, @JorenZ. Can I know what authentication strategy are you using in Kiali? (anonymous, token, login or openshift)

**Comment by JorenZ** [comment]
Anonymous for now, since it's behind OIDC.

**Comment by israel-hdez** [comment]
OK, let's go step by step. I would like to replicate.

Let's assume that I already an Istio installation. I think we are fine if I use the [istioctl installation](https://istio.io/docs/setup/install/istioctl/). Most likely, customization to Istio isn't needed to replicate.

I see that you are using the Kiali operator. In case you are using the [advanced install](https://kiali.io/documentation/getting-started/#_advanced_install_operator_only), can you provide the Kiali operator CR that you used to install Kiali? (If you are using the [quick install](https://kiali.io/documentation/getting-started/#_quick_install), no need to provide the CR).

For Ambassador, I could follow the [instructions to install the Edge Stack](https://www.getambassador.io/user-guide/getting-started/#install-the-ambassador-edge-stack). Thereafter, I guess the setup is customized. Can you provide the remaining setup after the bare Edge Stack?

**Comment by JorenZ** [comment]
Thanks for the effort in advance! I need to leave now; will edit tomorrow with information from my end (and then we'll probably miss each other, so after that I'll probably have to answer next week.)

**Comment by JorenZ** [comment]
Bump to alert the edit above.

**Comment by JorenZ** [comment]
Update: see my edits above; the JWT policy I mentioned turned out to be misconfigured, so it was not doing anything at all.

The issue thus simplifies to "Kiali UI fails API calls after the initial JWT has expired."

**Comment by israel-hdez** [comment]
@JorenZ I'll try to do the setup today. Please, expect my reply soon.

**Comment by israel-hdez** [comment]
The only part that is missing is your ingress configuration that accepts the kiali.our.url to forward the request to Ambassador. But I can more, or less, imagine how it is done.

So, I understand that traffic to kiali.our.url is hitting the Ambassador service rather than hitting Kiali directly. Then Ambassador does the redirection to the 3rd party authentication service and once the user has authenticated, it goes back to Ambassador which creates a JWT token for usage under kiali.our.url domain.

Since Ambassador is always in the middle, this is basically a reverse proxy setup.

I have to admit that in the past we have recommended a reverse proxy setup if none of the auth mechanisms are suitable. But I see that Kiali is not prepared for this. The issue here is in the front-end which is not honoring the redirection to the 3rd party authentication page. Even if it follows the redirection, the UI would try to parse the page as if it were a response from the Kiali API.

So, I think that the reverse proxy is not well supported :/
I'll discuss this with the team tomorrow to see if we can find a quick fix.

**Comment by jmazzitelli** [comment]
> # However, setting `pod_annotations: sidecar.istio.io/rewriteAppHTTPProbers: true`
> # results in an edit somewhere and the final actual annotation ends up being
> # sidecar.istio.io/rewrite_app_http_probers, which is not recognized by Istio.

This is a bug, and I know why and where this is happening. This is a separate issue, but definitely needs to be fixed in the kiali operator. I'll submit a separate issue.

**Comment by JorenZ** [comment]
@israel-hdez : thanks for the verification; we're interested in the solution, if any.
@jmazzitelli: thanks for the unexpected side-issue fix <3

**Comment by jmazzitelli** [comment]
That side issue about the pod annotation getting converted to snake_case has been fixed and should be in the next release of the kiali operator. See PR #2248 which has been merged to master.

**Comment by israel-hdez** [comment]
Hi, @JorenZ 
I tried to find a fix before v1.14 release, but I failed. I thought the fix was trivial, but actually it's quite hard to add reverse proxy support.

Since reverse proxy is currently not supported, I'm reclassifying this issue as _enhancement_. We have received several issues about Kiali authentication, so we will discuss how to improve the general authentication mechanism. The discussion should happen over the following days. 

I'm sorry that a solution for your issue won't happen very soon. But, hopefully, we may add support in the short term.

**Comment by JorenZ** [comment]
Thanks for the effort!
Currently we're probably looking to replace Ambassador for another solution, and we'll see how that works re: authentication.

**Comment by israel-hdez** [comment]
Hi, @JorenZ 

Starting Kiali 1.19 (to be released today), a new _openid_ strategy has been implemented.
If your Kubernetes cluster is configured to accept bearer tokens emitted by your OpenID provider, you should not longer need Ambassador and the suggested setup is to enable _openid_ strategy to connect Kiali directly to your OpenId provider.

Since Kiali will now support OpenId Connect as a client, I'll close this issue. Feel free to either re-open or open a new issue if Kiali's implementation of OpenID does not suit your needs.
