### ISSUE TITLE
Integrate galley checks into kiali yaml editor

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#2250]
When users apply a config that has syntax/static errors, Galley prevent the application of that error saying something like the following:

```admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: total destination weight 120 != 100```

Kiali should integrate this message within the YAML editor. The request here is not to integrate the ```istioctl analyze``` message though.

For instance, the message shown above, should be processed to take the specific message and place it in the YAML. The position of the yaml might be guessed or, as a first iteration, it might be shown in the very first line of the editor.

The outcome should be:
Show an error marker at line 0 with message: total destination weight 120 != 100

**Comment by lucasponce** [comment]
Scope of the issue is clear.

Due galley uses a webhook, galley errors are returned as "runtime" errors when saving the object.
Those runtime errors can be parsed in the UI to differentiate them from other "runtime" error situations (i.e. backend is not responding).

Probably, with the galley error, it can't be positioned in a specific line (yet) but as it happens in these situation, Kiali can place these errors at top of the file.
