### ISSUE TITLE
Service list: Configuration icon is always Valid

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#2252]
Happens on master.
In a VS or DR belonging to some Service, make a change, that Error or Warning message is shown for that config.
In Service list, the configuration is always green and valid.

![Screenshot from 2020-02-17 15-16-36](https://user-images.githubusercontent.com/604313/74661574-80712900-5198-11ea-9013-de0b7a3624cb.png)

![Screenshot from 2020-02-17 15-15-30](https://user-images.githubusercontent.com/604313/74661498-5b7cb600-5198-11ea-969b-211d0ce1a28f.png)

**Comment by lucasponce** [comment]
I can take a look.

**Comment by lucasponce** [comment]
@hhovsepy I think this is not a bug:
https://kiali.io/documentation/validations/#services

The Service Validations don't expand to the Istio objects related, that's why the Service Icon is still in green.
I think this has been consistent in previous behaviour.

I understand that perhaps a feature could be to expand this info to ServiceList, but that would require some discussion, so I would separate it from this one.
