### ISSUE TITLE
Update Kiali-ui libraries

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2279]
Updating libraries can cause regressions and incompatibilities.  But they also provide bug fixes and can avoid security issues.  CVEs are extremely time consuming to deal with and it is worth staying relatively up to date with libaries as they in turn pull in a series of dependencies.  This epic is devoted to keeping track of when we last updated various libraries and PRs to track those updates.

We should also pay attention to updated recommended by Snyk.

**React Libs (typically updated as a set)**
-  [x] 16.9 Aug 26, 2019
-  [ ] update

**Redux**
-  [x] 16.9 Aug 26, 2019
-  [ ] update

**@Patternfly (typically updated as a set)**
-  [x] 2.44.2 Dec 10, 2019
-  [ ] update

**Cytoscape**
-  [x] 3.11 Oct 3, 2019
-  [ ] update

Snyk Alert:
- [ ] react-datepicker

**Comment by jotak** [comment]
Hey @mtho11 ,
In addition to these targeted updates, should we consider also to run a full dependency upgrade (without any explicit version bump - basically just regenerate yarn.lock) ?

**Comment by mtho11** [comment]
@jotak yes probably.

**Comment by mtho11** [comment]
I think many of these libs have been updated. But maybe the start of next sprint we go update everything (or everything that doesn't break us). @jshaughn @lucasponce WDYT?

**Comment by jshaughn** [comment]
It's tempting to perform a big update because it stops us from having to constantly evaluate the current update warnings and spend time deciding which to apply.  But the downside is that updates invariably cause unexpected issues, and like when changing several variables in an experiment, the root cause of a problem can then be hard to explain.   My initial reaction is to continue to apply dependency updates incrementally, mainly as needed for either a feature need or important security risk.

**Comment by jshaughn** [comment]
This needs to be consolidated with https://github.com/kiali/kiali/issues/2600 into a single epic.

**Comment by jshaughn** [comment]
Actually, I'm just going to close this one.   If you have further comments about update process please add it to #2600 .
