### ISSUE TITLE
Ensure all validations has object references

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#2447]
Referenced objects on validations were introduced in https://github.com/kiali/kiali/pull/1551.
However, it was a first iteration. There wasn't any task to keep adding new references.

Make sure the following object type validations have references:
- [x] #4693
- [x] Destination Rules
- [x] Gateways
- [x] MeshPolicies
- [x] ServiceEntries
- [x] Services
- [x] #4695
- [x] Sidecars

This can be a small epic.

**Comment by lucasponce** [comment]
Added to the Project per priorities purposes.

**Comment by lucasponce** [comment]
This effort could be use to revisit the side panel in the Istio Config editor.

Today is used in some resources but I think it could be used in a more general way covering:
- References of the workloads linked with a resource (using workload selectors).
- References of the internal services linked with a resource.
- References of the external destinations defined through ServiceEntry (a destination in a VirtualService can point to a ServiceEntry host, so the side panel could include these cases as well).

Perhaps the current decorators for the VirtualService / DestinationRules can be revisited if they are adding value.
In particular I'd say more interesting to help user to understand how a matching rule is performed rather than to show visually the distribution, in other words, in the context of this effort if some of those looks outdated I'd be ok to remove it.

**Comment by hhovsepy** [comment]
These newly adding references are not validations, but a reference like we have in DestinationRule overview page linking to Service.
Question: So do we need to add reference in UI only or coming from modified backend which should support returning references without validations?

**Comment by lucasponce** [comment]
I think this one is should be part of https://github.com/kiali/kiali/issues/4241

**Comment by hhovsepy** [comment]
The road-plan for this epic is:

- Research, organize an open discussion to choose from two concepts.
- - Thick UI, thin back-end: First concept is to have all references generated in UI only.
- - Thin UI, thick back-end: Second concept it is creating all links in backend (similar to validations) and sending list of IstioLinkKeys (new struct for reference types besides the validations) to UI.
- Define the scope of this epic and create sub-epics.
- Complete the fist 2 PoC sub-epics (back-end, UI) to show the references to one type of objects.
- Do a demo to team.
- Collect the feedback.
- Complete the rest of the epics.
- Final demo.

**Comment by lucasponce** [comment]
> Thick UI, thin back-end: First concept is to have all references generated in UI only.
> Thin UI, thick back-end: Second concept it is creating all links in backend (similar to validations) and sending list of IstioLinkKeys (new struct for reference types besides the validations) to UI.

This is a very good discussion. I have also thought about this as well. Both approaches have pros/cons, but I guess that moving the logic to the front-end, it's a direction that we are changing i.e., https://github.com/kiali/kiali/issues/4611.

I'd say that in the short term, it could be good that the project tends to consolidate a single architecture (i.e. business logic in the backend and render in the front-end) before introducing big architectural changes.

But definitely in the context of mid/long term, all of this can be reviewed and see if that's something worth moving. For example, a pure/heavy front-end architecture is used in other projects like the OpenShift console.

Thinking in this issue in particular, I was thinking that probably at the moment that the Istio Configuration is fetched from the registry, perhaps is when that can trigger a process to build the references (this process could be sync/async depending on the design). And those references can be rendered in an optional way: if those exist, then perfect; if those are not available, the user keeps operating in the yaml.

**Comment by hhovsepy** [comment]
I did research of already done links with host references.
So the solution is somewhere between two suggestions.
It definitely require UI changes in a scope of https://github.com/kiali/kiali/issues/4241.
But also backend validations should return reference objects, including cross-namespace ones.

**Comment by hhovsepy** [comment]
> > These newly adding references are not validations, but a reference like we have in DestinationRule overview page linking to Service. Question: So do we need to add reference in UI only or coming from modified backend which should support returning references without validations?
> 
> @hhovsepy in the side panel re design, I guess that will be helpful to have the references split from validations, because when configs are ok, we still want to reference the config to other objects, right?.

Right, as we agreed on the call, the references will come form backend, in a form of a map, and will be rendered in UI.

**Comment by hhovsepy** [comment]
In IstioValidations mechanism, Kiali is making validations for all objects, then returning to UI only the validdations for requested Object by it's type and name. This is done it that way because Validations are shown in List page and in Overview page of objects.

The References should be shown in Object's Overview page only, so the logic of retrieving references in backend will be only for particular Object name/namespace/type, which will make response faster.

**Comment by hhovsepy** [comment]
Closing this issue as backend tasks are completed and integrated with UI https://github.com/kiali/kiali/issues/4241.
