### ISSUE TITLE
Validation references tied to a line/block of code

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#2448]
In the yaml editor page, when the yaml has multiple validations, each reference in the list is not clear which is the validation tied to.

Scenario: 
- Istio Object editor page,
- the yaml has multiple validations and 
- there is a list of referenced objects into the right side.

Similar to this one:
![Screenshot of Kiali Console (21)](https://user-images.githubusercontent.com/613814/75362310-d2146480-58b8-11ea-99c4-dafc6d60f335.png)

The feature request here is to tie each validation in the yaml editor to each reference in the right side.

This needs a bit of research regarding the functionalities of the ACEeditor. The options could be something like:

a) Click to the validation marker or place the cursor in one validation and show the referenced objects to that validation. The degree of interaction is high.

b) Change the layout of the sidebar to list all the validations and its related objects. The degree of interaction is low.

**Comment by lucasponce** [comment]
This issue is old but valid.
Current status of the sidepanel is the following:
![image](https://user-images.githubusercontent.com/1662329/107957352-c5dd5780-6fa0-11eb-9215-f7a796c8974e.png)

Adding changes in the current logic of the ACEditor may be tricky, as it looks this can trigger more cornercases on nested elements.

My suggestion would be to add support of the validations in the side panel as a list/table, just to indicate to the user the number of problems.

cc @xeviknal

**Comment by lucasponce** [comment]
I think this one is close to #2447 or it may need some progress first to decide how to address it.
I add @xeviknal on it but feel free if it can be taken by other engineer as well.

**Comment by hhovsepy** [comment]
Closing this issue as YAML editor and side panel was redesigned in scope of https://github.com/kiali/kiali/issues/4241

**Comment by lucasponce** [comment]
This is outdated, it can be addressed on this new issue https://github.com/kiali/kiali/issues/5204
