### ISSUE TITLE
kiali api not returning any data

### ISSUE THREAD

**Issue by himanshi23** [kiali/kiali#249]
when i'm accessing the productpage-v1 metrics using the api calls the data is not getting populated.
command : curl -u admin:admin http://169.53.36.106:31632/api/namespaces/istio-system/services/productpage-v1/metrics

output:
{"metrics":{"request_count_in":{"matrix":[]},"request_count_out":{"matrix":[]},"request_error_count_in":{"matrix":[]},"request_error_count_out":{"matrix":[]}},"histograms":{"request_duration_in":{"average":{"matrix":[]},"median":{"matrix":[]},"percentile95":{"matrix":[]},"percentile99":{"matrix":[]}},"request_duration_out":{"average":{"matrix":[]},"median":{"matrix":[]},"percentile95":{"matrix":[]},"percentile99":{"matrix":[]}},"request_size_in":{"average":{"matrix":[]},"median":{"matrix":[]},"percentile95":{"matrix":[]},"percentile99":{"matrix":[]}},"request_size_out":{"average":{"matrix":[]},"median":{"matrix":[]},"percentile95":{"matrix":[]},"percentile99":{"matrix":[]}},"response_size_in":{"average":{"matrix":[]},"median":{"matrix":[]},"percentile95":{"matrix":[]},"percentile99":{"matrix":[]}},"response_size_out":{"average":{"matrix":[]},"median":{"matrix":[]},"percentile95":{"matrix":[]},"percentile99":{"matrix":[]}}}}

Does anyone have documentation related to api calls?

**Comment by pilhuhn** [comment]
@himanshi23 Quick question: is the bookinfo demo deployed into the istio-system namespace? I.e. is there a productpage service in it?
If not could you try replacing `istio-system` in the above with `bookinfo`?

If the productpage is not in istio-system, then the api call should of course return a 404 and not an empty object. Otherwise we need to investigate further.

**Comment by jotak** [comment]
There's no real documentation at the moment except in-code comments: https://github.com/kiali/kiali/blob/master/routing/routes.go#L82-L95

If your service is named "productpage" and you try to get metrics for its v1, then the url should be /api/namespaces/bookinfo/services/productpage/metrics?version=v1

But note that it is not (yet?) really meant to be consumed by something else than the Kiali frontend - not because you can't, but because it may have breaking changes without further notice.

**Comment by himanshi23** [comment]
@pilhuhn Yes, you are right. In my case  productpage service is in default namespace but still the api call is returning an empty object. So i guess  some fixation need to be done here .

**Comment by himanshi23** [comment]
@jotak Thanks for your help.
