### ISSUE TITLE
Unable to add node affinity to Kiali Operator

### ISSUE THREAD

**Issue by ronberna** [kiali/kiali#2555]
We are in the process of implementing Istio and would like to utilize the Kiali Dashboard.  With our current setup we would like our Istio and Kiali components to run on certain K8s nodes.  Right now there is now way to set node affinity on the Kiali operator.  Would like to have the ability to set node afinity on the Kiali Operator

**Comment by jmazzitelli** [comment]
To implement this issue, we'd need to do two things:

1) Update deploy-kiali-operator.sh to somehow be given these custom settings (note: this would open a pandora's box - because what about being able to customize tolerations, resources, annotations on the deployment, annotations on the pod, node selectors, etc).

2) We should add analogous features to the OLM metadata to achieve feature parity. This would allow someone to set this kind of thing for the operator when installing via OLM. This kind of thing is already supported (well, tolerations and resources are - see https://github.com/operator-framework/operator-lifecycle-manager/pull/1334)

Workaround for this issue: Download the one or more yaml files you want to customize from https://github.com/kiali/kiali/tree/master/operator/deploy and modify as needed. Then run the deploy-kiali-operator.sh - it will use those local copies of files. If you only need to modify the Deployment (which is all that would be needed for affinity settings), then just modify that one "operator.yaml" file and put it in the directory - the rest should get pulled down by the script from github normally.

**Comment by israel-hdez** [comment]
I thought that affinity was doable by using proper settings in the operator CRD:

https://github.com/kiali/kiali/blob/8aedcb62e47d933d38d1f717af4483e20c0205c3/operator/deploy/kiali/kiali_cr.yaml#L186-L193

Isn't this what @ronberna is seeking?

**Comment by jmazzitelli** [comment]
> Isn't this what @ronberna is seeking?

no. that is the Kiali CR settings which means it configured Kiali server itself. He wants to set affinity to the Kiali OPERATOR (not Kiali server).

**Comment by jmazzitelli** [comment]
> I thought that affinity was doable by using proper settings in the operator CRD:

BTW: that is the kiali CR (the custom resource) not the Customer Resource Definition (CRD). The CRD defines the Kiali type - the Kiali CR defines an instance of Kiali.

**Comment by jmazzitelli** [comment]
This doesn't directly address this issue, but as an FYI, we are now going to be releasing all-in-one yaml files in the kiali-operator repo's deploy/ directory. So if the deploy script is not able to customize the operator resources the way you want, you can avoid running the script entirely by just grabbing the all-in-one, modifying it to customize the operator how you want, and use kubectl apply to deploy/update the operator.

For each release you can grab its all-in-one yaml from the specific release branch.

You will find the master copy of this file here (this is the master branch copy): https://github.com/kiali/kiali-operator/blob/master/deploy/kiali-operator-all-in-one.yaml

**Comment by jmazzitelli** [comment]
This is possible now with the helm chart: https://github.com/kiali/helm-charts/blob/v1.22.1/kiali-operator/values.yaml#L10-L17
