### ISSUE TITLE
Make the operator install script idempotent

### ISSUE THREAD

**Issue by yogeek** [kiali/kiali#2561]
**Is your feature request related to a problem? Please describe.**
When installing the operator in an automated pipeline with the following command :
```
bash <(curl -L https://git.io/getLatestKialiOperator) --operator-install-kiali false
```
the first time, the operator is installed correctly but the second time this pipeline is launched, the script is asking to uninstall the already installed operator version, even if the version has not changed. 
A way to avoid this interactive behaviour is apparently to set ` UNINSTALL_EXISTING_OPERATOR=true` but it causes the script to abort and exit with a non-zero status code.
It is not suited for regular automation installations.
An idempotent script would be better.

**Describe the solution you'd like**
A solution can be that the script re install the operator only if a new version is available. For this, the script could check the version already installed and compare to the version (either specified by the `OPERATOR_IMAGE_VERSION` or `lastrelease` by default) and do nothing but displaying a message if the operator is already installed in the same version.

**Comment by jmazzitelli** [comment]
There are [options](https://github.com/kiali/kiali/blob/master/operator/deploy/deploy-kiali-operator.sh#L362-L370) to help with non-interactive installs. However, if an operator is already seen to be installed and you opt not to remove it, [yes it aborts](https://github.com/kiali/kiali/blob/master/operator/deploy/deploy-kiali-operator.sh#L822-L824). This is because this script is not designed to do upgrades; it is mainly to be considered an installer (with "upgrades" being done in a brute force manner - uninstalling and then installing).

If you want true upgrades, the recommended solution is to use [OLM](https://github.com/operator-framework/operator-lifecycle-manager) to manage the operator, not this script.

With that said, it may be possible to change this script to perform standing upgrades, but it might not be trivial to do so.

**Comment by yogeek** [comment]
Hi @jmazzitelli , thanks for the clarification.
I will try to test some solutions for the script to check if a new version is needed and maybe propose a PR.

**Comment by jmazzitelli** [comment]
This doesn't directly address this issue, but as an FYI, we are now going to be releasing all-in-one yaml files in the kiali-operator repo's deploy/ directory. So if you want to avoid running the script entirely, you can grab the all-in-one (modifying it if you want to customize the operator) and use kubectl apply to deploy/update the operator.

For each release you can grab its all-in-one yaml from the specific release branch.

You will find the master copy of this file here (this is the master branch copy): https://github.com/kiali/kiali-operator/blob/master/deploy/kiali-operator-all-in-one.yaml

**Comment by jmazzitelli** [comment]
I have a PR for this. Won't be merged until someone reviews and tests it: https://github.com/kiali/kiali-operator/pull/37
