### ISSUE TITLE
Operator installer script default values

### ISSUE THREAD

**Issue by yogeek** [kiali/kiali#2565]
**Describe the bug**

[This section of the deploy-kiali-operator.sh](https://github.com/kiali/kiali/blob/master/operator/deploy/deploy-kiali-operator.sh#L863-L884) script does not seem to do what it describes.

In my tests, when I am not setting the variable `UNINSTALL_EXISTING_KIALI`, the script still uninstall the operator whereas the behaviour described [here](https://github.com/kiali/kiali/blob/master/operator/deploy/deploy-kiali-operator.sh#L44) indicates that the default value for this variable is `false`. 
As the script never sets this variable to false, when the section referenced above checks the variable, it enters the if even if the var is not set, the opposite the definition of the var indicates.

**Versions used**
Kiali: 1.15
Istio: 1.4
Kubernetes flavour and version: vanilla k8s 1.15

**To Reproduce**

1. Launch the script without setting any var :
```
bash <(curl -L https://git.io/getLatestKialiOperator)`
```
2. The script uninstall the already installed operator
3. Launch the script with the var :
```
export UNINSTALL_EXISTING_OPERATOR=false
export UNINSTALL_EXISTING_KIALI=false
export UNINSTALL_MODE=false
bash <(curl -L https://git.io/getLatestKialiOperator)
```
4. the script does not uninstall and abort (on this matter, I opened #2561 for the script to exit 'properly' when this happens)

**Expected behavior**

When no variable is set, the default value must be "false" as stated in the script comments

**Comment by jmazzitelli** [comment]
I haven't looked deeply, but try the cmdline opts `-uek` and `-ueo` rather than the env. variables and see if the behavior changes.

Run `bash <(curl -L https://git.io/getLatestKialiOperator) --help` for the help description on those options.

**Comment by jmazzitelli** [comment]
> In my tests, when I am not setting the variable UNINSTALL_EXISTING_KIALI, the script still uninstall the operator

That env var is only for Kiali, not the operator. The --uninstall-existing-kiali is only taking about uninstalling the kiali server - it is not affecting the operator. See --uninstall-existing-operator for that.

**Comment by jmazzitelli** [comment]
sorry - meant to hit comment not "close and comment" :)

**Comment by jmazzitelli** [comment]
I'll look into this shortly. Currently fighting  fire at the moment.

**Comment by jmazzitelli** [comment]
I cannot reproduce this.

But first I want to make clear about a possible misunderstanding.

In this issue description I read:

> [This section of the deploy-kiali-operator.sh](https://github.com/kiali/kiali/blob/v1.15.1/operator/deploy/deploy-kiali-operator.sh#L863-L884) script does not seem to do what it describes.
> In my tests, when I am not setting the variable UNINSTALL_EXISTING_KIALI, the script still uninstall the operator whereas the behaviour described [here](https://github.com/kiali/kiali/blob/v1.15.1/operator/deploy/deploy-kiali-operator.sh#L44) indicates that the default value for this variable is false.

Please note that the sections linked refer to the KIALI install (the server) *not* the operator. You want to look at [this section of the deploy-kiali-operator.sh](https://github.com/kiali/kiali/blob/v1.15.1/operator/deploy/deploy-kiali-operator.sh#L820-L846) which deals with the uninstall of the operator.

Remember the two are distinct. You can uninstall kiali (the server) but not the operator. But the reverse is not true - if you uninstall the operator, Kiali (the server) goes with it - that's just the nature of the beast (because removal of the operator means removal of the CRD and thus removal of the Kiali CR and thus removal of Kiali).

OK, but with that in mind, it really doesn't matter because there is similar code for the unistalling of the operator. But I did want to point out the difference between "kiali" and the "operator" (when "kiali" is mentioned it typically refers to the kiali  server deployment, not the operator).

Step 1 in replication procedures of the description says to run:

```
bash <(curl -L https://git.io/getLatestKialiOperator)
```

When I do this, I get a prompt:

`It appears the operator has already been installed. Do you want to uninstall it? This will uninstall Kiali, too. [Y/n]:`

And I have to answer interactively by typing in either Y or N. It doesn't blindly uninstall until I answer the prompt. And that is the behavior we want - we do not want to tear down the entire operator/kiali deployment unless the user explicitly says it is OK (either by answer Y at the prompt or passing in `-ueo true` on the command line).

The only way to not get the prompt is to pass in `-ueo` (aka `--uninstall-existing-operator`) with either true of false (this is the same as setting the env var - I prefer the cmdline options though). There are similar things for kiali (`-uek` or `--uninstall-existing-kiali`).

If you pass in `-ueo false` you will get the message `It appears the operator has already been installed. It will NOT be uninstalled. Aborting the operator installation.` and the script aborts. `-ueo true` will do the uninstall and then re-install.

With all of that, yes, the default documented in the comments should change. The defaults for the uninstall existing kiali and operator are not "false" - if not specified, you will be prompted for an answer.

This means these two comments should change:

https://github.com/kiali/kiali/blob/v1.15.1/operator/deploy/deploy-kiali-operator.sh#L44

https://github.com/kiali/kiali/blob/v1.15.1/operator/deploy/deploy-kiali-operator.sh#L51

Both should change to say:

```
Default: If not explicitly defined, an interactive prompt will ask for confirmation.
```

**Comment by yogeek** [comment]
Hi @jmazzitelli , thank you for your quick reply and for these precisions.

Indeed, when I copied the script section and vars, I switched the Kiali operator ones with the Kiali instance ones but you got it ;)

Thank you for the clarification.
