### ISSUE TITLE
Outbound Metrics Tab looks strange

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2614]
**Describe the bug**
Maybe things have been changed, however, the Outbound Metrics tab looks strange to me:

![Kiali_Console](https://user-images.githubusercontent.com/1312165/78408526-462ee000-75bc-11ea-8e97-3191654da275.png)

**Versions used**
Kiali: 1.16.0
Istio: 1.5.1
Kubernetes flavour and version: Minikube

**Comment by jotak** [comment]
I agree we could probably have something better, but today this is the intended display. See this issue: https://github.com/kiali/kiali/issues/2495

@lwrigh provided two mockups, one with bigger "empty state" blocks and the second with smaller ones & only texts. I chose the second, because the intent is to have small enough empty blocks to allow reaching easily metrics at the bottom (consider the case where you have no HTTP metrics, but TCP ones).

**Comment by jotak** [comment]
Just an idea: perhaps we could have every chart as a collapsible block. The chart title is always displayed, but content can be collapsed / expanded on click.
When there's no data, we show the bigger empty state block, but displayed collapsed on first display (whereas chart with data isn't collapsed by default).

**Comment by lwrigh** [comment]
I was thinking something similar, if there is data it should be left open as the default and the user can make the decision to collapse it if is collapsable.

**Comment by lucasponce** [comment]
> Just an idea: perhaps we could have every chart as a collapsible block. The chart title is always displayed, but content can be collapsed / expanded on click.
When there's no data, we show the bigger empty state block, but displayed collapsed on first display (whereas chart with data isn't collapsed by default).

+1 on this and it seems UX comments are aligned.

**Comment by jshaughn** [comment]
+1, please make this look better :)

**Comment by jotak** [comment]
Since we're going to have collapsible blocks now, I'm also thinking about introducing a new "StartCollapsed' flag in charts (including in monitoringdashboard CRD) so that we can mark charts as being collapsed by default.

This could be useful to prioritize metrics, and make some of them more visible than others. For instance we've just introduced new "throughput" metrics (https://github.com/kiali/kiali/pull/2912) but we could decide to make it collapsed by default.

**Comment by lucasponce** [comment]
@jotak it has +1, I'm always thinking that any improvement on the metrics charts could be a good addition.

**Comment by mtho11** [comment]
@jotak +1 seems like a good improvement!
