### ISSUE TITLE
Investigate Google Season of Docs for kiali.io

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#2619]
Epic: https://github.com/kiali/kiali/issues/2181

In our sprint retro @israel-hdez mentioned [Google Season of Docs](https://developers.google.com/season-of-docs) as something possibly beneficial for our Docs.  I don't know much about it but perhaps it is worth looking into.

@JStickler Any info/opinion on this?

**Comment by JStickler** [comment]
Google Season of Docs has come up a couple of times in the Community Docs Forum meetings.  @shaunix is looking at successful applications from the last round and working on a template for what should be included in applications.  From my point of view, the main difficulty is having documentation that you know needs to be done, but that can wait several months until you have an intern to work on it.  Which is why I'm glad @lucasponce linked to the reorganize documentation issue.

**Comment by JStickler** [comment]
There are a couple of information sessions scheduled for Season of Docs if people are interested or have questions.

Monday, April 20th at 17h00 UTC 
Monday, April 27th at 12h30 UTC 

https://groups.google.com/forum/#!msg/season-of-docs-announce/r5fdo49zKVc/R08F-SzYBAAJ

**Comment by israel-hdez** [comment]
So, deadline is May 4th. I think we virtually lost the chance for this year.

I was mainly thinking this for doc reorg rather than for writing new docs. Not sure if that's under the scope of the program. Anyway, not worth to keep this open if we cannot make a submission before the deadline, so I'll close this on Monday (the deadline for applications). Perhaps, try the next year is docs are still an issue.

**Comment by israel-hdez** [comment]
The deadline has passed. I'll close this issue.
