### ISSUE TITLE
Kiali Trace is not showing when service name different from application name

### ISSUE THREAD

**Issue by previousdeveloper** [kiali/kiali#2664]
**Versions used**
Kiali: 1.15.1
Istio: 1.15.1
Kubernetes flavor and version: on-prem

Kiali trace UI not showing when the service name is a different application name. 

Jeager UI Query Example

`jaeger/api/traces?end=1586978581317000&limit=20&lookback=1h&maxDuration&minDuration&service=product-detail-api.browsing-team&start=158697498131700`

Kiali Trace Ui Query Example

`kiali/api/namespaces/browsing-team/services/stage-product-detail-api/traces?limit=20&start=1586978063537000&end=1586978663537000 `

That's query return empty result. When we query with the application name the result not empty.

This case happens when the service name differs application name.

**Comment by aljesusg** [comment]
Hi @previousdeveloper , thanks to open the issue.

Can you share with me the tracing configuration that you have in the congif file?

**Comment by previousdeveloper** [comment]
This is a kali config map.

<img width="627" alt="Screen Shot 2020-04-15 at 23 01 09" src="https://user-images.githubusercontent.com/6371971/79383086-45f3f480-7f6d-11ea-9b1b-c70170d26d10.png">

<img width="1790" alt="Screen Shot 2020-04-15 at 23 04 32" src="https://user-images.githubusercontent.com/6371971/79383219-7dfb3780-7f6d-11ea-9d7d-e33db2435778.png">

<img width="704" alt="Screen Shot 2020-04-15 at 23 05 34" src="https://user-images.githubusercontent.com/6371971/79383315-abe07c00-7f6d-11ea-84ac-170e6adfd4bb.png">
This query result is empty.

When a change to query stage-product-detail-api to product-detail-api( this is application name )


<img width="840" alt="Screen Shot 2020-04-15 at 23 09 09" src="https://user-images.githubusercontent.com/6371971/79383620-26a99700-7f6e-11ea-9835-15f6f4c48890.png">

The query result is not empty.

When deleting stage prefix from URL that's works well.

<img width="1791" alt="Screen Shot 2020-04-15 at 23 12 47" src="https://user-images.githubusercontent.com/6371971/79383968-c404cb00-7f6e-11ea-8ebd-7ab10684cd06.png">

**Comment by aljesusg** [comment]
Hi @previousdeveloper 

So the problem here is the namespaceSelector param in configuration


In some env the tracing is adding the service like `<service>.<namespace>` and in other environment the user is doing the tracing with only `<service>`

I saw in your comment that in jaeger you use the namespace browsing-team

> Jeager UI Query Example
> 
> jaeger/api/traces?end=1586978581317000&limit=20&lookback=1h&maxDuration&minDuration&service=product-detail-api.browsing-team&start=158697498131700
> 
> Kiali Trace Ui Query Example
> 
> kiali/api/namespaces/browsing-team/services/stage-product-detail-api/traces?limit=20&start=1586978063537000&end=1586978663537000

by default 
```yaml
namespace_selector: true
```

You must set it to false.

**Comment by aljesusg** [comment]
> This is a kali config map.
> 
> <img alt="Screen Shot 2020-04-15 at 23 01 09" width="627" src="https://user-images.githubusercontent.com/6371971/79383086-45f3f480-7f6d-11ea-9b1b-c70170d26d10.png">
> 
> <img alt="Screen Shot 2020-04-15 at 23 04 32" width="1790" src="https://user-images.githubusercontent.com/6371971/79383219-7dfb3780-7f6d-11ea-9d7d-e33db2435778.png">
> 
This service is different than the other one
> <img alt="Screen Shot 2020-04-15 at 23 05 34" width="704" src="https://user-images.githubusercontent.com/6371971/79383315-abe07c00-7f6d-11ea-84ac-170e6adfd4bb.png">
> 
> This query result is empty.
> When a change to query stage-product-detail-api to product-detail-api( this is application name )
> 
> <img alt="Screen Shot 2020-04-15 at 23 09 09" width="840" src="https://user-images.githubusercontent.com/6371971/79383620-26a99700-7f6e-11ea-9835-15f6f4c48890.png">
> 
> When deleting stage prefix from URL that's works well because my application name is product-detail-api
> 
> <img alt="Screen Shot 2020-04-15 at 23 12 47" width="1791" src="https://user-images.githubusercontent.com/6371971/79383968-c404cb00-7f6e-11ea-8ebd-7ab10684cd06.png">

This one 

it seems that you have 2 services 

- product-detail-api
- stage-product-detail-api

Can you confirm that jaeger is returning traces for service **stage-product-detail-api**? I can only see traces for **product-detail-api**

**Comment by jotak** [comment]
@aljesusg as far as I understand, `product-detail-api` is the *application* name whereas `stage-product-detail-api` is the *service* name.

One assumption that we do in Kiali, and perhaps we don't document it as it should, is that we expect traces to be created with *service* name (or even better: *service.namespace*, to be consistent with envoy-generated traces), ie. the same name that is used for the Service kube resource. In other words, if your service is named `stage-product-detail-api`, we expect the traces to have that same service name.

Perhaps there is room for improvement here (more configuration about that? annotation-based service name? what else?)

**Comment by aljesusg** [comment]
> @aljesusg as far as I understand, `product-detail-api` is the _application_ name whereas `stage-product-detail-api` is the _service_ name.
mmm but the screenshoot the product-detail-api show traces in the service so it seems that he is propagating the traces by app instead by the service
> 
> @previousdeveloper One assumption that we do in Kiali, and perhaps we don't document it as it should, is that we expect traces to be created with _service_ name (or even better: _service.namespace_, to be consistent with envoy-generated traces), ie. the same name that is used for the Service kube resource. In other words, if your service is named `stage-product-detail-api`, we expect the traces to have that same service name.
> 
> Perhaps there is room for improvement here (more configuration about that? annotation-based service name? what else?)

yeah this is that I was thinking...Why are you creating the traces with the app name instead service?
Maybe it makes sense and we can add some flag in configuration to enable traces by app ??¿?

**Comment by jwurm** [comment]
I'm having a similar issue. It seems to hinge on the service name not matching the app label of the workload. Perhaps app label and workload name were identical in your case, and both differed from the service name.

Here is what i observed:

Kiali 1.20.0 and Istio 1.6.2

Example:
Workload: example with label **app=example-label** and version=2
Service: **example-v2** that selects for app=example-label and version=2

Cause some traffic on that service that should be registered by jaeger

In Kiali in the "Services" view, navigate to "Traces". There won't be any results

The URL on the traces page in the browser looks like this:
/kiali/console/namespaces/mynamespace/services/**example-v2**?tab=traces&limit=20

If i just manually change it to refer to the value of the app label, "example-label", then it displays the traces of the example-v2 service:
/kiali/console/namespaces/mynamespace/services/**example-label**?tab=traces&limit=20

The reason seems to be that Kiali queries Jaeger for traces for a "service" with the name of the kubernetes service, but in the jaeger UI the name of the service is listed as "operation", whereas there "service" apparently refers to the app label of the workload. 
So the cause may be a simple mismatch of parameters that doesn't get noticed if by coincidence/convention the service name matches the workload app label

**Comment by jotak** [comment]
Hi @jwurm , that's interesting, I didn't realize the 'app' label was used as the service name ... need to double-check in istio, and also check if it's something that they changed at some point . Thanks for your help.

**Comment by jotak** [comment]
If this is true, then it means the Traces tab would be better placed in App details than in Service details, in Kiali

**Comment by aljesusg** [comment]
Totally...

**Comment by jotak** [comment]
Fixed through https://github.com/kiali/kiali-ui/pull/1866

Follow-ups: #2710 and #3071
