### ISSUE TITLE
Labels in Apps list are randomly changed after refresh

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#2670]
Happens on Kiali master. And issue coming from Kiali backend.

List applications.
Search for "jaeger"
Refresh the results several times.
The "jaeger-infra: " label's value is changing with refresh.
This happens in the REST API call as well. "api/namespaces/istio-system/apps".

![Screenshot from 2020-04-16 17-35-24](https://user-images.githubusercontent.com/604313/79477084-0cbd9200-800a-11ea-9971-3fac293e98ec.png)
![Screenshot from 2020-04-16 17-35-26](https://user-images.githubusercontent.com/604313/79477087-0d562880-800a-11ea-86ba-31094f70882b.png)
![Screenshot from 2020-04-16 17-35-35](https://user-images.githubusercontent.com/604313/79477092-0deebf00-800a-11ea-86a8-c544fc8fef62.png)
![Screenshot from 2020-04-16 17-36-22](https://user-images.githubusercontent.com/604313/79477093-0e875580-800a-11ea-837e-5bbaec21f280.png)
![Screenshot from 2020-04-16 17-36-49](https://user-images.githubusercontent.com/604313/79477095-0f1fec00-800a-11ea-9414-e5219c56acc5.png)
![Screenshot from 2020-04-16 17-37-14](https://user-images.githubusercontent.com/604313/79477097-0f1fec00-800a-11ea-964c-ad8ebe23096f.png)

**Comment by aljesusg** [comment]
Ok so the "thing" that change is the value, I thought it was related with the order/sort. 

Is this happen when you deploy the environment in the first time or ever?

I think that maybe the jaeger-infra is not 100% ready in this case because is adding new components.

1. collector
2. collector, jaeger-service
3. collector, jaeger-service, agent-service

Is this changing in refresh after the 3º result? In that case there is a problem. On other case I think that this value change after that app is ready.

Maybe the Jaeger team can teach us about this.
Can you confirm this @objectiser, @pavolloffay  or @jpkrohling ?

**Comment by hhovsepy** [comment]
The change happens  much later after environment deployment, and not in order 1,2,3 but randomly, so after 3 labels it can switch to any of 1,2.

**Comment by aljesusg** [comment]
Ok, I'm going to check it because it's weird.
Is this only with Jaeger service?

**Comment by pavolloffay** [comment]
Which component is managing the object that has these labels? You can find that by owner reference in labels/annotations.

**Comment by aljesusg** [comment]
@hhovsepy I need more information I can't reproduce this in SM 1.1. 
is it Maistra? jaeger all-in-one?

**Comment by hhovsepy** [comment]
@aljesusg it happens on latest upstream Kiali and Istio 1.5.2 on istio-tracing workload's application.

**Comment by jotak** [comment]
I can reproduce as well; @aljesusg let me know if you don't reproduce I could take this one

**Comment by aljesusg** [comment]
I tested in Maistra not in Upstream I need to check if I can reproduce it. Anyway it seems this is comming from backend, feel free if you want take it @jotak

**Comment by jotak** [comment]
Taking it
