### ISSUE TITLE
[Tracing] Warning Check in Service 

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#2708]
# introduction
We are fetching the traces from jaeger in the last X min. We can check with a statistical standard deviation if there are traces that are taking more time than expected from other moments...in that case we can show any “tracing warning” and show the user that there is a workload taking more time than expected.

# Plus
In this point we can show the specific logs of the span that is taking the time. 
Maybe here it would be a nice idea set some light the lines of the log in the (workloads logs) related with this span to help the user find the problem.

**Comment by jotak** [comment]
+1 about introducing some analytic

We should try to figure out also when it makes more sense to work from traces or from metrics, because there is sometimes an overlap; for instance, doing analytic about latency with standard deviation can be achieved with both, but would probably be easier and faster to query with metrics than traces, and cover more cases since it would work even when tracing isn't enabled; however the advantage of using traces is that it gives more insight by being able to show the exact traces that are "off the rails". Perhaps a combination of both would be the most efficient...

See also https://github.com/kiali/kiali/issues/1981 , these two tasks can be part of the same "analytic" effort.

**Comment by jotak** [comment]
Also, about correlation with logs, are we able to have hard correlation (like if istio-proxy logs show span/trace IDs) ? Or would it be just by selecting a restrained time frame that corresponds to the time of the trace/span ?

**Comment by aljesusg** [comment]
> Also, about correlation with logs, are we able to have hard correlation (like if istio-proxy logs show span/trace IDs) ? Or would it be just by selecting a restrained time frame that corresponds to the time of the trace/span ?

I was thinking more in the second option **_selecting a restrained time frame that corresponds to the time of the trace/span_**

**Comment by aljesusg** [comment]
# UPDATE

## Cases to work

1. We can get the duration with the metrics in prometheus we need to filter by app and destination_app to be sure that the time is related with the app that we are requesting his health and no other "subservice"

2. Check if a app is generating traces. (Fetch jaeger, disable by default). Check if other apps in the NS are generating traces (cached) if there are others so we need to alert.

cc @lucasponce @jotak 

## Samples

```json
istio_request_duration_milliseconds_sum{app="reviews",connection_security_policy="mutual_tls",destination_app="reviews",destination_canonical_revision="v1",destination_canonical_service="reviews",destination_principal="spiffe://cluster.local/ns/bookinfo/sa/bookinfo-reviews",destination_service="reviews.bookinfo.svc.cluster.local",destination_service_name="reviews",destination_service_namespace="bookinfo",destination_version="v1",destination_workload="reviews-v1",destination_workload_namespace="bookinfo",instance="172.17.0.16:15020",istio_io_rev="default",job="kubernetes-pods",kubernetes_namespace="bookinfo",kubernetes_pod_name="reviews-v1-7f6558b974-szsvb",pod_template_hash="7f6558b974",reporter="destination",request_protocol="http",response_code="200",response_flags="-",security_istio_io_tlsMode="istio",service_istio_io_canonical_name="reviews",service_istio_io_canonical_revision="v1",source_app="productpage",source_canonical_revision="v1",source_canonical_service="productpage",source_principal="spiffe://cluster.local/ns/bookinfo/sa/bookinfo-productpage",source_version="v1",source_workload="productpage-v1",source_workload_namespace="bookinfo",version="v1"}  645
```

```json
istio_request_duration_milliseconds_sum{app="reviews",connection_security_policy="unknown",destination_app="ratings",destination_canonical_revision="v1",destination_canonical_service="ratings",destination_principal="spiffe://cluster.local/ns/bookinfo/sa/bookinfo-ratings",destination_service="ratings.bookinfo.svc.cluster.local",destination_service_name="ratings",destination_service_namespace="bookinfo",destination_version="v1",destination_workload="ratings-v1",destination_workload_namespace="bookinfo",instance="172.17.0.14:15020",istio_io_rev="default",job="kubernetes-pods",kubernetes_namespace="bookinfo",kubernetes_pod_name="reviews-v2-6cb6ccd848-c4k8k",pod_template_hash="6cb6ccd848",reporter="source",request_protocol="http",response_code="200",response_flags="-",security_istio_io_tlsMode="istio",service_istio_io_canonical_name="reviews",service_istio_io_canonical_revision="v2",source_app="reviews",source_canonical_revision="v2",source_canonical_service="reviews",source_principal="spiffe://cluster.local/ns/bookinfo/sa/bookinfo-reviews",source_version="v2",source_workload="reviews-v2",source_workload_namespace="bookinfo",version="v2"}
```

**Comment by lucasponce** [comment]
Why don't ellaborate the final proposal from top -> down ?
How would user see this ?

I know there was a lot of investigation but I don't follow all technical details in the previous comments, perhaps some draft about the changes/features would help.

**Comment by aljesusg** [comment]
The point here was fetch the jaeger (spans) to get the duration of each request to have a health check based in the duration, we discussed about get this information from prometheus metrics instead jaeger. 

My point is that we can have this check with prometheus. So we can have a health check when we have request X% > than average duration time last hour.

On the other hand we talked about to have a check if we have an app that is not generating traces. I don't know if this will be interesting from user perspective.

**Comment by lucasponce** [comment]
Yes I think we have two topics here.

One is thinking in tracing, which info can complement the existing info to spot a problem. Your last comment sounds in that direction:

> On the other hand we talked about to have a check if we have an app that is not generating traces. I don't know if this will be interesting from user perspective.

Perhaps it would be good to see in which scenarios and related with current traffic (no traffic and no tracing would mean something ok, but traffic but no tracing perhaps may spot some condition where user should be warned, I guess it may get developed more).

About the overlapping the tracing/spans and istio metrics, it's right, but then I put it on the context of this other epic 
https://github.com/kiali/kiali/issues/1416 and I see that perhaps we want to move in the direction to collect other signals rather than process more analytics internally.

I mean, this comment makes absolutely sense:

> request X% > than average duration time last hour.

But as we open here a door for multiple personalization I'm convinced that Kiali Health wouldn't be the right place to define this logic, but it can be the right place to visualize it.

So, in top of my head, a user may have his personalization in an Alert Manager (Prometheus probably) and perhaps Kiali should warn that "an user has alerting signals for this namespace or workload/service".

But that's part of the scope of https://github.com/kiali/kiali/issues/1416.

Perhaps I'd try to explore if from the first scenario:

> On the other hand we talked about to have a check if we have an app that is not generating traces. I don't know if this will be interesting from user perspective.

We identify a use case that is clear and the effort is worth (querying tracing is costly and we may spot some problem with the cost to enter in some perf penalty, then perhaps we may balance if the tradeoff makes sense or user would be ok).

**Comment by lucasponce** [comment]
Probably this issue is outdated with the recent work in the traces tab where there are several comparison between traces and the telemetry data.

**Comment by aljesusg** [comment]
I'll close this one
