### ISSUE TITLE
[Tracing] Tracing tab in workload page

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#2710]
I was checking datadog and another tools to check what we can do with the information that we have.

It would be nice have in the workloads a tracing tab with the times that spans are getting in this specific resource, helping to correlate with another resources to check what is happening with the spans that are getting more time.

_For that we need to check if there is some kind of fetch spans related with a workload, filtering then by operation Name. Or do this task in our backend_

## Add some charts
![Screenshot from 2020-04-28 15-43-22](https://user-images.githubusercontent.com/3019213/80494506-02cf5380-8967-11ea-9f96-0cff5633191a.png)

* Another chart grouped by http status could be great to check when the workload started denied requests for example.

## Add some panels with more information

- First panel with how many spans grouped by **http.status_code** . Useful to check how many of that spans are having errors

- Second panel with how many spans grouped by **http.method** (useful for some enterprise companies that want to know if their resources are getting or posting)

- A third panel with another charts that times getting with **GET methods and POST methods**. Sometimes the user needs to check what kind of spans are getting the time and maybe the problem is in the database when posting or in another external services in getting process.

**Comment by jotak** [comment]
Since traces/spans are stored by jaeger per service, how do you know that a trace comes from a given workload? Is it in the spans meta-data?

**Comment by aljesusg** [comment]
You can check the app by operation name and the workload is in the tags of each span. If you see the traces tab you can check how the "link" is tot he specific workload where this span was generated

**Comment by jotak** [comment]
Ok, I see now, you're using the `node_id` from the meta-data, I guess it's present in all spans created by envoy, sounds good

(btw the link generated to workload doesn't work for me, i'll open a separate issue about that)

**Comment by jotak** [comment]
Hey @aljesusg @lucasponce , I'm sending PRs for this task to add workload-based traces in Kiali, however this issue is broader than that: it's also about showing more traces stats & charts, like durations as timeseries or such.

So we need to decide, if we want to create a subtask for my PRs, and this one is kept open (and it's more like a RS task), or we reduce the scope and decide the PRs fulfil the needs.

One thing I want to raise, about showing more stats from traces, is that some might be better covered by istio metrics: especially durations, which already can be grouped / filtered per response code. Metrics do *not* provide, however, the stats per http method (get/post etc.) (well, unless the user configures it with the [classifying feature](https://istio.io/latest/docs/tasks/observability/metrics/classify-metrics/))

But istio metrics in general is a better source of data for those kind of stats, since there is no down-sampling. So, what do you think about that? Do we keep planning additional work here?

**Comment by lucasponce** [comment]
Yes, it's good to comment about this, I think we are collecting more or less similar topics around the same context.
I also posted here https://github.com/kiali/kiali/issues/3095#issuecomment-682390528 some suggestions that I think are related.

To me, one interesting thing from this issues is about the http methods, in the metrics + spans charts and in the traces tab I guess it could be doable to try to create a new series about methods (get, post, etc) and show spans focus on that info.

Also as I put in the comment below I think it's time to revisit the trace/span subview and align with tables as other subtabs in the details pages.

I don't think Kiali should have access to all headers / parameters, that's a better task for Jaeger, but I think that extracting the interesting one could be nice: operation, url, method.

So, from that, perhaps the links to log or metrics can be improved, with more contextual info, i.e. if I have a span with GET, it could be doable that the link to the logs can add a filter by "GET" (just an idea).

And if the user wants to inspect in detail the trace/span, then the link to tracing (Jaeger) should be the better place for that.

My comment is just an idea, but also dancing on the same context: improve the contextual info between all signals. In the same way perhaps there are other scenario that can be proposed (i.e. on Istio we may have always some fixed headers, perhaps Kiali can be focus just on that).

Anyway, this is a good discussion and I agree that the issue has a more "research" spirit.
