### ISSUE TITLE
[Next PF Release] Colors and recommendations on tooltips

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#2725]
Kiali is syncing some CSS styles for consistency.
In the tooltips, there are scenarios where content rendered includes icons:

![image](https://user-images.githubusercontent.com/1662329/80956419-8246a200-8e01-11ea-88cb-d8f0c434fcea.png)

![image](https://user-images.githubusercontent.com/1662329/80956448-8e326400-8e01-11ea-9f0d-ebff7c0a74d8.png)

We were wondering if palette and colors used are correct or there are some other recommendation.

Note, this is not a redesign of the tooltip content, it's more about a UI issue.

**Comment by jotak** [comment]
Giving more context which I wrote initially here: https://github.com/kiali/kiali-ui/pull/1763

The color palette in question is the usual pf4 one: https://www.patternfly.org/v4/design-guidelines/styles/colors#status-and-state-colors

However it seems to me that it is designed for a light / white background only. Recent changes in Kiali switched the background from white to black (because it's tooltips), and I wonder if these colors are still ok then, both in terms of being attractive, and for accessibility, as it makes the contrast quite different.

**Comment by lwrigh** [comment]
PF suggests a color contrast ratio of 4.5:1 and using this contrast checker https://color.a11y.com/?wc3 to make sure the background and element color create enough color contrast. For this situation we'll  have to make the status colors a couple shades brighter. 

Here are my value suggestions: 

**Success/checkmark icon:** https://color.a11y.com/ContrastPair/?bgcolor=151515&fgcolor=92D400

light-green-400
#92D400
CSS variables
--pf-global--palette--light-green-400
--pf-global--success-color--100

**Warning/alert icon:** https://color.a11y.com/ContrastPair/?bgcolor=151515&fgcolor=F0AB00

The default gold color (#F0AB00) for the warning/alert icon has enough contrast so that one can stay the same. 

**Error/ danger icon:** The brightest red is already in use here but doesn't pass the contrast ratio test on the black background https://color.a11y.com/ContrastPair/?bgcolor=151515&fgcolor=C9190B PF currently doesn't have any brighter red colors suggestions without getting into changing the color to pink which we want to avoid. A dark theme is currently in the works so that might change in the future. Here I would suggest changing the icon color to white #FFFFFF since this provides more contrast and still maintains the meaning of the icon since that wouldn't change.

**Comment by lucasponce** [comment]
Closing this one as it would be discussed in the context of a migration of patternfly
https://github.com/kiali/kiali/issues/4260
