### ISSUE TITLE
Filter by Istio Type Dropdown - Put a scroll in dropdown values

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#2759]
Currently in Istio Config Page, the dropdown "Filter by Istio Type" got a lot of values, and instead of scrolling within those values, it puts scroll on whole page.
[RFE] If the PF4 component allows, put scroll into dropdown values itself.

![Screenshot from 2020-05-11 13-29-29](https://user-images.githubusercontent.com/604313/81557200-dc101480-938b-11ea-83e1-5342c0a406a0.png)

**Comment by jshaughn** [comment]
Let's fix if easy or close if hard, adding to backlog.

**Comment by lucasponce** [comment]
I'd close this because it was triggered mostly by the large list of mixer types.

![image](https://user-images.githubusercontent.com/1662329/110312577-918c1280-8005-11eb-8b41-14b4b392ef17.png)

Now those are not present in Kiali, the dropdown is short.

I'll revisit in the future if we have another similar .situation
