### ISSUE TITLE
Error loading metrics: Cannot access namespace data: namespaces "unknown" not found

### ISSUE THREAD

**Issue by mikemilano** [kiali/kiali#2784]
**General remarks**

The namespaces of VirtualService objects I create are showing up as `unknown` on the graph. Upon inspection of the objects via `kubectl describe`, they do in fact have a namespace. 

I can reproduce this on 2 different fresh GKE clusters so it should be reproducible.

<img width="1459" alt="graph" src="https://user-images.githubusercontent.com/1287855/81888022-52ac3e00-9555-11ea-8478-d777676b2978.png">
<img width="956" alt="details" src="https://user-images.githubusercontent.com/1287855/81888033-563fc500-9555-11ea-8938-afecc0501421.png">

**Describe the bug**

VirtualServices I create appear on the graph different like so:
-  The top line includes the full system name instead of just the app name. i.e. `grafana.istio-system.svc.cluster.local`
- The next line where I expect the namespace to be, it shows `(unknown)`

When clicking on the service, the following error appears at the bottom of the right panel:
> Error loading metrics: Cannot access namespace data: namespaces "unknown" not found

Clicking on the link at the top of the right pane takes me to the details page 

Notice in the screenshot that `istio-ingressgateway` appears as expected, and the others have the problem. `kubectl describe vs grafana` shows that the namespace is in fact `istio-system`.

I'll focus on Grafana but note that I get the same thing for Prometheus, Jaeger, & Kiali after installing via the Istio demo profile. I have an issue with entirely custom apps/services running in a different namespace as well.

For the apps I mentioned, after the default installation, I added a Gateway and Virtual Service for each to serve them on a custom domain over https.

Here is the Gateway and VirtualService for Grafana:

```
$ k describe gw grafana-gateway
Name:         grafana-gateway
Namespace:    istio-system
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"networking.istio.io/v1alpha3","kind":"Gateway","metadata":{"annotations":{},"name":"grafana-gateway","namespace":"istio-sys...
API Version:  networking.istio.io/v1beta1
Kind:         Gateway
Metadata:
  Creation Timestamp:  2020-05-13T18:10:49Z
  Generation:          1
  Resource Version:    26138
  Self Link:           /apis/networking.istio.io/v1beta1/namespaces/istio-system/gateways/grafana-gateway
  UID:                 7e4d9471-ea98-43a3-8875-754d1c570976
Spec:
  Selector:
    Istio:  ingressgateway
  Servers:
    Hosts:
      grafana.example.com
    Port:
      Name:      http-grafana
      Number:    443
      Protocol:  HTTPS
    Tls:
      Credential Name:  example-tls
      Mode:             SIMPLE
Events:                 <none>
```

```
$ k describe vs grafana-vs
Name:         grafana-vs
Namespace:    istio-system
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"networking.istio.io/v1alpha3","kind":"VirtualService","metadata":{"annotations":{},"name":"grafana-vs","namespace":"istio-s...
API Version:  networking.istio.io/v1beta1
Kind:         VirtualService
Metadata:
  Creation Timestamp:  2020-05-13T18:10:49Z
  Generation:          1
  Resource Version:    26140
  Self Link:           /apis/networking.istio.io/v1beta1/namespaces/istio-system/virtualservices/grafana-vs
  UID:                 148166af-2614-464c-a81c-c78644653b9a
Spec:
  Gateways:
    grafana-gateway
  Hosts:
    grafana.example.com
  Http:
    Match:
      Port:  443
    Route:
      Destination:
        Host:  grafana
        Port:
          Number:  3000
Events:            <none>
```

**Versions used**
Kiali Server: v1.15.2 (718aedca76e612e2f95498d022fab1e116613792) (UI is 1.15.1 (1440a7722f9b4699caaee7b64d32db0f1beb5386))
Istio: 1.5.2
Kubernetes flavour and version: v1.15.11-gke.12

**To Reproduce**
Install Istio via `istioctl` with the demo profile.
```
istioctl manifest apply --set profile=demo
```
2. Apply the VirtualService and Gateway defined in the bug description.
3. Run Kiali via `istioctl dashboard kiali`

Note: I had a gateway and vs setup for Kiali, but it's easier to reproduce this way. I confirmed I get the same result.

**Expected behavior**
When going to the `Graph` page and selecting `istio-system` namespace, I expect to see the service name and the namespace listed below it. I also expect not to see an error on the right pane when I click on the service.

**Comment by jotak** [comment]
I think this happens because you don't have istio sidecar proxies on grafana / kiali / etc.
These components are usually not part of the mesh. So, the resulting telemetry is incomplete and show these "unknown" fields. Because of that, Kiali is unable to accurately match these elements with known kube services or workloads.

To verify that istio telemetry is incomplete: if you open the prometheus console (`istioctl dashboard prometheus`) and check for instance `istio_requests_total{destination_service="grafana.istio-system.svc.cluster.local"}` , you will probably see in result that `destination_service_namespace` is unknown.

Although it's a bit unusual to build graph for these non-mesh elements, if really we want to do something it could be possible to determine namespace by parsing the `destination_service`. (cc @jshaughn )

**Comment by mikemilano** [comment]
Confirmed, I verified that `destination_service_namespace` is unknown.

However, it's happening on my custom apps as well in a namespace where I have sidecars. I don't understand the issue well enough to know if this is relevant so I'll explain:

I create a new app in my custom `hd-proxies` namespace (istio injection enabled) that contains a deployment with a single pod w/sidecar, service, virtualservice, & gateway.

I confirmed all components mentioned above are listed in the `hd-proxies` namespace.

Visiting the public app in a browser works fine.

In Kialia -> Graph with `istio-system` namespace selected, I see this with the next screenshot the result of me clicking on the service link in the right pane.

<img width="1253" alt="Screen Shot 2020-05-14 at 2 35 01 AM" src="https://user-images.githubusercontent.com/1287855/81921696-da16a300-958f-11ea-95c4-973260f767cf.png">
<img width="1157" alt="Screen Shot 2020-05-14 at 2 57 07 AM" src="https://user-images.githubusercontent.com/1287855/81921736-edc20980-958f-11ea-9787-043b45b30120.png">

When selecting `hd-proxies` as the only namespace, I get this (After I also set to display unused nodes)

<img width="1271" alt="Screen Shot 2020-05-14 at 2 35 46 AM" src="https://user-images.githubusercontent.com/1287855/81921831-11854f80-9590-11ea-9a69-664b341f752a.png">

**Comment by jotak** [comment]
@mikemilano do you see this problem on your app just for a short moment after it's deployed, or does it keep showing errors even after some reasonable time (ideally a few seconds, but let's consider up to a couple of minutes) ?

I suspect this is something that we can see on fresh new deployments until they are fully synced.

You can run the command `istioctl proxy-status` to check sync status of the mesh. Your app pods should have state "SYNCED".

**Comment by mikemilano** [comment]
The app has been up for 2 hours now and I get the same result in Kiali.

`istioctl proxy-status` shows everything synced.

```
t093141-milano-thinktan-5b7487967b-mpst2.hd-proxies     SYNCED     SYNCED     SYNCED     SYNCED       istiod-5f75f97794-46pjd     1.5.2
```

**Comment by mikemilano** [comment]
I think you were onto something based what happens in the first minute, but it's reverse.

When I create a new app, it loads OK over https initially and continues to refresh fine within the same browser session. This is how I was testing my app.

When I load the app in a new browser however, the browser reports a `Network Protocol Error` and does not return a response.

I now believe my custom app issue is separate from the original Grafana related issue (no sidecar), which means we can probably ignore everything after your [your first comment](https://github.com/kiali/kiali/issues/2784#issuecomment-628437040)

Thanks for helping with the troubleshooting. I suspect my custom app issue is TLS related.

**Comment by mikemilano** [comment]
I deleted my last 2 comments because the custom app issue was entirely different. 

I added a sidecar manually to grafana and it did fix the graph. I then got "Mesh-wide mTLS status" errors.

It's not even critical for me to have graphs for these dashboards... it's just that I need the istio-system namespace enabled to see the path from the default ingress to my apps. Thinking back, that is what send me down the rabbit hole. Just feedback at this point.

Thanks again for the help troubleshooting.

**Comment by jshaughn** [comment]
I have started to see these "terminating" service nodes with unknown namespace in a couple of places.   We need to figure out how these nodes are getting generated.

**Comment by jshaughn** [comment]
You should not have to select the istio-system namespace to see traffic flowing from ingressgateway to your services in hd-proxies.  You should need to only select hd-proxies.  Kiali should show traffic entering into hd-proxies, within hd-proxies and leaving hd-proxies.

> Although it's a bit unusual to build graph for these non-mesh elements, if really we want to do something it could be possible to determine namespace by parsing the destination_service. (cc @jshaughn )

@jotak We do need to do something about these nodes because we really can't have nodes with an unknown namespace.  I think fundamentally that's bad telemetry to have destination_service set but destination_service_namespace be unknown.  Have you seen this?  I have not reproduced.

**Comment by jotak** [comment]
@jshaughn yeah i've been seeing this for a short time after deployment, using istio 1.5.x (i think it was 1.5.1). Once pods are ready/synced, the telemetry was back to normal.

**Comment by jshaughn** [comment]
@jotak I know they made some fixes in latter 1.5.x releases, and then again in 1.6.  Maybe it's another case of bad telemetry during pod lifecycle changes, and maybe it's been fixed.  I'll keep an eye out but have not seen this in my 1.6 testing.

As an aside, I have seen a similar issue with TCP when mTLS is not enabled for the request.  That is apparently a problem we need to handle in Kiali because the telemetry is, apparently, expected.

**Comment by jotak** [comment]
@jshaughn see this post, it might be related: https://discuss.istio.io/t/routing-issue-or-kiali-visualizing-issue/6861

Looks like Kiali fails to match `istio-egressgateway` here, having its namespace to `unknown` instead of `istio-system` ; here again it seems like we could guess the real namespace base of full-qualified service name.

**Comment by VladyslavLevchuk** [comment]
@mikemilano Hello, I've faced the same issue with the custom app, could please describe what was the solution for your custom app ?

**Comment by jshaughn** [comment]
The problem here is that for requests that can't (perhaps no response was received), or failed to properly perform a metadata exchange, which means the telemetry records only the requested host.  It is typically useful to see on the graph but since the namespace is unknown Kiali has no ability to show any detail or query for metrics in the side panel.  This is more the nature of telemetry V2 metrics, I think mixer was maybe more forgiving (or possibly misleading).  The solution is to make the nodes inaccessible/restricted, which has been done outside of this issue and will be in the next Kiali release (1.24).

**Comment by wdrdres3qew5ts21** [comment]
I also had this problem I had try to rollout restart CoreDNS, Pilot and all of pod that need to had side car injection but it still didn't work.
It seem like this problem will occur will you had remove previous Istio installation but somehow pilot still using misconfiguration.
I don't know how to debug or solve problem more than looking at Pilot and Ingress gateway but everything seem working correctly because Ingress response with HTTP 200 I got correctly response from API but Graph seem messing and incorrect at Istio-Gateway.

**Comment by jshaughn** [comment]
@wdrdres3qew5ts21 It really comes down to the telemetry generated by Istio.  That is what Kiali visualizes.  The more the telemetry matches the actual traffic the better the visualization.
