### ISSUE TITLE
upstream Istio removing v1alpha1 RBAC API - update Kiali accordingly

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#2801]
This issue is to have us check where Kiali needs to be modified due to the following issue.

Upstream Istio currently has [an open PR to remove the v1alpha1 RBAC API](https://github.com/istio/istio/pull/23668). This includes the following resources:

- ServiceRole
- ServiceRoleBinding
- RbacConfig
- ClusterRbacConfig

I believe this also affects ServiceMesh/Maistra's ServiceMeshRbacConfig.

Note that v1alpha1 Authentication API has already been removed (this includes Policy and MeshPolicy and ServiceMesh/Maistra's ServiceMeshPolicy) but I think we already took care of that or are in the process of doing that.

**Comment by lucasponce** [comment]
Note that kiali backend checks the presence of this rbac.
For Istio 1.6, Kiali 1.18 and higher versions should be safe.

We have decided to not remove these objects yet from the codebase in order to minimize the features that would work / not work in backward compatible way.

But if rbac CRD is present or not Kiali will detect it.

The only side effect is that it will be listed in the Istio Config type filter.

**Comment by xeviknal** [comment]
Adding up an screenshot to support lponce comment:
![Screenshot of Kiali Console (75)](https://user-images.githubusercontent.com/613814/82349384-511dc280-99fa-11ea-9fd2-c29ca5ee81c0.png)

**Comment by lucasponce** [comment]
I think we can close this.
Kiali codebase detects this API's presence.
The only side effect is that it's not removed from the "type" list in the filter, but that can be addressed in a future issue.
