### ISSUE TITLE
Calculate graph importance score

### ISSUE THREAD

**Issue by pavolloffay** [kiali/kiali#2888]
**Scope updated**
https://github.com/kiali/kiali/issues/2888#issuecomment-893382802

**Is your feature request related to a problem? Please describe.**

The traces (with metrics) could be used to calculate an "importance score" metric per workload/service. The scope could be used to highlight the most critical services that can be useful for defining SLAs.
 This score could be a combination of information:
* how deep is the service in the graph
* how many services depend on it
* requests per second

The high numbers of the service depth and the number of parents can mean wrong architecture decisions in the monitored app. 

**Describe the solution you'd like**

Show the score per service or annotate the services in the graph.

**Describe alternatives you've considered**

none

**Additional context**

Related to https://github.com/kiali/kiali/issues/2677

**Comment by lucasponce** [comment]
This issue is still valid.
First the Graph Find/Hide requires some improvement as probably an expression to define a "score" per services could be calculated following similar criteria as described on this issue.

But it's not obvious for a early/mid user in Kiali.

**Comment by lucasponce** [comment]
Related to https://github.com/kiali/kiali/issues/3708

The "Calculate importante score" is an example of a built-in expression that may be accessible to user in 1-click.

**Comment by lucasponce** [comment]
I think this issue is still valid and it could be started.
I'm going to reduce the scope to make it ready.

If we see this example:
![image](https://user-images.githubusercontent.com/1662329/128342190-3242c584-c031-497e-877b-0f8c30b21445.png)

I think the graph could generate a score based on ancestors, i.,e. the "mysqld" and "discounts" nodes should show a total of 8 parents (the sum of "flights", "insurances", "hotels", "cars", plus the "travels", and "voyages", "viaggi", "travels", etc).

This number could be optionally show in name badge of the graph (or to be discussed).

And, it would be nice that number is available for the "Find/Hide" feature, then, as a user, when I have a large deployment, I could use the score to identify the "critical" paths.

Perhaps this demo example is pretty obvious, but when not all services are invoking the same backend nodes "mysqldb" and "discounts", it can show useful results.

**Comment by nrfox** [comment]
> I think the graph could generate a score based on ancestors, i.,e. the "mysqld" and "discounts" nodes should show a total of 8 parents (the sum of "flights", "insurances", "hotels", "cars", plus the "travels", and "voyages", "viaggi", "travels", etc).

Said another way, these are the nodes with the most inbound edges?

From the discussion above, it seems like a scoring system that takes into account multiple customizable filters would be really nice to have e.g. "rank all nodes by number of inbound edges AND number of requests per second". A user might also want to rank by something like "number of failed requests". Being able to mix and match different criteria would give users a lot of flexibility to define what is important to them to highlight on the graph.

Ranking by number of inbound edges seems like a great place to start. There could be a "node_score_appender" which looks at selected criteria and adds a score to each node based on that. Starting off it'd be "number of inbound edges" but more scoring criteria can be added in the future.

**Comment by jshaughn** [comment]
> Won't this be true of everything being scored?

Good point :-)  Everything is relative.

>  Is there a computation step that happens after the data is received from the backend but before the graph is rendered?

Sort of, a lot of things do happen between fetch and render time.  See GraphDataSource.ts for where we actually fetch the data.  When it arrives we do manipulate it in GraphData.ts#decorateGraphData, and then may optionally do more work to fetch and assign node health.   Edge health isn't actually calculated (iirc) until we are rendering the edge in graphStyles.ts.

**Comment by nrfox** [comment]
@jmazzitelli @lucasponce continuing the conversation around verbiage on score/rank etc. The way that https://github.com/kiali/kiali-ui/pull/2259 is currently implemented, score is the raw score assigned to a node based on the scoring criteria e.g. if you had a graph with 2 separate nodes each with one inbound edge and your scoring criteria was Inbound Edges, the score for each node would be `node_inbound_edges / total_inbound_edges` == `1 / 2 = 0.5`.

The nodes are all sorted and given a rank based on the sort order. Ranks are normalized between 1..100. The highest scored nodes are the top ranking nodes which starts at 1 for the highest and goes to 100 for the lowest.

The raw score is not exposed to the user. I thought it'd be easiest to query for "the top two nodes" by rank rather than a relative score number e.g. `rank <= 2` vs `score > 0.9`. Happy to hear what others think about the verbiage.

**Comment by lucasponce** [comment]
> The raw score is not exposed to the user. I thought it'd be easiest to query for "the top two nodes" by rank rather than a relative score number e.g. rank <= 2 vs score > 0.9. Happy to hear what others think about the verbiage.

I'm +1 with your proposal @nrfox, also this feature is open to provide your own criteria and meaning in what a term means in this context. As soon as the user can see it from the proper tool what is the context, no objection from my side.

Note, probably score terms may vary with the time and as soon more scenarios are identified these may change as well.
