### ISSUE TITLE
[FEATURE] JSON based logging for day2 operations

### ISSUE THREAD

**Issue by MarianZoll** [kiali/kiali#2893]
**Is your feature request related to a problem? Please describe.**

Kiali is designed to support systems in being operated properly. One fundamental thing to do is forwarding the logs to the right place (e.g. Kibana) to make it easier for the DevOps team to read them as well as taking (automatic) actions around the logs. 
Unfortunately, the basic Go logger in the Kiali project does not support JSON based logging.

**Describe the solution you'd like**

Rework logging with a Go logger that supports JSON logging by either providing a startup environment or even better by providing an environmental variable. 

Some alternatives which come pretty handy which we might want to consider:
https://github.com/sirupsen/logrus
https://github.com/uber-go/zap

**Describe alternatives you've considered**

Changing logs in the log collector (e.g. fluentd) - stupid thing to do as it is very complex and the logging libs provide it out of the box

**Additional context**
None but I am happy to provide it.

**Comment by israel-hdez** [comment]
For logging, most of the Kiali code (if not all of it) is using the helpers available at: https://github.com/kiali/kiali/blob/1f7edad56004e2ec317d58dc845a7f7dbf6166ba/log/log.go

So, I think it's not hard to change the log library. However, without doing more work to enhance the logged messages with more metadata, the best log line we could offer short term would be of the form:

`{timestamp: 1591910720, severity: "warn", message: "The logged message"}`

Would that be enough for your case? or would you need more metadata on it?

**Comment by MarianZoll** [comment]
@israel-hdez 

That would be more than helpful, thanks for the response. It will reduce the size of transferred data and would allow the ops tool to automate actions and co.

We are currently working to get a couple of approvals from our mgmt. to add some contributions. Would that be something you (speaking about the Kiali. project) would be interested?

**Comment by israel-hdez** [comment]
@MarianZoll Contributions will be more than welcome :smiley: Just make sure to discuss your enhancements with the team by opening GitHub issues.

**Comment by MarianZoll** [comment]
@israel-hdez Haha this took some time but I was covered by a lot of project work. 

I had another look on the logging and how we could improve it with some advanced logging package. At the moment, a Kiali internal log class does abstract most of the logic (except formatting and co.): https://github.com/kiali/kiali/blob/master/log/log.go

I would suggest to have a look on some higher level logging packages such as https://github.com/uber-go/zap or https://github.com/rs/zerolog as they would implement the same functionality than the self-managed logging class but would come with additional configuration options fro JSON logging or development logs. 

I ran some short PoC on my fork with https://github.com/rs/zerolog where I removed the need for the internal class and moved all logging to the external package. Seems to work like a charm and we could provide configuration options for logging format and co which can be managed in a init function. 

What do you guys think about this change?

**Comment by jmazzitelli** [comment]
> What do you guys think about this change?

There is a huge amount of churn that would require changes like this (taken from https://github.com/MarianZoll/kiali/commit/fa3aa8669f9adefeb9363652ac2fefae9e35cb4e)

```
- log.Errorf("Error initializing Kiali Cache. Details: %s", err)
+ log.Error().Msgf("Error initializing Kiali Cache. Details: %s", err)
```

Is there anyway you can retrofit the Kiali log/log.go so it simply delegates?

```
Errorf(...) {
   log.Error().Msgf(...)
}
```

So really all that would change is the log/log.go ?

**Comment by MarianZoll** [comment]
@jmazzitelli 

Sure thing, I just did the changes with search and replace, but I do agree this probably causes less trouble than the changes I made. I will create a PR for changing the `log.go` and will think about some reasonable configuration options which I will state in another PR.

**Comment by MarianZoll** [comment]
@jmazzitelli 

Made the changes to `log.go` as you proposed and checked it to another branch in my fork: https://github.com/MarianZoll/kiali/tree/MarianZoll/logging

Logger config is based on some env variables `LOG_LEVEL` (info, warn, debug, error, fatal) and `LOG_FORMAT` (text, json). This should be better than providing it in yaml, as `kiali.go` uses the logger before finally reading the config. 

Feedback is highly welcome! If you like it I would clean up the commits and issue a PR. Afterwards, I can add it as a config option to the operator crd.

**Comment by jmazzitelli** [comment]
> Logger config is based on some env variables `LOG_LEVEL` (info, warn, debug, error, fatal)

This is going to require additional changes in the operator and helm charts (see below), so I will mark this issue with the appropriate labels.

When adding new config items, here's a [developer checklist](https://github.com/kiali/kiali-operator/blob/master/DEVELOPING.adoc#how-to-change-resources-or-configuration) you can follow to know what has to change where in both operator and helm chart. We'll need the Kiali Server Deployment object to be created slightly differently - one using env variables rather than `-v` options as I explain below.

Today we pass the `deployment.verbose_mode` (what you are calling "LOG_LEVEL"), as defined in [the Kiali CR](https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L355-L358), via the typical go-lang "-v" option. The verbose_mode is also passed to the Server helm chart for those using helm.

When the operator is told what verbose mode to use, it creates the Kiali Deployment with the appropriate `-v` option as seen here: https://github.com/kiali/kiali-operator/blob/v1.25.0/roles/default/kiali-deploy/templates/openshift/deployment.yaml#L60-L61

When the server helm chart is told what verbose mode to use, it creates the Kiali Deployment with the appropriate `-v` option as seen here: https://github.com/kiali/helm-charts/blob/v1.25.0/kiali-server/templates/deployment.yaml#L55-L56

To maintain backward compatibility, we'll want to keep supporting the `deployment.verbose_mode` setting. We can have it translate to an env var definition as opposed to `-v` option in the Deployment object that gets created, but the name of the setting in the Kiali CR and the helm chart should remain. I would be open to supporting a new `deployment.logger` dict that let's you override this old deployment.verbose_mode setting via this:

```
deployment:
  logger:
    log_level: info
    log_format: text
```

"info" and "text" should be the default.

Finally, for backward compatibility, we will need to allow for the verbose_mode at least (if not also log_level, but if we do not add a new deployment.logger dict, we'll need to change verbose_mode to support this) to be a number (verbose_mode is specified as a string today, but the values are numeric like `"3"` or `"4"`.). Because that value is considered a string today, we can support new values we'll allow now (e.g. "info", "debug", "warn", etc) but we need to still support at least things like "3" and "4". So we'll need the initialize method to be able to map the generic go verbose values to the new log levels. For example, I see this [here in InitializeLogger()](https://github.com/MarianZoll/kiali/commit/a451ab69523a4595dc1fa7d3f7f629999b3bf20e#diff-894630a7ed925c7768a861c4465bc9ad393f7937df7cac5c77ab123c03921aeeR11):

```
	logLevel, err := zerolog.ParseLevel(os.Getenv("LOG_LEVEL"))
```

There probably needs to be some code before that call to convert numeric verbose mode values to valid zerolog levels. Note: I'm assuming `zerolog.ParseLevel` does NOT accept strings like "3" or "4" as valid log levels. But if that function does properly map these generic Go verbose levels to their own log levels, nothing needs to be done here. However, if that zerolog function fails to parse log levels specified as numerics like "3" or "4" we will need something like this in that initializeLogger func:

```
        logLevelName := os.Getenv("LOG_LEVEL")
        if (logLevelName == "3") {
          logLevelName := "info"
        } else if (logLevelName == "4") {
          logLevelName := "debug"
        } ... and whatever else appropriate ...
	logLevel, err := zerolog.ParseLevel(logLevelName)
```

That's all I can think of for now.

**Comment by MarianZoll** [comment]
Thanks for sharing the information. I incorporated the required changes to both the helm charts and the operator and checked for additional things. Some manual tests performed on minikube and Openshift worked fine. The automated make tests as well. For the hack script I am missing authorization to pull the required container images.
```
make molecule-test -e CLUSTER_TYPE=minikube -e MINIKUBE_PROFILE=ci -e MOLECULE_USE_DEV_IMAGES=true 
Minikube repos: external=[192.168.99.100:5000] internal=[localhost:5000]
| registry                    | ci      | enabled ✅   |
/bin/bash: getent: command not found
/bin/bash: getent: command not found
/bin/bash: getent: command not found
Will auto-detect hosts to add based on the CLUSTER_REPO: 192.168.99.100:5000
Auto-detected add host args: 
for msn in default; do docker run --rm -t --env MOLECULE_HELM_CHARTS_REPO=/tmp/helm-charts-repo -v "/Users/marianzoll/Documents/Kunden/OpenSource/kiali/helm-charts":/tmp/helm-charts-repo:ro -v "/Users/marianzoll/Documents/Kunden/OpenSource/kiali/kiali/operator":/tmp/"/Users/marianzoll/Documents/Kunden/OpenSource/kiali/kiali/operator":ro -v "/Users/marianzoll/.kube/config":/root/.kube/config:ro -v /var/run/docker.sock:/var/run/docker.sock -v /Users/marianzoll/.minikube:/Users/marianzoll/.minikube --env MOLECULE_MINIKUBE_IP=192.168.99.100 -w /tmp/"/Users/marianzoll/Documents/Kunden/OpenSource/kiali/kiali/operator" --network="host"  --add-host="api.crc.testing:192.168.130.11" --add-host="kiali-istio-system.apps-crc.testing:192.168.130.11" --add-host="prometheus-istio-system.apps-crc.testing:192.168.130.11" --env DORP=docker --env MOLECULE_KIALI_OPERATOR_IMAGE_NAME=localhost:5000/kiali/kiali-operator --env MOLECULE_KIALI_OPERATOR_IMAGE_VERSION=dev --env MOLECULE_KIALI_IMAGE_NAME=localhost:5000/kiali/kiali --env MOLECULE_KIALI_IMAGE_VERSION=dev --env MOLECULE_DUMP_LOGS_ON_ERROR=true  --env MOLECULE_WAIT_RETRIES=120 kiali-molecule:latest molecule  test  --scenario-name ${msn}; if [ "$?" != "0" ]; then echo "Molecule test failed: ${msn}"; exit 1; fi; done
Unable to find image 'kiali-molecule:latest' locally
docker: Error response from daemon: pull access denied for kiali-molecule, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
Molecule test failed: default
make: *** [molecule-test] Error 1
``` 

I also checked on the log levels for the current glog based implementation which should follow the severity level being defined here https://github.com/golang/glog/blob/master/glog.go#L100-L106. According to this implementation, the log levels currently being used are as described below. Maybe I am misinterpreting something but if so, we can turn the implemented switch case easily.
```
0 - INFO
1 - WARN
2 - ERROR
3 - FATAL
4 - DEBUG
5 - TRACE
```

Currently I did not create PRs. So let me know what else needs to be done in case you can think about something:

Kiali-Server: https://github.com/MarianZoll/kiali
Kiali-Operator: https://github.com/MarianZoll/kiali-operator
Helm-Charts: https://github.com/MarianZoll/helm-charts

**Comment by jmazzitelli** [comment]
> For the hack script I am missing authorization to pull the required container images

See the [operator DEVELOPER page](https://github.com/kiali/kiali-operator/blob/master/DEVELOPING.adoc#run-molecule-tests), specifically the NOTE:
```
If you have never run the Molecule tests before, you need to build the Molecule
container image via `make molecule-build`. This is a one-time-only step.
```

**Comment by jmazzitelli** [comment]
> Currently I did not create PRs. So let me know what else needs to be done in case you can think about something:

I would create the PRs now. I looked at the diffs for all your branches and they look good. I see some very trivial things but overall it looks good. Thanks for the work, and thanks for running the tests.

Once the PRs are in place, we can hold discussions in each as part of the reviews.

**Comment by MarianZoll** [comment]
I created the PRs in the different repos:

https://github.com/kiali/kiali/pull/3382
https://github.com/kiali/helm-charts/pull/15
https://github.com/kiali/kiali-operator/pull/187

Thanks for your input!

**Comment by jmazzitelli** [comment]
We missed a spot - fixing: https://github.com/kiali/kiali/pull/3421
