### ISSUE TITLE
be able to turn on/off auto-injection of sidecars

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#2896]
The Kiali UI should provide a feature that will allow a user to turn on or off auto-injection of sidecars.

It should be possible to do this from a namespace level, but it also would be nice to do this at the workload level, too.

This would involve being able to manipulate the sidecar injection annotation that is found either on the namespace or on the workload itself (Deployment, or Pod, or whatever).

**Comment by lucasponce** [comment]
Side comment: this is also related with other issue https://github.com/kiali/kiali/issues/2860 that would require to set actions at workload level.

So, I think this issue should be first to extend actions from service, to workload and namespaces and that would help #2860 to place other actions from extensions.

**Comment by lucasponce** [comment]
I've spent some time solving some UI problems to share actions across cards and tables, but I think we are ready to start thinking more in the wording and additional icons to mark when a namespace is in/out the mesh.
![image](https://user-images.githubusercontent.com/1662329/85016014-39f10280-b169-11ea-9906-a5f4a050804d.png)
![image](https://user-images.githubusercontent.com/1662329/85016040-44ab9780-b169-11ea-9cc2-c8eb45ecdf87.png)
![image](https://user-images.githubusercontent.com/1662329/85016081-53924a00-b169-11ea-8366-5911e5f9ec55.png)

These are just mockups, I guess we would need some minor icon (like the used for TLS one) and just to detect when it's in/out to adjust the action on it.

**Comment by jmazzitelli** [comment]
Just a small trivial change --- it should be "Remove Namespace from Mesh" (notice the word `from`). You add "to" things, and remove "from" things.

**Comment by lucasponce** [comment]
> Just a small trivial change --- it should be "Remove Namespace from Mesh" (notice the word from). You add "to" things, and remove "from" things.

Yes, it was a typo, it's a mock and it was a quick copy/past to test how to add several personalized actions per row/card.

**Comment by jshaughn** [comment]
Just looking quickly a few reactions (some are just random optinions on l+f):
- I like cards more that a list view.
- In/Out mesh could be indicated by a different background (white/gray), also sortable
- Only one Add/Remove option should be active
- Remove icon links and create kebab links (grouped)
- I like the namespace name left adjusted but would increase font and move all icons to the right
- "labels" would look better left adjusted under the name instead of floating in the middle
- same for "applications", everything left-adjusted would look more clean, leaving the kebab on the right and clearing the center.

**Comment by lucasponce** [comment]
> I like cards more that a list view.

We are not introducing list here.
List is something included on this page some time ago for several reasons, as cards cannot show too much info (i.e. labels).

> In/Out mesh could be indicated by a different background (white/gray), also sortable

I think states need icons/text as TLS, otherwise we will enter with those ways to use only colors and accessbility.

> Only one Add/Remove option should be active

Yes, as commented, the previous screen is a mock, to check that per namespace granularity different actions can be added.

> Remove icon links and create kebab links (grouped)

I was thinking on the same thing. I like the icons, but now with the kebab we need to be consistency with other places in Kiali which are using a similar pattern.

> "labels" would look better left adjusted under the name instead of floating in the middle
> same for "applications", everything left-adjusted would look more clean, leaving the kebab on the right and clearing the center.

I'm +1 with this. When actions are present, the card adjust things at the left, so I think it makes totally sense to move the apps and labels links there, too.

> But the thing that I find confusing is the whole "Add Namespace to the Mesh". Aren't all of these namespaces already in the mesh? Sidecar injection is an option, I don't think sidecar injection at the namespace level is the same as saying in/out of the mesh.

I think this may have more deep discussion. In short, no. We query all namespaces that user has access too. They can be in the mesh or may be not. 

This is different if you are in Maistra/OpenShift vs Istio/Kubernetes, as in the first case, probably only namespaces you have access are included in the mesh, but the second case may be really pretty open, hence this action. Also, the istio-system itself is not a namespace that has sidecar injection.

So this triggers to me, if we want to rename the "Add Namespace to Mesh" to "Add Sidecar Injection to Namespace" or something that doesn't create ambiguity in this concept.

**Comment by lucasponce** [comment]
"Enable/Disable Sidecar Injection" starts to sound better to me for this action.

**Comment by jmazzitelli** [comment]
> "Enable/Disable Sidecar Injection" starts to sound better to me for this action.

I was wondering about this. If you see cards in the Overview page, that means these namespaces are already in the accessible_namespaces list (i.e. already in the mesh). We would need a view to show all other namespaces (not in accessible_namespaces) and THEN have an option to "Add namespace to mesh".

You could have "remove namespace from mesh" here - but that would require the operator to do some things and will cause the Kiali pod to reboot. So, yeah, maybe we need to step back and think about this whole "add namespace/remove namespace" feature some more.

**Comment by lucasponce** [comment]
> I was wondering about this. If you see cards in the Overview page, that means these namespaces are already in the accessible_namespaces list (i.e. already in the mesh). We would need a view to show all other namespaces (not in accessible_namespaces) and THEN have an option to "Add namespace to mesh" (or just have a text field that you type in a namespace name).

I think you are thinking only on Maistra only. Then, if Kiali creates the ServiceMeshMember, I think it will trigger the whole process with the parent Maistra operator.

But, we need to think also on those Istio/Upstream scenarios which mostly use accessible_namespaces = '**', then having a enable/disable sidecar per namespace sounds a good action (also, we would need them in any way at workload level, too).

**Comment by jshaughn** [comment]
This all looks better to me.  Other thoughts:
- I'd maybe like to see the lock icon after the name
- I'd like the name to have more emphasis
- I'd consider pulling up the application health to the right of the "N Applications", eliminate the bar graph and just let the sparkline take the whole width.

**Comment by lucasponce** [comment]
> 
> * I'd maybe like to see the lock icon after the name

+1

> * I'd like the name to have more emphasis

+1, yes, for some reason we are not using the standard pf4 style, I think it makes sense to increase the "bold" style there.

> * I'd consider pulling up the application health to the right of the "N Applications", eliminate the bar graph and just let the sparkline take the whole width.

+1, I was also thinking the same, also, in the table view it looks odd and and the bar doesn't add additional info that the "N Applicacions + icons" is adding, it's pure cosmetic and redundant and Status may get benefit of more detail.

**Comment by maltron** [comment]
The proposed UI from @lucasponce address the Service Mesh Onboarding and this is fantastic.
I wonder if a simple checkbox would do the job ? It would be visually clear, a single click (instead of two) and informs about what it means. I like @jshaughn's idea about having a different background, which it's way more appealing visually speaking.  

@lucasponce I a bit confused how this impacts #2860. Would you care to explain ?

Maybe most of my experience is around Maistra, where there isn't namespace annotation regarding sidecar (only sidecar annotation at the Deployment level). Will that change ? If so, would that affect Kiali at all ?

@lucasponce point regarding upstream is a valid point. I wonder if there is anything that it can be done to address this issue on both upstream and downstream ?

**Comment by lucasponce** [comment]
> @lucasponce I a bit confused how this impacts #2860. Would you care to explain ?

It is related to Mazz's comments:
> It should be possible to do this from a namespace level, but it also would be nice to do this at the workload level, too.

In a parallel discussion in #2860 we are discussing to introdcuce also actions at workload level, so, probably both efforts would share some implementation tasks (i.e. enable actions at workload details page as a preliminary step to add specific actions for enabling/disabling Istio injection and/or adding a specific 3scale label).

**Comment by lucasponce** [comment]
This one was waiting some previous work in the Namespace/Workload actions.
I'm going to resume it adding a couple of actions at namespace level to manage the istio-injection label in kubernetes scenarios.
