### ISSUE TITLE
Invalid Graph Find/Hide expression issues

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#2979]
**Describe the bug**
When a invalid expression is put in the Graph Find/hide text boxes the error message below the text find/hide pushes the 'Display' dropdown below where it should be:

![Kiali_Console](https://user-images.githubusercontent.com/1312165/87173534-c84d3580-c28a-11ea-80fc-b1cd0938c77e.png)

This is a visual bug only.

**Comment by jshaughn** [comment]
I think we should abandon this approach of putting the message below the input box and just make it a tooltip on the red icon.

**Comment by mtho11** [comment]
I agree, it's problematic.

**Comment by mtho11** [comment]
Maybe we can run these validation error issues past UxD for a better solution.

**Comment by mattmahoneyrh** [comment]
Attempting to reproduce this bug shows another potential issue:

 - Be sure that Display->Operations is NOT selected
 - Enter '@!!' into Find dialog
 - Note that there is no Error message, as described above
 - Now select Display->Operations, and note that the Error message is now displayed

![Selection_224](https://user-images.githubusercontent.com/7262987/87458553-286c1080-c5d8-11ea-9dff-6195f74e2663.jpg)
![Selection_225](https://user-images.githubusercontent.com/7262987/87458603-39b51d00-c5d8-11ea-8e3b-5a3ec43a6a03.jpg)

**Comment by mtho11** [comment]
Good find @mattmahoneyrh looks worse than the one I found

**Comment by jshaughn** [comment]
bogus. i am so getting rid of these bottom-posted error strings.

**Comment by jshaughn** [comment]
@mtho11 @mattmahoneyrh OK, I took a quick look at this and have decided that we need to fix only the issue with the error not showing up.  The positioning of the error text below this input, despite looking a bit odd, is still the PF style.  Because we're in a toolbar the hight adjusts as needed to fit the error under the graphFind component, and the rest of the components center as needed.  To actually present this under the entire toolbar is 1) hard and 2) not worth it.  I did the due diligence and tried fixing it with tooltips and it looked like shite.  So it is what it is.  Really not worth more time.

I suggest a similar approach be used for the log show/hide, just present the error string underneath and move on.  It's only like that until they get the input correct.

Generating PR now for the missing error issue...
