### ISSUE TITLE
Trace details / ux issue about service link

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#3014]
While navigating in trace details I'm often annoyed by this link on Operation / service details (the "stadium(default)" link in picture below):

![Capture d’écran de 2020-07-22 11-56-33](https://user-images.githubusercontent.com/2153442/88163240-a6509d00-cc12-11ea-93aa-db9b465f96a6.png)

My intent when clicking on it is to expand its content, just like the ">" sign on the left. But it's actually a link to the service details page. So it's causing some frustration, because I think when we are in trace details our primary intent is to get traces/spans information.

My suggestion would be to change this link for expanding content, and add a new "service details" column on the right, before "View metrics".

Thoughts?

**Comment by aljesusg** [comment]
In fact this expand the content with tags and span information...

**Comment by lucasponce** [comment]
> So it's causing some frustration, because I think when we are in trace details our primary intent is to get traces/spans information.

I think we have discussed this with @aljesusg. The idea here is to show always a *correlation* relation, on this case the idea is to show that this trace is linked with a Service and make available metrics and logs.

If there is a proposal to improve this but without loosing the *correlation* scenario, that's fine, otherwise, trace details should be forwarded to the specific tracing tool.

I'm less worried about the UI, there is always room to improve, but my concern is to not miss the Service link information which is critical in Kiali scenario.

**Comment by jotak** [comment]
> In fact this expand the content with tags and span information...

The ">" sign expands, but not the link just next to it

@lucasponce I agree my suggestion is not to remove completely this link, but just to expand the content (it's already expandable via ">") and add a new column for that link to service. So I don't think it would remove any capability for correlation. It's just a matter of UX.

**Comment by aljesusg** [comment]
I think that this is fixed in @jotak PR
