### ISSUE TITLE
Traces are being searched for by service name but apparently it's the app label that actually matters

### ISSUE THREAD

**Issue by jwurm** [kiali/kiali#3045]
Hello,

this issue was observed with Kiali 1.20.0 and Istio 1.6.5

Needed to reproduce
Workload: example with label app=example-label and version=2
Service: example-v2 that selects for app=example-label and version=2

Cause some traffic on that service that should be registered by jaeger

In Kiali in the "Services" view, navigate to "Traces". There won't be any results

The URL on the traces page in the browser looks like this:
/kiali/console/namespaces/mynamespace/services/**example-v2**?tab=traces&limit=20

Manually change the URL to refer to the value of the app label, "example-label", then it displays the traces of the example-v2 service:
/kiali/console/namespaces/mynamespace/services/**example-label**?tab=traces&limit=20

The reason seems to be that Kiali queries Jaeger for traces for a "service" with the name of the kubernetes service, but in the jaeger UI the name of the kubernetes service is listed as "operation", whereas there "service" apparently refers to the app label of the workload. 

Perhaps this inconsistency of terminology led to a mismatch of parameters, which does not get noticed if by convention or coincidence the app label of the workload matches the name of the service (which is very often the case, i guess)

**Comment by jotak** [comment]
Thanks @jwurm for reporting this.

@lucasponce @aljesusg I think we should work on that rather sooner than later. It has already been reported previously (but I can't retrieve the ticket). I don't know if something has changed with recent Istio or if it was an "historical" mistake ... anyway do you think it's ok if we fix it regardless the version of istio? (ie . even if it's due to a change in istio, we stick to the latest version)

**Comment by jwurm** [comment]
That may have been this ticket:

https://github.com/kiali/kiali/issues/2664

**Comment by aljesusg** [comment]
mmm I'll check if something changed in Istio, but maybe we can add in the configuration some kind of selector in tracing conf to set look by "app" or "service"

**Comment by jotak** [comment]
I wonder, what happens if we don't set any app label on pods? does it fall back to service name?

**Comment by jotak** [comment]
> I wonder, what happens if we don't set any app label on pods? does it fall back to service name?

I can self-answer, just tested => it falls back to the workload name.

**Comment by jotak** [comment]
So finally, after testing on istio 1.5 branch, it is also using app label instead of service name. I don't know how it is for older versions of Istio but I think we can forget about them. (=> no need for a config flag)

I think, what we need to do is to move the Trace tab from Service Details to App Details, update all related navigation links, and we're good. It's also going to impact the in-graph tracing (need to focus on app nodes instead of service nodes).

Perhaps as a later step, figure out if/how we want also to handle the case with app label not defined.

What do you think, @aljesusg , @lucasponce ? Sounds good?

**Comment by jwurm** [comment]
Would it be possible to change the query that searches the traces instead? In my opinion the traces view makes a lot of sense where it currently is.
I guess finding out the app label of the workload that the service refers to should be possible. 

But then again a weird service configuration might refer to multiple workloads with different app label values, so having the traces view at the workloads instead of the services would be more resilient in case people get creative with their service endpoints

.

**Comment by jotak** [comment]
But traces from the Workload page can be misleading because we'll end up seeing traces for the whole Application, that is to say, more than just the workload we're focused on. (unless we add some post-filtering on traces per workload ... and that's something we are planning to do, then we can't see traces for the whole app).

And as you said, traces per service will result in some buggy behaviours sometimes.

Why do you say, by the way, it makes more sense in Services? Technically speaking it's more correct to have them under Applications.

**Comment by jwurm** [comment]
IMHO that depends on what exactly is being displayed, if it would be all the traces of the application, or filtered by service.

The jaeger UI can search by what jaeger calls service (application in kiali) and operation (service in kiali) too after all, so it may be possible to show just the traces that belong to that exact service there. 

Also it would make sense to have the traces on a tab next to the traffic and metrics overview of the service.

**Comment by lucasponce** [comment]
> I think, what we need to do is to move the Trace tab from Service Details to App Details, update all related navigation links, and we're good. It's also going to impact the in-graph tracing (need to focus on app nodes instead of service nodes).

> Perhaps as a later step, figure out if/how we want also to handle the case with app label not defined.

> What do you think, @aljesusg , @lucasponce ? Sounds good?

It's a good suggestion, I was also wondering the implications but it seems that focus the tab under "app" has a better context.

I'd like to see what @aljesusg thinks as he also worked a lot on this feature.

**Comment by aljesusg** [comment]
IMO if tracing group the traces by app the tab should be in the app view

**Comment by jotak** [comment]
@jwurm perhaps we can split the problem into two separate things:

1. Fix the issue around the app label, that is to say, we are incorrectly assuming Kiali service == Jaeger Service, whereas in fact Kiali App == Jaeger Service; meaning that fetching traces as we currently do relates to an Application and not a Service.

2. Add more places where we can see Traces: Service details, Workload details. For Services, we will need to 1/ Get the "app" label of that service; 2/ Fetch traces for this app; 3/ Filter service traces based on operation name. And for Workloads, we can do something similar.

So the bug fix for this issue would be just 1. , and we can open a separate task for adding more traces views.

**Comment by lucasponce** [comment]
I like to see more traces tabs under the application and workload details.

**Comment by jshaughn** [comment]
Probably not relevant but just a reminder that with telemetry v2 app in the metrics/graph is set via canonical_service, which defaults to workload name if neither the `app.kubernetes.io/name` or `app` label are set.

**Comment by jotak** [comment]
Related tasks / follow-ups :

- Add traces to workload details https://github.com/kiali/kiali/issues/2710
- Add Traces to service details https://github.com/kiali/kiali/issues/3071
