### ISSUE TITLE
There is a storage in kiali?

### ISSUE THREAD

**Issue by matty111** [kiali/kiali#3092]
Does Kiali use storage? 
I can store resource of Istio with them version? And if i change the setting of a resousce i can restore a old configuration or i can see a history?

**Comment by lucasponce** [comment]
@matty111 Kiali doesn't provide any additonal storage.
It interacts directly with Kubernete API for resources and Prometheus/Jaeger for telemetry signaling.

The use case you comment is interesting, but I'm afraid that then we would need a generic resource versioning for Kubernetes objects and CRDs.

Basically the problem is to check when a resource is changed from any call (kubectl, or any other UI that interacts with the API).

To address this, we should be able to "plug" any native control versioning, and via webhooks, be able to apply versioning (I applied some changes, but I want to see all the history and get an old one).

Kiali doesn't provide that functionality.

Also, Istio has a concept that the control plane watches for changes in the definition and it applies a "runtime configuration" (via galley), so it's not first time we discuss that probably Istio Galley component should be the good place to add this info (it's not trivial I guess, because it's basically to apply a CVS for resources internally).

**Comment by jshaughn** [comment]
@matty111 Hopefully we answered your question.  If not feel free to re-open.
