### ISSUE TITLE
Change Welcome screen from "Service Mesh Observability" to "Service Mesh Management for Istio"

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3101]
In order to change Kiali's perception and move away of a pure "Service Mesh Observability", I would like to suggest to change the Welcome screen (right before landing into Kiali's UI) to "Service Mesh Management for Istio" and align exactly what it states on the community website: http://kiali.io

https://issues.redhat.com/browse/OSSM-223

**Comment by jshaughn** [comment]
@lucasponce @maltron , The issue is slightly ambiguous.  To "align exactly" with kiali.io it should be, "Service mesh management for Istio" but the description also says, "Service Mesh Management for Istio".   I went with the former (lowercase) but let me know if it was supposed to be the other way, if it matters enough to change.
