### ISSUE TITLE
Kiali Blog should be on Kiali.io and not hosted on Medium or other hosting sites

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#3118]
**Is your feature request related to a problem? Please describe.**
I would like to see the Kiali Blog hosted on Kiali.io not Medium or other publishers.

Linking to other sites is not a first-class experience.

**Describe the solution you'd like**
Kiali should publish their own blogs and not be hosted by other sites (especially as they change their policies and paywall strategies).

**Comment by mtho11** [comment]
We should also support RSS feeds and email updates to changes.

**Comment by jshaughn** [comment]
As much as I like Medium's features and I do still think we should publish to Medium for its wide distribution, I do hate the tiny limit on free articles, I'm constantly blocked.  Perhaps writing blogs in adoc on kiali.io would make sense, and then publish to Medium with a link back to kiali.io?

**Comment by lucasponce** [comment]
Jumping here to put two comments.
Changing of source of platform is a PITA.
We can't do that, because there will be people that would still use Medium, also, seeing a project moving from here and there is always seen as confusing.

I don't think the platform is a problem now, it's more to have a good number of quality articles.
If we want to duplicate, medium + copy/paste in kiali.io as plain html should be fine, but I don't really see the point.

Personally, I'd like to see more people publishing rather than discussing about which platform is best.
And let's take advantage we have a talented community manager in the team to promote the article in several medias.

**Comment by jshaughn** [comment]
Having lots of good articles that no one can read because Medium blocks them is not a good experience.

**Comment by lucasponce** [comment]
> Having lots of good articles that no one can read because Medium blocks them is not a good experience.

Medium blocks the reader, not the (free) publisher.

If we want to create a "blog" entry, and start adding plain articles in kiali.io, fine, but I think we should keep also posting in medium.

What I don't want is another sprint one-person-full-time just moving things from medium to kiali.io. 
Sorry, that's a no go.

I prefer people keep posting quality articles in medium instead.

**Comment by lucasponce** [comment]
Also, there are plenty of channels well setup that perhaps we can reuse and just post, instead to always looping on the infrastructure to post.

Just an example: https://developers.redhat.com/topics/service-mesh

**Comment by jmazzitelli** [comment]
IIRC, kiali.io articles are not limited. Articles are only limited if you turn on some monetary feature (which we do not do).
I'll double check this - but I'm almost positive none of this affects kiali articles - anyone can read any amount of them without being blocked.

**Comment by lucasponce** [comment]
> IIRC, kiali.io articles are not limited. Articles are only limited if you turn on some monetary feature (which we do not do).

Correct, is the reader that is limited. When you use a lot Medium, then their model is to move readers under subscription.

But if Kiali publishes in free mode it'll continue in that way.

In any case, I reinforce my message: more articles and less discussion in platforms.

**Comment by mtho11** [comment]
I get blocked so many times on medium articles that no I refuse to even click on a medium article anymore. I'm done with them.

**Comment by lucasponce** [comment]
> I get blocked so many times on medium articles that no I refuse to even click on a medium article anymore. I'm done with them.

But you can write KialiProject articles, I think.

**Comment by jmazzitelli** [comment]
> But you can write KialiProject articles, I think.

Right. No one should ever be blocked from seeing Kiali articles on medium.com - they aren't rate-limited or subscribe-only limited. If someone IS getting blocked from seeing a  Kiali article, we need to know because that means somehow they got published as a "premium" article (or whatever medium calls it) and it should not be.

**Comment by jshaughn** [comment]
If no readers are blocked from our Medium blog posts then I retract my comments and am fine with staying on Medium.  I was just concerned because I feel like I get blocked on Medium all the time, even when I restrict myself to [what I thinkare non-premium articles.  Perhaps I'll experiment with my wife or something and see how many Kiali blogs she can read :)

**Comment by lucasponce** [comment]
Again, I think this discussion is moving to the point.

a) We can't move from Medium. Sorry, it's not professional. Kiali has a number of followers in that channel that may feel uncomfortable with this.

![image](https://user-images.githubusercontent.com/1662329/90175910-75dec780-dda8-11ea-8f58-d652dc6a608f.png)

Medium allows to see free articles to everyone in a limited number per month, but this channel reaches a lot of new comers.
So, we shouldn't move from here.

b) If we want to add a simple "blog" section on the "kiali.io" and publish raw post there, it's fine with me, but I don't really want to insert any new blog engine.

c) There is no "I don't like Medium", if we write an article we publish in BOTH places. To keep our audience there. It's not "I only publish here or I tweet there", we are doing an effort with project media and we should keep on that.

**Comment by mtho11** [comment]
This is the type of blockage I'm referring to (unless you have a Paid subscription):
<img width="690" alt="How_to_Set_Up_Your_MacBook_for_Web_Development_in_2020___by_Vinicius_De_Antoni___Better_Programming___Medium" src="https://user-images.githubusercontent.com/1312165/90183871-17debf80-dd69-11ea-8943-62b2eafeb97f.png">

So you have to throttle your reading unless you want to pay them.

**Comment by israel-hdez** [comment]
Here is another downvote. We have been using Medium since pre-1.0 versions of Kiali. I think moving away from Medium is a bad idea.

As has been said, Kiali posts shouldn't be under the paywall. Even people who have depleted their free stories should still be able to read Kiali posts. So, I don't think this is a factor for a decision.

FWIW: Medium has support for RSS. Link for Kiali publication is https://medium.com/feed/kialiproject.

**Comment by lucasponce** [comment]
@mtho11 @jshaughn I don't think we are on the same page here, or I have feeling we are not discussing about the same thing.

Please, read my previous comment, I think it's clear in the options a), b) and c) I posted.

Medium is a platform that monetizes readings through readers.

Kiali project decided to use it in 2018 as it's still one channel with a number of followers, so we need to keep posting there (option a)). Note that this is not to hold the content, it's to reach new readers and increase the community. Someone interested in ServiceMesh will be suggested to read a Kiali article.

Nothing wrong if we want to create a "blog" entry in "kiali.io" to also have the content duplicated there (option b)).

But, we need to be consistent, so, it's not optional, if we create a "blog" it shouldn't be articles here and there, we should try to keep content in our channels (and synced by our community manager).

Kiali Project has presence in a channel, a decision to stop posting in a social media has a cascade of potential side effects, so, as I reiterated several times, I'm fine with option b), but option a) and c) are part of the scenario as well.

Yes, if you can get your Medium free account to the limit and get blocked, but that's a completely different point here.

**Comment by mtho11** [comment]
@lucasponce I understand what you are saying I'm fine with that. We can close this issue.

**Comment by mtho11** [comment]
There is one last thing that I forgot to mention and that is SEO. Having links and searches come to our site instead of Medium is great for SEO and making our site more sticky. Ok, that's all.

**Comment by lucasponce** [comment]
I think SEO is an orthogonal aspect in all the discussion and perfectly compatible with the option b) mentioned.

Also, as a side note, @xeviknal, as part of his community coordination effort, had several sessions about SEO recommendations for kiali.io with Red Hat specialists.

I remember that there is a document with some recommendations where we started to apply some of them, but again, it seems to me a different discussion.

**Comment by jshaughn** [comment]
> @jshaughn I don't think we are on the same page here

@lucasponce I wasn't really on a page.  I originally suggested that we could keep Medium and short blogs that referred back to the other blog.  The only concern was what I said, that people would not see the medium posts due to limits.  Since you are sure that's not a problem then it's not a problem.
