### ISSUE TITLE
I can see app from default namespace when I didn't select it

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#3129]
I can see apps from default namespace in graph when I didn't select it.

![Screenshot from 2020-08-17 13-22-04](https://user-images.githubusercontent.com/3019213/90391027-b8e0b980-e08c-11ea-90fc-a89d745d6eea.png)

Demo https://github.com/lucasponce/test-error-rates
Reproduce: 

1. Install betha and alpha Namespace demo
2. Install betha and alpha deploys in namespace default too
3. Go kiali graph and select betha and alpha namespace

You can see the generators from default namespace too.

**Comment by jmazzitelli** [comment]
This is expected behavior. That icon in the default node (the "network" icon) means "you have traffic coming in from this node which is external to the selected namespaces".

**Comment by aljesusg** [comment]
Thanks @jmazzitelli I asked it in the irc about that. It makes sense

**Comment by jshaughn** [comment]
Right, just to be verbose, the graph will show "1-degree" outside your selected namespaces so that you can see incoming and outgoing traffic.  If you have access to those namespaces you'll get the "network" icon and a double-click will bring you there.  If you don't have access, or if it's external to the mesh, you will have a "restricted" icon and click will do nothing.
