### ISSUE TITLE
Display percentage is shown an 50% instead of 100%

### ISSUE THREAD

**Issue by hariyada** [kiali/kiali#3137]
Hi All
<img width="623" alt="Screenshot 2020-08-20 at 10 43 54 AM" src="https://user-images.githubusercontent.com/2751777/90719448-1154c880-e2d2-11ea-89ec-7f8db80b2b47.png">

<img width="617" alt="Screenshot 2020-08-20 at 9 48 02 AM" src="https://user-images.githubusercontent.com/2751777/90718830-8c1ce400-e2d0-11ea-83ae-9b15de314f72.png">

As shown in the picture, I have the following istio config:

    **one** Gateway configured with two hosts (using common istio ingress gateway)

    1. prom-0
    2. prom-1

    **two** virtual services bound to above gateway with the destination routes

     1. prometheus-thanos-sidecar-0  ( is mapped to local service sidecar-0)
     2. prometheus-thanos-sidecar-1 ( is mapped to local service sidecar-1)

    **two** actual services 
     1. sidecar-0
     2. sidecar-1

   
   so finally how the communication flows is

    prom-0  -> ingressgateway -> prometheus-thanos-sidecar-0 -> sidecar-0

    prom-1  -> ingressgateway -> prometheus-thanos-sidecar-1 -> sidecar-1

   **How the display percentages are shown in the graph(refer attached picture)**

                              50%                                             100%
    prom-0  -> ingressgateway ----------------> prometheus-thanos-sidecar-0 --------------> sidecar-0
                                                                                                                               
                              50%                                             100%
    prom-1  -> ingressgateway ----------------> prometheus-thanos-sidecar-1 --------------> sidecar-1

   
   **My Expectation is :**

   since the hosts are mapped to different virtual services and in turn to different destination routes

                               100%                                               100%
    prom-0  -> ingressgateway ----------------> prometheus-thanos-sidecar-0 --------------> sidecar-0
                               100%                                               100%
    prom-1  -> ingressgateway ----------------> prometheus-thanos-sidecar-1 --------------> sidecar-1

**note :**

if i introduce one more host,virtualservice,service the percentages are shown like this

                                    33.33%                                       100%
    prom-0  -> ingressgateway ----------------> prometheus-thanos-sidecar-0 --------------> sidecar-0
                                    33.33%                                       100%
    prom-1  -> ingressgateway ----------------> prometheus-thanos-sidecar-1 --------------> sidecar-1
                                    33.33%                                      100%
    prom-2  -> ingressgateway ----------------> prometheus-thanos-sidecar-2--------------> sidecar-2

**Comment by jshaughn** [comment]
@hariyada I think what the graph is showing is correct so maybe there is a misunderstanding about the "Request Percentage" edge labeling.  It shows the percentage of requests for outbound traffic from a node.  So, the edges should add up to 100%.  In this case ingressgateway is making requests to both prometheus-thanos-sidecar-0 and prometheus-thanos-sidecar-1.  The 50% / 50% indicates that for the time period half of those requests went to -0 and half went to -1.

Istio telemetry provides only the "result routing" after virtual services have performed any logic given the requested host.   Also, because ingress is the starting point for traffic entering the mesh you don't have any incoming edge from which to capture the host information for the ingress request.  So, there is no way to know with the given telemetry that 100% of the prom-0 requested host went to prometheus-thanos-sidecar-0 and that 100% of the prom-1 requested host went to prometheus-thanos-sidecar-1.  We only know the resulting path of those requests, after VS processing.

You may be able to see this information if you enable Jaeger tracing, I'm not sure.

Having said all of that, the original request_host attribute, I think, is available to be set on the telemetry if configured by the user for the istio telemetry.  I'm not 100% sure what this field would hold for ingress and currently kiali would not make use of that additional information, it would only be in prometheus.

**Comment by jshaughn** [comment]
@hariyada Any feedback here?

**Comment by jshaughn** [comment]
@hariyada Hopefully we answered your question.  Feel free to re-open if necessary,

**Comment by hariyada** [comment]
@jshaughn  Thanks for answering the question.
