### ISSUE TITLE
Add fullscreen zooming beyond browser chrome

### ISSUE THREAD

**Issue by mtho11** [kiali/kiali#3155]
**Describe the solution you'd like**
As a Kiali user, I would like to have the full-screen zooming use the entire real estate of the monitor and not just 

**Describe alternatives you've considered**
I found a web API that enables this capability.

**Additional context**
Perhaps we can PoC this on the logging tab.

**Comment by jshaughn** [comment]
@mtho11 If it's relatively easy (1-2 days) I would like to see a POC for this feature.  I could imagine many screens (graph, logs) potentially benefitting from a true full screen.  If it seems to work we should then discuss how it could be applied in a consistent way.

**Comment by mtho11** [comment]
@jshaughn yes, that should not be hard looking at the API.

**Comment by lucasponce** [comment]
Please, ellaborate this.
If what you want to do here is to trigger a "F11" key from an API to just put the browser in full screen, that's one thing.
If you are thinking in a re-org of the pages (as for example github project does) that needs a discussion before to start an effort because I don't want to see a feature in one tab/page and not in others.

**Comment by jshaughn** [comment]
@lucasponce , Did you see my previous comment:

>  I would like to see a POC for this feature. I could imagine many screens (graph, logs) potentially benefitting from a true full screen. If it seems to work we should then discuss how it could be applied in a consistent way.

This is a quick POC to explore a true full-screen ability.  And then if it works figure out how we may want to use it in a consistent way.  Not sue what you are worried about.

**Comment by lucasponce** [comment]
> Not sure what you are worried about.

I see that web pages are implemented in two styles:
- Interacting with the browser to simulate a F11 behaviour.
- Changing the layout (as for example, github proposes in its "full screen" features).

If this POC is about second, we must discuss it, because I'm not sure if I agree.

As I don't understand what @mtho11 is planning to do, I'm sorry if I disturb folks but I need to ask.

**Comment by jshaughn** [comment]
@lucasponce I don't think this has anything to do with layout, just making what you are looking at bigger.  We can wait for @mtho11 to repsond.

**Comment by mtho11** [comment]
This PoC doesn't affect layout it takes whatever screen/dialog that we currently use and allows it to utilize the monitor's full height and width. True full-screen mode. It allows the page/dialog to go beyond the boundary of the browser window.

I think this capability would be useful for people running NOCs.

**Comment by lucasponce** [comment]
> This PoC doesn't affect layout it takes whatever screen/dialog that we currently use and allows it to utilize the monitor's full height and width. True full-screen mode. It allows the page/dialog to go beyond the boundary of the browser window.

Then I understand that you are refering to the second style I commented in https://github.com/kiali/kiali/issues/3155#issuecomment-684824692

Just to be clear, the first style, like what github does, offers a button like this:

![image](https://user-images.githubusercontent.com/1662329/95557084-96c44180-0a14-11eb-85e3-7a314946852d.png)

But it's a complete re-layout inside the same browser:

![image](https://user-images.githubusercontent.com/1662329/95557157-acd20200-0a14-11eb-9178-fb604cacba20.png)

Not affecting to the Operating System window size.

But, the second option it emulates a "F11" key and it delegates into the OS to use the full size of the screen.

I understand that you are planning to study this second option, but as I wasn't unsure I'd like to confirm, because in this "full screen" context people may understand two different things (and the first one it's tricky).

If the efforts of this is to emulate the "F11" key from the app like an easier shortcut it may be ok.

**Comment by mtho11** [comment]
Yes @lucasponce to confirm this is the F11 option for full screen.
