### ISSUE TITLE
debug   code    kiali

### ISSUE THREAD

**Issue by felix-hxz** [kiali/kiali#3166]
I0902 17:41:53.391741   19384 kiali.go:64] Kiali: Version: unknown, Commit: unknown
I0902 17:41:53.400553   19384 kiali.go:75] No configuration file specified. Will rely on environment for configuration.
F0902 17:46:06.786033   19384 kiali.go:81] server static content root directory does not exist: /opt/kiali/console

@jshaughn
@jpkrohling 
@pavolloffay

**Comment by jmazzitelli** [comment]
I have no idea what this is asking. Is there a question?

I'm just guessing here - is there something you want to know about how to run Kiali outside of a cluster? Did you read:

* https://github.com/kiali/kiali/blob/master/README.adoc#running-standalone
* https://github.com/kiali/kiali-ui#developing
* https://github.com/kiali/kiali/blob/master/README.adoc#running-the-ui-outside-the-core
* https://github.com/kiali/kiali/blob/master/README.adoc#running-a-locally-built-ui-inside-the-core

**Comment by HFeilx** [comment]
Native debugging backend kiali source code, how to debug, prompt missing the following file
@jmazzitelli

**Comment by HFeilx** [comment]
Debug code：

I0902 17:41:53.391741 19384 kiali.go:64] Kiali: Version: unknown, Commit: unknown
I0902 17:41:53.400553 19384 kiali.go:75] No configuration file specified. Will rely on environment for configuration.
F0902 17:46:06.786033 19384 kiali.go:81] server static content root directory does not exist: /opt/kiali/console

@jmazzitelli

**Comment by jmazzitelli** [comment]
The links I provided earlier will discuss that. I also know that @lucasponce does this (run Kiali outside of a cluster and be able to debug the server). - perhaps he can share some docs that he has.

**Comment by HFeilx** [comment]
@lucasponce

**Comment by HFeilx** [comment]
@lucasponce 
@jmazzitelli 
@jpkrohling 
@israel-hdez

**Comment by lucasponce** [comment]
@HFeilx Hi, not sure what are you asking for.

Happy to help if I have more info, would you mind to join us our channel on IRC or slack and perhaps we can spot better your issue ?

There is a link to access directly to the IRC we usually work:
https://kiali.io/contribute/

But if you are on Istio Slack, that works too, there is a kiali room where we can try to help you.

**Comment by HFeilx** [comment]
我把kiali源码clone下来在本地debug，报错，提示：
server static content root directory does not exist: /opt/kiali/console

**Comment by HFeilx** [comment]
@lucasponce 
@jmazzitelli 
@jpkrohling 
Where is the missing configuration file

**Comment by jmazzitelli** [comment]
> server static content root directory does not exist: /opt/kiali/console
> Where is the missing configuration file

That is the kiali-ui code. When the kiali server container image is built, the kiali-ui frontend code is copied into this directory. It is not a configuration file. It is an entire frontend javascript application. This directory is where Kiali server expects to find the frontend application. This application gets served to the client browser.

Read these comments here: https://github.com/kiali/kiali/blob/master/Makefile#L13-L21

You can see how this /opt/kiali/console is created in the image here: https://github.com/kiali/kiali/blob/master/make/Makefile.container.mk#L7

That uses this script to copy the console files: https://github.com/kiali/kiali/blob/master/deploy/get-console.sh

The code for this kiali-ui frontend javascript application is found here: https://github.com/kiali/kiali-ui
You must build this Kiali UI code (usually via `yarn install; yarn run build`) in order to be able to build the Kiali server and get this /opt/kiali/console content. See the README in that kiali-ui github repo.

**Comment by HFeilx** [comment]
@jmazzitelli 
this var (
	argConfigFile = flag.String("config", "", "Path to the YAML configuration file. If not specified, environment variables will be used for configuration.")
)

What is the configuration file for k8s cluster

**Comment by israel-hdez** [comment]
> What is the configuration file for k8s cluster

For k8s, it's a config map that's usually mounted in `/kiali-configuration/config.yaml`.

Why are you trying to debug Kiali?
What's the underlying issue you want to solve?

**Comment by HFeilx** [comment]
@israel-hdez 

Want to contribute source code ！
Where is the configuration you are talking about? I installed it through istioctl

**Comment by lucasponce** [comment]
Hi @felix-hxz, not sure if you're interested to keep this issue opened.
There is a new discussions section https://github.com/kiali/kiali/discussions that we can use for more generic questions that don't necessarily involve a change in Kiali.

Thanks
