### ISSUE TITLE
Kiali namespace filter "Select all" option

### ISSUE THREAD

**Issue by gyucegok** [kiali/kiali#3173]
Dear Team,

I would like to make an RFE request for namespace filtering

Steps to reproduce:
Kiali Console -> any item on the left (Apps, workload, services) -> type something in the namespace filter box on the top -> get a list of those namespaces.

What is proposed for change:
Can we add a Select all button?
There is already a "clean all" button on the right of that dropbox, so maybe we can add a "select all" on the left?

Thanks

Best Regards
Gokhan Yucegok

**Comment by jshaughn** [comment]
I think there are several improvements needed to namespace selection:
- select all
- clear all
- batch changes (as opposed to immediate reaction to each selection)
  - explicit cancel/submit

Here is a POC video (thoughths @lucasponce @jotak  @jmazzitelli ?):

![kiali#3173](https://user-images.githubusercontent.com/2104052/98700555-4ce9b680-2346-11eb-93e1-93527e7fa043.gif)

**Comment by lucasponce** [comment]
The "cancel" and "ok" buttons are a drawback in usability, you are adding more clicks.

I'd add a "select all" link similar as "clear all" and play with the focus or similar, but definitely not adding a new Ok/Cancel buttons there.
![image](https://user-images.githubusercontent.com/1662329/98701282-66582600-2379-11eb-9a2e-9070a089b45c.png)

**Comment by jshaughn** [comment]
> The "cancel" and "ok" buttons are a drawback in usability, you are adding more clicks.

I disagree.  It serves multiple purposes.  It allows for batch updates, which is a big win over today's immediate reaction to every click, which I find to be horrible usability.  Also, it gets rid of the dropdown, which today already requires a click and so you are actually not adding more clicks.

**Comment by lucasponce** [comment]
> I disagree. It serves multiple purposes. It allows for batch updates, which is a big win over today's immediate reaction to every click, which I find to be horrible usability. Also, it gets rid of the dropdown, which today already requires a click and so you are actually not adding more clicks.

I disagree with your disagreement :).

I think you can implement same behaviour you are talking about playing a little bit with the existing components.

I'm -1 to put a ok/cancel button, it looks very bad.

But, if you want to implement a batch behaviour you can play with the focus or closing event of the dropdown.

**Comment by jshaughn** [comment]
Time to call in UX :-)  cc @lwrigh , any guidance here?

**Comment by lwrigh** [comment]
The filter should be automatic so there's no need for the cancel/ok buttons on the filter dropdown. The dropdown should disappear once the user clicks on the filter again or outside of the filter dropdown. 

For components to reference, I would take a look at the filter chips since you can easily clear those: https://www.patternfly.org/v4/guidelines/filters/design-guidelines/#filter-chips

Bulk selection is also an opinion for needing to select all: https://www.patternfly.org/v4/guidelines/bulk-selection/#bulk-selection

**Comment by jshaughn** [comment]
@lwrigh OK, so you are saying there is no need for a "Cancel" feature and that all selections should simply be applied when the user clicks outside (or hits Escape)?

**Comment by lwrigh** [comment]
Yeah there's no need for the cancel button on it. Yes whichever selections the user makes should be applied even after the user clicks outside of the dropdown or hit escape.

**Comment by jshaughn** [comment]
@lwrigh OK, thanks.  Goodbye buttons...

**Comment by lucasponce** [comment]
I don't get why to use the same checkbox to an action and value, the "select all" / "clear all" is confusing to me.
Also it pushes the find textinput to the left looking less balanced.

I think you could use the same pattern
![image](https://user-images.githubusercontent.com/1662329/98784836-fccd2b80-23fb-11eb-86ae-dc00598a15a8.png)

But with the considerations of batch update

**Comment by lwrigh** [comment]
![Kiali- Namespace selector](https://user-images.githubusercontent.com/20227374/98822435-db217380-23fe-11eb-96f9-d9bf3dae665d.png)

I would suggest just doing something like this. It should be obvious enough to the user that they can select the 'Select all' checkbox to select and deselect all the namespaces. It's a pretty common interaction.

**Comment by jshaughn** [comment]
@lwrigh OK, I'll make that change.   I had originally kept it up with the filter text box because I was following [the PF bulk selector pattern](https://www.patternfly.org/v3/pattern-library/forms-and-controls/bulk-selector/index.html).  @lucasponce the bulk selector checkbox is pretty common and seems to be the PF way, as well.  Laura's approach is a modification that seems well-suited to this use case.

**Comment by lucasponce** [comment]
> Laura's approach is a modification that seems well-suited to this use case.

@lwrigh +1 :)

**Comment by jshaughn** [comment]
Latest revision... note also a proposed simplification of the button label when there are multiple namespaces. Instead of:
"Namespace: 4 namespaces" it is just "[4] Namespaces".  Also, in the dropdown the namespace names are no longer emphasized, as in Laura's mocks.  I think it is cleaner and more consistent with other dropdowns.

![kiali#3173-3](https://user-images.githubusercontent.com/2104052/98855516-20a76600-242a-11eb-968c-183b498126a6.gif)

**Comment by lwrigh** [comment]
> Latest revision... note also a proposed simplification of the button label when there are multiple namespaces. Instead of:
> "Namespace: 4 namespaces" it is just "[4] Namespaces". Also, in the dropdown the namespace names are no longer emphasized, as in Laura's mocks. I think it is cleaner and more consistent with other dropdowns.
> 
> ![kiali#3173-3](https://user-images.githubusercontent.com/2104052/98855516-20a76600-242a-11eb-968c-183b498126a6.gif)

The update is looking good @jshaughn! Instead of showing the [4] when multiple namespaces are selected, I would recommend using a badge to show the number. You can see an example of that type of filter here: https://www.patternfly.org/v4/components/toolbar/react/#with-filters

Here's the link to the individual badge component: https://www.patternfly.org/v4/components/badge/

**Comment by jshaughn** [comment]
@lwrigh Yes, that's better:

![image](https://user-images.githubusercontent.com/2104052/98868813-b816b400-243e-11eb-8c25-380be071a304.png)

![image](https://user-images.githubusercontent.com/2104052/98868679-8271cb00-243e-11eb-9f86-2672c1e5abe9.png)

**Comment by lwrigh** [comment]
That's looking good to me @jshaughn !
