### ISSUE TITLE
Direct Login to Kiali via access token (By pass log in with openId)

### ISSUE THREAD

**Issue by widdix123** [kiali/kiali#3205]
**Is your feature request related to a problem? Please describe.**

I have different services hosted on a single dashboard with one login via dex. Once i am authenticated as a user to the dashboard, i can access any services such as grafana, kubernetes-dashboard, minio , prometheus, alertmanager with the same login as dex. 

Currently OIDC works fine with v1.23 fix works perfectly but it requires me to click on "Log In with OpenId" that redirects me to dex and then back to the kial console

**Describe the solution you'd like**
I am looking for a way to directly use a dex token and login to the Kiali console bypassing the "login with openid" . T

**Describe alternatives you've considered**

Another alternative we are considering is using a JS code to click on the 
"Login with Open Id" via the dashboard application but i was hoping Kiali does provide something to directly authenticate . Currently Kubernetes dashboard using kube-oidc-proxy on EKS 1.16 works fine by directly using the dex token/access token when i first login to my application

**Comment by widdix123** [comment]
@jmazzitelli  @israel-hdez  - i am not sure if this is already implemented but i was hoping Kiali could provide us a way to use an already verified JWT token from Dex

**Comment by israel-hdez** [comment]
If you already are successfully using `openid` strategy, and if you are going to always have a dex token in advance, then you may want to switch to `token` strategy. You should be able to paste your previously obtained dex token and it should work as long as you keep the cluster integration with OpenId. The only thing that won't work is that the the username won't be displayed.

But try this and if it suit your needs, we could then fix the username indicator.

**Comment by israel-hdez** [comment]
Hmm... although if you are using `kube-oidc-proxy` my suggestion won't work.

**Comment by jmazzitelli** [comment]
@israel-hdez if I understand what this is asking for - this person doesn't even want to see the login screen (ANY login screen). So `you should be able to paste your previously obtained dex token` doesn't get the desired behavior because that would still require you to go through the token login screen and paste the token in the token field.

What I think this issue is asking for is: "given an existing valid OpenID token, can I somehow get directly in the Kiali overview page without going through any login page?" Whether that is possible or not, I do not know, but that seems to me what is being asked.

@widdix123 can correct  me if I'm wrong.

**Comment by widdix123** [comment]
@jmazzitelli  - Yeah i get validated once when i login to the dashboard , again i click on kiali services it redirects me to "Log In with OpenId" .  When i click the button, it reauthenticates me to dex but i was hoping if i could bypass the step to redirect me to Kiali console if i am authenticated already 

Currently i have to do it in 2 steps

**Comment by israel-hdez** [comment]
@widdix123 OK, so once you login into one of the services that also use dex, your expectation is that the other services should no longer ask for user/password again.

**Comment by widdix123** [comment]
@israel-hdez  - Yeah something like that , once i get verified i should be able to access all services with another login/password . Sort of single on .

**Comment by israel-hdez** [comment]
@widdix123 I think I don't understand clearly.
Let's see. About the Kubernetes dashboard, what do you mean that you use a dex token to login into the dashboard? Are you pasting a token in this screen?

![](https://github.com/kubernetes/dashboard/raw/master/docs/images/signin.png)

If so, how do you obtain that dex token?

**Comment by widdix123** [comment]
@israel-hdez  - I will send you the screen shot today as i am bringing up a cluster

**Comment by widdix123** [comment]
![image](https://user-images.githubusercontent.com/38529736/93880261-d2fc6000-fcfa-11ea-8ec0-3e9a162b1a6a.png)

This is how we login, it uses the JWT token that bypasses the token screen and directly logins to the dashboard landing page

**Comment by israel-hdez** [comment]
@widdix123 Well, that would mean that you are exposing the dashboard through a reverse proxy. Is this true?

**Comment by widdix123** [comment]
Yeah i think so ..

**Comment by israel-hdez** [comment]
OK, within the scope of Kiali, I don't think this is directly related to our OpenID support. It's something else because Kiali is not handling the authentication.

If you are using reverse proxies, I know that a community user may be going to contribute the code to support this scenario in Kiali. Given it's a community contribution, I cannot say if/when it is going to be available.

**Comment by israel-hdez** [comment]
I think this was solved by a community use who introduced the `Header` authentication. Please check these docs and see if it solves your issue: https://kiali.io/documentation/latest/configuration/authentication/header/

Closing for now.
