### ISSUE TITLE
New health chart in metrics

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#3222]
After the health configuration task, it would be interesting to have a chart with the degraded/failure threshold based in the configuration and the % of error rate to check in what moment passed from healthy to degraded for example.

![Screenshot from 2020-09-17 11-35-52](https://user-images.githubusercontent.com/3019213/93453421-f62da680-f8d9-11ea-8cb5-ed3bf4fcaf68.png)

PF4-chart: https://patternfly-react.surge.sh/documentation/react/charts/chartthreshold/

cc @jotak , @lucasponce

**Comment by lucasponce** [comment]
The idea is good, but Health Config is based on percentages, so, Metrics don't collect those metrics, but in the SummaryPanel:
![image](https://user-images.githubusercontent.com/1662329/93462504-bb7e3b00-f8e6-11ea-9b79-9a7bf1494e44.png)

There would be a candidate to propose some decoration based on the % defined in health config.

**Comment by lucasponce** [comment]
I mean, in these charts:
![image](https://user-images.githubusercontent.com/1662329/93462633-e7012580-f8e6-11ea-880e-1fae548e9d5c.png)

User has not visibility of the % and it would need to re-arrange them, but in the summary panel, a dotted line or other similar decoration showing where you mark degraded or failure would be the first place I'd look.

**Comment by jshaughn** [comment]
@lucasponce @aljesusg , I agree that it's an interesting idea but I also agree that it's not easy to show in an existing chart.  The side panel sparkline is maybe possible but given the potential complexity of the configurable thresholding I'm not sure it's possible to overlay anything useful on the sparkline, which is already just for trending and not so much for analysis.  The %error it is showing is just 4xx+5xx, and that may not map to an actual problem.  I think the health indicator, already in the side-panel, is probably sufficient.

Unless someone has more ideas here I'd probably suggest closing this one.

**Comment by lucasponce** [comment]
This issue is valid, and probably it will be re-formulated as a subtask in a bigger Epic that will take care of represent the status of Health configuration.

There are several aspects that may impact here:
- Filters by codes (health config may be different in 4XX vs 5XX)
- Filter by source (incoming/outcoming)

So, it's clear that user must know why health of an element is in a particular status, and also charts may offer some kind of dotted line as helpers to define thresholds.

But I'm going to put the "future" label on this one until we define the scope of the epic, but for sure we will revisit this one.

**Comment by lucasponce** [comment]
Some of the ideas discussed on this issue may be part of the global https://github.com/kiali/kiali/discussions/4080 discussion.

So, they would be incorporated in that discussion, but this issue could be closed.
