### ISSUE TITLE
Kiali is not working with non-root user

### ISSUE THREAD

**Issue by a8j8i8t8** [kiali/kiali#3224]
**Describe the bug**
Kiali is not working with non-root user.

**Versions used**
Kiali: 1.23
Istio: 1.7.0
Kubernetes flavour and version: Kubernetes 1.18.0

**To Reproduce**
Started Kiali as non-root user using below: -
```
        securityContext:
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
```
Following are the start-up logs: - 
```
I0917 13:21:35.281821       1 kiali.go:64] Kiali: Version: v1.23.0, Commit: 61d506bb658265552ab835c5e4183ccf8d86dcec
I0917 13:21:35.283900       1 kiali.go:155] Using authentication strategy [anonymous]
W0917 13:21:35.283914       1 kiali.go:157] Kiali auth strategy is configured for anonymous access - users will not be authenticated.
I0917 13:21:35.283955       1 kiali.go:85] Kiali: Console version: 1.23.0
I0917 13:21:35.283965       1 kiali.go:230] Updating base URL in index.html with [/kiali]
E0917 13:21:35.284008       1 kiali.go:256] File I/O error [open /opt/kiali/console/index.html: read-only file system]
I0917 13:21:35.284021       1 kiali.go:211] Generating env.js from config
E0917 13:21:35.284040       1 kiali.go:256] File I/O error [open /opt/kiali/console/env.js: read-only file system]
I0917 13:21:35.286095       1 server.go:67] Server endpoint will start at [:20001/kiali]
I0917 13:21:35.286109       1 server.go:68] Server endpoint will serve static content from [/opt/kiali/console]
I0917 13:21:35.286118       1 metrics_server.go:18] Starting Metrics Server on [:9090]
```
**Expected behavior**
We should not see any File I/O error.

**Comment by jmazzitelli** [comment]
Kiali is already running as a non-root user as defined in the image : https://github.com/kiali/kiali/commit/a6affb4f74664f866cf6b27c532a9435ff656d57

I'm not sure if what you are doing is breaking that ?

**Comment by a8j8i8t8** [comment]
@jmazzitelli Not doing anything special. Any pointers would help. 🤔

**Comment by jmazzitelli** [comment]
> @jmazzitelli Not doing anything special. Any pointers would help.

When you set security context for a Pod, [it applies to all Containers in the Pod](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod). And as [this commit shows](https://github.com/kiali/kiali/commit/a6affb4f74664f866cf6b27c532a9435ff656d57), the kiali container image has files in it that were created for use by the user "kiali" only and it runs as user "kiali". We did this as part of https://github.com/kiali/kiali/issues/2745 so people didn't have to set a securityContext.

If you set the securityContext to run as a different user, that will fail because the user won't be able to read the files that are only available to the user kiali and thus get the error you see. The only way it would work is if you set the user ID to the "kiali" user ID (I don't know what the default ID is for that user when the container is created). But unless there is something I'm missing, there doesn't seem to be a need to set a securityContext to a non-root user because the container already does that. This is what this issue was about: https://github.com/kiali/kiali/issues/2745

**Comment by a8j8i8t8** [comment]
@jmazzitelli Not sure what is wrong but I'm using the correct uid and gid.
![image](https://user-images.githubusercontent.com/9692020/93487497-9fd65d00-f905-11ea-8ca2-1c905e3bb18b.png)

**Comment by jmazzitelli** [comment]
Unsure.

What I do know is issue https://github.com/kiali/kiali/issues/2745 was created and PR merged https://github.com/kiali/kiali/pull/2769 to solve the issue where Kiali was not running as a non-root user. Now it is running as a non-root user. Not sure what setting a `securityContext` buys you in terms of value-add because it is really only going to do at most what the container file itself does (run as a specific user where only that user can access the files in the container).

Why are you setting a securityContext? Is there a problem you are trying to solve that the Dockerfile's non-root user fix does not solve?

**Comment by israel-hdez** [comment]
Did you do any additional changes to the deployment?
I don't use the `securityContext` attribute, but I'm dubious about if that's the source of the `read-only file system` message.

I would think we should, instead, see a "permission denied" message if wrong gid/uid were the issue.
So, I lean towards thinking there is some other customization that is turning as "read-only" the whole file-system of the kiali pod.

**Comment by a8j8i8t8** [comment]
@israel-hdez If I don't use `securityContext` it complains saying `Error: container has runAsNonRoot and image has non-numeric user (kiali), cannot verify user is non-root`

**Comment by jmazzitelli** [comment]
> If I don't use `securityContext` it complains saying `Error: container has runAsNonRoot and image has non-numeric user (kiali), cannot verify user is non-root`

I have never seen this error before.

How did you install Kiali?

Do you happen to be using PodSecurityPolicies anywhere?

**Comment by a8j8i8t8** [comment]
@jmazzitelli Yes I'm using `PodSecurityPolicies`. Kiali is installed using `https://github.com/istio/istio/blob/release-1.7/samples/addons/kiali.yaml` but the only thing that I added is `securityContext`.

**Comment by jmazzitelli** [comment]
I have a feeling the PodSecurityPolicies is screwing this up. If the only thing you want is to have kiali run as a non-root user, you do not need the PSP/securityContext - Kiali is already running as a non-root user.

What we can do is set the user to be a non-numeric user (we'll just set it 1000 in the Dockerfile, rather than "kiali") and see if that helps.

**Comment by jmazzitelli** [comment]
OK, I created a PR to address the error `Error: container has runAsNonRoot and image has non-numeric user (kiali), cannot verify user is non-root`. But again, if all you want is to have kiali run as non-root, it already does that so there is no need to create that PSP. It is possible other things might break with that PSP you have (as @israel-hdez said, there might be something else in your setup causing Kiali's file system to be mounted as a read-only file system). But, the PR #3228 will fix that "numeric user" issue.

**Comment by jmazzitelli** [comment]
the PR has been merged. I think that addresses this issue.

**Comment by israel-hdez** [comment]
@a8j8i8t8 Can you try Kiali v1.24 to see if it fixes your issue?

**Comment by a8j8i8t8** [comment]
@israel-hdez I'm afraid but there is still an issue. 😟 But at least it's starting up without `securityContext`.
I think after pod is started it's trying to edit files but it's not able to.
```
I0922 19:30:46.980524       1 kiali.go:64] Kiali: Version: v1.24.0, Commit: fff05cd7a637abdd616b818e19160af75b7eb0a6
I0922 19:30:46.981342       1 kiali.go:155] Using authentication strategy [anonymous]
W0922 19:30:46.981362       1 kiali.go:157] Kiali auth strategy is configured for anonymous access - users will not be authenticated.
I0922 19:30:46.981395       1 kiali.go:85] Kiali: Console version: 1.24.0
I0922 19:30:46.981402       1 kiali.go:230] Updating base URL in index.html with [/kiali]
E0922 19:30:46.981449       1 kiali.go:256] File I/O error [open /opt/kiali/console/index.html: read-only file system]
I0922 19:30:46.981457       1 kiali.go:211] Generating env.js from config
E0922 19:30:46.981477       1 kiali.go:256] File I/O error [open /opt/kiali/console/env.js: read-only file system]
I0922 19:30:46.983936       1 server.go:67] Server endpoint will start at [:20001/kiali]
I0922 19:30:46.983952       1 server.go:68] Server endpoint will serve static content from [/opt/kiali/console]
I0922 19:30:46.983959       1 metrics_server.go:18] Starting Metrics Server on [:9090]
```

**Comment by israel-hdez** [comment]
Yes, I think your `PodSecurityPolicies` are causing the filesystem to be mounted as read-only, while Kiali expects the filesystem to be writeable.

Can you remove that policy? Or, at least, allow a writing to the Kiali pod via `securityContext`? Perhaps, try overriding the policy by setting this in Kiali:

```yaml
securityContext:  
    readOnlyRootFilesystem: false
```

If this does not work, well... we may need to do more changes to solve this, in case Kiali is unusable for your setup.

**Comment by jmazzitelli** [comment]
Yes, I'm convinced your custom PodSecurityPolicy that is in effect for the Kiali pod is causing this problem.

**Comment by a8j8i8t8** [comment]
@jmazzitelli @israel-hdez I think Kiali needs to have one elevated privilege of `readOnlyRootFilesystem: false` and then this needs to be documented somewhere. Except Kiali all our other applications are running fine with same PSP.
Please feel free to close this issue.

**Comment by jmazzitelli** [comment]
We have not had any other user encounter this issue. We do not create our file systems as read only (indeed, we can't, because as you see we do write some things at startup). I am not sure why your system behaves differently.

**Comment by a8j8i8t8** [comment]
@jmazzitelli It's not an issue, but the deployment requirement for Kiali. If you don't have any PSPs then of course it'll run without any issue. But if your cluster has restrictive PSPs then this requirement needs to be documented.

**Comment by jmazzitelli** [comment]
So I guess that means `readOnlyRootFilesystem: true` is the default value if not explicitly specified in a PSP? We can put this in our FAQ. I'll create a new doc issue specifically for that.

**Comment by jmazzitelli** [comment]
Doc issue here: https://github.com/kiali/kiali/issues/3297
