### ISSUE TITLE
Idle workloads should be marked different than normal workloads in Graph

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3232]
I'd like to differentiate an "iddle" status vs a "healthy/normal" in the graph:

![image](https://user-images.githubusercontent.com/1662329/93878345-332eda00-fcda-11ea-8733-bc1b44768e87.png)

perhaps just to change the decorator of the node.

While running an experiment I noticed it was difficult to differentiate both status.

**Comment by jshaughn** [comment]
@lucasponce In the above screen shot there seems to be incoming and outgoing traffic yet the health shows idle, and no pods.  Why is that?

**Comment by lucasponce** [comment]
> @lucasponce In the above screen shot there seems to be incoming and outgoing traffic yet the health shows idle, and no pods. Why is that?

At some point I decided to scale to 0 a reviews-v2 workload.

I guess that in the context of the telemetry, there is telemetry, but workload is iddle, so perhaps some decorator could help to show that scenario.

In the time interval there was traffic, but workload was moved to 0 pods on purpose, health traffic probably it's ok in terms of prometheus query, but in terms of workload status perhaps it's better to mark different "iddle" workloads.

**Comment by jshaughn** [comment]
This is sort of a tricky point because health is mixing current pod state with potentially older metrics.  Perhaps pod status should be ignored when the time frame is not current.  In this case it was likely a minor skew in time, but it still shows something potentially confusing.  I'm not 100% sure I want to change the look of the node for idle, as I think traffic for the current time period is the more critical element in the graph.

**Comment by lucasponce** [comment]
I'm not sure if I agree, there are two different situations that may get benefit of a different decorator:

A healthy workload (v3):
![image](https://user-images.githubusercontent.com/1662329/93888850-ce2eb080-fce8-11ea-8edb-bd54b4e39021.png)

An iddle one (v2):
![image](https://user-images.githubusercontent.com/1662329/93888903-e0105380-fce8-11ea-9d63-79676cd5decf.png)

So, from this view:
![image](https://user-images.githubusercontent.com/1662329/93888936-e999bb80-fce8-11ea-9d03-7759a200912e.png)

I can't differentiate that situation.
To me rest of the graph is ok but as user perhaps on this case I'd like to see decorated the workload as iddle.

**Comment by aljesusg** [comment]
Here we have 2 cases:

- if we scale to 0 and we have metrics from Last X minutes, in this case I would expect the actual status and maybe some indicator about is scaled to 0
- There are not metrics about because we scaled the resource to 0. In this case I agree about to mark the node with another color

**Comment by jshaughn** [comment]
Reviving this discussion...   A couple of thoughts:
- Even without health we already flag workloads with no backing pods (IsDead=true).   It has been there since the beginning of Kiali but has never been used in the visualization.  
- With the latest changes the default behavior would be to hide idle edges (and therefor idle workloads).  But this enhancement is still relvant when the "Idle Edges" display option is enabled.

Instea dof introducing another color option, perhaps this could be done with a badge (like VS, CB, etc).  This would be a nice visual queue without complicating the color scheme, which is already fairly robust.

**Comment by lucasponce** [comment]
Some badge or decorator should help (or perhaps a dashed line?) but I think this is still relevant as it may introduce some inconsistency with the other ways to represent "health" from the workload.

![image](https://user-images.githubusercontent.com/1662329/128152712-147b756a-37e1-4b8d-b5d5-1fb31eebbe77.png)

**Comment by jshaughn** [comment]
Useful but closing as part of routine backlog maintenance.  Can be re-opened as needed.
