### ISSUE TITLE
Feature request: Real time graphs

### ISSUE THREAD

**Issue by e-minguez** [kiali/kiali#324]
Maybe adding a switch to show real time graphs (not the default view), but I think having something similar as http://logstalgia.io/ does would be impressive (and fun!)

**Comment by jshaughn** [comment]
I don't think we have anything quite like that planned.  We do have auto-refresh of the graph in order to capture topology changes.  But, I think you are looking more for traffic animation.  We do now have animations for HTTP and TCP traffic.  Give it a try and let us know what you think.  If you have an idea for something more let us know, maybe we could guide you towards a contribution!
