### ISSUE TITLE
Internal metrics revisit

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#3244]
_This is something that was discussed in a call and, IMO, the perception was that this is good to have. However, it's unsure if it's worth to do._

Kiali have a few internal metrics in place. For example, we expose how much it takes for Kiali to complete the processing of different paths within the code flow and we expose this metrics in a prometheus format. So, if the user has prometheus, it could collect Kiali internal metrics.

The number of internal Kiali metrics is little and Kiali is lacking some screens to give visibility and provide real usage for the users. Also, the scope is limited to the back-end and are quite technical metrics. These metrics were supposed to enable users to provide feedback when users report issues, but are probably underused.

The scope of these internal metrics probably should be extended to also cover the UI, and also to generate more less-technical, more high-level metrics. Some ideas:

* Measure which pages are the most used
* Measure which options/features are mostly turned on or off
* Error metrics
* Response time metrics

Some of these metrics could easily be generated by adding an Istio sidecar to Kiali. This could help to understand what Kiali features are the most used and how and this would empower users to share more refined feedback to the project, and can make it easier to ask for feedback when users report bugs/issues.

We could re-use the prometheus instance used for istio to store these metrics and provide some screens summarizing these metrics.

**Comment by israel-hdez** [comment]
cc @maltron :)

**Comment by lucasponce** [comment]
I see this issue confusing.
The collection of metrics and send to any place is out of the scope of the project.
This issue should be about the current stats and how that info can be available (configured and documented) to the user.

**Comment by israel-hdez** [comment]
@lucasponce OK, I reworked the description as we already are generating internal metrics. So, I think it's more that the scope of the current internal metrics is so limited, that it's probably almost useless for users to take advantage of it.

**Comment by jmazzitelli** [comment]
> the current internal metrics is so limited, that it's probably almost useless for users to take advantage of it.

FYI: The main purpose of the current metrics was not for users to take advantage of. It was for kiali devs to be able to look at the metric data and see how the server internals are behaving (particularly, we looked to these metrics for performance). It would also be useful for support (supporting end users who might be having performance issues in Kiali - we could use these to help narrow down where problems might be). For example, one of the main drivers for these metrics was to see how efficient/fast the graph generation code was, how the graph generation performs as the number of namespaces grow, and how each appender affected the graph performance. These metrics were highly useful at the time we were using them to initially implement the graph generation.

We should consider exposing the graph generation time metrics within the [kiali Monitoring Dashboard yaml](https://github.com/kiali/kiali-operator/blob/v1.24.0/roles/default/kiali-deploy/templates/dashboards/kiali.yaml) - we already expose the server API times via the dashboard.

Whether users ACTUALLY take advantage of looking at these metrics, I doubt it :) But that's probably because we don't advertise the fact that the metrics exist (other than [here](https://github.com/kiali/kiali-operator/blob/v1.24.0/deploy/kiali/kiali_cr.yaml#L772-L779)).

These metrics were not meant for collecting end-user UI statistics (e.g. what portions of the UI are used the most). Unless we play games with shipping down to the server all the metrics collected in the browser, we would have to do something like use [request classifications](https://istio.io/latest/docs/tasks/observability/metrics/classify-metrics/#classify-metrics-by-request), but that would require customizing the istio proxy config. That seems like an awful lot to have to engineer and maintain just to emit metrics that, frankly, end-users won't care a whole lot about - only the kiali team would care about those metrics (I mean, why would the customer care that they use the "application details screen" 5x more than the "metrics tables" screen)? I suppose response time metrics would be useful here - but we could get that for free with just an istio sidecar.

**Comment by lucasponce** [comment]
Revisit the current internal metrics is a good task.
As @jmazzitelli some of them could be out of the context for 1.24.

But about the initial list, my thought on this is to have a very/ultra lightweight collection (some) of the endpoints, that would be enough info.

Basically user can get benefit to see if fetching one pages take more time than anothers, that's all, I wouldn't go deep.

Also, if this info is collected and available in a lightweight manner, it can be part of the debug info available in Kiali.

Then the user would be able to share that info (if they want) when opening a issue.

**Comment by lucasponce** [comment]
I saw some activity, on this area.
I'd use this issue to scope the tasks:
- Validate if internal metrics are working in major business method used by Kiali.
- Check if internal metrics are well documented and can be easily enabled by users.

Today this feature is not known and probably more than one user can get benefit of it.

**Comment by lucasponce** [comment]
This task can be a good candidate for @nrfox @leandroberetta or @hhovsepy as it is a review tasks if the internal metrics are setup correctly and update/fix missing or wrong reports.

@jshaughn let me know what do you think, if @nrfox has already a backlog I can use this one for @leandroberetta in next days as part of the onboarding process.

**Comment by leandroberetta** [comment]
I checked the metrics starting from each API route (handler) going through business methods and I found the following:

- Every handler is being measured with a middleware in the router, so every API call is measured (observed)
- Each handler calls at least one business method (sometimes none, sometimes more than one), that business method contains code to measure its duration, in the most cases you can map one API call to a business method
- There are cases that there are nested calls to business methods from a handler, any method (function) will be measured independently with no relation to others business methods in the same handler
- Graph metrics are not shown in the Kiali internal metrics dashboard

With the motivation of clarify this metrics to users and help them to understand how they are using Kiali and help us in the case of performance/bug issues my proposal is:

- Reduce the amount of metrics, keeping the measurement in the handlers (every API route) because the majority is a 1:1 call (handler to a business method)
- Create a new issue for a future version to add tracing, instrumenting the parts of the code that are relevant, because it would be easier to follow a trace in the case of a performance issue. Right now for the cases that we have nested calls, it wouldn't be easy to correlate the info gathered by the user
- Add graph metrics to the dashboard
- Change the failures metrics to count the 5xx errors instead of business errors (instead of check the err object, check the response from the handler in the middleware

What do you think?

**Comment by lucasponce** [comment]
> With the motivation of clarify this metrics to users and help them to understand how they are using Kiali and help us in the case of performance/bug issues my proposal is:
> 
> * Reduce the amount of metrics, keeping the measurement in the handlers (every API route) because the majority is a 1:1 call (handler to a business method)
> * Create a new issue for a future version to add tracing, instrumenting the parts of the code that are relevant, because it would be easier to follow a trace in the case of a performance issue. Right now for the cases that we have nested calls, it wouldn't be easy to correlate the info gathered by the user
> * Add graph metrics to the dashboard
> * Change the failures metrics to count the 5xx errors instead of business errors (instead of check the err object, check the response from the handler in the middleware
> 
> What do you think?

+1

It sounds good to me.
Also it can be addressed in a progressive way if at some point you see that the task can grow.
