### ISSUE TITLE
Left bar too wide

### ISSUE THREAD

**Issue by e-minguez** [kiali/kiali#325]
Currently, the left bar only shows 4 options and there is too much blank space. AFAIK in patternfly (bear with me, I barely know patternfly) you can squeeze it to show only the icons (I think is this visual element http://www.patternfly.org/pattern-library/application-framework/masthead/ ), so I think it should be the default to avoid having too much blank space.

**Comment by pilhuhn** [comment]
On 29 Jun 2018, at 10:42, Eduardo Mínguez wrote:

> Currently, the left bar only shows 4 options and there is

You should be able to click on the burger (the 3 stripes in the top 
left) to collapse the menu
-- 
hwr@pilhuhn.de  m:0179/207 4919  b:http://pilhuhn.blogspot.com

**Comment by e-minguez** [comment]
Sure. I was talking about making it smaller by default.

**Comment by pilhuhn** [comment]
On 29 Jun 2018, at 10:56, Eduardo Mínguez wrote:

> Sure. I was talking about making it smaller by default.

I think it is good that it is expanded by default for folks that are new 
to the UI.
It should perhaps (on a per user) basis remember the setting, so that if 
someone
collapses it, it will open collapsed the next time (?)

-- 
hwr@pilhuhn.de  m:0179/207 4919  b:http://pilhuhn.blogspot.com

**Comment by e-minguez** [comment]
Much better option :+1:

**Comment by aljesusg** [comment]
Feat: User preferences horizontal/vertical navigation ^^

**Comment by pilhuhn** [comment]
I have opened https://issues.jboss.org/browse/KIALI-1071 for this.

**Comment by aljesusg** [comment]
Closed by https://github.com/kiali/kiali-ui/pull/497
