### ISSUE TITLE
Wrong workload for kiali-traffic-generator in Traces Spans

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#3306]
In Traces Spans tab, for 'kiali-traffic-generator' the workload is displayed as 'kiali-traffic', which causes wrong linking.

![Screenshot from 2020-10-08 15-37-32](https://user-images.githubusercontent.com/604313/95466591-c889c980-097c-11eb-85e5-b973f2fd8f9b.png)
![Screenshot from 2020-10-08 15-37-16](https://user-images.githubusercontent.com/604313/95466588-c6c00600-097c-11eb-8cac-3983ace24e99.png)

**Comment by lucasponce** [comment]
This is weird, is `kiali-traffic-generator` showed in the list of workloads ?

Which controller uses ?

**Comment by jshaughn** [comment]
I thought it was a replica-set, is it strange?

**Comment by jotak** [comment]
Ok, it seems to come from a regex that parses pod names to guess the workload name out of it. At the moment it won't work with replica sets.
To summarize the problem, we need a regex that is able to extract:

- `mydeployment` from string `mydeployment-123abc-456def.namespace`
- `my-deployment` from string `my-workload-123abc-456def.namespace`
- `my-replicaset` from string `my-replicaset-123abc.namespace`

This is tricky (impossible?) since workload names can contain dashes. My current regex is `/([a-z0-9-.]+)-[a-z0-9]+-[a-z0-9]+.([a-z0-9-]+)/`. Solving case 1 would break case 3, and vice-versa. I fear this will be a known issue that we'll have to live with... or someone has a better idea?

**Comment by jotak** [comment]
Ok perhaps I start to see a solution, as the sequence of generated alphanums is longer in the replica set identifier than in the pod identifier. Not sure how safe it is to rely on that, but it worth it to check

**Comment by lucasponce** [comment]
Perhaps you can add something to help on that logic, if you start this request from a known workload, the workload has info about the pods, that perhaps (if it's not a bad performance increase) could be used to calculated better what to filter (I think).

Just an idea, I know without extra info, it's not an easy problem as there will be always cornercases in naming.

**Comment by jotak** [comment]
it won't solve all the cases, as we're identified workloads all along the trace and not only the one we're focused on.
But I think using length of the generated parts will fix the issue.

**Comment by lucasponce** [comment]
> But I think using length of the generated parts will fix the issue.

Right, the previous trick only works for a single workload. Yes, having this info about the lenght may work, I guess that probably something different may be a corner case that can be applied later.
