### ISSUE TITLE
Alignment issue with Custom TimeRange

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#3350]
The time range component can overlap the tabs on the detail pages.  When using the Custom time range option the problem can hit pretty easily, see here:

![image](https://user-images.githubusercontent.com/2104052/97037747-b8a2e580-1537-11eb-983e-86e38c10e5f1.png)

**Comment by lucasponce** [comment]
I don't think it has an easy workaround.
Main problem here is that component belongs to the tab content instead of the page and it's using floating style to place it there.
Floating style and z-level has some drawbacks when not using same position system, so when using together with other components with different z-level may produce this.

I think this may trigger a major refactor moving this component to the page, not to the tab as it's today, adjusting the current layout there and allowing that when screen is narrowing the component doesn't float but pushes the tabs down.

I'm going to put it on my side as I think it's related to other z-level problems I've found and perhaps we can unify them.

**Comment by jshaughn** [comment]
I actually find it strange to be part of the tab content and not managed by the detail page itself, I think I'm +1 to moving it to the page and probably pushing the settings to the tabs as properties.  It makes sense to me that each tab in the detail page honors the same time range.

Also, Perhaps it should be considered to have this custom range look consistent with the graph replay approach, which is imho, a nicer layout.  My final comment is just a question, what exactly is the behavior of the refresh interval period when looking at a custom range?  Should it be hidden?

**Comment by lucasponce** [comment]
> My final comment is just a question, what exactly is the behavior of the refresh interval period when looking at a custom range? Should it be hidden?

It doesn't make much sense if I'm querying a fixed interval 10:00 AM - 10:30 AM to constant refresh it, yeah, I agree that it can be help here.

This component belonged to the tab logic instead to the page because not all tabs share same parameters here.

I won't touch that (if possible) in this effort, I'll try to address the refactoring keeping the current logic.

**Comment by mtho11** [comment]
Shouldn't the refresh be set to **pause** if one is using a custom timeframe? Sounds like possibly a separate issue.

**Comment by jshaughn** [comment]
@lucasponce @mtho11 , yes, a separate issue.  Either Pause or just omitted completely (which would help with overlap issues).

As for different time ranges on different tabs, even today the setting made on some tabs are  carried over to other tabs, which is great for correlation.  I thought maybe manging the time range(s) from the page may actually make impl easier, but I'm OK to solve this issue any way you see fit.

**Comment by lucasponce** [comment]
Fixed by https://github.com/kiali/kiali-ui/pull/1992
