### ISSUE TITLE
udpate prometheus client

### ISSUE THREAD

**Issue by zackzhangkai** [kiali/kiali#3417]
**Is your feature request related to a problem? Please describe.**

prometheus client is too old , update prometheus client to github.com/prometheus/client_golang v1.8.0

**Comment by jotak** [comment]
Hi @zackzhangkai ,
I see that you've sent already some PRs about this issue, thank you for that. Upgrading the prometheus client is indeed something to be considered. As you see, there is some dependency relations with k-charted lib here. But, note that we are considering moving the k-charted code into the kiali repo directly (or at least, remove the dependency on prometheus client from k-charted). So, perhaps this client upgrade can be done after merge, to reduce the hassle. (cc @lucasponce )
Can I ask you why are you interested in this change? Is it because you are consuming Kiali go code as a dependency? (just to understand the motivation)

**Comment by zackzhangkai** [comment]
@jotak Thanks for your replying. The reason is exactly as what you said.

**Comment by lucasponce** [comment]
Note, I've sent an email to kiali-dev asking for feedback about the proposal to consolidate k-charted into kiali repo:

https://groups.google.com/g/kiali-dev/c/vI-Kg8gXBgs

If no objections we will open an issue about that.
