### ISSUE TITLE
kiali.io build is broken - no updates can be built/deployed to kiali.io

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#3445]
see: https://app.netlify.com/sites/kiali/deploys

```
3:03:16 PM: Building sites … ERROR 2020/11/18 20:03:16 Failed to get CSV resource "https://docs.google.com/spreadsheets/d/e/2PACX-1vQEuJ1_zcsbU5f0wdsZ5ytwyV5h3Q9ufHdc4rqEGnqBvlBNANKqwYyV8YxXJ9qj2gxBzuSMc4zvao5R/pub?gid=0&single=true&output=csv&ts=2676216": failed to parse CSV file https://docs.google.com/spreadsheets/d/e/2PACX-1vQEuJ1_zcsbU5f0wdsZ5ytwyV5h3Q9ufHdc4rqEGnqBvlBNANKqwYyV8YxXJ9qj2gxBzuSMc4zvao5R/pub?gid=0&single=true&output=csv&ts=2676216: parse error on line 3, column 11: bare " in non-quoted-field
3:03:16 PM: Total in 177585 ms
3:03:16 PM: Error: Error building site: failed to render pages: render of "home" failed: execute of template failed: template: index.html.html:13:5: executing "content" at <partial "home/events...>: error calling partial: "/opt/build/repo/themes/kiali/layouts/partials/home/events-latest-section.html:8:47": execute of template failed: template: partials/home/events-latest-section.html:8:47: executing "partials/home/events-latest-section.html" at <index $latestEvent 0>: error calling index: index of untyped nil
Makefile:17: recipe for target 'build' failed
3:03:16 PM: make: *** [build] Error 255
```

I don't know who owns [this Google doc](https://docs.google.com/spreadsheets/d/e/2PACX-1vQEuJ1_zcsbU5f0wdsZ5ytwyV5h3Q9ufHdc4rqEGnqBvlBNANKqwYyV8YxXJ9qj2gxBzuSMc4zvao5R/pub?gid=0&single=true&output=csv&ts=2676216), but it appears it no longer contains a CSV that can be accessed.

**Comment by jmazzitelli** [comment]
This was added here: https://github.com/kiali/kiali.io/commit/ff2d6f8feb7030fd10e48a67f8ff3bdea929bb77

cc @xeviknal

**Comment by mtho11** [comment]
I just ran into this as well with my PR: https://github.com/kiali/kiali.io/pull/329

**Comment by xeviknal** [comment]
Google drive has changed the permissions of that document without notifying. I've re-opened to public.
However I don't like the solution, because in 4 month, google might move it to private.
I need to re-think how to implement that or if it is worth to have that section in the web.
I've created a test pr and I see it is working back. I've also shared with you guys the document, just in case.

**Comment by jmazzitelli** [comment]
Yeah, I agree to move off Google docs as the solution here. Can you put that file somewhere in kiali.io and just refer to it via a github.com URL instead? That way it is in kiali.io git source control and easily referenced via the github URL.

**Comment by xeviknal** [comment]
Moving it into the repo is quite the same as put it directly as html. The idea behind having it into google docs is because the csv is fed from a Google form. So this way we would fetch the latest events in each deploy automatically. That was the whole point.

I guess that the best way then, it is to move this to html and remove the dynamism. It is a bit of going backwards though.

**Comment by mtho11** [comment]
Looks like we are fixed now right?
I re-pushed my changes and everything went well.

**Comment by jshaughn** [comment]
This looks to be resolved.
