### ISSUE TITLE
Kiali OpenID unable to use signing_key from Kubernetes secret

### ISSUE THREAD

**Issue by khankth** [kiali/kiali#3466]
If the signing_key is defined as k8s secret, the kiali OpenID page does not proceed after clicking on "Login with OpenID", following is logged in kiali container:

```
I1125 09:33:27.961512       1 kiali.go:64] Kiali: Version: v1.26.0, Commit: 237953b327b61ae365aae807cade16a7f138d231
I1125 09:33:28.013957       1 kiali.go:153] Using authentication strategy [openid]
I1125 09:33:28.014053       1 kiali.go:85] Kiali: Console version: 1.26.0
I1125 09:33:28.014073       1 kiali.go:237] Updating base URL in index.html with [/kiali]
I1125 09:33:28.014509       1 kiali.go:209] Generating env.js from config
I1125 09:33:28.020272       1 server.go:67] Server endpoint will start at [:20001/kiali]
I1125 09:33:28.020301       1 server.go:68] Server endpoint will serve static content from [/opt/kiali/console]
I1125 09:33:28.020321       1 metrics_server.go:18] Starting Metrics Server on [:9090]
I1125 09:34:36.743845       1 authentication.go:688] Not handling OpenId code flow authentication: No nonce code present. Login window timed out.
W1125 09:34:43.091629       1 openid_auth.go:427] Cannot use OpenId authorization code flow because signing key is not 16, 24 nor 32 bytes long
I1125 09:34:43.173676       1 authentication.go:688] Not handling OpenId code flow authentication: State parameter is empty or invalid.

```

Signing_key is defined as k8s secret:
`kubectl create secret generic kiali-oidc-signingkey --from-literal="oidc-secret=<20 chars>" -n ns `
The signing_key is defined according to defined format in docs, in the kiali configmap as:

```
   login_token:
      expiration_seconds: 28800
      signing_key: \"secret:kiali-oidc-signingkey:oidc-secret\"

```

On the other hand, if the key is **statically** defined in the kiali configmap as:
```
   login_token:
      expiration_seconds: 28800
      signing_key: \"<20 characters>\"   

```
The Kiali OpenID login page redirects to Idp portal and login is **successful**, user is redirected back to Kiali.
Note: Key of length <20 chars is not accepted

Kiali oidc is configured as:
```
   auth:
      strategy: openid
      openid:
        authentication_timeout: 300
        client_id: "kubernetes"
        issuer_uri: "https://<ISSUER URI>"
        username_claim: "email"
        insecure_skip_verify_tls: true
        scopes:
        - "openid"
        - "email"
        - "groups"
        - "profile"   

```

**Versions used**
Kiali: 1.26.1
Istio: 1.7.4
Kubernetes flavour and version: Redhat: **7.8**, Kubernetes:**1.19.2**

**Comment by jmazzitelli** [comment]
You must install Kiali server via the Kiali operator in order to use the "secret:" notation for the signing key.  The [documentation for this "secret:" notation is located in the Kiali CR example file](https://github.com/kiali/kiali-operator/blob/v1.27.0/deploy/kiali/kiali_cr.yaml#L685-L693) - it is only applicable within the Kiali CR/operator installation mode. More specifically, if you installed the Kiali server only via the server helm chart and you set signing key value as "secret:foo:bar" (or you directly set that value by editing the ConfigMap) - it will not take effect the way you think it will. That value's string will literally be the signing key in that case.

_Note: The server helm chart is not a full-featured installer like the operator (whether the operator is installed via helm chart or OLM) - some features that are handled by the operator will be missing from the server helm chart. This is why we only published the server helm chart as a convenient "quick start" method that is meant for first-time users of Kiali. It is to more easily get up and running to demo and kick the tires, so to speak. But we recommend using the operator in more formal, production environments - see [the first sentence in the Quick Start guide](https://kiali.io/documentation/latest/quick-start/)_

With all of that said, you did not indicate if you installed Kiali with the operator - I assume you did not. However, if you did install with the Operator, can you look at the Kiali Deployment and specifically look at the environment variables that are set in the container? You should see a `LOGIN_TOKEN_SIGNING_KEY` environment variable set and it should be taking its value from a ref to your secret. So you should see something like this in the Kiali Deployment:

```
 - name: LOGIN_TOKEN_SIGNING_KEY
   valueFrom:
     secretKeyRef:
       name: kiali-oidc-signingkey
       key: oidc-secret
```

**Comment by khankth** [comment]
Thanks @jmazzitelli for quick feedback!

The installation is done through istioctl(not operator) e-g.
`    istioctl install -f profile/${CLUSTER}/custom-profile.yaml --kubeconfig=${K8S_CONFIG_FILE}`
This then mean we cannot use the k8s secret with our current installation mode.

We do not have the env var **LOGIN_TOKEN_SIGNING_KEY** defined. Perhaps, we can work it around by defining the env var in our kiali deployment and map the secrect as per the snippet your shared?

**Comment by jmazzitelli** [comment]
> We do not have the env var **LOGIN_TOKEN_SIGNING_KEY** defined. Perhaps, we can work it around by defining the env var in our kiali deployment

Yes. If you manually inject that env var into your Kiali deployment (with the secret ref as I indicated in my previous comment), it should take effect.
