### ISSUE TITLE
Kiali reconciliation is stuck 

### ISSUE THREAD

**Issue by FilipB** [kiali/kiali#3468]
**Describe the bug**
Kiali operator is stuck in endless loop after adding 30 bookinfo application namespaces to accessibleNamespaces.

**Versions used**
```
Kiali UI
    1.28.0 (20529cb8e631bde12d782822ace5cec0fcf6cfe1)
Kiali Server
    v1.28.0-SNAPSHOT (2b6eb2037c41750c11d7ad475ed010934e139f13)
Kiali Container
    v1.28.0-SNAPSHOT
Components
Istio
    1.8.0 
Prometheus
    2.21.0 
Kubernetes
    v1.19.0+9f84db3 
```
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9)
OCP 4.6

**To Reproduce**
1. Install Istio 1.8 and the latest kiali operator (from master branch) with the latest kiali (from master branch).
2. Install 30 bookinfo apps and add them to kiali CR spec.deployment.accessibleNamespaces

**Expected behavior**
Reconciliation should be finished.

**Actual behavior**
Reconciliation is stuck: message: Running reconciliation
Kiali UI correctly shows all bookinfo namespaces

Kiali log, kiali cr and operator log attached.
[logs.tar.gz](https://github.com/kiali/kiali/files/5596764/logs.tar.gz)

**Comment by FilipB** [comment]
So the eventually it's finished:
conditions:
    - ansibleResult:
        changed: 0
        completion: '2020-11-25T12:53:32.478204'
        failures: 0
        ok: 507
        skipped: 101
      lastTransitionTime: '2020-11-25T10:22:46Z'
      message: Awaiting next reconciliation
      reason: Successful
      status: 'True'
      type: Running

It just runs very long time.
@jmazzitelli could you please check operator log what is taking so long? If it's expected, please close this.

**Comment by jmazzitelli** [comment]
> * Install 30 bookinfo apps and add them to kiali CR spec.deployment.accessibleNamespaces

For the record, it is `spec.deployment.accessible_namespaces` not `spec.deployment.accessibleNamespaces`

I'm not sure what to say - if it finishes completely and successfully, then it is working right?

If the problem is it took "a long time" - define "a long time". Remember that the Kiali Operator is implemented in Ansible, and Ansible playbooks are definitely going to take longer to do the work as opposed to a Go-implemented operator.

**Comment by jmazzitelli** [comment]
Logs show the expected initial two runs for the reconciliation (it initially runs a second loop due to a quirk in the way the SDK reports dependent resource changes and how the operator needs to generate a random signing key - you will always get two reconciliation runs when you first create the Kiali CR).

The first took 533 seconds to complete, the second 614 seconds.  So it needed roughly 9 to 10 minutes for each loop. The cause of this is almost certainly due to the fact that Ansible operators are just slower than Go operators and due to the extra number of namespaces being deployed (more than what you are probably used to), the Ansible code has to create roles/role bindings/namespace labels for all of them, as well as the operator SDK work happening under the covers for its caching.

**Comment by jmazzitelli** [comment]
FYI: I created this: https://github.com/kiali/kiali/issues/3469

**Comment by FilipB** [comment]
@jmazzitelli thanks for looking into this. Just to add some numbers for "very long". I tried to remove one namespace from accessible_namespaces (so only 29 namespaces were remaining) and it took 26 minutes to finish reconciliation.

**Comment by jmazzitelli** [comment]
@FilipB almost a half hour - ugh. Would you be able to do something to profile and find out where the bottleneck is on your cluster? You can do this (I assume you have a kiali dev environment - if not, you can ignore this message :) :

1. Check out this PR: https://github.com/kiali/kiali-operator/pull/205
2. Build the operator with that PR in place and push it into your cluster (`make cluster-push-operator`)
3. Uninstall any Kiali operator / server you already have and then install it via `make operator-create`
4. Then set this env var in the operator Deployment via `kubectl set env deploy/kiali-operator -n kiali-operator -e ANSIBLE_CONFIG=/opt/ansible/ansible-profiler.cfg`
5. Now you can install your custom Kiali CR.

At this point, the operator will log a profiler report at the end of the log output, and it will tell you the ansible tasks that take up the most time. I'm curious what the report will say when running in your environment - it will tell us where most of the 26 minutes are from.

If you can't do this right now, I'll try to get this merged into master and you should be able to try it with the "latest" image (you would just have to do step 3, 4, 5).

**Comment by FilipB** [comment]
@jmazzitelli I'm not using kiali dev env but I can build and use the operator from PR 205 in my cluster. I will report results to https://github.com/kiali/kiali/issues/3469
