### ISSUE TITLE
when the name of namespace is started with kube, the kiali cannot graph for it .

### ISSUE THREAD

**Issue by zackzhangkai** [kiali/kiali#3478]
**Describe the bug**

when my namespace is started with kube, then kiali cannot graph for it

For UI issues please also add a screenshot that shows the issue.

```
$ k get ns kube-test
NAME        STATUS   AGE
kube-test   Active   149m
```

![image](https://user-images.githubusercontent.com/20178386/100534165-d3f3c580-3246-11eb-875b-86a28c5b2f84.png)

**Versions used**
Kiali:  v1.26.1
Istio: 1.6.10
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9)

**Comment by jmazzitelli** [comment]
This is not a bug. This is working as expected. By default, Kiali will not show any namespaces that start with "kube" because typically those are internal-use only namespaces that are never part of the mesh.

If, for some reason, you want to create namespaces that start with "kube" and put them in your mesh, you can tell Kiali about it by modifying the Kiali CR setting `spec.api.namespaces.exclude` as documented here: https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L95-L114 - in that documented example CR, you can see `"kube.*"` is in the default list of excluded namespaces.

**Comment by zackzhangkai** [comment]
Thanks a lot, it's really helpful for me.
