### ISSUE TITLE
Kiali should not depend on all the labels for creating the graph

### ISSUE THREAD

**Issue by rakesh-garimella** [kiali/kiali#3496]
**Is your feature request related to a problem? Please describe.**

Kiali creates network graphs based on the information it receives from various istio metrics that are being scraped by promehteus. Usually in a production environment we have to drop several labels from these istio metrics in order to reduce the metric cardinality so as to bring the memory usage under control. However the side effect of this is kiali is not able to create graphs.

**Describe the solution you'd like**

In such a scenario it would be nice that we get to see some graphs based on the labels available rather than having no graph at all. 

**Additional context**

The requirements to drop labels from istio metrics comes because of the open [issue](https://github.com/istio/istio/issues/21377) in telemetry V2 where the metrics are not expired anymore.

**Comment by jshaughn** [comment]
As much as I empathize with the situation there is no plan to generate partial or crippled graphs.  The metrics required by Kiali are [listed here](https://kiali.io/documentation/v1.26/faq/#prom-metrics).

Instead of asking Kiali to adapt to partial metrics I think the real solution is to pressure Istio to generate a leaner set of telemetry,  with better expiration handling, such that Prometheus is less likely to get overloaded, and proxies themselves will require less resources.   Kiali actually uses a fairly small subset of the generated metrics.

**Comment by jotak** [comment]
Just, to clarify something: among the labels listed in the documentation, only a few of them are really mandatory. If I'm correct, they are:

`source_workload_namespace`, `source_workload`, `source_canonical_service`, `source_canonical_revision`, `destination_service_namespace`, `destination_service`, `destination_service_name`, `destination_workload_namespace`, `destination_workload`, `destination_canonical_service`, `destination_canonical_revision`, `request_protocol`, `response_code`, `response_flags`.

With just this subset, wouldn't it be fine for you?

If we take a closer look, only a few in this subset really impact the metrics cardinality: it's essentially source / destination workloads, request protocol and response code / flags. The other ones are unlikely to have some impact on the cardinality (which doesn't mean they don't have an impact on the global memory footprint). Things like response code and flags are really some important pieces in Kiali I think, that we cannot/don't want to eliminate.

@jshaughn one thing I can see that wouldn't impact too much the user experience in Kiali, would be to be able to turn off all grpc related stuff, assuming then all request protocol is http, and ignoring the grpc related labels?

**Comment by lucasponce** [comment]
> source_workload_namespace, source_workload, source_canonical_service, source_canonical_revision, destination_service_namespace, destination_service, destination_service_name, destination_workload_namespace, destination_workload, destination_canonical_service, destination_canonical_revision, request_protocol, response_code, response_flags.

Side comment:

Kiali depends on *_principal for other features, like AuthorizationPolicies generation so I'm afraid that list needs to be updated.

**Comment by jotak** [comment]
> Kiali depends on *_principal for other features, like AuthorizationPolicies generation so I'm afraid that list needs to be updated.

They are listed, as non mandatory. Do you mean they are mandatory?

**Comment by lucasponce** [comment]
> They are listed, as non mandatory. Do you mean they are mandatory?

Perhaps I guess "mandatory" here is ambiguos, because, if those are not present, some features should show broken.
Probably in any case that list would need some update.

**Comment by jshaughn** [comment]
@jotak `grpc_response_status` is reported only when `request_protocol="http"` .   So it doesn't really com into play if there is no grpc traffic.  We could actually eliminat the need, in the graph, for request_protocol as we know it is "grpc" when `grpc_response_status` is provided, otherwise "http".  But this is a very minor savings.

The current list on kiali.io does not specify specifically what is needed for the graph and what is needed for other kiali features, and maybe that would be helpful, but if metric pressure is so high as to not be able to provide the relatively small set of metrics and attibrutes we require, I still think it is an indication that Istio telemetry has more fundamental issues around resources needed, both for prom and for proxies.

I think one thing maybe we could push on Istio is an option, possibly a default option, to report only one time-series per request, meaning for one request they generate only source or dest telemetry.  In other words, the the dest proxy always report, but limit the source proxy to report only client-side failures (requests that don't route to a workload (or possibly break the connection).  It would immediately reduce load by about 50%.

**Comment by rakesh-garimella** [comment]
After trying some permutations I find dropping following labels makes the kiali graphs work again for our use case.
```
^(grpc_response_status|request_protocol|source_version|destination_version|source_principal|destination_principal|source_app|destination_app)$
```

**Comment by jshaughn** [comment]
@rakesh-garimella Are you sure about request_protocol, I think that one is required at the moment.  If you check the Kiali lohs you may see messages like "Skipping ... missing expected TS labels ...".  If you see those it means some of your telemetry is being thrown away because it is missing expected labels.

**Comment by jshaughn** [comment]
There is no work planned around this discussion, so closing.  I do still suggest to pressure istio to be more lean in its metric generation.
