### ISSUE TITLE
Don't hardcode istio namespace

### ISSUE THREAD

**Issue by sebastien-prudhomme** [kiali/kiali#350]
"istio-system" is hardcoded in several places and prevents using anything else.

Allow user to setup istio namespace by environment variable.

Also i will suggest that by default Kiali uses the namespace in which it is installed to get Istio services instead of "istio-system".

**Comment by jotak** [comment]
+1, I see several places where it is hardcoded and that must be fixed.

However, just to understand better, is it breaking anything? As far as I can tell, it's going to affect the exclusion of istio infra services from the graph - which was done in order to make it easier to read - but in spite of that, it's still going to "work" though not optimally - Am I correct?

**Comment by abonas** [comment]
So what is the desired change here? I see 2 things proposed unless I misunderstood something:
1. Allow installing Kiali in other namespaces besides istio-system - sounds like the right thing.
2. Assuming that Istio is installed also in the same namespace as Kiali (which per item 1 can be not istio-system) and attempting to make calls accordingly?  If so, this sounds a bit problematic because it is not necessarily true and not necessarily the same personas install them. Perhaps it should be configurable in Kiali where istio is?

**Comment by lucasponce** [comment]
I guess better to start adding "istio-system" from the config, and let modify that at startup.

**Comment by jotak** [comment]
Yeah, we can focus just on having istio installed in another place, but still having Kiali in that same namespace. That would be just a config flag with very few impact.

If we *also* want Kiali to be installed in a separate namespace, there's a little more work to do but I think it's pretty easy too. As I understand it's not the request here.

**Comment by sebastien-prudhomme** [comment]
My use case is having Kiali installed in the same Istio namespace which is not "istio-system" but i see no problem if Kiali can also be installed in another namespace than Istio.

**Comment by jshaughn** [comment]
I think we should stay with installing Kiali in the same namespace as Istio.

**Comment by abonas** [comment]
@jshaughn can you elaborate why? also, how do you ensure this? should the install check Istio's ns automatically?

**Comment by jshaughn** [comment]
@abonas, I guess mainly because we don't have the need to do it so to avoid work.  It's not clear why it would be needed and I think we may hit unexpected issues.  So basically I'm just in favor of meeting the needed use case.

**Comment by christian-posta** [comment]
Definitely should be able to configure the namespace into which Kiali is installed. If it's not too much work, it'd be best to sort out installing Kiali in its own namespace as well. In general, in most orgs, services are deployed into their own namespace and managed independently.

**Comment by abonas** [comment]
@jshaughn @christian-posta I think you are presenting contradicting points as per installing Kiali and Istio in the same namespace or not :)
It will be good to converge on one direction for this.

**Comment by pilhuhn** [comment]
I think that is solved?

**Comment by sebastien-prudhomme** [comment]
@pilhuhn Yes, no more problems
