### ISSUE TITLE
Feature request: support istio multi clusters

### ISSUE THREAD

**Issue by rimusz** [kiali/kiali#356]
Support for istio multi clusters would be a nice feature to have :)

https://istio.io/docs/setup/kubernetes/multicluster-install/

**Comment by abonas** [comment]
Hi, can you please elaborate more on multi clusters use case that you are seeking? It will be very helpful.
What is exactly Istio multi clusters and in which case it is useful to have them supported on one Kiali instance?
Do you mean one Kiali pointed at separate isolated Istio instances (which in turn implies separate openshift/kubernetes clusters) or something else?
CC @pilhuhn @lponce @mwringe

**Comment by rimusz** [comment]
sorry I should included (updated my original comment) the url to it.

**Comment by pilhuhn** [comment]
@rimusz I don't see any url - could you check this? Or just add the url in a new comment?

**Comment by rimusz** [comment]
weird it did not get saved in the original comments at the first time.

https://istio.io/docs/setup/kubernetes/multicluster-install/

**Comment by pilhuhn** [comment]
Thanks @rimusz ! Do you know how in such a multicluster the individual namespaces are handled? E.g. if I have in both clusters a namespace 'fuu' - will that be seen as a global (joint) namespace or two separate ones? But then I probably don't know enough about this yet :)

**Comment by abonas** [comment]
@knrc is multicluster supported in Istio on openshift too?

**Comment by christian-posta** [comment]
@rimusz Are you guys using multi-cluster?

So going forward, that way of doing multi cluster will most likely be replaced with the istio control plane being deployed into each cluster and then federating them. In that case, Kiali would probably be running on one single cluster and pulling information back from the control plane's of each of the clusters involved.

Is that what you're hoping to have supported?

**Comment by knrc** [comment]
@abonas Not at this time, federation has been identified for GA although our priority will be on multi-tenancy

**Comment by knrc** [comment]
@christian-posta +1 there was talk about the groundwork for this landing in 1.0 but I have not yet evaluated it to see how capable it is.

**Comment by christian-posta** [comment]
The ground work is there (Gateway/VirtualService/ServiceEndpoint)... I've not tried recently to do it, but it should work

**Comment by gdoctor** [comment]
@christian-posta are you sure multi cluster is moving in the direction of one control plane per cluster? I see that being very useful for active-active cluster deployments and cluster down resiliency scenarios, but I haven't seen much effort in pushing multi cluster in that direction. 

That being said, most of the data needed to formulate a graphical interface should be available in a single Pilot since it holds the state of the mesh anyway. I attached an example screenshot showing this. The reviews-v3 is in a different cluster from the rest, yet still is listed here. +1 for this feature request.
<img width="1072" alt="screen shot 2018-09-24 at 10 03 37 am" src="https://user-images.githubusercontent.com/5168204/45966859-2a1eab80-bfe1-11e8-9ab8-d0fb1dcdc076.png">

**Comment by gdoctor** [comment]
@christian-posta are you sure multi cluster is moving in the direction of one control plane per cluster? I see that being very useful for active-active cluster deployments and cluster down resiliency scenarios, but I haven't seen much effort in pushing multi cluster in that direction.

That being said, most of the data needed to formulate a graphical interface should be available in a single Pilot since it holds the state of the mesh anyway. I attached an example screenshot showing this. The reviews-v3 is in a different cluster from the rest, yet still is listed here. +1 for this feature request.
![screen shot 2018-09-24 at 10 03 37 am](https://user-images.githubusercontent.com/5168204/45967148-ed9f7f80-bfe1-11e8-8d77-37e18834797e.png)

**Comment by hansanghoon** [comment]
Along with Istio 1.1, **multicluster deployments** is now listed as a one of the concepts of Istio. Hope kiali supports multi clusters.

https://istio.io/docs/concepts/multicluster-deployments/

**Comment by mwringe** [comment]
We have a JIRA to look into multicluster support but its not something we have been working on: https://issues.jboss.org/browse/KIALI-1797

I don't know where this falls on our roadmap. We are an open source project so if someone wants to investigate multicluster support it would be appreciated.

**Comment by pilhuhn** [comment]
See also https://issues.jboss.org/browse/KIALI-2584

**Comment by israel-hdez** [comment]
This is now being tracked in: https://github.com/kiali/kiali/issues/1363
