### ISSUE TITLE
Possibility to overwrite component status url

### ISSUE THREAD

**Issue by tesharp** [kiali/kiali#3631]
**Is your feature request related to a problem? Please describe.**
Prometheus component status is always showing **Unreachable** when using Victoria Metrics as prometheus source. Seems like it is just checking if prometheus url returns http code less than 400. Victoria Metrics returns 400, and therefore always showing **Unreachable**.

**Describe the solution you'd like**
Would be nice to be able to define a custom check url instead of using the prometheus url.

**Describe alternatives you've considered**
No solution atm.

**Comment by jotak** [comment]
Hi @tesharp ,
Thanks for reporting this.
I wonder if, apart from this wrong status, you have other metrics-related issues with Victoria in Kiali, or does everything look fine? I'm asking because I think Victoria is not 100% compatible with prom API / promql, at least that's what I've heard a couple of times.

**Comment by tesharp** [comment]
I've run this for almost 2 weeks now and haven't really seen any other issues so far. Biggest problem was to get the correct metrics labels etc really. Running everything inside istio service mesh (also victoria metrics) it was a bit problematic to get setup correct, but now it is working very nice. I could live with component status showing incorrect, but it is also showing that the service is degraded since part of traffic in mesh is failing. So Id like to solve it somehow so it doesn't show the service as degraded.

**Comment by jotak** [comment]
@xeviknal @lucasponce what do you think? sounds good to you, to make that endpoint configurable? Or perhaps there is another one that could work for both, some "health" endpoint?

**Comment by lucasponce** [comment]
Sorry @tesharp, for some some reason we missed to answer.
I'm +1 to add more personalization to the prometheus check, I understand that users may have a custom prometheus setup and I don't see bad to see how can be used.

Having said that, I know that Kiali is also checking pod status of prometheus, so perhaps it could be good to have an example of setup where we can take a look how to approach that from implementation view.

But I let @xeviknal to comment as he worked a lot of on this feature and perhaps has more info than me.

**Comment by xeviknal** [comment]
@tesharp @jotak I am not very familiar with this prom installation so I might be asking dummy questions.

Right now, the istio component status fetches the very same url that is used for fetching the metrics across the whole kiali project. I understand that this URL is a base URL and it might not work for every p8s deployment to check its healthz, right?

If so, It looks good to me to add a field where let the users specify the `liveliness` probe urls (absolute path).

@lucasponce We stopped checking for pod status a while ago since we had really different p8s deployments which really different installation approaches. Even Prometheus installed outside of the mesh.
