### ISSUE TITLE
Cluster awareness for "Create/Update/Delete Traffic Policies" feature

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#3632]
In the Overview page, we have these options:

![image](https://user-images.githubusercontent.com/23639005/105921912-31b24d00-5fff-11eb-9507-0703e30f9211.png)

In a multi-primary, multi-network setup (multi-cluster) it all works fine.

There are a few things that should be improved:
1. As this options uses the graph data to do it's work, it should show a warning that Kiali will only be able to create traffic policies for workloads in the current cluster. Workloads on remote clusters are not affected by this option.
2. The code should be modified to make it "cluster-safe". Right now, the feature is working OK and this is by chance. Graph edges representing traffic going to remote clusters are not being flagged as secure, and don't have principals attached to them. Because of the missing principals, all is working OK. But if in the future, if Istio improves it's telemetry and start including principals, this feature will break.

**Additional context**
This is true for Istio 1.8. For Istio 1.9 there may be telemetry changes.

Epic #1833

**Comment by lucasponce** [comment]
See https://github.com/kiali/kiali/issues/3633#issuecomment-768110348

**Comment by lucasponce** [comment]
This issue is related to the main discussion:
https://github.com/kiali/kiali/discussions/4081

It requires to define a high level design of how features should work in multi-cluster scenarios.

So, I propose to close this one in favor of the discussion, and reopen it when some of the decisions are progressed.

Note that this is a very active topic in Kiali.
