### ISSUE TITLE
Cluster awareness for "Enable/Disable/Remove Auto Injection" feature

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#3633]
In the Overview page, we have these options:

![image](https://user-images.githubusercontent.com/23639005/105922493-68d52e00-6000-11eb-93f6-887b79f521a1.png)

The feature itself works fine and as designed. However, in a multi-primary, multi-network setup this feature has impact only in the local cluster. People using Kiali in a multi-cluster environment may think that this setting may have effect across all clusters. If possible, there should be a warning message that this option will apply only to the "local" cluster.

**Additional context**
This is only true for multi-primary, multi-network setup. Possibly, this is different when several clusters are being managed by the same control plane (but this setup is yet to be understood).

Epic #1833

**Comment by lucasponce** [comment]
I guess instead of individual issues, we need to put in common the strategy for management in multi-cluster and federation environments.

That was something I was expected.

Then as result of our discussions we can decide what route to follow.

**Comment by lucasponce** [comment]
This issue is related to the main discussion:
#4081

It requires to define a high level design of how features should work in multi-cluster scenarios.

So, I propose to close this one in favor of the discussion, and reopen it when some of the decisions are progressed.

Note that this is a very active topic in Kiali.
