### ISSUE TITLE
Kiali requires port 8080 to be opened on GKE firewall

### ISSUE THREAD

**Issue by dex4er** [kiali/kiali#3679]
**General remarks**

**Describe the bug**
Kiali doesn't work if port 8080 is blocked and then I see following errors in log:

```
2021-02-05T12:48:14Z WRN GetPodProxyStatus is failing for [namespace: echoserver] [pod: echoserver-6c7fddd4c7-ddbqf]: the server is currently unable to handle the request (get pods istiod-78dcc7bc64-7tg25)
2021-02-05T12:48:14Z WRN GetPodProxyStatus is failing for [namespace: echoserver] [pod: echoserver-6c7fddd4c7-vhg9p]: the server is currently unable to handle the request (get pods istiod-78dcc7bc64-7tg25)
2021-02-05T12:48:14Z WRN GetPodProxyStatus is failing for [namespace: echoserver] [pod: echoserver-6c7fddd4c7-ddbqf]: the server is currently unable to handle the request (get pods istiod-78dcc7bc64-7tg25)
```

When port 8080 is unblocked then everything is fine.

It is not strict bug in Kiali but I think it should be mentioned in FAQ as Kiali's prerequisities.

Port 8080 seems to be obsoleted and it replaced with new API available on port 15010 or 15012. I'm not sure if Istio developers will keep this 8080 for long time and I think it is worth of investigation.

**Versions used**
Kiali: 1.29
Istio: 1.8.2
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9)

**Comment by xeviknal** [comment]
@dex4er thanks for opening the issue and letting us know about it.

There is this PR that goes in the same exact position https://github.com/kiali/kiali/issues/3494
We are preparing a couple of PRs for documenting the scenario and preventing the pending request due to the lack of connectivity.

> Port 8080 seems to be obsoleted and it replaced with new API available on port 15010 or 15012. I'm not sure if Istio developers will keep this 8080 for long time and I think it is worth of investigation.

As far as we know, the `/debug/*` endpoints hasn't any `End of Life` schedule. We know that istio team is preparing alternative ways to fetch this information, but they are not still clear which will be the approach.

Do you have more information about the `15010` port? Which endpoints are available there? I haven't noticed there were new endpoints to fetch info from istiod.

I am going to close the PR because it is a duplicate. However, thank you very very much for the time and investigation. You'll see that we've spend a lot of trials for this issue. :rocket:

**Comment by xeviknal** [comment]
Btw, if you want to check the preview of the documentaiton PR here the links:
- https://deploy-preview-347--kiali.netlify.app/documentation/latest/installation-guide/#_google_cloud_private_cluster_requirements
- https://github.com/kiali/kiali.io/pull/347

Feel free to add whatever correction you feel appropiate.
