### ISSUE TITLE
Traces display options are shown then Jaeger is not configured.

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#3698]
Happens on master.
Wrongly configure both urls for traces in kiali configmap.
Error is displayed, but also the Display options are still displayed.
![Screenshot from 2021-02-12 16-50-32](https://user-images.githubusercontent.com/604313/107790210-d0a2ad00-6d52-11eb-8707-f4ace0938252.png)

It is better to hide this options in case for wrongly configure Traces or pod failure.

**Comment by lucasponce** [comment]
+1
Also, perhaps it's time to replace the coloured logo of Jaeger for a similar grey one used in graph and/or charts or empty results :)

**Comment by jotak** [comment]
Note that it doesn't say there's an error here, it says there's no trace. It could be that there are no traces due to the query filters selected, in which case they must still be actionable.
So perhaps the error path should be displayed differently. But: it's possible that there are errors _and_ traces are displayed (because a previous fetch succeeded) so ... not sure how to do :-)
