### ISSUE TITLE
Move away from ingress and use Istio Gateway

### ISSUE THREAD

**Issue by christian-posta** [kiali/kiali#371]
We should use Istio Gateway instead of ingress.

**Comment by dcberg** [comment]
Agreed...

**Comment by abonas** [comment]
Hi @christian-posta , thanks for looking at Kiali.
Can you please clarify a few things:
Do you mean change Ingress to Gateway in Kiali deployment for k8s? Or do you mean also in its openshift deployment change Route to Gateway? 
If so, will users be able to view the route/endpoint in openshift webconsole after moving to Istio gateway? (I might be wrong but it sounds like no)
Can you please give a short background why should it be used instead of the existing objects?
thank you

**Comment by pilhuhn** [comment]
Ping @christian-posta
