### ISSUE TITLE
Kiali website - latest events section is too low

### ISSUE THREAD

**Issue by abonas** [kiali/kiali#3712]
Currently the "latest events" part is at the bottom of the website, for me it required a lot of scrolling, and only because I knew I wanted to search for this section.
IMO it should be bumped to a much higher location so users will notice it.

**Comment by lucasponce** [comment]
This should be incorporated by https://github.com/kiali/kiali/issues/3455
Assuming that no whole re-design is needed, joining the videos section into one would help to this issue.

Otherwise, a change of the sections will trigger move other and at the end it will mean to re-study the design of Kiali.io.

So closing in favor of #3455
