### ISSUE TITLE
Overview Filter Healthy - Shows Failure and Degraded as well

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#3719]
Happens on Kiali master.
In Overview page, show Apps and filter by 'Healthy' ones, but it shows failure and degraded app's namespaces as well.
![Screenshot from 2021-02-18 16-44-51](https://user-images.githubusercontent.com/604313/108382353-07703b80-7209-11eb-8100-7ff21a36e707.png)

**Comment by hhovsepy** [comment]
Is there some delay in calculating health for namespaces?

**Comment by lucasponce** [comment]
> Is there some delay in calculating health for namespaces?

Well, health is fetched in an async call, so, if the backend is slow, it may produce a delay on the frontend, but user should see the "loading" icon in the masthead on those cases.

I'm taking a look to this one.

**Comment by lucasponce** [comment]
I think is working as expected, perhaps because the behaviour is.

- "Filter any namespace with any failure apps"

![image](https://user-images.githubusercontent.com/1662329/109813351-8617a080-7c2d-11eb-9711-1c439dcdab3d.png)

- "Filter any namespace with any degraded apps"

![image](https://user-images.githubusercontent.com/1662329/109813404-962f8000-7c2d-11eb-9a02-c84359f9a39b.png)

I admit that the healthy one may be confusing as it works in the same way:

- "Filter any namespace with any app healthy"

![image](https://user-images.githubusercontent.com/1662329/109813513-c0813d80-7c2d-11eb-89d3-402547648257.png)

Perhaps for this case, it would make sense to show "all apps healthy" which I guess could be the expected behaviour and perhaps that's what triggered the issue.

@hhovsepy let me know what do you think, I can try to add a "all apps healthy" case for this one if it makes sense.

**Comment by hhovsepy** [comment]
@lucasponce I think from customer perspective the Healthy means that all apps are healthy in a single namespace, so +1 on filtering "Healthy" shows only namespaces with only healthy apps.

**Comment by lucasponce** [comment]
> I think from customer perspective the Healthy means that all apps are healthy in a single namespace, so +1 on filtering "Healthy" shows only namespaces with only healthy apps.

+1 I'll prepare a fix for that case, it's safe and it will only affect to the overview which is covering that case (filtering elements with multiple states)
