### ISSUE TITLE
Make the url of the repo configurable in the Ansible Tasks

### ISSUE THREAD

**Issue by sass1997** [kiali/kiali#3753]
**Is your feature request related to a problem? Please describe.**
In a secure setup of a cluster you should prevent access to github directly and use your own tools. Since Kiali Operator isn't able to have the url of the task [Confirm the cluster can access github.com when it needs to determine the last release of Kiali] manual configured we can't use the operator. May the steps on this side can be completely prevented and all the needed sources are already in the operator image. 

**Describe the solution you'd like**
Best solution for me would be as described that this task isn't really needed all the resources are already in the image.

**Describe alternatives you've considered**
Alternatively it would be good to being able to configure this url. Please consider that it has to be possible then to also configure credentials (username/password, ssh-key) etc.

**Comment by jmazzitelli** [comment]
> In a secure setup of a cluster you should prevent access to github directly and use your own tools.

We do. I will explain below. But in short you can prevent access to github directly by configuring the Kiali CR `spec.deployment.image_version` yourself.

> Since Kiali Operator isn't able to have the url of the task [Confirm the cluster can access github.com when it needs to determine the last release of Kiali] manual configured we can't use the operator. 

That task is a no-op [if the image_version configured is NOT set to "lastrelease"](https://github.com/kiali/kiali-operator/blob/v1.31.0/roles/default/kiali-deploy/tasks/main.yml#L397) - same is true with the [other](https://github.com/kiali/kiali-operator/blob/v1.31.0/roles/default/kiali-deploy/tasks/main.yml#L402) [tasks](https://github.com/kiali/kiali-operator/blob/v1.31.0/roles/default/kiali-deploy/tasks/main.yml#L406) that use that url. You can use the operator if you override the default behavior and configure the operator with the version you want (e.g. NOT "lastrelease").

The operator doesn't require you to access github. The only reason why the operator MIGHT access github is to determine what version of Kiali image to pull - but that is only necessary if you have not told the operator what version to use.

Please see this for details (in short, simply tell the operator what version you want and it will not need github access to determine the version):

* https://github.com/kiali/kiali-operator/blob/v1.31.0/deploy/kiali/kiali_cr.yaml#L248-L262

(for completeness, [here](https://github.com/kiali/kiali-operator/blob/v1.31.0/playbooks/default-supported-images.yml#L1) is where you can see the default version being set to "lastrelease" - that's why by default github will be accessed - again, tell the operator what version you want, and this is overridden and github is never accessed)

Here is the only place where the operator accesses github - you can see it ONLY goes here to look up the last release version number (i.e. it only does this when image_version is set to the value "lastrelease"). Note also the operator does NOT pull content or images - it only looks at the github metadata to get the last release number:

https://github.com/kiali/kiali-operator/blob/v1.31.0/roles/default/kiali-deploy/tasks/main.yml#L393-L406

I suggest using a value of `operator_version` [as documented here](https://github.com/kiali/kiali-operator/blob/v1.31.0/deploy/kiali/kiali_cr.yaml#L251) for `spec.deployment.image_version` since it is almost always the case that you want the operator to install the same kiali image version as that of the operator itself. In fact, that used to be the default in the past, but since it is not necessarily the case that the operator version has a peer kiali image version of the same version number, that was changed. Although, today, I believe every released operator version has a peer kiali image with the same version number, so it should be safe to use "operator_version" for this image_version setting.

I will close this github issue since this enhancement request is not needed. Rather than have a github URL be configurable (BTW: what URL would you use? Github is a public service - there is no on-premise private Github service that I am aware of?), you simply configure the version which you want the operator to install. When you do that, there is no need to access github (and indeed the operator will not access github when you tell it what version of kiali to install). Thus, this is all working as expected. If you have a private network that does not want to or cannot access github.com, you can easily use the operator by simply telling the operator what version of the kiali image to install.

**Comment by sass1997** [comment]
Thank you for explaining why this happened. I retrace the issue and I'm able to fix it with setting this variable. May it would be good to have the same version in the default Kiali CR from the operator.

**Comment by jmazzitelli** [comment]
> May it would be good to have the same version in the default Kiali CR from the operator.

As I mentioned in my previous comment, `In fact, that used to be the default in the past, but since it is not necessarily the case that the operator version has a peer kiali image version of the same version number, that was changed. Although, today, I believe every released operator version has a peer kiali image with the same version number, so it should be safe to use "operator_version" for this image_version setting.`

The reason we changed the default away from "operator_version" is because we wanted to leave open the possibility of being able to release a z-stream version of the operator ("x.y.z" where "z" is increased from the previous release -- this would be in the case of, say, a very bad bug or a security vulnerability fix) without then having to ask all users to not only use that latest z-stream version of the operator but to also then have users modify their Kiali CR (to override that default of "operator_version" which would then break because there wouldn't be a kiali image with version x.y.z).
