### ISSUE TITLE
OIDC Auth Redirect not working

### ISSUE THREAD

**Issue by arctiqaurora** [kiali/kiali#3762]
I enabled OIDC auth login on Kiali, when using implicit flow, kiali works fine. When using auth code flow, it is redirected to OIDC login but ends up with the same login page:

<img width="823" alt="Screen Shot 2021-03-10 at 9 11 20 AM" src="https://user-images.githubusercontent.com/60113774/110642093-ae992080-8180-11eb-8f9e-ebc134092ff6.png">
<img width="823" alt="Screen Shot 2021-03-10 at 9 12 57 AM" src="https://user-images.githubusercontent.com/60113774/110642445-0899e600-8181-11eb-879a-99d37373d866.png">
<img width="823" alt="Screen Shot 2021-03-10 at 9 14 10 AM" src="https://user-images.githubusercontent.com/60113774/110642480-0fc0f400-8181-11eb-8bbf-e67f133d2268.png">

**Versions used**
Kiali: v1.30
Istio: 1.7
Kubernetes flavour and version: Google Anthos on VMWare 1.5.0

**To Reproduce**
1. Configure Kiali with OIDC login, set up signing_key with 24 bytes string
1. Go to kiali UI
2. Click on `Log In With OpenID`
3. Continue with OIDC login
4. Page is redirected back to the login page. 

**Expected behavior**
User should be logged in to Kiali Dashboard

More details: [Discussion board](https://github.com/kiali/kiali/discussions/3745#discussioncomment-427121)

**Comment by arctiqaurora** [comment]
FYI here's the network capture: 
<img width="875" alt="Screen Shot 2021-03-12 at 2 11 23 PM" src="https://user-images.githubusercontent.com/60113774/110987377-fbc1f180-833c-11eb-84aa-c60b3641fce5.png">
I see a `/` being appended after `/kiali`

**Comment by arctiqaurora** [comment]
Is this planned to be fixed in the next release?

**Comment by israel-hdez** [comment]
I think it's possible to work on this in the next week and can be fixed for the upcoming v1.32 release.
It's not a promise, though.

**Comment by israel-hdez** [comment]
@arctiqaurora @matthiasdeblock
Although I have a PR to fix the unneeded redirection, I'm a little doubtful about if that will fix the issue.

After looking closely at @arctiqaurora browser network capture, I see the redirection is still carrying query string parameters. So, the request should still trigger authentication. What calls my attention is that I see some data being loaded from browser cache. So, there is some chance that the browser cache (or any reverse proxy in the middle) is being conflictive.

I'd suggest you to disable your browser's cache and see if that fixes the issue. If not, the redundant redirection is anyway going to be fixed in next Kiali version and, hopefully, that may solve the issue.

**Comment by arctiqaurora** [comment]
Just tried disabling the cache, unfortunately it is not fixing the issue. Will wait for the new release.
