### ISSUE TITLE
Uppercase app label crashes app detail view - Kiali v1.31

### ISSUE THREAD

**Issue by ahsanqaisar** [kiali/kiali#3776]
Describe the bug
I am getting "Sorry, there was a problem. Try a refresh or navigate to a different page." when click on object under Application Tab in Kiali UI

Kiali UI
1.31.0 (faa0a96400cd1b712a13a29f65cc34c270eed386)

Kiali Server
v1.31.0 (26ce4585311ddba9e66a06c3746c9f21c8900aee)

Kiali Container
v1.31.0

Components
Istio
1.8.1

Prometheus
2.22.0

Kubernetes
v1.18.12-gke.1210

Grafana URL
N/A

Jaeger URL
N/A

To Reproduce

Go to Application
Click on any object listed under Application
See error above

![image](https://user-images.githubusercontent.com/73361295/111345112-587e1e80-8653-11eb-96ff-4e04ccb6bc88.png)

![image](https://user-images.githubusercontent.com/73361295/111345166-66cc3a80-8653-11eb-8cb1-3da4ebd92384.png)

**Comment by jmazzitelli** [comment]
> To Reproduce
> Steps to reproduce the behavior:
> 
> Go to Application
> Click on any object listed under Application
> See error above

No one else has reported this and I do not see this behavior - so just going to any object under Application isn't the only thing that would trigger this (otherwise, everyone would be seeing this). There must be something else happening under the covers.

Can you look in your kiali server pod and see what types of log messages you see related to this (perhaps an error message?)

How did you install? Operator? Or just the server helm chart?

**Comment by ahsanqaisar** [comment]
Yeah Thanks! Fixed it. I was using uppercase in the app label which was causing issues.

**Comment by jshaughn** [comment]
Thanks for the feedback @ahsanqaisar , we will definitely look into why that would cause such bad behavior.

**Comment by jmazzitelli** [comment]
What was the exact label (key and value) that caused it. That will help us narrow it down and replicate/fix it.

**Comment by ahsanqaisar** [comment]
Here is the app label I was using - `INTL.CANADA.ASVE.application-v1.dev` When I inspect it through dev console (on chrome), I was getting toUpperCase exception. Changed the label to lowercase which did the trick for me
