### ISSUE TITLE
[Performance] Significant performance drop on /api/namespaces/graph endpoint

### ISSUE THREAD

**Issue by FilipB** [kiali/kiali#3787]
**Describe the bug**
Test which is hitting following endpoint:
`/api/namespaces/graph?namespaces=bookinfo,bookinfo2&graphType=service&duration=600s`
is showing significant performance drop (increased mean response time).

It's caused by following commits:
1e4b7dc021e301f7bcdff825b0a9d4ab3a5c4a83
6610f85f967faa5c51865bfbcb7d53d38a6bfed7

Mean response time when hitting that endpoint from 20 users on earlier kiali build (e55048674fb76fec19186b625326f82d34234eec) is 847 ms. After 6610f85f967faa5c51865bfbcb7d53d38a6bfed7 it was increased to 1168ms and after 1e4b7dc021e301f7bcdff825b0a9d4ab3a5c4a83 it was increased to 1623.
Those two commits are causing 100% increase in mean response time.

We need either to approve those changes and accept the performance cost or revisit and try to improve the performance.
I will be adding more tests for different graph types.

**Versions used**
Kiali: the latest master (4c4a3)
Istio:     1.9.1 
Kubernetes flavour and version: (e.g. OpenShift Origin 3.9)
OCP 4.7

**Comment by lucasponce** [comment]
In a first thought I see some kubernetes resources that it would be nice to put them into the cache as well as part of the strategy.

**Comment by jshaughn** [comment]
I can understand a possible drop due to https://github.com/kiali/kiali/commit/1e4b7dc021e301f7bcdff825b0a9d4ab3a5c4a83.  I'm not sure it's avoidable in any simple way.  To capture more comprehensive traffic telemetry we need to fetch a significant amount of overlapping source and destination telemetry, and then filter away duplicated traffic.

As for https://github.com/kiali/kiali/commit/6610f85f967faa5c51865bfbcb7d53d38a6bfed7, we may want to involve @israel-hdez , because it may be due to "home cluster" detection.  I think this should only need to happen one time and the value then cached, so if we are re-calculating each time then there would be a hit.

As an aside, it can be useful to understand how much time is spent in base graph generation and how much is time is spent in the appenders.  We generate these stats already.  But, if you are measuring independently of the stats be aware that `/api/namespaces/graph?namespaces=bookinfo,bookinfo2&graphType=service&duration=600s` is running all appenders, and so it represents something of a worst-case time.  Actually, worst case would probably also add `&injectServiceNodes=true`.

To test without running any appenders you can add `&appenders=`

**Comment by israel-hdez** [comment]
I think we can add a _cache_ to the `ResolveKialiControlPlaneCluster` function, and that would solve the introduced performance loss in https://github.com/kiali/kiali/commit/6610f85f967faa5c51865bfbcb7d53d38a6bfed7. It will be only the first call that will take longer, but the mean response time should improve.

**Comment by israel-hdez** [comment]
And for https://github.com/kiali/kiali/commit/1e4b7dc021e301f7bcdff825b0a9d4ab3a5c4a83, my only idea is to fetch telemetry in parallel by using goroutines. TBH, I don't like this, because we add pressure to Prometheus which I think it's bad in web apps.

**Comment by jshaughn** [comment]
@israel-hdez I agree, we don't want to use parallel queries into Prometheus, it will just add pressure on prom.   We may want to look at unifying the fetches used for both graph gen and health determination, but that's a larger effort.  For now, I think if we can at least add the caching, which I think is straightforward.

@FilipB We'll close this when the caching goes in.  Any downgrade in perf due to https://github.com/kiali/kiali/commit/1e4b7dc021e301f7bcdff825b0a9d4ab3a5c4a83 is currently acceptable.  But hopefully the caching will help a bit.

**Comment by FilipB** [comment]
Confirming that 1894f resolves this problem. After 1894f the response time is back to ~ 847 ms.

**Comment by jshaughn** [comment]
Thanks @FilipB , that's excellent news.
