### ISSUE TITLE
More cluster badging needed

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#3879]
Currently in the graph and graph side-panel it is very hard to know the cluster of remote-cluster nodes if cluster-boxing is not enabled.  We need to add PF-badging when appropriate.

**Comment by lucasponce** [comment]
Probably out of this PR only, but I see this weird:
![image](https://user-images.githubusercontent.com/1662329/115883069-ab66a500-a44d-11eb-875f-6878219b5db0.png)

I understand it, as I created that example, and I see that ServiceEntry belongs to that namespace because is where the definition lives, but to move it to an unknown cluster sounds weird. I understand that is because it comes from telemetry, but I wonder if there is a different possibility of wording.

Anyway, I know probably is unrelated to this work but I leave a note here to not forget.

**Comment by jshaughn** [comment]
@lucasponce Service Entry handling is a constant work in progress.  Looking at this I agree with you, a service entry should not have an unknown cluster as it's supposed to be associated with a service, which itself is in a cluster.  It may be exported to 1..N namespaces, but those namespaces should all be within a cluster.  We need to figure out if why this is "unknown", it could be a problem in Istio as part of the SE definitions returned from k8s, or it could be a problem in Kiali making a proper assignment of the cluster.  I'd probably lean towards the latter case and maybe a missed case in the recent cluster work on our side.  

I think this actually deserves it's own Bug issue.  I will create one...
