### ISSUE TITLE
Wrong Health info at Service level

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3904]
In an scenario where a service have several workloads, and some of them don't have sidecars, there is a wrong health information reported as this:

![image](https://user-images.githubusercontent.com/1662329/115227640-02e4d800-a111-11eb-8b64-8ea696fe697b.png)

But there are traffic activity:

![image](https://user-images.githubusercontent.com/1662329/115227752-2ad43b80-a111-11eb-91c6-77ae1637ef43.png)

It looks like a bug.

Note that health UI is being refactored (a little bit the presentaiton) in the context of https://github.com/kiali/kiali-ui/pull/2122 but I think the bug is independent of the logic as I can see it in previous work.

**Comment by lucasponce** [comment]
Co-asigned this issue to @hhovsepy and @lucasponce
This one can a good one for Hayk to catch up with the code and getting familiar with this logic.

**Comment by hhovsepy** [comment]
The issue comes from this logic: "s.IstioSidecar = mPods.HasIstioSidecar()" in service.go.
Which means that if any of pods belonging to this service does not have a sidecar, then consider this service without sidecar, thus no health information can be available. This happens in both service list and details page.
Question is: Should we consider health on service where not all workloads have sidecars?

**Comment by lucasponce** [comment]
> Question is: Should we consider health on service where not all workloads have sidecars?

Yes, I think if we have a service but 2 workloads in the mesh and 1 out the mesh, from "Kiali" perspective the health should be used with the mesh workloads as those will have telemetry.

**Comment by lucasponce** [comment]
Closed by https://github.com/kiali/kiali/pull/4092
