### ISSUE TITLE
add securityContext in kiali-operator helm chart

### ISSUE THREAD

**Issue by mickael1026** [kiali/kiali#3918]
**Is your feature request related to a problem? Please describe.**
We have some security constraint in our K8s cluster that enforce some securityContext parameter to be set for all deployment.
The minimums are  :

        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true

**Describe the solution you'd like**
Define basic securityContext or add a helm parameter to define some securityContext in https://github.com/kiali/helm-charts/blob/master/kiali-operator/templates/deployment.yaml
allowPrivilegeEscalation: false and runAsNonRoot: true should not have any impact as the operator is running with UID 1001

**Additional context**
Should be nice to also make the operator working with readOnlyRootFilesystem: true 
The operator is running with GID 0, it should also be nice to run as non root gid if possible.

**Comment by jmazzitelli** [comment]
related (or at least is a companion) to https://github.com/kiali/kiali/issues/3810

**Comment by jmazzitelli** [comment]
unassigning @israel-hdez since this does not involve the work he is doing with https://github.com/kiali/kiali/issues/3810
We will implement this separately.

I suspect all we need to do is add this securityContext to the kiali-operator deployment:
```
securityContext:
runAsNonRoot: true
allowPrivilegeEscalation: false
readOnlyRootFilesystem: true
privileged: false
capabilities:
  drop:
  - ALL
```

**Comment by jmazzitelli** [comment]
Well, for the record, ansible operator base image requires writable filesystem - so we can't use readOnlyRootFilesystem=true... this error occurs otherwise:
```
{"level":"error","ts":1621350243.0242796,"logger":"reconciler","msg":"Unable to generate kubeconfig","job":"6129484611666145821","name":"kiali","namespace":"kiali-operator","error":"open /tmp/kubeconfig383419091: read-only file system"
```

**Comment by israel-hdez** [comment]
@jmazzitelli Perhaps you could mount a volume on `/tmp`?
I think it just wants some place to store data (rather than to let the whole pod "unsecured")

**Comment by jmazzitelli** [comment]
@israel-hdez I'm not sure. There might be other places it wants to write - I didn't try to work around that /tmp issue to see if there was something else its writing. Since this issue was written to just create some basic security constraints (specifically mentioning securityContext.allowPrivilegeEscalation and securityContext.runAsNonRoot) we can leave this as-is for now. Later if we find we need read-only root filesystems, we can do more investigation. I'm just getting in some low-hanging fruit here by simply adding a securityContext section with no other changes required.
