### ISSUE TITLE
[helm] server helm chart for loglevel is wrong

### ISSUE THREAD

**Issue by rwong2888** [kiali/kiali#3922]
https://github.com/kiali/helm-charts/blob/master/kiali-server/templates/deployment.yaml#L93

should be {{ .Values.deployment.logger. log_level }} as per
https://github.com/kiali/helm-charts/blob/master/kiali-server/values.yaml#L47

**Comment by jmazzitelli** [comment]
This is not a bug - this is correct.

This is code that was introduced for backward compatibility for older versions that used numbers instead of strings for log level. 

See: https://github.com/kiali/helm-charts/blob/master/kiali-server/templates/_helpers.tpl#L35-L44

As you can see there, the template uses `.Values.deployment.logger.log_level` but ONLY if you did not have set the older `Values.deployment.verbose_mode` value. Because some users have older helm chart values files, we wanted to support them without asking them to rename the verbose_mode setting and change from number to string. So we support both.

Please see PR that introduced this here: https://github.com/kiali/helm-charts/pull/15/files

And here is the server side code that supports this: https://github.com/kiali/kiali/blob/v1.33.0/log/log.go#L121-L150

**Comment by jmazzitelli** [comment]
Feel free to re-open this if you think there is still a bug in this part of the code.
