### ISSUE TITLE
Show cluster names when the number of cluster is > 1

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#3955]
This extra "Kubernetes" labels make no sense on single cluster meshes.

![image](https://user-images.githubusercontent.com/1662329/116361884-c3e60f00-a801-11eb-8a02-349434d195a6.png)

![image](https://user-images.githubusercontent.com/1662329/116361930-d102fe00-a801-11eb-927d-6e0b461445d3.png)

![image](https://user-images.githubusercontent.com/1662329/116361962-d82a0c00-a801-11eb-953e-0938c34ce96e.png)

I understand that may make sense when Kiali is under a multi-cluster scenario but I don't see correct to bring this info when that's not the case.

**Comment by jshaughn** [comment]
Hmmm, it's maybe not the easiest thing to solve using a `> 1` sort of logic.   Perhaps the home cluster should simply never be shown.  I'll revisit this again.

**Comment by jshaughn** [comment]
@lucasponce Which Istio version were you running?

**Comment by jshaughn** [comment]
I think part of the reasoning here was due to the "unknown" cluster, which was showing up in my tests and so it sort of made sense to show the discriminator.  Istio is now assigning a cluster name, "kubernetes", by default.  And often times there is also the "unknown" cluster, so you end up with 2 clusters, even in a "single cluster" env.
