### ISSUE TITLE
need to change the default kiali server image installed by the operator

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#3968]
Last year we changed [the default kiali image the operator will install from "operator_version" to "lastrelease"](https://github.com/kiali/kiali-operator/blob/v1.33.1/playbooks/default-supported-images.yml#L1). To see the reason for that change, see https://github.com/kiali/kiali/issues/2666

This isn't great because if we release a new Kiali server that requires new or different permissions, or requires new/different CR/ConfigMap settings, an old operator that is installed will now attempt to install that new Kiali server and errors will result.

The workaround to that problem used to be simple - we just tell people to set the ["spec.deployment.image_version" field in the Kiali CR](https://github.com/kiali/kiali-operator/blob/v1.33.1/deploy/kiali/kiali_cr.yaml#L250-L264) to the old Kiali Server version that is supported by the old operator.

However, very recently, we added a feature that does not allow the user to set this image_version field (for security purposes). This feature can be turned off, but it is enabled by default. See:

* https://github.com/kiali/kiali/issues/3865
* https://github.com/kiali/helm-charts/blob/master/kiali-operator/values.yaml#L51-L55

So we need a solution here for the user who downgrades an operator and wants to also downgrade the kiali server (and usually, the user wants to downgrade to the same version of kiali server as the operator - so if operator v1.40 is installed and you want to downgrade to operator v1.39, you will most likely want to install kiali server v1.39 as well).

Now, the main reason for the change from `operator_version` to `lastrelease` as the default kiali server image to install was because it became at least theoretically possible that the kiali operator and kiali server versions would diverge (e.g. we could release an operator but not a server, or vice versa). In reality, this has not happened yet and there is no plans for this to happen.

So, the first solution we could do is simply revert that change so the operator's default image goes back to "operator_version". So if you downgrade to operator v1.39, it will by default install kiali server v1.39 - if you downgrade to v1.38, it will by default install kiali server v1.38.  This is the simplest solution.

A second solution could be to simply document how the user can override the default image the operator will install using the [RELATED_IMAGES environment variables](https://github.com/kiali/kiali-operator/blob/v1.32.0/playbooks/kiali-deploy.yml#L29-L43). This is more complicated because it requires action on the user's part and requires a complex command to execute if we want to document a command-line option to do this. I just want to point out this second option simple to put it out there, but I don't think we should do this. I think we'll just go with the first option and revert back the default to "operator_version".

**Comment by jshaughn** [comment]
After a long discussion on Slack it seems like this will be fine.  Here are the gory details:

Jay Shaughnessy  1 hour ago
So what about the situation like downstream where a single operator is responsible for multiple versions?  The 2.0.3 operator installs 2.0.3 or 1.1.13 ?

John Mazzitelli  1 hour ago
this won't effect downstream at all because we don't rely on the defaults set in that playbook file - instead we rely on the environment variables that override the defaults:  https://github.com/kiali/kiali-operator/blob/master/manifests/kiali-ossm/manifests/kiali.clusterserviceversion.yaml#L282-L289
This RELATED_IMAGES stuff is required also because that is how OSBS is able to pin our tags to the SHAs of the brew builds. It's magical.

Jay Shaughnessy  45 minutes ago
OK, so this is only the upstream operator we're talking about

John Mazzitelli  44 minutes ago
it will only affect upstream yes

Jay Shaughnessy  43 minutes ago
I would agree that lastrelease doesn't seem like a great idea because for compatibility you would in fact potentially need to update your operator anyway.  In general it would seem a bad idea to ever try to install a kiali newer than the kiali operator you have

Jay Shaughnessy  42 minutes ago
if anything you would expect an operator to be able to manage an equivalent version, or possibly an earlier version if it had some sort of backcompat ability.

Jay Shaughnessy  38 minutes ago
I suppose it could also be compatible with a newer server, but to try and install it by default seems like a bad idea.  BUT, we do need patch releases to update automatically, what happens there?

John Mazzitelli  36 minutes ago
with the way it is now, patch releases are picked up by default because the patch release is the new "lastrelease". With this proposed way, we would need to release an operator/helm chart with the patch release. But, as I mention in the issue, we do this anyway. I cannot recall a time when we released JUST a Kiali Server but did not also at the same time release a Kiali Operator. They are released in lock-step today.

John Mazzitelli  35 minutes ago
so users would update the operator patch release to pick up the kiali server patch release (its a basic upgrade)

John Mazzitelli  34 minutes ago
(note this doesn't affect users of the upstream Istio addon yaml because that uses yaml produced by the server helm -chart - so there is no operator to deal with this .. so this is moot for those users)

Jay Shaughnessy  32 minutes ago
right, but it would affect upstream users that installed via our operator

John Mazzitelli  30 minutes ago
yes. they would need to upgrade the operator as opposed to what they would do now (and that is - delete their Kiali CR and re-create it - forcing the operator to install a new kiali server (the "lastrelease" and thus getting the patched image. Honestly, I think people would just upgrade the operator and think they are getting the patch rather than know to delete and re-create the CR.

Jay Shaughnessy  30 minutes ago
They would need to delete kiali (the current operator) and install a new one, or manually enable the image change ability and then change the image to the new patch version?

John Mazzitelli  29 minutes ago
yes. Or just use helm's "upgrade" feature to move up to the new operator (rather than delete it and install a new one - which is fine, too, you can do that if you want).

John Mazzitelli  27 minutes ago
in fact, now that I think about it - I think just doing a helm upgrade might just do everything - no need to muck with the Kiali CR - because when the helm upgrade is done, I'm pretty sure it means a new operator pod will be deployed (the old one removed) which causes the new operator to immediately/automatically run a reconciliation - and thus cause Kiali server to be upgraded. So a helm-upgrade to the new patched operator is all that is needed.

Jay Shaughnessy  27 minutes ago
so one question I have is how a user could know which kiali images are compatible with an operator version.  In theory you would not have to update the operator just to pick up a patch release, or to downgrade.  You would just need to enable the manual image specification and change the image.

John Mazzitelli  25 minutes ago
they woudl have to ask us :slightly_smiling_face: yes, it is not trivial to know this. I would say in theory you MIGHT not have to update the operator, but some cases, even in a patch release, it will be required (think of a patch release that requires a new permission added or a new configmap setting is added or changed?)
So, I think its best to just always say, "upgrade the operator, its safer"

John Mazzitelli  24 minutes ago
This is the OLM model, too. You upgrade operators in OperatorHub to pick up new operands

John Mazzitelli  23 minutes ago
(i.e. go to OpenShift Console's OperatorHub page, and upgrade the operator if you want to upgrade the actual operand software)

Jay Shaughnessy  23 minutes ago
with OLM you get the operatr update magically and so you're good to go

John Mazzitelli  23 minutes ago
right.

Jay Shaughnessy  23 minutes ago
for upstream why use the operator as opposed to helm?

John Mazzitelli  23 minutes ago
but what I'm saying is - in OLM there is no option to just pull in a new operand version - you have to update the operator to get it

Jay Shaughnessy  23 minutes ago
for the auto-pod restarts?

John Mazzitelli  22 minutes ago
upstream users use operators for the same reason downstream users do

John Mazzitelli  22 minutes ago
I mainly say its for multitenancy support.

John Mazzitelli  21 minutes ago
(one operator can install N kiali instances)

Jay Shaughnessy  21 minutes ago
all of the same version

John Mazzitelli  21 minutes ago
yes

John Mazzitelli  21 minutes ago
unless you configure the operator's RELATED_IMAGES :slightly_smiling_face: but that's an advanced topic

John Mazzitelli  20 minutes ago
but yes - in reality - all the same verison

Jay Shaughnessy  20 minutes ago
well we definitely don't want to manage an operator compatibility matrix.  so, it seems like a more sane and simple thing to just say Operater X.Y.Z manages Kiali X.Y.Z and they will always match.  It may also manage other versions that are strictly controlled by RELATED_IMAGES

John Mazzitelli  19 minutes ago
yes

Jay Shaughnessy  19 minutes ago
but that is mainly managed but us for the downstream, right?

John Mazzitelli  19 minutes ago
we just have to always release in lock-step (operator and server) with the same version number. but we have always done that and I don't see us changing that

John Mazzitelli  19 minutes ago
RELATED_IMAGES is really for downstream only.

Nick Fox  18 minutes ago
Is there any reason to have spec.deployement.image_version then?

Jay Shaughnessy  18 minutes ago
so, in reality the versions managed by an operator release are fixed, and for upstream it will always be a 1:1

John Mazzitelli  18 minutes ago
@nfox yes, it is really helpful, at minimum, for our QE folks who many times publish internally a brew build of our server so they can test it. So they need a way to tell the operator to pull from their internal quay repo

John Mazzitelli  17 minutes ago
but it is also useful for users who may have a special need to tell the operator to pull a specific version (for example, we may build a patch fix for someone in the community and put it up on quay and ask them to test it - this is how they can do that)

John Mazzitelli  16 minutes ago
"hey, Mr. Community Guy - I think I fixed your bug, can you test it by pulling quay.io/jmazzitelli/kiali:bugfix123"

Nick Fox  16 minutes ago
Could they not install the patch the same way they'd install a normal upgrade by just upgrading the operator?

Nick Fox  15 minutes ago
To the patch version

John Mazzitelli  15 minutes ago
sometimes its easier to set a version in the CR (as opposed to installing a whole new IIB in their OpenShift and installing a new patched operator).

John Mazzitelli  14 minutes ago
It is a real pain to upgrade an operator in OpenShift because of the way OLM does things

Nick Fox  14 minutes ago
:thumbsup: gothca

Jay Shaughnessy  14 minutes ago
so, would this change affect the canary release/revision stuff in any way?

John Mazzitelli  13 minutes ago
i don't see how that canary stuff would be involved, unless I am missing something.
That involves Istio versions, not kiali versions

Nick Fox  12 minutes ago
Yeah I don't think that process would change at all unless we are talking about canary versions of kiali

John Mazzitelli  12 minutes ago
right - definitely NOT talking about canary versions of kiali.

Nick Fox  7 minutes ago
The compatibility matrix was definitely a concern when operators were managing databases but that was mostly for client compatibility. If your operator used v3.0 of a database client and you had v2.0 CRs in your cluster you'd probably have problems.

John Mazzitelli  3 minutes ago
yeah, this is why upstream we are trying to keep it 1-to-1 (operator version to kiali version) and we don't want to support multiple kiali versions in the operator upstream. Downstream we do it with multiple ansible playbooks (that's why under the operator's "role" folder we have the different versions - its how we have one operator support the different kiali versions supported in OSSM (e.g. v1.12 and v1.24). We have been fairly lucky in being able to support multiple versions with a single CR schema (well, its not luck - its why we dont have a true schema in our CR :slightly_smiling_face: we don't want to have to support multiple versions of the CR)

Jay Shaughnessy  2 minutes ago
OK, so this seems like a reasonable change but in addition to the code change I'd like a review of the installation docs on kiali.io.  Let's make sure this is clear because it should be pretty straightforward now that there would be a 1:1 operator-kiali version sync.  Then we should point out spec.deployment.image_version , how to enable the ability to specify a special version and why it's a bad idea in general, for security.

John Mazzitelli  < 1 minute ago
I can do that... just a new section in the "Installation Guide" page or FAQ entry? (I'm thinking former, but I don't care)

Jay Shaughnessy  < 1 minute ago
In the install guide
