### ISSUE TITLE
Application Traffic - some outbound traffic is not shown

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#3974]
Happens on master using bookinfo with activated mongodb.

In graph page, the TCP traffic flow from ratings-v2 to mongodb is shown.
![Screenshot from 2021-05-03 09-48-40](https://user-images.githubusercontent.com/604313/116852615-f1adc800-abf4-11eb-9b6e-6ea20e87a7c9.png)
Also in mongodb application, the inbound traffic from ratings-v2 is shown. as well as in mongodb workload.
![Screenshot from 2021-05-03 09-49-30](https://user-images.githubusercontent.com/604313/116852630-f6727c00-abf4-11eb-938d-2c9e4ffd2310.png)
![Screenshot from 2021-05-03 09-49-46](https://user-images.githubusercontent.com/604313/116852648-fc685d00-abf4-11eb-8699-abf2cf8ffdc3.png)

**Issue**:
But in ratings app, the outbound traffic to mongodb is not shown:
![Screenshot from 2021-05-03 09-51-06](https://user-images.githubusercontent.com/604313/116852730-2457c080-abf5-11eb-8818-b95c1795e3e7.png)

**Comment by jshaughn** [comment]
I had a bunch of env problems today but managed to finally recreate this at the end of the day.  I'll take a look.    In addition to this issue I noticed something a little strange in the Overview tab for an App.

@lucasponce  Did we mean to show a versioned-app graph for the mini-graph, as opposed to an app graph?  I think it's OK if we used versioned app graph, but what does not seem correct is the way we have ratings-v1 selected in the graph below.  I would think it should be the entire app box.  I know this tangential to this issue, but just asking here:

![Screenshot from 2021-05-03 17-09-55](https://user-images.githubusercontent.com/2104052/116934134-8b479a80-ac32-11eb-9284-e5045a6146ec.png)

**Comment by jshaughn** [comment]
This is a regression due to the Overview tabs refactoring PR. Specifically, [this line](https://github.com/kiali/kiali-ui/commit/6bdefa08b66623eaf5bf26a27fc5706ab949ff14#diff-1557fcf43df0f40e6bbbfc0a1e6e2ec9cc96d8392b0799f29b7de428dc6a7025R254).   The Traffic tab was not designed to itself aggregate traffic, it had assumed single edges to/from the node-of-interest,  in this case an app node.  By changing to a versionedapp graph the aggregation is lost and we ended up just seeing the traffic for one of the reviews nodes.  So in fact the inbound is also wrong.

I think it's good to have the versionedApp for an application mini-graph, it gives nicer detail. So I'm not going to revert that for this fix.

**Comment by lucasponce** [comment]
> @lucasponce Did we mean to show a versioned-app graph for the mini-graph, as opposed to an app graph? I think it's OK if we used versioned app graph, but what does not seem correct is the way we have ratings-v1 selected in the graph below. I would think it should be the entire app box. I know this tangential to this issue, but just asking here:

Yes, the minigraph in the app details only showed the box but now that we show the workloads I think the versioned app is more correct, it adds more information for the app. And you're right, I missed to fix the focus, good catch.
