### ISSUE TITLE
Upgrade kubernetes/client-go version and update beta interfaces for workloads

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#4042]
A lot of warnings on Kubernetes 1.21 clusters like this:

```
W0524 13:55:34.638105  209600 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
```

Worth to review the beta apis used for k8s in Kiali

**Comment by jmazzitelli** [comment]
We also have this (has 2 PRs that I'm waiting to figure out a good time to merge): https://github.com/kiali/kiali/issues/3706

The problem to watch out for --> we cannot switch to a new api version IF that new api version was introduced AFTER the earliest k8s version we support. Otherwise, we'll immediately not be able to run on those earlier k8s versions.

For example, if we are using "v1beta1" and k8s v1.19 added api version "v1", we can't switch away from v1beta1 until we no longer support k8s v1.18.

**Comment by lucasponce** [comment]
I'm revisiting this one.
I guess we could use this issue to upgrade the client-go dependency that we have:

Kiali tries to get in sync with Istio code https://github.com/istio/istio/blob/master/go.mod#L104

Also the original description of the issue could be addressed updating the beta interface used for CronJob controllers.

So, the scope would be reduced to those two tasks.
