### ISSUE TITLE
Consolidate Dashboards CRDs into main Kiali config, also handled via Kiali Operator

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#4057]
Custom Dashboards is a feature that allows Kiali to extend the metrics tabs with specific dashboards definitions [1].

This isssue doesn't touch the business of the feature but it proposes a change in the implementation of the definitions.

I think it could be good to move the defaults definitions into the regular Kiali config, also managed via helm/manual or via the operator.

So, same definitions populated via the kiali moniroting API could be found from the config.

[1] https://kiali.io/documentation/latest/runtimes-monitoring/

**Comment by jmazzitelli** [comment]
I have not thought about this a lot, so I have no firm opinion. But just to point out the "pros and cons":

PRO: This will make the implementation and installation of the dashboards much easier.
CON: But this will make the Kiali CR (or helm values.yaml, if using helm) much larger and complex for the end user to manage.

If I had to choose right now what do to, I would say, yes, let's do this. In fact, if we do this, it solves [a problem we have today](https://github.com/kiali/kiali-operator/pull/313#issuecomment-841528868) with managing multiple instances of Kiali in the same namespace. I'll repeat what I said over there, just to have it documented in this issue:

===

This is a rare edge case. The following will not be handled gracefully, but can be worked around.

If you elect to install multiple Kialis in the same deployment namespace, the dashboards you enabled in each Kiali CR will overwrite each other. This is fine when installing multiple Kialis, since dashboards have the same spec content whether installed by one or N Kiali instances. The problem is when you remove one Kiali CR to uninstall the one Kiali instance, the dashboards will be removed, thus all other Kiali instances will see them disappear.

The workaround is fairly simple - just tell one Kiali CR to install the dashboards again (to do this, you can simply touch the Kiali CR, thus forcing the operator to run a reconciliation). Another alternative is the user manage the dashboards manually by creating them outside of having the Kiali operator deploy them (this is how you would do it, for example, if you have your own custom dashboards, anyway).

There is talk about changing the way dashboards are published/deployed, so I won't spend any time trying to make this work more gracefully. And, again, this is only a problem if you want to install multiple Kialis in the same namespace and then you delete only one of them and want to keep the others.

**Comment by lucasponce** [comment]
Thanks @jmazzitelli for the feedback.

Yes, I'd like to see the pros/cons, today it's not a feature that is broadly used, so probably the "defaults" values could be ok (even if not present in the config), and having the possibility to adjust them in some scenario may help to simplify the installation without the CRDs / APIs.

The cons is to add more things into the Kiali CR, but as most of the defaults are "just ok" the tradeoff could be positive.

**Comment by jmazzitelli** [comment]
> so probably the "defaults" values could be ok (even if not present in the config), and having the possibility to adjust them in some scenario

Yes. That could work. Have some hardcoded defaults for all the known dashboards (but perhaps do not put them in the normal `config.go` -- put them in some other place for just the dashboard defaults since it will be a large default - maybe even just put the yaml we already have in some folder that the server can access), but be able to override existing defaults or add new ones directly in Kiali CR.

Note that we can keep the current Kiali CR settings that we already have - these can be useful:

1 - [exclude/include list](https://github.com/kiali/kiali-operator/blob/v1.34.0/deploy/kiali/kiali_cr.yaml#L198-L209) - so the user can even disable some of the hardcoded dashboards just by entering their names here.
2 - [disable all dashboards](https://github.com/kiali/kiali-operator/blob/v1.34.0/deploy/kiali/kiali_cr.yaml#L436) - so the user can just completely turn off the dashboard feature if they want.

Those are still going to be useful (we would just have to change the semantics of the exclude/include lists - those today are names of the yaml files (e.g. `vertx-server.yaml`), but if we implement this new feature, those could just be the names of the dashboards (e.g. `vertx-server`).

**Comment by jmazzitelli** [comment]
I'm working on a PoC to see how hard/easy this would be and what it would look like

**Comment by lucasponce** [comment]
> I'm working on a PoC to see how hard/easy this would be and what it would look like

Thanks Mazz.
Let me know if I can help you.

**Comment by jmazzitelli** [comment]
As part of this, I'm going to remove the monitoringdashboard CRD entirely (from the [operator helm chart](https://github.com/kiali/helm-charts/blob/v1.35.0/kiali-operator/crds/crds.yaml#L1-L22) and [server helm chart](https://github.com/kiali/helm-charts/blob/v1.35.0/kiali-server/crds/crds.yaml#L1-L22) and the OLM metadata for the [community](https://github.com/kiali/kiali-operator/blob/master/manifests/kiali-community/1.35.0/kiali.monitoringdashboards.crd.yaml) and [upstream](https://github.com/kiali/kiali-operator/blob/master/manifests/kiali-upstream/1.35.0/kiali.monitoringdashboards.crd.yaml) operator).

This means that users of upstream releases of the operator must use the operator's default ansible playbooks - they won't be able to set `spec.version` to anything other than `default` (i.e., they can't specify the other values of `v1.12` or `v1.24`) - but this is OK because those versions of Kiali are no longer supported upstream, and the vast majority of Kiali users never set `spec.version` anyway.

That said, if, for some odd reason, someone does need to fallback to one of those earlier `spec.version` values, they only have to install that CRD manually and things should work. They could do this via `kubectl apply -f https://raw.githubusercontent.com/kiali/helm-charts/v1.35.0/kiali-server/crds/crds.yaml`

**Comment by jmazzitelli** [comment]
I have the PoC working.

The related PRs:
* https://github.com/kiali/kiali/pull/4059
* https://github.com/kiali/kiali-operator/pull/326
* https://github.com/kiali/helm-charts/pull/81
* https://github.com/kiali/kiali.io/pull/380

There is one thing that changes by removing this feature - before it was possible to have dashboards in different namespaces so you could create them where ever you wanted and have the associated only with a specific app. Now we just have one global set defined in the server across all namespaces in the mesh. Personally, I never knew we had that feature and I am skeptical that many people use that feature (if they even know about it). So this will probably have minimum effect on people, but we will have to document it in release notes or somewhere like that.

This change seems to allow the operator to run faster, too (because now we don't have to wait for the CRD to be ready and all the dashboards to be created).

**Comment by jmazzitelli** [comment]
> I will do some more testing.

I can see the  Go and Kiali metrics in the custom dashboards:

![image](https://user-images.githubusercontent.com/2029470/120707564-7e63d400-c488-11eb-8fa1-32f58994d756.png)

You will know you have this new stuff if you see this debug message get logged as soon as the server starts:

```
2021-06-03T20:28:15Z DBG Custom dashboards [count=20, enabled=true]: envoy,go,kiali,
micrometer-1.0.6-jvm,micrometer-1.0.6-jvm-pool,micrometer-1.1-jvm,microprofile-1.1,
microprofile-x.y,nodejs,quarkus,springboot-jvm,springboot-jvm-pool,springboot-tomcat,
thorntail,tomcat,vertx-client,vertx-eventbus,vertx-jvm,vertx-pool,vertx-server
```

If you set to `false` the `spec.external_services.custom_dashboards.enabled` field (this was already an existing setting), then no dashboards will be enabled:
```
2021-06-03T20:31:06Z DBG Custom dashboards [count=0, enabled=false]: 
```

And you will not see any custom dashboards:
![image](https://user-images.githubusercontent.com/2029470/120708245-55900e80-c489-11eb-8108-e7386e2a3d11.png)

**Comment by jmazzitelli** [comment]
There is one thing that changes by removing this feature - before it was possible to have dashboards in different namespaces so you could create them where ever you wanted and have them associated only with a specific app in that namespace. Now we just have one global set defined in the server across all namespaces in the mesh. Personally, I never knew we had that feature and I am skeptical that many people use that feature (if they even know about it). So this will probably have minimum effect on people, but we will have to document it in release notes or somewhere like that. This feature is mentioned in this snippet on the [kiali.io docs page](https://kiali.io/documentation/latest/runtimes-monitoring/#_create_new_dashboards) where it says, `To make the dashboard resources available cluster-wide, just create them in Kiali namespace (usually istio-system). Else, they will be available only for applications or workloads of the same namespace. In the case where the same dashboard name exists in a specific namespace and in Kiali namespace, the former takes precedence.`

**Comment by lucasponce** [comment]
> Personally, I never knew we had that feature and I am skeptical that many people use that feature (if they even know about it). 

Yes, perhaps even in the config if needed it can be defined an optional map with namespace as a key to define a specific per namespace if needed (health config has a similar pattern), in that case that would help.

One basic test scenario would be this:

https://github.com/kiali/demos/tree/master/runtimes-demo

So to me the test would be:
- Envoy Metrics are present in regular sidecar workloads.
- Kiali workload has the specific Go + Kiali Metrics tabs.
- An extended example like the Runtimes Demo presents no visible regressions.

The feature to personalize the CRD per namespace can be addressed as commented but to me it's ok to not include it in this first round unlesss something basic seems broken.

(by the way, ping me when you think the PoC is ready and I can give it a try from my side as well and helping to spot any problem)

Thanks again !

**Comment by jmazzitelli** [comment]
> The feature to personalize the CRD per namespace can be addressed as commented but to me it's ok to not include it in this first round unlesss something basic seems broken.

I agree. What will probably happen is no one will notice :) So we might not have to do that at all.

> (by the way, ping me when you think the PoC is ready and I can give it a try from my side as well and helping to spot any problem)

I moved all the PRs out of "draft" - they are ready for people to review now. All unit tests and molecule tests pass; my quick smoke tests show things working (I just verified that Go + Kiali metrics show up on the Kiali workload page). I will now go through that [runtimes examples](https://github.com/kiali/demos/tree/master/runtimes-demo) to see how it works.

**Comment by jmazzitelli** [comment]
This is what I see when running the runtimes demo - not sure if this is all correct - the quarkus one has some JVM ones but no Quarkus specific dashboard. Is that right?

nodejs:
![image](https://user-images.githubusercontent.com/2029470/120814235-ac92f380-c51c-11eb-890e-3325a7a284a2.png)

springboot:
![image](https://user-images.githubusercontent.com/2029470/120814359-ca605880-c51c-11eb-8922-925785c3b68a.png)

vertx:
![image](https://user-images.githubusercontent.com/2029470/120814447-e106af80-c51c-11eb-8f37-52e352da05df.png)

quarkus:
![image](https://user-images.githubusercontent.com/2029470/120814482-e9f78100-c51c-11eb-9327-2508beb79083.png)

**Comment by lucasponce** [comment]
Yes @jmazzitelli it's what I have by default in master, I remember the quarkus default only has JVM ones.

**Comment by jmazzitelli** [comment]
I added a molecule test to confirm the API works from the client perspective. All testing looks good.

The PRs are ready for review and merge:
* https://github.com/kiali/kiali/pull/4059
* https://github.com/kiali/kiali-operator/pull/326
* https://github.com/kiali/helm-charts/pull/81
* https://github.com/kiali/kiali.io/pull/380

**Comment by vbergbauer** [comment]
We have been using MonitoringDashboard custom resources so that multiple teams can create dashboards independently and deploy them along with their applications without contention on the centrally managed Kiali configuration.
I don't see how to do this with this change.

**Comment by lucasponce** [comment]
Thanks for the feedback @vbergbauer.
The goal of this change was to centralize the configuration in Kiali for this feature.

For personalization at namespace and/or pod level one trend we is to use the annotations as a way to consolidate personalized config.

Could you give us more details of your use case ?

- I mean, can the Kiali CR operator persona manages the templates ?
- You'd have a personalized template per namespace ? meaning that i.e. the same template would be different depending on the namespace which is read ?

Again, thanks for letting us know, the goal was not feature change, but a way in how to configure them, so yes, this brings a regression for the personalization level.

[1] https://istio.io/latest/docs/reference/config/annotations/

**Comment by vbergbauer** [comment]
Hello @lucasponce ,
This is our use case:
Our applications are composed of multiple microservices developed  by multiple developers across multiple teams and deployed independently.
Many of these services have custom metrics attached to them:
- OperationId derived from OpenAPI specs and implemented as per-workload Envoy filters
- Custom metrics implemented in code with libraries like OpenTelemetry
- Custom metrics from co-deployed external probes that constantly measure workloads

The author of a service will typically implement Prometheus recording rules and alerts as well as Grafana dashboards. We actually have standardized Helm charts to help create SLI rules and dashboards.

Kiali is popular with our developers because it provides the ability to drill down from a graph to specific workloads.
It then makes sense to have a simplified dashboard per workload, possibly with a link to a more comprehensive Grafana dashboard.

Take a trivial example, like a dashboard of latency per operation ID within a service:
![image](https://user-images.githubusercontent.com/8659572/124357259-3dbebe00-dbe0-11eb-9012-50eced93868b.png)

Both Grafana and Prometheus have mechanism to decentralize the authoring and deployment of service-specific artifacts:
- PrometheusRule (or ThanosRuler) for Prometheus rules
- ConfigMap with "grafana_dashboard" labels for Grafana dashboards
The MonitoringDashboard CRD provided us with the same functionality for Kiali.

So, what mechanism do  you propose to support these workflows?

**Comment by lucasponce** [comment]
Thank you @vbergbauer for the detailed explanation, we really appreciate the feedback about how Kiali features are used.

The MonitoringDashboard CRD was moved into the main Kiali CR to consolidate the configuration and also simplify the management of the installation/configuration.

But you are right, it was introduced that regression in this iteration as commented https://github.com/kiali/kiali/issues/4057#issuecomment-854480502 that is pending to address.

Following same pattern that Istio, Kiali started to move personalization of the global config to the Workload annotations (a health is an example [1]), so we could follow same way here, then if a MonitoringDashboard is defined for all Kiali, it can be added in the Kiali CR as it happens today, or if a Workload needs to personalize one, it could be added in a similar was as Istio overwrites this config, here in [2] you have an example.

With that feature I think the personalization feature would be back, we could propotype something and get your feedback about it.

[1] https://github.com/kiali/kiali/blob/master/models/health_config.go#L8
[2] https://github.com/kiali/demos/blob/master/travels/travels-v2.yaml#L15

**Comment by vbergbauer** [comment]
Thank you @lucasponce 
Indeed defining custom dashboard via annotations on the workload would be consistent with Istio's approach and would work for us.

**Comment by lucasponce** [comment]
Thanks @vbergbauer I cc-ed you in the PR that is being used to address this.
I slighty changed the proposal moving the template annotation from the workload to the namespace to keep consistency with the MonitoringDashboard CRD.

Workload already support kiali annotations to point to the references of the templates that are typically shared in that namespace.

I put an example in the PR, feel free to jump with comments or testing, if it's something missing, just let us know.

**Comment by vbergbauer** [comment]
Hello @lucasponce 

Workloads (deployment, statefulset) were the correct place  to attach custom dashboards, since each workload can have its own Swagger file and its own application-specific custom metrics.

Also, in our current system, namespaces are centrally allocated for each team and environment and are not meant to be modified by every team's CI/CD pipeline (besides, adding/editing annotations on an existing namespace with Helm is not simple).

I don't mind having annotations at the namespace too, but we do need them at the workload level (like Istio's [proxy.istio.io/config](https://istio.io/latest/docs/tasks/observability/distributed-tracing/configurability/#using-proxy-istio-io-config-annotation-for-trace-settings) annotation)

**Comment by lucasponce** [comment]
Ok.

So, we can support boths, note that current implementation of the MonitoringDashboard CRD works sharing a template per namespace level, and annotation a Workload with the Dashboard reference.

But +1 with your proposal, it may also search into the workload annotation, probably that would make your use case clean.

And also namespace annotations can be used in scenarios where you have too many workloads with same template.
