### ISSUE TITLE
gRPC Streaming traffic

### ISSUE THREAD

**Issue by emcake** [kiali/kiali#4070]
**Is your feature request related to a problem? Please describe.**
We run a large number of gRPC bidi streaming services talking to each other over long-lived streams, and wanted to use Kiali for observability. At the minute this doesn't show up in the metrics that kiali uses to show gRPC traffic. We see one request on completion where this may consist of many hundreds of messages.

**Describe the solution you'd like**
Istio concurrently exposes message stats under `istio_request_messages_total` and `istio_response_messages_total`, and some rudimentary prometheus querig looks like they would produce suitable metrics.

I think adding it as a new traffic type (gRPC streaming?) and logging message counts would work, and I can see the approximate location (https://github.com/kiali/kiali/blob/master/graph/telemetry/istio/istio.go#L82) where streaming traffic sniffing could be added. Then it comes down to how to represent this on the UI - I think this could either be summed into gRPC traffic or represented as a different type. The former is probably simpler and doesn't require choosing between gRPC and gRPC streaming for visual representations (e.g traffic animations).

 I may experiment with replacing my request_total messages with the sum of these two, just to see something in the traffic, but it'd be great to see it correctly implemented so that I could see both requests and message stats.

**Comment by lucasponce** [comment]
Hi @emcake, side comment, I have a gRPC example what we use for testing the protocol in Kiali:

https://github.com/kiali/demos/tree/master/fraud-detection

Would you mind to take a look ?
I'd like to check that is a "valid" example that we can use to model your feature.

Thanks

**Comment by emcake** [comment]
Possibly yeah, it looks like you'd get stats from `istio_response_messages_total`. By and large we are using long-lived gRPC streams with low-N requests messages and high-N response messages.

**Comment by jshaughn** [comment]
@emcake OK, so I guess istio_requests_total is only incrementing at the end, but istio_request_messages_total/istio_response_messages_total increments whenever messages are initiated on the existing stream.  I don't see those metrics locally, but that may be because I don't have this scenario.  Are those metrics enabled by default in Istio, or did you have to configure them explicitly?

You are on the right track with the changes, although it wouldn't be trivial.  We'd likely have to add an option to calculate grpc edge rates via the alternate metrics and then perform several more queries, generating the edges from the different metric source.

**Comment by emcake** [comment]
> Are those metrics enabled by default in Istio, or did you have to configure them explicitly?

I'm on istio 1.9.5, they appear to be on by default and in the [latest documentation](https://istio.io/latest/docs/reference/config/metrics/) are listed as part of the 'standard metrics'.

>  so I guess istio_requests_total is only incrementing at the end, but istio_request_messages_total/istio_response_messages_total increments whenever messages are initiated on the existing stream

yeah, this is what I'm seeing locally. I agree that the current grpc tracking model doesn't quite fit with the streaming model - it leads to some interesting results, like request durations taking an hour (!) and response codes not quite mapping correctly. I have some (truly awful) prom config locally that, as a POC, remaps `istio_request_messages_total` and `istio_response_messages_total` onto `istio_requests_total` and I can confirm it comes up with sensible numbers of requests per second (if you interpret that as messages) and the traffic animations look fine, but most of the other sparklines aren't informative at all.

As a proposal, what if bidi gRPC streaming was a 'new protocol' type that used `istio_request_messages_total/istio_requests_total` and `istio_response_messages_total/istio_requests_total` as edge rates? Health and duration are probably still probably based on request status codes, but an update to `(request|response)_messages_total` without a change in the last observed response code is likely still a healthy service. 

The logic that chooses between gRPC/HTTP/TCP now has one extra layer, to choose whether to use bidi-streaming views instead of plain gRPC views, where you can have an arrow with two points and little dots going both ways (or two arrows pointing in a cycle).

I'm happy to hack around and prototype something, if someone can point me at where the display picking/logic happens?

**Comment by jshaughn** [comment]
Right, definitely standard metrics, I wasn't seeing it only because I didn't have any gRPC traffic.  I'm starting to think we need a variety of new options to offer users more flexibility on the "Request Rates" that they see.  Today, as you say, we offer only the `istio_requests_total` rate for gRPC.  But the streaming support is needed and there really are two varieties, request and response message counts.   Similarly, for TCP we offer only sent bytes.  But there is also received bytes, as well as opened and closed connection counts.   Users should likely be able to choose from all of these options how they want the edges labeled for rates.  One issue is that it's not just about the graph, there is is also the Health aspect.  And other charts, etc.   We don't have to do everything at once but we do need to offer sane views.

With respect to the graph it's important to understand that the graph IS a traffic graph.  So the choices made for rates will affect the graph being seen.  If there is no traffic (rate == 0) for the time period then the edge won't show up in the graph (unless showing idle edges).

One othe thing about allowing the user to choose options would be the ability to deselect a protocol, so perhaps ignore TCP and/or HTTP completely if it's not relevant.  That could actually be a time-saver for graph-generation.

Let me play a little with gRPC traffic to take a look at the streaming/message count stats...

**Comment by jshaughn** [comment]
@emcake , it looks to me like all gRPC traffic generates entries in `istio_requests_total`, `istio_request_messages_total` and `istio_response_messages_total`.  I think the `istio_requests_total` entries happen only when the request ends, and so for streaming you may get a lot of message count increments before you see even 1 request count increment for `istio_requests_total`.  That makes `istio_requests_total` fairly useless for getting a rate for a long-running stream in Kiali, unless you are using large time periods to catch the entire streaming window.  Does this match your experience?   Using `istio_requests_total`  is fine for generating rates for short-lived, non-streaming, gRPC edges.  But message rates seem necessary for streaming.  The tricky thing is that only `istio_requests_total` provides the gRPC status codes.  What I'm afraid of is ending up with two edges for every grpc connection, one for "parent" requests and one for the message rates.  But the other fear is not getting any edge at all for streams because of the long request time and very low counts.

Still thinking about it, it seems we're going to need some options for folks to tell kiali what they are interested in, because there is also the additional load involved with querying several metrics.

**Comment by emcake** [comment]
Yeah, this matches my experience.

One change to the underlying proxy could be to tract requests started?
Therefore ‘requests in flight’ could be requests_started - requests_total.

**Comment by emcake** [comment]
Raised https://github.com/istio/istio/issues/33408 as a suggestion for the istio proxy

**Comment by emcake** [comment]
I think short-term just picking one to drive graph generation would be sufficient. Likely I think you’d want to pick between requests_total and request_messages + response_messages. 

Noting your thread on #3730 about tcp. It strikes me the way this works multi-protocol is to have the presence of a graph edge driven by connections, and the traffic rate driven by requests/responses or sent/received bytes. As an aside we also use Kafka and see similar behaviour with our tcp edges.

**Comment by jshaughn** [comment]
@emcake I am going to investigate the idea for optionally choosing how to determine the traffic rates.  The Kafka use-case was what originally prompted that related TCP issue, same sort of problem where just considering sent-bytes can be insufficient.  I'll let you know how it goes, thanks for your feedback.

**Comment by jshaughn** [comment]
@emcake If you are still interested, there will be an enhancement in Kiali 1.38 allowing greater flexibility when determing with traffic will be used to generate the Kiali graph.  You can now opt for messages as opposed to requests, either sent/received, or both.  For TCP you now also have the option of sent/received bytes, or both.  I am hoping this solves the issues around the graph, and streaming.

**Comment by emcake** [comment]
@jshaughn That sounds awesome! I'll be sure to give it a try.

**Comment by jshaughn** [comment]
@emcake If/When you get a chance to try 1.38 I'm curious to know how if the bi-directional gRPC option for traffic does in fact address your needs...
