### ISSUE TITLE
Circuit Breaker Badge is missing in the Graph

### ISSUE THREAD

**Issue by pbajjuri20** [kiali/kiali#4076]
Reproducing steps:

1. deploy upstream Istio
2. bookinfo
3. oc apply -f https://github.com/kiali/kiali/blob/master/hack/istio/bookinfo-reviews-v1-cb.yaml -n bookinfo

I'm able to see the Circuit Breaker Badge in the side panel and missing in the graph.

![cb-missing1](https://user-images.githubusercontent.com/55099523/121079209-dc096080-c7a7-11eb-9cb1-92a1d4eab822.png)

**Comment by nrfox** [comment]
This is a case where all "traffic routing" badging (circuit breaker, request timeouts...) is lumped under Virtual Services and hidden/shown by the presence of a virtual service in the node data, `hasVS`, and the show/hide toggle, `showVirtualServices`, even though circuit breakers exist on the Destination Rule object and not the Virtual Service.

In this bug there is a circuit breaker present but no virtual service present. Still you would expect to see the circuit breaker badge on the graph when "show virtual services" is toggled on especially since the node summary panel shows the circuit breaker present.

Maybe the "show virtual services" toggle could be renamed something more generic like "show traffic routing" since it's not specific to virtual services anymore?

**Comment by jshaughn** [comment]
> Maybe the "show virtual services" toggle could be renamed something more generic like "show traffic routing"

I agree that "show virtual services" isn't quite right.  I'm OK if we leave it because the CB case is sort of an outlier.  But if we change it I don't think "show traffic routing" is correct because not everything has to do with routing, like timeouts.  Maybe more like "show traffic management".
