### ISSUE TITLE
Kiali Developer API documentation is not available now

### ISSUE THREAD

**Issue by DInuwan97** [kiali/kiali#4114]
https://kiali.io/documentation/latest/developer-api/

I have done through with above reference. But URL is not found.
Is it going to be fixed?
Then does Kiali API no longer exsit?

**Comment by jshaughn** [comment]
Hi @DInuwan97 , We have removed the Kiali API from kiali.io because the API is not now, nor has it been in the past, a supported API.  Meaning, it is subject to change at any time.  But, the API does remain fairly stable and for any interested devleoper you can now find the API doc checked into github at https://github.com/kiali/kiali/blob/master/kiali_api.md.

**Comment by DInuwan97** [comment]
Thanks for the support 👍
