### ISSUE TITLE
fix support matrix now that 1.7 is EOL and we use 1.8 things

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#4154]
Istio 1.7 is EOLed: https://istio.io/latest/news/support/announcing-1.7-eol/

Kiali [now supports workloadgroup features introduced by Istio 1.8](https://github.com/kiali/kiali/pull/4024). If you try to run with 1.7 it has been reported that Kiali spits out some errors about not being able to find workloadgroups.

We should update our kiali.io docs support matrix to indicate Kiali 1.35 and up no longer support Istio 1.7.

**Comment by jshaughn** [comment]
@jmazzitelli Yes, we can update the matrix.  Our matrix covers Istio version that are out of support because the reality is that users use the older versions.  But we don't test against those old versions so we don't really catch these sorts of problems.  But we can make an update given the feedback.
