### ISSUE TITLE
accessible_namespaces regexp is not working

### ISSUE THREAD

**Issue by Yorkerrr** [kiali/kiali#4191]
If I try to specify regexp in deployment.accessible_namespaces, it does not filter namespaces

```
    deployment:
      accessible_namespaces:
      - 'example.*'
```

Related Logs:
`
2021-07-19T17:04:55Z WRN Kiali has an accessible namespace [example.*] which doesn't exist
`

**Versions used**
Kiali: 1.37
Istio: 1.10.2
Kubernetes flavour and version: AKS 1.20

**To Reproduce**
- Update kiali configmap to add
```
    deployment:
      accessible_namespaces:
      - 'example.*'
```

- restart kiali pod

**Expected behavior**
Expected result:
Kali fetches istio configuration in namespaces: example-dev, example-qa, etc.

Related Logs:
`
2021-07-19T17:04:55Z WRN Kiali has an accessible namespace [example.*] which doesn't exist
`

**Comment by jmazzitelli** [comment]
> * Update kiali configmap to add

This is not a bug and is expected. The regex is ONLY supported by the Kiali operator and within the Kiali CR. The docs [here](https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L11-L12) and [here](https://kiali.io/documentation/latest/installation-guide/#_accessible_namespaces) that talk about the [accessible_namespaces](https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L184-L192) (and its regex) are for the Kiali CR. Information here in the Kiali CR gets translated into the Kiali ConfigMap but is it not a direct one-to-one for some of these settings. Accessible namespaces is one of those settings.

This is one reason why we suggest people use the operator and not the server-helm chart (or the demo addon yaml that ships with Istio) - because the operator will be able to do things based on Kiali CR settings that the server itself cannot do.
