### ISSUE TITLE
Move React-scripts and node-sass to dependencies

### ISSUE THREAD

**Issue by aljesusg** [kiali/kiali#4201]
In the build process we use node-saas and react-scripts

https://github.com/kiali/kiali-ui/blob/e612ba03baee852257e82f2e505dfe645a756b0d/package.json#L38-L40

we use node-sass and react-scripts packages to perform the tasks. It makes no sense to have them in devdependencies. https://github.com/kiali/kiali-ui/blob/master/package.json#L103

On the other hand cachito not support devdependencies for yarn[1] so we should move them to dependencies

[1]- https://github.com/release-engineering/cachito#feature-support

**Comment by jshaughn** [comment]
>  It makes no sense to have them in devdependencies.

As I understand it, after talking about it in the call, the devDependencies is currently listing everything not needed for running Kiali.  It is a combination of dependencies used for building and testing Kiali.   If Cachito is ignoring the devDependencies and trying to use only the production dependencies for building, then yes, that's a problem.   Unfortunately there is no breakdown like Prod/Build/Test.

We have used the devDependencies to keep the build-deps so that we don't bloat the production deps in the containers (I think) and also to be able to ignore CVEs that are only in the dev-deps (even if they are needed for builds).

It sounds like Cachito should better support devDependencies and allow them to be used for builds (yet ignore them when packaging for production), but until that happens it seems we will need to move our build dependencies from devDependencies to the main dependencies section in package.json.   Perhaps we should add a new github issue for Kiali, to move them back if and when Cachito adds the necessary support.

**Comment by jshaughn** [comment]
@aljesusg @israel-hdez @xeviknal @nrfox , you were all on the call, does the above make sense?  If people agree, then @aljesusg , I think you can assign yourself and move forward.

**Comment by israel-hdez** [comment]
I'm OK with the temporary solution.

**Comment by aljesusg** [comment]
We don’t need it. Thanks
