### ISSUE TITLE
[validations] Don't show KIA0203 when there are no VS referencing the DR subset

### ISSUE THREAD

**Issue by xeviknal** [kiali/kiali#4218]
> KIA0203 - This subset's labels are not found in any matching host. Our CD pipeline controls VirtualServices and DestinationRules, but the DRs often have references to pods that don't exist (e.g. a canary pod) but when this happens the VS would not reference the DR subset anyway, so it's not a problem.

from https://github.com/kiali/kiali/issues/4197

Plus,
> What if we remove the validation in the DR when there are no VS referencing the DR subset? When a VS used the host specified in the DR, then we should trigger the validation and warn you.
Would that change help you? I think it would keep giving value to you, right?

from https://github.com/kiali/kiali/issues/4197#issuecomment-885075152
cc @linjmeyer

**Comment by hhovsepy** [comment]
But this feature can cause a confusion among those users who create DR first, make sure that it is valid and then create VS over this DR. And they will see new errors which did not happen after DR creation.
So for avoiding any confusion over existing users, I think this new feature can be configurable in Kiali CR, and disabled by default.
And for users who need to ignore those errors in DR when VS is not created yet can activate manually this feature.

**Comment by linjmeyer** [comment]
Do DRs serve any purpose if not referenced by another Istio resource like a VirtualService?  That almost seems to me like it should be an error in itself "This DR is not referenced by any other resources and serves no purpose".  I've never personally had a use case for creating a DR on it's own so I'm curious what the reason would be for that?

**Comment by hhovsepy** [comment]
Having a VirtualService created is not a mandatory, as it is enough to have DestinationRule with appropriate subsets, and Istio (OpenShift) will have a default VirtualService with equally distributed traffic between subsets. 
VS is necessary when traffic distribution needs to be under control and specified by % per subset.

**Comment by xeviknal** [comment]
@linjmeyer you are right. DRs itselves aren't of use for istio. They are useful when they are referenced by a VirtualService.

> Note: Policies specified for subsets will not take effect until a route rule explicitly sends traffic to this subset.

from https://istio.io/latest/docs/reference/config/networking/destination-rule/

What do you think if we play with the severity of the validation? Idea:

1. When the DR is not used, keep the validation but in informative severity. Because it won't affect any behavior in the cluster. Informative messages are only seen if you are browsing the object itself and won't create noise.
2. When the DR is referenced, increase the severity to error (as it is now). Error is the severity because this definitely create wrong traffic routing.

Besides that, I am wondering to explore the option of throwing the validation of "DR not used" as a warning. I see that could be really useful for big clusters. Though one question to @linjmeyer: if we create this validation and regarding to the scenario you mention, wouldn't this validation be always present? I understand that you have DRs created first and at some point you create a VS which points at them. Therefore between the DR creation and VS creation, wouldn't this validation annoy you?

**Comment by linjmeyer** [comment]
@xeviknal  A warning on orphaned/unused DRs makes sense to me.  Our issue is regarding DR subsets though, we always have a DR with a VS - but the VS may not reference all of the DR's subsets.  Subsets can exist for pods that don't exist, but it's okay because the subset is not used. 

We basically treat the DR as a list of options, and the VS decides which DR subsets to reference based on pipeline state (ie: is a canary active or not).  So I think point 2 makes sense, with the caveat it should apply to DR subsets that are referenced by a VS.  If the DR subset refers to missing pods, but isn't actually used by a VS that shouldn't be an error.

**Comment by hhovsepy** [comment]
@linjmeyer the requested feature of showing Info message instead of Error message on DestinationRule's not existing subset, which is not linked in any VirtualService, is approached in pull request https://github.com/kiali/kiali/pull/4256 and is also documented in https://github.com/kiali/kiali.io/pull/402 .
This feature will be released in upcoming Kiali v1.40  release.
Can you please take a look whether the solution meet the requirements you needed?

**Comment by jshaughn** [comment]
I believe the work here has been merged and so I am closing the issue.  It can be re-opened if I am wrong.

**Comment by linjmeyer** [comment]
Sorry guys just saw the updates here, thank you for implementing this!  @jshaughn  @hhovsepy
