### ISSUE TITLE
Kiali operator not spinning up Kiali by printing Unable to determine if virtual resource Error

### ISSUE THREAD

**Issue by saithejareddy** [kiali/kiali#4275]
Hi,

We tried installing kiali operator in EKS. We are facing below issue.

Kiali operator is trying to access different API's and failing with below error. 

![image](https://user-images.githubusercontent.com/50693675/129255445-977c4cdc-7da2-45d5-b22a-66baa0d2ae39.png)

`❯ k get apiservices.apiregistration.k8s.io | grep metrics

v1beta1.custom.metrics.k8s.io          custom-metrics/api-custom-metrics   True        110d
v1beta1.metrics.k8s.io                 kube-system/metrics-server          True        111d
`

We verified the apiservices as well. It's up and running. We are running our own version of custom-autoscaler. If i delete this API Service, operator is able to create kiali. Is there a way to configure this?

**Comment by jmazzitelli** [comment]
Well, I wouldn't categorize this as a bug. Having a custom version of a cluster service is not guaranteed to work. I'm not exactly sure where this error happened since you only included a screen shot of an error message - a log file might be more useful. This could be an issue in the underlying operator SDK because the kiali operator doesn't explicitly do anything with `custom.metrics.k8s.io`.

The only thing I could suggest is that since this appears to be dealing with metrics, disable the metrics in the operator - see https://github.com/kiali/helm-charts/blob/master/kiali-operator/values.yaml#L20-L22

You might also have to set `spec.server.metrics_enabled: false` in your [Kiali CR](https://github.com/kiali/kiali-operator/blob/master/deploy/kiali/kiali_cr.yaml#L894-L896) as well.

But these are all just guesses though.

**Comment by jmazzitelli** [comment]
Note: the operator SDK repo is here: https://github.com/operator-framework/operator-sdk

Might need to ask them how operators built on top of the SDK can work with your custom cluster service.

**Comment by saithejareddy** [comment]
[]([kiali-operator.log.gz](https://github.com/kiali/kiali/files/6978234/kiali-operator.log.gz))Thanks @jmazzitelli
Unluckily disabling metrics doesn't help here.
Attaching screenshots and log file for your reference.
AFAIK, kiali-operator is hitting custom metrics server for some metrics, but that's [failing.](url)

**Comment by israel-hdez** [comment]
@saithejareddy I think you forgot to attach the logs.

**Comment by saithejareddy** [comment]
[kiali-operator.log.gz](https://github.com/kiali/kiali/files/6978412/kiali-operator.log.gz)

**Comment by saithejareddy** [comment]
@israel-hdez Added the log file.

**Comment by jmazzitelli** [comment]
This error is appearing all throughout the logs when the kiali operator is trying to do all different things. This definitely appears to be an operator SDK issue.

e.g.

```
{"level":"error","ts":1628797807.8133538,"logger":"proxy","msg":"Unable to determine if virtual resource","gvk":"/v1, Kind=Namespace","error":"unable to retrieve the complete list of server APIs: custom.metrics.k8s.io/v1beta1: 0-length response with status code: 200 and content type: text/plain; charset=utf-8","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\toperator-sdk/vendor/github.com/go-logr/zapr/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/log.(*DelegatingLogger).Error\n\toperator-sdk/vendor/sigs.k8s.io/controller-runtime/pkg/log/deleg.go:144\ngithub.com/operator-framework/operator-sdk/internal/ansible/proxy.(*cacheResponseHandler).ServeHTTP\n\toperator-sdk/internal/ansible/proxy/cache_response.go:97\nnet/http.serverHandler.ServeHTTP\n\t/usr/lib/golang/src/net/http/server.go:2855\nnet/http.(*conn).serve\n\t/usr/lib/golang/src/net/http/server.go:1937"}
```

```
TASK [default/kiali-deploy : Create kiali-signing-key secret to store a random signing key if a secret does not already exist and we need one] ***
fatal: [localhost]: FAILED! => {"changed": false, "error": 500, "msg": "Failed to create object: b'Unable to determine if virtual resource\\n'", "reason": "Internal Server Error", "status": 500}
```

There is something wrong with the cluster here... the k8s API master is returning some odd responses which is what I think this is saying: `unable to retrieve the complete list of server APIs: custom.metrics.k8s.io/v1beta1: 0-length response with status code: 200 `

Probably needs to escalate this to the operator SDK folks and let them know what is happening. I don't know anything about this custom cluster service you have deployed - they would probably need to know specifically what you are doing since that appears to be the trigger that causes this.

**Comment by jshaughn** [comment]
@jmazzitelli Still relevant, did we get an operator SDK update for this?

**Comment by jmazzitelli** [comment]
We have since upgraded to a new SDK. Unsure if that even matters, though. I don't think there is anything we can do here.

**Comment by jshaughn** [comment]
Closing, no further actions identified.
