### ISSUE TITLE
Medium post for Kiali versions 1.34 to 1.39

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#4280]
Write feature updates for the mentioned versions

**Comment by israel-hdez** [comment]
(To be done on Sprint 62)

**Comment by lucasponce** [comment]
Hi @israel-hdez,

Thanks for opening the issue.
As you commented in the discussion, I'm +1 to change how we write these articles, with all the videos we are producing on every Sprint I personally think we can rely on that and perhaps write articles/blog post for more specific areas.

I don't see a problem to remove this issue from the Sprint.
There are already several tasks to update the content of kiali.io and perhaps we can focus on those rather than this.

**Comment by israel-hdez** [comment]
> I don't see a problem to remove this issue from the Sprint.

I will remove from Sprint 61 and, then, add it to Sprint 62 when that entry becomes available. This is just to add visibility about what I'm working on :-)

**Comment by israel-hdez** [comment]
Done: https://medium.com/kialiproject/kiali-releases-1-34-to-1-39-overview-587f33fac41a
