### ISSUE TITLE
ingress created by Kiali CR does not include ingress class - need new deployment.ingress setting

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#4342]
The Ingress object created from the Kiali CR does not include the `ingress.spec.ingressClassName` field or the (deprecated) class name annotation. As a result, the Ingress object is ignored by the nginx controller and fails to be ready.

Versions tested with:
- Minikube: v1.23.0
- Kubernetes: v1.22.1

**Comment by jmazzitelli** [comment]
Because Ingress definitions can differ across cluster implementations, Kiali will produce a "basic" Ingress definition. If it doesn't work for your environment, or you want to customize it, that is the purpose of this setting:

https://github.com/kiali/kiali-operator/blob/v1.39.0/deploy/kiali/kiali_cr.yaml#L311-L336

**Comment by nrfox** [comment]
Ah I did not know about that override field. Shouldn't the basic nginx definition work out of the box though? Starting in kube 1.22+ or at least with minikube 1.23+ the basic definition will no longer work without the addition of the `ingressClassName` field.

**Comment by jmazzitelli** [comment]
> Ah I did not know about that override field. Shouldn't the basic nginx definition work out of the box though? Starting in kube 1.22+ or at least with minikube 1.23+ the basic definition will no longer work without the addition of the `ingressClassName` field.

We can update the basic definition if it doesn't work for the majority of users. I don't know how many people are using the kube 1.22+ - alot of people still seem to be on older versions.

**Comment by nrfox** [comment]
It looks like there's already checks for `Ingress.v1`: https://github.com/kiali/kiali-operator/blob/master/roles/default/kiali-deploy/templates/kubernetes/ingress.yaml#L1

The operator could do the same for adding the `ingressClassName` field only if the `Ingress.v1` kind exists.

**Comment by jmazzitelli** [comment]
> The operator could do the same for adding the `ingressClassName` field only if the `Ingress.v1` kind exists.

Here's that exact if-else stmt in the ingress template: https://github.com/kiali/kiali-operator/blob/v1.39.0/roles/default/kiali-deploy/templates/kubernetes/ingress.yaml#L25

**Comment by israel-hdez** [comment]
I'm :-1: for this issue.

The behavior about how an Ingress resource is processed is completely dependent on cluster setup.
Perhaps you used minikube's ingress add-on? If so, that's a change in how minikube is setting up k8s v1.22.1 + Ingress-nginx. You may fix you setup manually by following these instructions: https://kubernetes.github.io/ingress-nginx/#i-have-only-one-instance-of-the-ingresss-nginx-controller-in-my-cluster-what-should-i-do.

For a while now, I've been thinking that we probably should drop support for creating the Ingress resource, and let people expose Kiali using the method that works in their env.

**Comment by nrfox** [comment]
> The behavior about how an Ingress resource is processed is completely dependent on cluster setup.
> Perhaps you used minikube's ingress add-on? If so, that's a change in how minikube is setting up k8s v1.22.1 + Ingress-nginx. You may fix you setup manually by following these instructions: https://kubernetes.github.io/ingress-nginx/#i-have-only-one-instance-of-the-ingresss-nginx-controller-in-my-cluster-what-should-i-do.

That flag looks like it will fix the issue for my environment. My assumption was that since the Ingress object created by the default Kiali CR had nginx specific annotations, that was the default setup. Does the default setup now work in any environment in k8s v1.22+ without the user having to tweak either their nginx ingress controller or the Kiali CR in some way? I guess you could rename this issue as "defaults no longer work". I'm not sure if that's true exactly. It could just be my minikube env but it seems like this would affect any kube 1.22+ cluster.

**Comment by lucasponce** [comment]
As how ingress are exposed, I wonder why don't rely in the "recommended" way exposed by Istio ?

https://istio.io/latest/docs/tasks/observability/gateways/

I mean, if the operator should automate something in that direction, I'd suggest to follow a document like that, otherwise I'd let the user to configure this manually in his own way.

(I've jumped as Ingress are a hot topic in the community forums and to me, that document is the reference one for new users, once they are familiar with Istio and Kiali installation, they could personalize in their own way).

**Comment by israel-hdez** [comment]
> As how ingress are exposed, I wonder why don't rely in the "recommended" way exposed by Istio ?

I only scanned the page. But IMO it's more complex than what we currently have and I wouldn't like to add another bunch of options to support configuring the Istio Ingress.

I know this can be nice for starters, but I have the thought that most people will want to turn it off to expose via their stable method in production. So, I don't feel motivated in maintaining this feature.

I would lean towards removing it to simplify the operator, and provide sample YAML files in docs. (which is the way Istio has adopted in the link you posted).

**Comment by nrfox** [comment]
Instead of removing it, the default option in the CR could be `deployment.ingress_enabled = false`. That way an ingress is not created when it's not asked for. I don't feel strongly either way except that whatever the defaults are should just work without additional configuration.

**Comment by jmazzitelli** [comment]
I'm OK disabling it (or even removing it) for kubernetes , but we should leave it as-is for OpenShift because it is used when deploying on OpenShift - it creates a Route and that normally always works with our default template.

See: https://github.com/kiali/kiali-operator/blob/master/roles/default/kiali-deploy/templates/openshift/route.yaml and https://github.com/kiali/kiali-operator/blob/master/roles/default/kiali-deploy/tasks/openshift/os-main.yml#L40-L51

That said, I know for a fact people are using this ingress and override_ingress stuff on kubernetes. So if someone wants to vote to remove it, I'll ask you to document it in the release notes where you document what those people need to do when upgrading to the version of Kiali that removes this support :)

**Comment by lucasponce** [comment]
This issue is showing a recurrent problem we have in Kiali.
We don't have properly documented this use case, how to expose Kiali for users.
Istio has a recommendation, and the Kiali operator has some support in the Ingress

Personally, I don't think is a matter to automate more things but document it properly.
Istio has a page for this and it's the first reference for "starters", as you comment, I'm fine if the operator doesn't have this logic but this deserves a better documentation, and to be in sync with what Istio recommends (otherwise users may get confused to read something in istio.io and something different in kiali.io).

With a proper tutorial, an important number of issues/questions can be answered just pointing users to the documentation.

**Comment by jshaughn** [comment]
I'm removing the Bug label, as there is no consensus on that point.  I'll move this to an enhancement, probably for our docs.

**Comment by jmazzitelli** [comment]
This is going to include a change in the way the ingress is configured. Rather than have independent settings, we will roll them (including the new one) under a new `deployment.ingress` setting.

We are going to go from this:

```yaml
deployment:
  ingress_enabled: <true|false>
  override_ingress_yaml:
    ...the override yaml here...
```

to this:

```yaml
deployment:
  ingress:
    class_name: <class name or empty string>
    enabled: <true|false>
    override_yaml:
      ...the override yaml here...
```

By default, the enabled flag will be true on OpenShift and false on Kubernetes (i.e. no Ingress will be installed when on a non-OpenShift cluster).

The class name will default to "nginx" since the default yaml in the created Ingress will be geared towards the NGinx implementation.

For more details, see the associated PRs:

* https://github.com/kiali/kiali-operator/pull/440
* https://github.com/kiali/helm-charts/pull/113
* https://github.com/kiali/kiali.io/pull/466
