### ISSUE TITLE
Show mirroring info or badge on the graph

### ISSUE THREAD

**Issue by jotak** [kiali/kiali#4383]
There's already several information on virtual service configs displayed on the graph, such as request routing, fault inject, etc. but one that I've found missing is when mirroring is set up. I guess it could be made visible, if not with a new badge, as part of the "request routing" badge with additional information, next to the details of hosts?

Cf:
![Capture d’écran de 2021-09-21 10-42-03](https://user-images.githubusercontent.com/2153442/134176347-bdab6cd1-2f03-4da5-8a18-e95bfadd0c70.png)

cc @jshaughn  @lucasponce

**Comment by jmazzitelli** [comment]
I'm not sure this is relevant, but I will bring this up just in case. We need Istio telemetry to add some additional data in order to know what traffic is mirrored and what is not. See https://github.com/istio/istio/issues/11475 and https://github.com/istio/istio/issues/11093. This may not be relevant because this issue appears to want to badge a node and I don't think telemetry missing this mirror information is needed for that.

**Comment by lucasponce** [comment]
I don't have the details of the VS/DR appender in mind, but perhaps is just a special badge for that case, not the edge.
