### ISSUE TITLE
Kiali deployed behind proxy does not work as expected

### ISSUE THREAD

**Issue by brendarearden** [kiali/kiali#4459]
## Description

Starting in Kiali 1.35, Kiali's pod was changed to a read-only file system https://github.com/kiali/kiali/pull/4022/files. This is now causing issues for deployments of Kiali that are behind a proxy as there is no way to specify the proxy path as well as a server.web_root. 

Prior to this change, I was utilizing the `env.js file` to [manually override](https://github.com/rancher/charts/blob/dev-v2.6/charts/rancher-kiali-server/rancher-kiali-server/100.0.0%2Bup1.35.0/templates/web-root-configmap.yaml#L11) the `window.WEB_ROOT` value. This meant that I was able to leave the `server.web_root` value as the default value of `/kiali` and also have the `window.WEB_ROOT` be my proxy path + the `server.web_root`. 

## Example

http://localhost:2001/kiali is where the UI is accessible from. This means `server.web_root=/kiali`.

http://localhost:8080/proxy is the endpoint that will proxy `http://localhost:2001/kiali` so my `window.WEB_ROOT` would need to be `/proxy/kiali`. Since the `window.WEB_ROOT` is set by the `server.web_root`, then there is no value that I can set the `server.web_root` that will work for kiali to still be served from `/kiali` but my window root to be `/proxy/kiali`.

If I set `server.web_root=/proxy/kiali`in an attempt to include my proxy path, then when I hit my proxy endpoint `http://localhost:8080/proxy` it will redirect the traffic to `http://localhost:8080/proxy/proxy/kiali` because kiali is being served from `/proxy/kiali`, then the `window.WEB_ROOT` will overwrite the url path and it will be left at `http://localhost:8080/proxy/kiali` which is my proxy end point, but not the path where kiali is currently being served up from because we set that to `/proxy/kiali` and with the `window.WEB_ROOT` rewrite we are now only hitting `/kiali`.

https://github.com/brendarearden/example-kiali-redirect I have created a simple proxy example using python to help explain this a little more and you can see how the path overwrite is occurring.

**Comment by brendarearden** [comment]
The actual use case looks more like the former example, I created the latter as a very basic proxy example for the sake of opening this issue to make it easier to visualize what was going on.  I can definitely see how that example implementation could be exploited for sure. 

https://github.com/rancher/charts/blob/e52195cb0810175f42630a1f1f31e617381d3a43/charts/rancher-kiali-server/rancher-kiali-server/100.0.0%2Bup1.35.0/templates/web-root-configmap.yaml#L11 here is what our current window.WEB_ROOT `proxy+server.web_root` endpoint looks - It includes the path to the cluster, to the namespace and then to the service. You have to be authenticated to even reach the proxy endpoint. 

I assume that the redirect_uri for the OIDC configuration would just have to include the full url (proxy + web_root) for the redirect back from authentication to work. I am sure the proxy passthrough could ensure all the required values were on the headers to ensure the OIDC was working properly, but again this is all just assumptions and would have to be tested.

**Comment by israel-hdez** [comment]
Honestly, I don't think we need to add more configs to Kiali. As I mentioned in the Slack thread, you simply need to set the `server.web_root` configuration to the public path where Kiali is being accessed.

However, I think the main problem is that the proxy implementation is somewhat different to most k8s ingress proxies that we have heard of.

In the "example-kiali-redirect" that you provided I would do the following to fix the problem:

1) Instead of `--set server.web_root=/some/random/path/`, I would use `--set server.web_root="/http://localhost:20001"` to install Kiali via Helm charts, because this is the "public path" that you will be typing in the browser. No need to overthink what value should be used. It is that simple.

2) Fix the proxy implementation. The problem I see with that python proxy, is that it is conditionally truncating the request path, while most k8s Ingresses/reverse-proxies I've heard of are not truncating the request path. Instead, proxies usually forward the request path as is. Specifically, these lines are causing the problem: https://github.com/brendarearden/example-kiali-redirect/blob/main/kialiProxy.py#L16-L19. I would replace those lines with a single line `shutil.copyfileobj(urllib.request.urlopen(URL+url), self.wfile)`. That way, this python proxy will always pass down the path as-is typed in the browser.

With these changes in the example code, redirections should work correctly (assuming that the special characters in the `server.web_root` won't be a problem in Kiali, nor in the Python proxy).

**Comment by brendarearden** [comment]
@israel-hdez I still feel like we are not on the same page with the issue so let me try a different example: If you deploy kiali server, and you run `kubectl port-forward svc/kiali 20001:20001 -n istio-system` which allows you to access the service at port 20001, and when you access that service, you are re-directed to `http://localhost:20001/kiali` because `/kiali` is the default value for `server.web_root` and that is where the UI is accessible from in the service. So the web_root is where the UI is accessible from, it's not equivalent to the public path. No matter what I use for the proxy to access the service, I still need to know the where the UI is accessible from at.

If I take what you are saying and apply it to this basic situation, then if the service and UI is available at `http://localhost:20001/kiali` that would be the public path, and therefore I should set the `server.web_root` `http://localhost:20001/kiali` but that would actually result in me being redirect to `http://localhost:20001/http://localhost:20001/kiali` which is not where the UI is accessible from. 

Also a note: the project I created for this issue was simply to demonstrate the window.WEB_ROOT rewrite in the browser and is not in use.

**Comment by jmazzitelli** [comment]
@brendarearden How does this proxy work with OTHER apps (not Kiali). For example, suppose I have Prometheus. It is on `http://localhost:9090/graph` -- how do you put your proxy in front of that? Is Kiali somehow different than other apps that it can't be placed behind a proxy? (I do know we have other users that use a proxy in front of Kiali - I do not know why your proxy is different).

Also - what if you just set `server.web_root` to "/" - Kiali in that case won't redirect to anything other than to the root of the server URL. The only thing I can think of is the use of `window.WEB_ROOT` is the crux of the problem. But I don't understand why other proxy users haven't run into this issue.

**Comment by brendarearden** [comment]
"_The only thing I can think of is the use of window.WEB_ROOT is the crux of the problem. But I don't understand why other proxy users haven't run into this issue._"

Yes, for our particular proxy implementation this is the root of the problem because it re-writes the entire browser path - I don't want to include my proxy path in the `service.web_root` setting because I still want the kiali UI to be accessible at `/kiali` when I access the kiali service, but I don't want the browser path to be re-written without my proxy in it. 

I will take a look at our prometheus / grafana implementation for the proxy and I will let you know what I find.

**Comment by israel-hdez** [comment]
> If I take what you are saying and apply it to this basic situation, then if the service and UI is available at `http://localhost:20001/kiali` that would be the public path, and therefore I should set the `server.web_root`

Well not exactly... If `http://localhost:20001/kiali` is what you are going to type in the browser, then this is the _full URL_ and the path is, simply `/kiali` and this is what you should use for the `server.web_root` config.

This is why in your "example-kiali-redirect", in step 5 you say:

> 5. Then navigate to http://localhost:9097/http://localhost:20001 to access kiali.

if that's the full URL, you remove the first component, and you set `/http://localhost:20001` as value for `server.web_root`.

> Yes, for our particular proxy implementation this is the root of the problem

Well... all these Kiali configurations are intented to work with [Kubernetes Ingresses](https://kubernetes.io/docs/concepts/services-networking/ingress/) or proxies that behave similarly to Ingresses. Specifically, we test using [ingress-nginx](https://kubernetes.github.io/ingress-nginx/) which is backed by an [nginx](https://www.nginx.com/) server configured as a reverse proxy.

Honestly, I think using a `ConfigMap` to provide a customized `env.js` file was probably a hacky way to force Kiali to work with your proxy config :-) My thinking is motivated because we've never recommended to do this.

Personally, I don't see a bug here. Kiali works fine with reverse proxies, as long as the reverse proxy is configured with a similar behavior to an Ingress. This always has been the assumption on the design.

So, I see these options to fix the issue:

- If possible, use an Ingress to expose Kiali, rather than your custom proxy.
- Else, reconfigure your proxy to forward requests using the original URL path of the request, rather than doing URL rewrite to `/kiali`.
  - If you are open to tell which proxy server you are using and how it is configured, we probably can help with the configs. Else, you are on your own.
- Else, if you are **very sure** that you cannot reconfigure your proxy, maybe Kiali needs to be modified. However, since we don't have a reference, it's hard to test. Most likely, you will need to contribute the fix.

Anyway, it will be helpful to know how prometheus and grafana are working in your env. There are some chances that you simply need to replicate configs.

**Comment by brendarearden** [comment]
I am still looking into how our proxy is currently working, but I wanted to follow up so that you know this is still on my radar. I will be looking into the different options that are supported currently with Kiali as you suggested to verify if those will meet our needs.

One thing I wanted to circle back on and clarify: 

Our setup is the service endpoint that gives you access to the kiali UI and not really a proxy. So we are just using the service endpoint from within our cluster to access to the Kiali UI which is why I make this comparison when discussing why setting the `server.web_root` won't work in this particular situation:
 |Endpoint|Kiali UI Path|
|----|-----|
|http://localhost:20001 | /kiali |
| http://localhost:8081/k8s/clusters/local/api/v1/namespaces/istio-system/services/http:kiali:20001/proxy| /kiali|

**Comment by brendarearden** [comment]
Here is the exact scenario that is causing a bug to show up: 

Install Kiali https://kiali.io/docs/installation/quick-start/#install-via-helm
```
helm install \
  --namespace istio-system \
  --set auth.strategy="anonymous" \
  --repo https://kiali.org/helm-charts \
  kiali-server \
  kiali-server
```
run `kubectl proxy --port=8080` to expose the kubernetes api server 

Navigate to the service via the kubernetes api server proxy endpoint:

`http://localhost:8080/api/v1/namespaces/istio-system/services/kiali:20001/proxy` (note: you might need to change the domain depending on where you are running these steps from)

The ui will load, but then the browser window path will be overwritten to `http://localhost:8080/kiali/console/overview?duration=60&refresh=15000`, which means the path is longer hitting the endpoint where the service is exposed via the server api.

**Comment by jmazzitelli** [comment]
> The ui will load, but then the browser window path will be overwritten to `http://localhost:8080/kiali/console/overview?duration=60&refresh=15000`

I see that. And when I install with the helm setting `--set server.web_root=/api/v1/namespaces/istio-system/services/kiali:20001/proxy` I get the following error in the browser: `localhost redirected you too many times. ... ERR_TOO_MANY_REDIRECTS` Trying to curl confirms:

```
$ curl -L http://localhost:8080/api/v1/namespaces/istio-system/services/kiali:20001/proxy/
curl: (47) Maximum (50) redirects followed
```

The only way that I can think of that would solve this problem is to provide a way to configure this env.js setting.

cc @israel-hdez

**Comment by israel-hdez** [comment]
Well... We haven't supported `kubectl proxy` for a while, because it breaks all authentication mechanisms but anonymous. It injects an `Authorization` HTTP header which enters in conflict with Kiali's one.

So, I'm not sure we want to add a new setting to allow `kubectl proxy` to work OK only for the anonymous auth. I don't see that much value add.

Our typical suggested workaround has been to use `kubectl port-forward` as explained here: https://kiali.io/docs/installation/installation-guide/accessing-kiali/#accessing-kiali-using-port-forwarding

**Comment by jmazzitelli** [comment]
Even though this is uniquely targeted to a specific use-case and not generally needed, we could support it. But to support this use-case it sounds like we need a new CR setting `server.redirect_path` (or whatever we think it should be called - I don't know a good name for it) and have the server use that for the in-memory replace within the env.js file. If it isn't specified, use web_root as the default value for it.

This new config setting would be needed to be added to the server helm chart as well as the operator. See: https://github.com/kiali/kiali-operator/blob/master/DEVELOPING.adoc#are-you-altering-a-kiali-server-configuration-setting

If you want this capability, feel free to contribute a PR on this.

**Comment by jmazzitelli** [comment]
There is a very simple yet effective solution to this. See PR https://github.com/kiali/kiali/pull/4914/files - in case anyone else that has a need for this wants to test it out.
