### ISSUE TITLE
Node rank should be displayed in side-panel

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#4494]
The new node-rank feature is good but currently doesn't offer the user a way of seeing the node ranks.  It's probably unnecessary to display ranks on or around the nodes themselves, but it would be good to see it in the side-panel, when the node is selected.  It would make sense probably in the same place as the badging info.

**Comment by nrfox** [comment]
Preview:
![Screenshot from 2021-11-12 14-19-38](https://user-images.githubusercontent.com/6226732/141527926-1fbdf2d9-4ba0-4455-bacc-d26348db596f.png)
![Screenshot from 2021-11-12 14-19-45](https://user-images.githubusercontent.com/6226732/141527944-5adc7de7-8264-42af-a82c-34cf03df4863.png)
![Screenshot from 2021-11-12 15-02-09](https://user-images.githubusercontent.com/6226732/141527955-efb4b865-f66e-4ae0-8d2a-b845af3f3558.png)
![Screenshot from 2021-11-12 15-02-24](https://user-images.githubusercontent.com/6226732/141527972-2084c56a-c16b-447c-9e47-11d7345c965c.png)

I used the same expandable dropdown that hosts/workload-entries have. Perhaps rank needs an icon here since the rest of the badging info all has icons?

**Comment by jshaughn** [comment]
Hmm, all of the other badge entries have an obvious icon that ties to the graph.  Rank doesn't but it would look better if we used one here.   I'm not sure we actually need to have the dropdown if it is just reflecting the same thing that is displayed in the Display  menu.  If you were going to show the actual values for each criteria then I think it would be justified.  Last comment is that I'd pull this up into the badging section, having it split up with the other node links is sort of busy.

**Comment by nrfox** [comment]
> Hmm, all of the other badge entries have an obvious icon that ties to the graph. Rank doesn't but it would look better if we used one here.

Agreed, I'll take a look at the patternfly icons and perhaps @andrew-ronaldson could weigh in as well on what icon would best fit rank.

> I'm not sure we actually need to have the dropdown if it is just reflecting the same thing that is displayed in the Display menu. If you were going to show the actual values for each criteria then I think it would be justified. 

That's a good point. It does just duplicate what's on the display menu. I thought it'd be nice to see the selected criteria next to the rank on the node panel but I'm not sure the benefits outweigh the cost of screen real estate given that the same info is in the display options.

**Comment by nrfox** [comment]
> Agreed, I'll take a look at the patternfly icons and perhaps @andrew-ronaldson could weigh in as well on what icon would best fit rank.

`fa-sort-amount-down-alt` seems like a good option

**Comment by jshaughn** [comment]
> I'm not sure the benefits outweigh the cost of screen real estate...

I'm sure. They don't :-)  (unless the raw values are also presented, but until someone asks for it, it's not needed).
