### ISSUE TITLE
missing expected TS labels on Graph

### ISSUE THREAD

**Issue by Stono** [kiali/kiali#4517]
Hey
It's been a long time since I have looked at Kiali, so thought i'd see how it's matured!

I'm having some problems getting the "Graph" page to render prometheus metrics, in the logs I see:

```
2021-11-21T10:47:57Z WRN Skipping {destination_service="app.istio-test-app-2.svc.cluster.local", destination_service_name="app", destination_service_namespace="istio-test-app-2", destination_workload="istio-test-app-2", destination_w
orkload_namespace="istio-test-app-2", response_code="200", response_flags="-", source_workload="istio-test-app-1", source_workload_namespace="istio-test-app-1"}, missing expected TS labels
```

![Screenshot 2021-11-21 at 10 47 44](https://user-images.githubusercontent.com/1486729/142758800-5226d48d-39ca-4166-a18a-2461c652d529.png)

However on the individual workload page, it does seem to render metrics OK:

![Screenshot 2021-11-21 at 10 48 16](https://user-images.githubusercontent.com/1486729/142758807-77658bd8-4c0b-417e-bf1b-3997ef9e8330.png)

Providing I select the right reporter (source, we don't record destination metrics).

We drop quite a large amount of labels at Envoy, using the istiooperator config:

```
        prometheus:
          configOverride:
            outboundSidecar:
              debug: false
              stat_prefix: istio
              metrics:
              - tags_to_remove:
                - destination_canonical_service
                - source_canonical_service
                - destination_principal
                - source_principal
                - connection_security_policy
                - grpc_response_status
                - source_version
                - destination_version
                - request_protocol
                - source_canonical_revision
                - destination_canonical_revision
                - source_cluster
                - destination_cluster
                - destination_app
              - name: request_duration_milliseconds
                tags_to_remove:
                - response_code
                - response_flags
                - source_cluster
                - destination_cluster
              - name: request_bytes
                tags_to_remove:
                - response_code
                - response_flags
                - source_cluster
                - destination_cluster
              - name: response_bytes
                tags_to_remove:
                - response_code
                - response_flags
                - source_cluster
                - destination_cluster
```

Is there any way I can get this to work?

**Comment by jshaughn** [comment]
Hi Karl, yes, it's definitely a problem with the metric labels being removed, some are required for the graph to render.  That's why you're seeing [a lot] of those "Skipping" warnings, because expected TimeSeries labels are unset.  You would need to add back most of the labels, as specified here: https://kiali.io/docs/faq/general/#which-istio-metrics-and-attributes-are-required-by-kiali.

Without destination reporting things will be a bit crippled, as the graph does combine source and destination metrics.  I think you will still be able to get something to render using only source metrics, if you add back the required labels.

Even if you decide not to support the graph metrics, perhaps you will still find some value with Kiali, the validations, unified logging, maybe the trace support and/or wizards, etc.

**Comment by Stono** [comment]
Ahh thanks for the link to the doco on the required labels @jshaughn. 
I will do a bit of a differential!  Thanks
Karl
