### ISSUE TITLE
Possible memory leak in /api/istio/status endpoint

### ISSUE THREAD

**Issue by FilipB** [kiali/kiali#4527]
When hitting /api/istio/status endpoint kiali pod memory usage grows steadily until it reaches 1GB limit and the pod is OOMKiled.

### Version
Kiali UI
    1.44.0 (e3238fb2f2493b23540125d4e15d4665e608dc8c)
Kiali Server
    v1.44.0-SNAPSHOT (e9a4b6f469d9bb1a0eef3bfabe5b0a9e4a83ffcd)
Kiali Container
    v1.44.0-SNAPSHOT
Istio
    1.12.0 
Prometheus
    2.26.0 
Kubernetes
    v1.22.2+5e38c72 

### Repro steps
1. install istio and kiali to istio-system namespace
2. oc login to your cluster
3. java must be available (e.g dnf install -y java-11-openjdk)
4. run attached repro.sh from /tmp dir
5. watch kiali pod memory usage -> it grows very fast until it reaches 1GB limit
6. then the kiali pod is OOMKilled and restarted and running repro test is showing 503 response codes

Attaching as txt as sh is not supported. Please rename to repro.sh
[repro.sh.txt](https://github.com/kiali/kiali/files/7604704/repro.sh.txt)

**Comment by FilipB** [comment]
When removing the pod memory limit it grows to 6GB after 10 minutes. It's growing linearly.

**Comment by lucasponce** [comment]
Thanks @FilipB, I'll investigate this endpoint, it sounds a clear leak from your comments.

**Comment by lucasponce** [comment]
@FilipB these are the steps I did for the investigation.

I used latest "master" Kiali code but on a CRC Maistra 2.1/Istio 1.9 environment, I guess that if the problem is a leak, the version of Istio shouldn't affect here.

First step was to test the endpoint using an "anonymous" strategy, and with a similar rate of concurrent users, the backend was stable in ~150 Mb of RAM, also the garbage collector seemed to work as expected.

Second step, I tested the "openshift" strategy as it requires additional steps and logic that could be affected to this leak and same results (I used a manual loop of curl to simulate users).

![image](https://user-images.githubusercontent.com/1662329/143564813-661e7fac-958f-4ce6-b342-ca3c9cccafdb.png)

![image](https://user-images.githubusercontent.com/1662329/143564748-a104a867-0b0a-4500-9612-90f6666bc4ef.png)

![image](https://user-images.githubusercontent.com/1662329/143564780-7572833e-7d0e-471d-8c43-44ae7cfb71bf.png)

So nothing unusual from the Kiali backend code.

I wonder if we are hitting a problem that the infrastructure is slow and for some reason the garbage collector of the go process doesn't start as fast as my machine, that could explain what you see.

I don't have any conclusion yet, but keep investigating on this.

**Comment by lucasponce** [comment]
Using the repro.sh have same results:

![image](https://user-images.githubusercontent.com/1662329/143571826-55fe68d8-de91-4cd6-8b69-6e8241dc1fe2.png)

![image](https://user-images.githubusercontent.com/1662329/143571860-9322ef2b-fff6-48a9-8126-1f5d6e7c9022.png)

**Comment by lucasponce** [comment]
Ok, as discussed, when using the `/api/istio/status` on upstream with Jaeger configured in grpc, the kiali backend has a problem with the jaeger client generated, probably due the bump of the protobuf dependencies.

That created a memory leak in those cases, and generally, the traces feature were broken using grpc after that bump.

I think then the issue is more clear and that explains that my first environment didn't catch the problem as it was all used in http instead of grpc.
