### ISSUE TITLE
Research workload/service label filters on Graph

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#4605]
Kiali offers visualization for different pre-defined types of Graphs: applications, workload, services, and versioned applications.

During the scalability discussions, https://github.com/kiali/kiali/discussions/4080 one area to improve is to let the user define the list of elements to represent in a Graph using filtering expressions.

It's a common practice in Kubernetes to use labels to filter workloads and services and that feature could be incorporated in Kiali as well as part of the Graph generation.

Additionally, a Graph generated using filtering expressions may introduce dynamic boxing/grouping (in addition to the standard {app, namespace, boxing} capabilities that Kiali offers today).

But this feature would require some research to identify the potential subtasks needed as this effort may require changes in how the graph model is built and rendered.

Suggested test plan (QE @mattmahoneyrh):
- This Epic will research and define a new filter capability in the Kiali Graph based on workload/service labels.
- The QE test plan should define a new UI flow that validates the new changes proposed in the Epic.
- This Epic may be split into different subtasks (the definition of the tasks is part of the initial research), QE/Dev should sync if the test plan may be split into subtasks as well or consolidate a final test once the Epic is progressed.

**Comment by jshaughn** [comment]
I think this is also related to https://github.com/kiali/kiali/issues/1269, where we talk about using labels as part of a global scope.

**Comment by jmazzitelli** [comment]
It seems like we will need a label filtering capability similar to what the OpenShift Console has. We will need this in the Graph page as well as the list pages for Applications, Workloads and Services.

Without getting into specifics of how we should implement this in the UI, these are just illustrations to show something that we would need (notice the new label filter under the Namespace dropdown - this label filter is very similar to the OpenShift Console label filter component):

![graph-label-filter](https://user-images.githubusercontent.com/2029470/152240171-206b46c0-3557-4c78-b216-558bc1f91b2c.jpg)

![label-filter](https://user-images.githubusercontent.com/2029470/152240186-81584bd4-7567-422b-962a-bba268e65859.jpg)

The details pages (i.e. app details, workload details, service details) will need to know which labels (if any) were filtered because those detail pages will need to aggregate data for all resources in the application/workload/service (and those resources need to be filtered by the selected labels, if there were any). You certainly don't want to filter the list but then lose that filtering in the details page, which is why the details pages need the label filters. However, I do not believe we should have this filtering UI on the details pages; those detail pages will need to be given the label filters (via URL query strings, for example) that were used on the list pages. So the idea would be you filter the list pages (apps, workloads, or services) and once you filter down the list, you can pick, say, an application and navigate to its details page, at which time those details are limited to those app resources that have the labels that were in the filter.

I suppose we could just have the ability for the user to directly set the label filter UI on the details page - but as I sit here thinking about it, I tend to think the details page should reflect the filtering that was selected on the list page from which the user navigated from. That may not be the best way to go, and I could be convinced otherwise.

The tasks we would need to do would be:

- Design and implement a shared label filtering UI component
- Implement filtering on the graph - this likely will need to be done server-side, perhaps as another appender (but that's an implementation detail to be determined later).
- Implement filtering on the list pages - 3 subtasks for each list page (app, workload, service)
- Implement filtering on the details pages - 3 subtasks for each detail page (app, workload, service).

Note that the subtasks for each detail page could be further broken down into subtasks for each tab in the details page (overview, traffic, metrics, traces). We most likely will need to filter on labels whenever any aggregate data is computed (such as aggregate metrics and traces).

**Comment by lucasponce** [comment]
All comments are right, but refactoring the current filters is not a trivial effort.
I'd consider progressing in an interactive way and reducing the scope of the label filter for the graph generation.

To have a global scope is something we need, but that is going to trigger a large refactor of the whole pages and it will take more sprints than expected.

A global scope/state should have also had a unique way to map it in the URL and there are several components (due to technical debts) that need to be aligned there.

And not to mention that the UI filter component is something that needs to be renewed as that would require a bump of the Patternfly framework.

We want that and it's a good approach but I'm trying to define a good strategy about how to approach this without opening too many fronts.

**Comment by jmazzitelli** [comment]
> I'd consider in a first phase to see this feature more like an extension of the "find/hide" where the user refines the view:
> 
> * "Show me all workloads with version=v1"
> * "Hide me all apps with env=test and healthy"

Yes, we could skip the label filter UI component entirely and just enhance the find/hide language to support `label=value` expressions. But that wouldn't make any iterative step forward to the ultimate goal of a global scope label filter.

Rather than enhance the find/hide functionality, what if we just add the label filter UI component only to the graph page (leave all the other pages untouched - we will worry about those later):

![graph-label-filter](https://user-images.githubusercontent.com/2029470/152240171-206b46c0-3557-4c78-b216-558bc1f91b2c.jpg)

The benefit here would be this is the first iterative step toward a global label filter since we would be designing and implementing a common label filter UI component (though it is only used on the graph page at first). We could then be able to get community feedback and tweak the label filter UI component functionality without it having to affect all the pages in the UI.

Once we get graph generation to work with the label filtering, then we can later start introducing it to the other pages.

**Comment by lucasponce** [comment]
> But that wouldn't make any iterative step forward to the ultimate goal of a global scope label filter.

But a global label filter is implemented in other platforms that potentially we may want to integrate, so to me adding it as part of the graph filter (find/hide) makes that feature belongs to the Graph itself, and later can be propagated in other pages (or platforms).

Also in the find/hide you would be able to process expressions easily that in the Graph page, so, that would be my strategy for this, instead to apply a generic label filter component.

**Comment by jmazzitelli** [comment]
OK, so what is this issue conclusion? The subject of this issue is "Research workload/service label filters on Graph".

Do we close this and just say, "We will add hide/find expressions"?

**Comment by jshaughn** [comment]
A couple of things.  Hide/Find works completely client-side.  It maps the DSL to a cytoscape selector, and then applies that to the cy graph to identify the elements of interest.  That's one reason it's not really conducive to a label selector, but there are more.  Today the graph elements do not have label information attached, and so filtering client-side isn't possible.  We could of course hack our way around these issues, add label info in an appender, or mangle find/hide and somehow extract a label selector, if found.   But to work in the right direction I think we want to do this sort of filtering/scoping server-side, like we do with namespaces.  If a user wants to limit his scope based on a label selector I think the returned graph should not contain the filtered elements.  As mazz mentioned above, this would likely need to be done in some sort of appender (actually, it may have to be more of a post-processing step, like a finalizer).

Also, we have worked hard to keep the graph toolbar fairly clean and limited to 2 rows.  I would suggest something similar to a find/hide text box, but on the top row, which is more of the "scope" area.  As Lucas suggested, something textual, like, "version=v1" or "version=v1 and app=finance".

**Comment by lucasponce** [comment]
As I user I don't think I need to know if that feature is implemented in the server/client.

I see it handy to just annotate the workloads with the labeling in the graph generation and allow that information to be part of the find/hide feature.

That would really give more powerful query capabilities AND the graph can be more easily adapted as a component and integrated into other places keeping that feature.

But to me combined "find/hide" expressions as 

- "Show me all workloads with version=v1"
- "Hide the rest"

Are really what I'd think.

A global filter makes sense, but is not going to allow to "hide" and I think it will limit the find/hide, also I don't think as a user I'd like to perform too much filtering (namespace -> labels -> find/hide).

There is an already appended that iterates on the workloads, I see it interesting to explore to add the labels and make them available to the client.

In the future, yes, with a new model, probably all this logic may be discussed if backend/frontend (disclaimer, other platforms are moving to have caches for features like this in the client, so, the topic is not as obvious as it may look, but that's part of another broader and deep session).

**Comment by jshaughn** [comment]
I agree that the user doesn't need to know any impl, but we don't need to ignore relevant technical details when talking about enhancing existing features.   Offering this via find/hide is, in my opinion, is a very near-term approach.  It would work only with the graph and would not lend itself to a similar global mechanism, or something consistent across overview and list pages. And it does not reduce the size of the returned graph, which could be unnecessarily inefficient.

Having said that, if people think find/hide is the way to go, then yes, we would need to add labels to the returned graph nodes.  Or, perhaps, only a set of labels specifically configured by the user.  With that we may be better equipped to validate the find/hide DSL, and possibly add to the autocomplete.

**Comment by lucasponce** [comment]
> It would work only with the graph and would not lend itself to a similar global mechanism, or something consistent across overview and list pages. And it does not reduce the size of the returned graph, which could be unnecessarily inefficient.

Yes, I know, but it won't add too much overhead compared with the current implementation, and in terms of user experience, it can add value and opportunity to enhance the graph-query requirements.

It's a tradeoff, seeing the effort that is required to work in the direction of a common filter vs an enhancement in the find/hide, I see it interesting to start with the find/hide, collect feedback than can help us to draft the needs for a long-term model discussion.

Also, I think that the "find/hide", "validations" and the "correlation" are the three main features that Kiali can offer to other platforms as well, so, that's part of my rationale for what I'd prefer to explore that design.

**Comment by lucasponce** [comment]
Another comment, that can fit in this discussion, I think that the "find/hide" component can be combined into a single box:

And just play with the expressions ("find ...", "hide ...", "find this & hide that").

That would move in a similar UX as other tools that support expressions for observability:

And in the context of this thread, it would make it more natural to add "labels" as part of the expressions for "find/hide".

**Comment by nrfox** [comment]
> I think that the "find/hide" component can be combined into a single box

That's an interesting idea. Perhaps the find/hide box itself could be global similar to how the namespace box is global across tabs today:
![Screenshot from 2022-02-04 11-33-15](https://user-images.githubusercontent.com/6226732/152566650-2fe89893-67cd-466d-85ae-7c75c39ce357.png)
![Screenshot from 2022-02-04 11-33-20](https://user-images.githubusercontent.com/6226732/152566656-b0a8bb81-4a06-4ea9-85d3-dcb927997505.png)
![Screenshot from 2022-02-04 11-33-31](https://user-images.githubusercontent.com/6226732/152566661-3e7e5877-5c7b-469c-850f-b5c322aa6015.png)

**Comment by nrfox** [comment]
> Perhaps the find/hide box itself could be global similar to how the namespace box is global across tabs today

A lot of the find/hide functionality probably doesn't translate to other parts of the app aside from the graph though. But a generic "filtering" box probably would. At least a way to filter each page by qualities that would apply to each page. "Labels" seems like it'd apply regardless of whether you are looking at apps/workloads etc. Maybe "rank" would as well.

**Comment by jshaughn** [comment]
I'm not sure I'm very keen on a unified find/hide, it seems maybe like a solution in search of a problem.

**Comment by jmazzitelli** [comment]
re: unified find/hide - seems we are getting too far away from what I originally thought was the direction this issue would take - and that is: progressing in an iterative way towards a global label filter. Unified find/hide seems like a separate issue.

Then again, if this issue evolves into "add label filtering to the expression syntax of the graph find/hide" then we've already gone away from that iterative approach because anything we do to enhance find/hide will have no applicability to the rest of the UI since, as @nrfox points out, find/hide functionality probably doesn't translate to other parts of the app aside from the graph.

**Comment by jshaughn** [comment]
> we do to enhance find/hide will have no applicability to the rest of the UI...

True, but then again, as per the title of the issue, this is ultimately targeted to the graph.  For a near-term approach it's probably the easiest thing we can do.  If and when we have a robust server-side model, the idea of a global, server-side approach is more relevant.

**Comment by lucasponce** [comment]
> True, but then again, as per the title of the issue, this is ultimately targeted to the graph. 

And that's ok. It could be good to progress in the feature within the Graph context as there are several areas to be developed in the mid/long term, especially related to the integration with other platforms or the development of a new model.

Adding (and improving) this feature in the find/hide is something that is going to help in any scenario, I wouldn't consider progress in a global scope for now due to all effort involved that may also delay other areas (i.e. future integrations).
