### ISSUE TITLE
Failing to Display Larger Number of Log Lines

### ISSUE THREAD

**Issue by s7an-it** [kiali/kiali#4701]
Requirement:
We use Kiali as a log correlation tool in our development stack aside the regular kiali use cases. I know this is not the main feature of Kiali and is not fully supported but it what our developers preference to be using it compared to other tools like datadog/kibana.

Installed with kiali-operator helm chart.
kiali version: 1.44
istio version: 1.11.4 (installed through helm manifests)
EKS 1.20.7

When enabling trace in logs last thing I see before freeze or before I refresh whole browser is similar to, happens to any container:
2022-02-02T11:27:06Z DBG Skipping empty log line [2022-02-02T11:22:44.708153712Z ]
2022-02-02T11:27:06Z DBG Skipping empty log line [2022-02-02T11:22:44.708676239Z ]
2022-02-02T11:27:06Z DBG Skipping empty log line [2022-02-02T11:22:44.718115411Z ]
2022-02-02T11:27:06Z DBG Skipping empty log line [2022-02-02T11:22:44.718534737Z ]
2022-02-02T11:27:07Z DBG Skipping unexpected log line []

Symptom:
The problem we generate hunder of millions of events daily so the default 10MB which is equal to 20k lines in our log format was not enough for us. Kiali has no issues handling this, it may be a bit slower on 20k lines, I have to wit 10-20 sec but it eventually fetch it same when copy, wait a bit and display.
Now since default rotation gives is 1 min of log in our case when we troubleshoot is useless, even if we have injest is kibana if we want to use kiali to correlate traces and envoy data we have to modify logdriver of docker daemon, so eventually we have set 300MB logs on contaner level.

However as soon as log becomes larger than 20k (I only managed to display 25k once), everything in kiali freezes (no error in console, no error in trace aside from some empty log line messsage), ui freeze and whole kiali freezes/dies, once it got OOM killed on 1-2 Gi, but eventually I tried higher resources but it looks when this happens it doesn't use anything that much, maybe at some point it leaked but the usual after I increase over the leak limit I get something like 300MB and 50m usage... Ultimately tried qps/burst 2000/2000, no gzip compression, but nothing seems to influence it.
When I process from kubectl logs I get 500k lines response in 4 seconds and all is good. It looks like something is breaking the buffer maybe in Kiali?

**Comment by lucasponce** [comment]
Thanks @s7an-it for creating the issue

**Comment by jshaughn** [comment]
Addingt to backlog.  It's not clear what we can do here but minimally we need to protect from the freeze-up behavior.  Kiali is not streaming the logs, it it attempting to gather all of the requested logs in one request.  Minimally, we may need to set a hard maximum on the number of log lines we can process.  Otherwise, we may need to look at a chunking or streaming solution.

**Comment by israel-hdez** [comment]
I think it is possible to stream the logs to the front-end without involving websockets. It could be a back-end only change. That would solve the high memory consumption on the cluster side.

However, if the UI is also freezing, that means that once the UI has loaded the data, then front-end rendering also takes a lot of time. In my tests, even at 12k lines, UI rendering time is greater than back-end logs processing time :-/ So, in this case rendering needs to be done only when needed (i.e. when the log line is visible in the pane).

Feel free to assign to me, if you think this is worth to fix.

**Comment by jshaughn** [comment]
Sure, I think this is relevant to the scale and perf focus.  What we do is a little interesting, as there is currently backend processing/parsing (to handle the various options, as well as identify access logging), and client-side processing (for the unified view, find/hide).  So a solution here would need to be sensitive to the features we offer.  I'm sure there are faster ways to present logs, but we need the added value because other mechanisms can give straight logging.
