### ISSUE TITLE
support canary version auto-injection

### ISSUE THREAD

**Issue by Xunzhuo** [kiali/kiali#4756]
For now, I think when we disable/enable auto-injection, we patch the 
+ `"istio-injection":"disabled"` or `"istio-injection":"enabled"` 

to update the namespaces, but in canary mode in istio, I think this update will not work.
Labels always look like `"istio.io/rev":"1-10-3"`, can we make this configurable to inject?

**Comment by lucasponce** [comment]
I'd say this feature is implemented on some level cc @hhovsepy as he has more information about the implementation.

**Comment by hhovsepy** [comment]
This was implemented in https://github.com/kiali/kiali/issues/3988

**Comment by Xunzhuo** [comment]
Thanks @hhovsepy for your quick response and @lucasponce :)

**Comment by lucasponce** [comment]
There should be some documentation in the reference:
https://kiali.io/docs/configuration/kialis.kiali.io/#.spec.external_services.istio.istio_canary_revision

I'm going to close the issue itself, but please, give a try and let's see if this issue is useful as it's implemented or it can evolve with more enhancements.

Thanks

**Comment by Xunzhuo** [comment]
Sure I will recheck this :)
