### ISSUE TITLE
Envoy metrics look broken

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#4769]
Probably there were some changes that affect the Envoy metrics, but today they look broken:
![image](https://user-images.githubusercontent.com/1662329/156208687-3f29d793-474e-4699-bd82-5c3cae1ad896.png)

**Comment by gregory-v** [comment]
In Workloads, tabs Envoy -> Metrics I have the following error : "Sorry, there was a problem. Try a refresh or navigate to a different page."
I increased logs in container kiali but I am not able to find anything. I have the same behaviour with previous version of kiali (v1.46.0) and Istio (1.12.2)

Kiali UI  1.47.0 (d37fff0dad452ed0bc1b122d4543fc40bd0b8510)
Kiali Server v1.47.0 (31da692118694362f1a04b25f2d661edc5e8c11f)
Kiali Container v1.47.0  (Kiali-operator)
Components Istio 1.13.1  (Istio-operator)
Prometheus 2.29.1    (kube-prometheus)
Kubernetes v1.21.5-eks-bc4871b (EKS)

The "click" doesn't generate any network request. but an JS Error: Minified React.

In my console :
2.5e6844a0.chunk.js:2 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ku (2.5e6844a0.chunk.js:2:2109490)
    at 2.5e6844a0.chunk.js:2:2055231
    at ja (2.5e6844a0.chunk.js:2:2065325)
    at gs (2.5e6844a0.chunk.js:2:2105838)
    at lu (2.5e6844a0.chunk.js:2:2096347)
    at su (2.5e6844a0.chunk.js:2:2096272)
    at Zs (2.5e6844a0.chunk.js:2:2093281)
    at 2.5e6844a0.chunk.js:2:2044666
    at t.unstable_runWithPriority (2.5e6844a0.chunk.js:2:2120247)
    at Wi (2.5e6844a0.chunk.js:2:2044375)

It seems istio_tcp* metrics are missing in prom since I am using kube-prometheus. My serviceMonitor config :
https://pastebin.com/mCXar3xb

**Comment by lucasponce** [comment]
Ok, I confirm it's a problem with Istio 1.13.x. In Istio 1.12.1 those metrics are enabled by default:
![image](https://user-images.githubusercontent.com/1662329/156216041-eb29f30d-dd47-4e3f-8128-8ee3ec80486e.png)

I'm going to figure out how to re-enable them in the Istio 1.13.x as a workaround for this problem.

Perhaps if those are disabled by default, Kiali could disable the tab with a feature flag.

**Comment by jmazzitelli** [comment]
> An easy fix for this (and potentially to backport to 1.47.1) would be to modify the dashboard for the Envoy.

Just FYI: if you have the new Envoy dashboard yaml that will work, people can put that dashboard directly in their Kiali CR to override the envoy dashboard. This works today, so people won't have to wait for a new z-stream release or other patch.

See: https://kiali.io/docs/configuration/custom-dashboard/#declaring-a-custom-dashboard
```
Modifying Built-in Dashboards: If you want to modify or remove a built-in dashboard, you can set its
new definition in the Kiali CR’s spec.custom_dashboards. Simply define a custom dashboard with
the same name as the built-in dashboard. To remove a built-in dashboard so Kiali doesn’t use it,
simply define a custom dashboard by defining only its name with no other data associated with it
(e.g. in spec.custom_dashboards you add a list item that has "- name: <name of built-in dashboard to remove>"
```

**Comment by lucasponce** [comment]
> Just FYI: if you have the new Envoy dashboard yaml that will work, people can put that dashboard directly in their Kiali CR to override the envoy dashboard. This works today, so people won't have to wait for a new z-stream release or other patch.

Yes, it's a workaround for this bug, to avoid the crash.
I'm going to update the defaults and also fix the "crash", as in the case of a typo in the dashboard, the problem would be there.

**Comment by lucasponce** [comment]
cc @gregory-v 

There are a couple of PRs to fix this problem both in backend/frontend, in short, a simple workaround is to modify the configuration of the CustomDashboard namespace param.

I guess PRs are easy to follow, but let us know if you have any comments.

Thanks

**Comment by jmazzitelli** [comment]
> in short, a simple workaround is to modify the configuration of the CustomDashboard namespace param.

I believe @lucasponce is referring to this: https://kiali.io/docs/configuration/kialis.kiali.io/#.spec.external_services.custom_dashboards.namespace_label

```yaml
spec:
  external_services:
    custom_dashboards:
      namespace_label: namespace
```
