### ISSUE TITLE
Mismatched Node Graph Type breaks UI in Application

### ISSUE THREAD

**Issue by Xunzhuo** [kiali/kiali#4797]
Choose the application node view:

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/48784001/157850068-632ca53c-2930-4346-bdbd-afb6dcf5444c.png">

As you can see, the list allows us to choose service graph and workload graph( which is confusing ).

<img width="921" alt="image" src="https://user-images.githubusercontent.com/48784001/157850206-1a9eed5e-96ca-4886-8e7d-06fc992cfdaf.png">

If we choose service graph, it is unsupported as expectation

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/48784001/157850145-3c3dc639-7300-4ac3-94a1-9d55c08e21ca.png">

If we choose workload graph, it is unsupported as expectation

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/48784001/157850172-e020db77-4c52-4678-9040-6174db5a0811.png">

Should we cut off workload/service graph in application graph node view? They should not be there.

**Comment by lucasponce** [comment]
So, the bug here is that when the user is in the graph node view, it can't change the type of graph.
If the proposal is to "lock" the dropdown to the type of the graph node, perhaps that's not a bad addition.

But I remember this was brought in the past, I'll wait for others maintainers to comment.

**Comment by jshaughn** [comment]
I'm not sure I'd call this a bug, because the situation is handled with proper messaging.  Maybe it's more of a UX improvement.  I haven't looked at the code, so I'm not sure why we are lazy about preventing the situation.  Anyway, if the change is easy I'm fine with it, but in general we don't remove options, we disable them when not applicable.

**Comment by israel-hdez** [comment]
I *do* think this is a bug.

If I remember correctly, on the _node_ graph you are not supposed to be able to change the graph type. If you do, you would no longer be viewing the same node that whatever previous page was referring to.

Probably, the bug was introduced when the graph type drop-down moved from the bottom/second toolbar to the upper/first one. I remember, in the past, the graph type was not available on the node graph.

**Comment by jshaughn** [comment]
OK, well let's resolve this.  I can take it.
