### ISSUE TITLE
Kiali graph is not working with disabled Istio's /debug endpoints

### ISSUE THREAD

**Issue by NamalaR1** [kiali/kiali#4798]
We recently upgraded Kiali version from v1.39 to v1.47.0 to address go vulnerability found in v1.39. After the upgrade , Kiali stopped working and it's unable to pull graph data from the mesh.

![image](https://user-images.githubusercontent.com/51207992/157930414-89a5170e-97a8-488c-b495-e48d95a27891.png)

On further investigation, we found that new version of Kiali started using istiod's /debug endpoints to pull the mesh information, since we disabled this endpoint as per Istio's security best practices [https://istio.io/latest/docs/ops/best-practices/security/#control-plane] Kiali stopped working altogether.

flag to disable this endpoint -> ENABLE_DEBUG_ON_HTTP

**Comment by jshaughn** [comment]
What is your Istio version? Maybe a compat issue? https://kiali.io/docs/installation/installation-guide/prerequisites/#istio-version-compatibility

**Comment by NamalaR1** [comment]
we are at 1.11.4 but in the process of migrating it to 1.13 but the problem still exist right as long as kiali uses /debug endpoints?

**Comment by NamalaR1** [comment]
and the go vulnerability is only fixed on 1.47
https://github.com/kiali/kiali/blob/v1.47/go.mod#L3

**Comment by jshaughn** [comment]
I'm not an expert in this area, I'd wait for @lucasponce to comment. But as I understand it, Kiali does use a subset of the istio debug endpoints in order to utilize the information in the Istio registry.  This gives Kiali a more robust ability to work with services resulting from istio config, and other entries, that may not exist via the straight k8s API.  I think access will need to be granted to allow Kiali to use those endpoints.

I don't currently see anything on kiali.io discussing this potential configuration need, if it's required I think the docs will need to be updated.

**Comment by lucasponce** [comment]
Well, Kiali is using the same design as "istioctl" to fetch Istiod status that is used to provide some features to Istio users, such as validations and access to the Istio configuration resources.

As it's commented in the documentation, disabling those endpoints will stop working these features both in "istioctl" and "kiali":

![image](https://user-images.githubusercontent.com/1662329/158136954-30ac90d7-5ecc-435d-9dbc-3e59dcf29453.png)

I don't see a proper alternative, but protect those endpoints in another way, rather than disable them.

Otherwise, users won't have information if the control plane is synced, and also in Kiali, instead to query the Istiod status to collect the Istio configuration in a single request, it would require to iterate per all namespaces introducing performance penalties in the cluster.

I can understand the scenario, perhaps this can trigger a request on the Istio side to offer a different protection mechanism.

With those endpoints disabled, yes, "istioctl" and "kiali" will not work.

**Comment by jshaughn** [comment]
@lucasponce , I think we should use this just as a documentation issue.  We should probably add this into the installation or prerequisite docs.

**Comment by NamalaR1** [comment]
> Well, Kiali is using the same design as "istioctl" to fetch Istiod status that is used to provide some features to Istio users, such as validations and access to the Istio configuration resources.
> 
> As it's commented in the documentation, disabling those endpoints will stop working these features both in "istioctl" and "kiali":
> 
> ![image](https://user-images.githubusercontent.com/1662329/158136954-30ac90d7-5ecc-435d-9dbc-3e59dcf29453.png)
> 
> I don't see a proper alternative, but protect those endpoints in another way, rather than disable them.
> 
> Otherwise, users won't have information if the control plane is synced, and also in Kiali, instead to query the Istiod status to collect the Istio configuration in a single request, it would require to iterate per all namespaces introducing performance penalties in the cluster.
> 
> I can understand the scenario, perhaps this can trigger a request on the Istio side to offer a different protection mechanism.
> 
> With those endpoints disabled, yes, "istioctl" and "kiali" will not work.

Yep, I noticed that I believe they forgot to update the documentation as well. I believe they need this for istioctl for debug purposes and use it in lower envs. Many places they recommend this to disable in production env

https://istio.io/latest/docs/reference/commands/pilot-agent/
![image](https://user-images.githubusercontent.com/51207992/158242655-5c6a2b48-330a-44ea-bae0-ce22913a8e09.png)

**Comment by lucasponce** [comment]
There are three types of debug handlers used in pilot: debug, profiling and admin.

The only way to access to the status of the proxies and the Istio registry is through the Istio debug endpoints, so yes, I don't see a way to provide status info without those ones.

But I also +1 to not enable profiling and/or admin endpoints.

We'll update the information, but from the Istio user perspective when something doesn't work as you expect, those endpoints will give extra information about the status, Kiali is just a high-level UI interface that adds value to operate them.

**Comment by jshaughn** [comment]
I'm -1 on this proposed option.  Kiali would be badly crippled and we would have more testing paths.  I think we should just document the requirements.  If there is a major groundswell against the decision we can revisit.

**Comment by lucasponce** [comment]
For security reasons, to have those endpoints enabled and add a security rule that only the Kiali pod may access is a better workaround alternative than "eliminating" that core feature.

**Comment by nrfox** [comment]
> I'm -1 on this proposed option. Kiali would be badly crippled and we would have more testing paths. I think we should just document the requirements. If there is a major groundswell against the decision we can revisit.

Agreed I don't think it's a _good_ option given the amount of work involved in maintaining it unless there are significant requests for it.

> For security reasons, to have those endpoints enabled and add a security rule that only the Kiali pod may access is a better workaround alternative than "eliminating" that core feature.

That seems like a good alternative for users who require a more locked down environment.
