### ISSUE TITLE
Cross-namespace endpoints

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#4832]
From discussion: https://github.com/kiali/kiali/discussions/4801

Kiali should provide cross-namespace endpoints for any resource that will need to be queried per namespace by the UI. For example:

- [x] Workloads: `/api/workloads`
- [x] Services: `/api/services`
- [x] Apps: `/api/apps`
- [x] Validations: `/api/validations`
- [x] Health: `/api/health`
- [x] Metrics: `/api/metrics`

Queries can be limited to a specific namespace by query params e.g. `/api/workloads/?namespaces=bookinfo,default,istio-system`. Here requested namespaces are specified as a comma separated list.

The `*` param will be interpreted as "all namespaces that the requesting user has access to". This is useful in cases where the user "selects all" namespaces on the front-end. For example, if 3 namespaces exist named `ns1`, `ns2`, and `ns3` and the user has `get` permission rights on `ns1` and `ns2` but not `ns3`, information for `ns1` and `ns2` will be returned by not `ns3`.

There could be thousands of namespaces, each with very long names, but URLs are limited in size so the UI will need to make multiple requests to fetch data for all the namespaces in these cases. It will still be cheaper than the cost of the UI making an individual request _per namespace_.

Optionally, regex support can be added for namespace filtering e.g. `/api/workloads/?namespaces="^development.*"`. This is more of a optimization that can be added later if support is added on the front-end in the namespace selector.

**Comment by lucasponce** [comment]
> There could be thousands of namespaces, each with very long names, but URLs are limited in size so the UI will need to make multiple requests to fetch data for all the namespaces in these cases. It will still be cheaper than the cost of the UI making an individual request per namespace.

Well, for this situation when we have a large population of namespaces I think that the main pain point would be the design of the backend.

https://github.com/kiali/kiali/issues/4678

The endpoint design would help, but it won't have a real impact compared to enabling cluster-rights and taking that assumption on some circumstances (nothing strange, most of the Kubernetes admin consoles take this).

Multiplexing URLs are good, and I think handlers can be improved in that way, but the real work would be to use the "--all-namespace" semantic in the backend, which we couldn't use due to the cluster-less restriction.

To me is doable to point a user to give Kiali cluster rights under high namespaces population.

**Comment by hhovsepy** [comment]
It seems this task is already done, in a scope of perf optmization epic.
