### ISSUE TITLE
Move OpenShift authentication to use the "authorization code" flow

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#4890]
The OpenShift authentication is currently using OAuth's _implicit flow_. For improved security, OpenShift auth should use the OAuth _authorization code_ flow.

**Comment by israel-hdez** [comment]
From a security perspective, I think "experts" would say that the _authorization code_ must be preferred. I would say this is on the "Important / Not Urgent" quadrant of the Eisenhower Matrix. However, it does not fit in current priorities.

I would be tempted to ask for a contribution, although I'm not sure if it makes sense given this is for OpenShift.

I'm going to ping @nrfox for a 2nd opinion.

**Comment by israel-hdez** [comment]
ping @nrfox ^

**Comment by lucasponce** [comment]
Note that third-party plugins like https://github.com/kiali/openshift-servicemesh-plugin rely on this flow.

Just be sure that the proposed changes/work in this area is compatible with the use cases that are already in place.

**Comment by nrfox** [comment]
Sorry I missed this one. I'd agree with @israel-hdez that this one is important but not urgent since, from what I understand, the implicit flow just makes it easier for users to leak their access token by opening them up to more attacks but isn't a leak itself. I'd advocate for it going on the backlog though since it's a security hardening issue particularly within Openshift. I don't have a great sense of the scope of changes required here but iirc Kiali already handles the authorization code flow for OIDC so implementing this could reduce the number of differing auth strategies within Kiali.
