### ISSUE TITLE
Provide a way to get API coverage by Integration Tests

### ISSUE THREAD

**Issue by mattmahoneyrh** [kiali/kiali#4988]
The Python E2Es provided a method to get the API test coverage by evaluating existing API tests against SWAGGER API definitions.

https://github.com/kiali/kiali/blob/master/tests/e2e/tests/test_api_methods.py#L59

Consider providing a way to get a list of API entry points that are not covered by current Integration tests, as be be able to easily identify new test case coverage.

**Comment by lucasponce** [comment]
I'm not sure about this one.
The swagger may be deprecated as the API is private.
Also, we can maintain some kind of annotation, but I'd prefer if we shift into the coverage of the UI test.

The UI page defines the "flow" between those private API and personally, I'd prefer to have more UI flows that covers multiple endpoints rather than endpoints tests that may not test the whole feature.

Having said my comment is to not rely on swagger as it may be reconsidered.

**Comment by jshaughn** [comment]
Closing as out-of-scope
