### ISSUE TITLE
Fix "info" icons in the yaml config editor

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#5097]
After the Patternfly update we lost the "Info" icons in the yaml editor.  We need to fix this regression.

![image](https://user-images.githubusercontent.com/1662329/166652383-2560e2d5-2be3-42b1-b986-667dafa14d0b.png)

**Comment by josunect** [comment]
@jshaughn , I think this is because in firefox had a different style:
![Screenshot from 2022-05-25 11-20-55](https://user-images.githubusercontent.com/49480155/170247444-ecdf938f-c02a-48f3-b684-43982d449660.png)

I've changed to show in Firefox and Chrome: 

![Screenshot from 2022-05-25 11-56-12](https://user-images.githubusercontent.com/49480155/170247557-a21d5fdb-1b29-4ed7-a1e7-02ce48708f78.png)

If that looks good, I will create the PR. 

Regards,

**Comment by lucasponce** [comment]
@leandroberetta can help on this as he worked on that feature.
He can guide you if you'd need more details about the design.

**Comment by josunect** [comment]
Thanks, @lucasponce , I'll ask him.

**Comment by josunect** [comment]
The original icons, thanks @leandroberetta 

![image](https://user-images.githubusercontent.com/49480155/170486845-61f42072-8a64-4f0d-8176-7e817f135596.png)
