### ISSUE TITLE
kiali.io CI is validating against staging.kiali.io

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#5136]
HTML-Proofer is validating the url staging.kiali.io instead of the netlify link that the PR deployment is creating. 

See: https://github.com/kiali/kiali.io/runs/6687054315?check_suite_focus=true

`External link https://staging.kiali.io/docs/contribution-guidelines/development-environment/ failed: 404 No error`

Instead of checking:

`https://deploy-preview-537--kiali.netlify.app/docs/contribution-guidelines/development-environment/`

cc @jmazzitelli

**Comment by jmazzitelli** [comment]
I think we knew about this, but left it the way it is. I can't remember why :)

@jshaughn Do you remember why we validate staging during the PR CI checks?

**Comment by jshaughn** [comment]
I really don't remember, but perhaps it just wasn't possible to access the netlify link for the htmlproofer.  @josunect, feel free to investigate this but unless it's an easy change it's probably not worth spending too much time.

cc @israel-hdez @leandroberetta for any input here.

**Comment by josunect** [comment]
There is an specific section in the html-proofer documentation that explains this situation - there are some new files in a pull request, and the tests are failing because links to those files are not live yet: 

https://github.com/gjtorikian/html-proofer#ignoring-new-files

**Comment by jshaughn** [comment]
Right.  I think we were just deferring to the PR writer to sanity check the errors and decide whether they were valid.  You can try and impl the suggestion about ignoring files, if you like.   If you prefer to leave things as they are, that's OK too.  Up to you.

**Comment by israel-hdez** [comment]
> See: https://github.com/kiali/kiali.io/runs/6687054315?check_suite_focus=true
> 
> `External link https://staging.kiali.io/docs/contribution-guidelines/development-environment/ failed: 404 No error`
> 
> Instead of checking:
> 
> `https://deploy-preview-537--kiali.netlify.app/docs/contribution-guidelines/development-environment/`

It is because indexes/TOCs are being generated with full absolute URLs, using the [`baseURL` configured in the `config.toml` file](https://github.com/kiali/kiali.io/blob/staging/config.toml#L1).

I think that even if we change it to be the URL of the Netlify preview, there is no warranty that CI will pass, because it's two independent processes (the netlify service and our own CI). So, there is no warranty that the preview is available at the time the `htmlproofer` runs.

I'm not sure how to fix that. Perhaps, we may need to run CI with a blank baseURL, or with '/' to fix that issue?

**Comment by jshaughn** [comment]
I'm going to close this one as low priority.
