### ISSUE TITLE
Reorganize the Overview page to better show data plane vs control plane status

### ISSUE THREAD

**Issue by lucasponce** [kiali/kiali#5167]
Today Kiali's overview page is focused on the data-plane status:
![image](https://user-images.githubusercontent.com/1662329/172578782-53523e92-be4f-4046-a95e-eb9d71b4c97b.png)

It shows pretty much the same information provided by the "Mesh Dashboard" which is also focused on the data plane:
![image](https://user-images.githubusercontent.com/1662329/172578936-79a8a55a-fcee-4356-9102-af646b8c25f1.png)

Global ratio, % of errors, and health per app/services/workloads. It also allows to operate per namespace level:
![image](https://user-images.githubusercontent.com/1662329/172579229-3798919e-d8ca-44be-918e-777942c12b9f.png)

The "control plane" is handled like another regular namespace on the page, but it's also special as it has some specific "control plane" options that are less visible:
![image](https://user-images.githubusercontent.com/1662329/172579616-330d38c6-583d-4082-ab56-98ff8015eca8.png)

I think this epic could be used to review how to make a better distinction on this page for the control plane namespace, and probably try to better add in the "istio-system" card, a status that belongs to the control plane itself:
![image](https://user-images.githubusercontent.com/1662329/172580001-e8c6f08a-cffe-45b7-9a19-45248c9a5bbb.png)

So, a proposal could be that the "istio-system" (or any other namespace that works like a control plane) may have a slightly different design and show a combined status with the relevant info, but it's still kept integrated into the overview view (compact, expand, list).

**Comment by leandroberetta** [comment]
@andrew-ronaldson thanks for your ideas, and yes, this looks good and it's what I'm doing right now.

Also, we discuss about adding more information about the control plane in the Mesh section, I will attach an screenshoot next:

![image](https://user-images.githubusercontent.com/1286393/177199710-ecb2f773-86fe-4b52-bae1-57f97958a43a.png)

Although, this section is used mainly to show different control planes (meshes, if 1 mesh = 1 control plane) Kiali has configured to talk to, I guess we can use it to show more detailed information about control planes. 

I'm not sure about the naming "Mesh", and the header "Clusters". 

What do you think?.

My original idea or what I would like to do of course is give the control plane a proper dashboard, with unique graphs compared to the dataplane ones. This section could work or maybe we can add another one.

**Comment by lucasponce** [comment]
@leandroberetta but this issue is focused first on the Overview page.
And yes, from the overview page you can link to the Mesh details that probably will grow from this "Mesh" page.

But that's a different Epic https://github.com/kiali/kiali/issues/4435 that would evolve.

**Comment by leandroberetta** [comment]
Yes, you're right, I will keep this effort to just the card in the overview page, glad we talked yesterday, I was actuallty starting to update the Mesh section :D.

**Comment by leandroberetta** [comment]
From my investigation about control plane monitoring, the following metrics can be used for certain aspects of the control plane:

**pilot_proxy_convergence_time**

The time (latency) since there is an update until that change arrives to workloads (as an Envoy configuration)

**container_cpu_usage_seconds_total**

This is the CPU usage (saturation) of the istiod process. 

**process_virtual_memory_bytes**

Also the memory usage, the virtual seems to be the more important to show.

**pilot_total_xds_rejects**

Errors are important to monitor, and they often occur when there is a performance issue.

**pilot_services**

A good way to see the size of a mesh, a number to see how many services pilot knows.

**pilot_xds_pushes**

The number of pushes made by the control plane (clusters, listeners, routes and endpoints).

This information is preliminar but looks promising if in the future we add tresholds (recommended ones or configured by the user) so users can monitor and act better in case of the need of scaling.

For the card in the overview page, I think it's a lot of information but this could be useful for the future task of giving the control plane a proper section (and maybe the control planes thinking in a multi mesh scenario). The epic https://github.com/kiali/kiali/issues/4435 is related to this.

For the overview card, I'm working to add the cpu, memory and the time pilot lasts to update all the data plane.
