### ISSUE TITLE
Add Argocd Rollout as workload type to Kiali.

### ISSUE THREAD

**Issue by tomahkvt** [kiali/kiali#5261]
We are using Argocd rollout instead Kubernetes Deployment because Argocd rollout has more features.
But we have a problem with Workload visualization in Kiali. The picture you can see below.
![image](https://user-images.githubusercontent.com/13186324/176418107-47388b33-4233-46f8-965b-f78e3a063254.png)
We are using Kiali virsion v1.50.0.
We analyzed the Kiali code and find out that there is no workload type.
Please add the flowing Workload type to kiali:
apiVersion: argoproj.io/v1alpha1  
kind: Rollout 
You can read more about Argocd by using this reference: https://argoproj.github.io/argo-rollouts/migrating.
Thank you in advance.

**Comment by lucasponce** [comment]
I guess you should have minimal support for this, at least in the telemetry.
Perhaps some label at pod generation is missed.

Is this scenario easily deployable in a demo cluster?

The policy for "custom controllers" (i.e. different from Deployments, etc) is to have only basic features from the pods, so we don't plan to support them all or 100% features (contributions are welcome!) but at least using the default pods I think the workloads logic should capture more information than you show here.

Worth to take a look.

**Comment by leandroberetta** [comment]
Hi, I'm also investigating the following issue related to Argo rollouts (https://github.com/kiali/kiali/issues/4210), it could be related but not sure. 

I will take a look too.

**Comment by jshaughn** [comment]
Adding to the backlog as we've now had multiple reports of bad behavior for ArgoCD rollouts, and ArgoCD seems to be a popular approach.

**Comment by jshaughn** [comment]
@leandroberetta The issue here seems to be confusion about what should be a workload from Kiali's perspective.  The workload list seems to be capturing the rollout itself, which I think is the workload controller and it can be responsible for one or more replicasets.  The istio telemetry reports the replicaset as the workload, and so there is a mismatch.  If Kiali were to list the replicasets as the workload then the graph would probably be happy.  We should talk more about how Kiali should handle this situation.
