### ISSUE TITLE
easy UI way to "hide" a node

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#5350]
Kiali has an option to "hide" nodes - but you have to know the syntax and what the name of the nodes you want to hide.

It would be nice to just be able to click on a node in the graph, right mouse click, and in the popup menu get an option "Hide". When you select it, the name of the node (or whatever) gets populated in the "hide" text box so the node is hidden. This way its quick for the user and the user doesn't have to know what/where/how to enter the node information to hide it.

For example, I want to hide the jaeger collector node - I just want to click on it and say "GO AWAY!" and have it get hidden.
![image](https://user-images.githubusercontent.com/2029470/181824235-ce5728f5-3997-4266-b4c9-49caddd77eec.png)

**Comment by jshaughn** [comment]
This seems a little like a slippery slope, because you would have to be able to ensure the addition is valid with an existing hide expression, and how do you get it back?  I guess if it's just one you can delete the the hide expression, but if you have added to an existing expression or clicked on multiple nodes, it seems more tricky.   I don't know, maybe it's not too hard and you could just prepend an "app=xyz [AND]" sort of thing and not worry much about the removal.
