### ISSUE TITLE
dev env needs to be able to deploy using OLM

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#5364]
One thing we are missing is the ability to have our dev environments easily deploy the operator using OLM. We have our make targets that hide the actual deployment mechanism - they use helm under the covers. Which is nice - those make targets essentially test out the helm charts to ensure they are correct. But we need something similar to test deploying on OLM. This will allow us to find and fix bugs related to our metadata. Today, we do not have an easy way to do this (in fact, we don't do any OLM testing other than downstream). We need something to be able to test things in an upstream/dev environment.

We can copy what we do in the new plugin make infrastructure. It also has make targets that run the operator locally using the SDK (which is another useful dev/testing environment - it allows us to run the operator locally in the exact same manner as the operator runs in cluster). See: https://github.com/kiali/openshift-servicemesh-plugin/blob/main/make/Makefile.operator.mk#L134-L144 and https://github.com/kiali/openshift-servicemesh-plugin/blob/main/make/Makefile.olm.mk

**Comment by jshaughn** [comment]
Relevant Slack Convo:

[Jay Shaughnessy]
If you do that does it just overlap downstream testing?

And then what will test the helm charts?  which is the preferred upstream mechanism, no?

[John Mazzitelli]
in some sense, yes, but in other senses no. it actually can be used to test installing with olm on non-openshift (this would be testing our manifests that we ship in [OperatorHub.io](http://operatorhub.io/), for example). But even for OpenShift, it allows us to actually install using OLM rather than helm - so we don't have to wait to build a downstream build and get QE to run tests to see things work (or break). Right now, we have no idea if, for example, our permissions are correct in the olm metadata - we just build downstream and cross our fingers that when QE tests stuff it works. And when it doesn't work, we have to change the metadata, build another downstream and test that again. Tehre is no way today to easily test our metadata outside of building downstream and getting QE to test it

I plan on leaving what we have alone - so we are still going to test using helm by default.

i'm going to add some new make targets to say "operator-create-via-olm" or something like that

**Comment by jmazzitelli** [comment]
This is done and the PRs are ready for testing.
