### ISSUE TITLE
[CI] Test flake - workload details

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#5407]
Scenario: See Envoy metrics for a workload

Example: https://github.com/kiali/kiali/runs/7997292946?check_suite_focus=true

Screenshot from failure:
![Kiali Workload Details page -- See Envoy metrics for a workload (failed)](https://user-images.githubusercontent.com/6226732/186470166-bbd23bc7-8299-473c-b1a6-28acb5a3bbcb.png)

**Comment by hhovsepy** [comment]
It seems failure happens when "API.getCustomDashboard" is returned, but the sate.dashboard is not set yet, thus dashboards are not drawn: but tests wait until "API.getCustomDashboard" response and expects dashboard to be not empty.
For instance for traces tests, there is a "No traces" div  which disappears when traces response comes.

**Comment by hhovsepy** [comment]
Should be fixed now.
