### ISSUE TITLE
make container securityContext configurable

### ISSUE THREAD

**Issue by sdomme** [kiali/kiali#5455]
Hello. It would be nice to have securityContext for containers in the Helm Charts configurable. Since #5409 shows us difficulties to provide the right configuration for different k8s flavours, imho it would make sense to set some sensible defaults and give the user the freedom to configure it themselves.

Thanks.

**Comment by jmazzitelli** [comment]
changed title - it is more than just the helm charts - need to support this in the operator so a Kiali CR can define a context for the kiali server.

**Comment by jshaughn** [comment]
I think this one gets a "head of the line" pass, as this has definitely become a hot topic lately.

**Comment by jmazzitelli** [comment]
My first iteration of the implementation will be to provide an entire override of the security context. So the user can override completely the security context.

But as I am doing this, I'm getting paranoid. There should be some settings that the user need not (and should not) be able to override. I'm thinking of things like:

```
           allowPrivilegeEscalation: false
           privileged: false
           runAsNonRoot: true
```

Those should probably be non-negotiable. Eliminating those may provide a way to introduce a backdoor security hole. So I'm not sure if providing a full override is the proper thing to do. I will continue with this as a first iteration, but the implementation might change if it is decided to make some of these settings non-negotiable.

**Comment by jmazzitelli** [comment]
Here is how the solution will work.

The operator helm chart has a `securityContext` value that defines the operator container securityContext. The server helm chart has a `deployment.security_context` value that defines the server container securityContext. Whatever you set in those values will be the full securityContext of the server/operator container. You must, therefore, ensure you provide a full and complete securityContext or else the pod will not start properly.

There is now a `deployment.security_context` setting in the Kiali CR. When the operator sees it, it will use that as the kiali server container's securityContext. HOWEVER! By default, the operator will not pass through that securityContext and use it as the full securityContext of the server container - it will only do this if you change the operator's env var `ALLOW_SECURITY_CONTEXT_OVERRIDE` to "true". You can do this if you install the operator via the helm chart and pass in `--set allowSecurityContextOverride=true`. If you do this, ensure you provide a full and complete `deployment.security_context` or else the server pod will not start properly. The default behavior of the operator (i.e. `ALLOW_SECURITY_CONTEXT_OVERRIDE=false`) is that it will keep the default securityContext settings but will allow you to add additional security context settings as defined in the `deployment.security_context` value. This is useful, for example, if you need to set `seccompProfile` on the securityContext of the kiali server pod.

There are two PRs:
* https://github.com/kiali/kiali-operator/pull/568
* https://github.com/kiali/helm-charts/pull/166
with a third doc PR:
* https://github.com/kiali/kiali.io/pull/579

Test procedures for the helm chart changes are [here](https://github.com/kiali/helm-charts/pull/166#issuecomment-1245508869).
Test procedures for the operator are [here](https://github.com/kiali/kiali-operator/pull/568#issuecomment-1245625717) and [here](https://github.com/kiali/kiali-operator/pull/568#issuecomment-1245861346).

**Comment by jmazzitelli** [comment]
cc @sdomme please read the last comment above. I believe this will do what you need it to do.

**Comment by sdomme** [comment]
@jmazzitelli First of all, thanks for the fast implementation. If feedback is allowed, here are my 2 cents. It might be a matter of taste for the naming, but in nearly any Helm chart I used, developer used something like `.Values.deployment.securityContext` or `.Values.deployment.containerSecurityContext` if you need to distinguish between POD and container Level. Maybe worth a look here https://helm.sh/docs/chart_best_practices/values/#naming-conventions

What about to set this [deployment.yaml](https://github.com/kiali/helm-charts/blob/3aefd9f2d640132d5bac63742a2d5cf2b1b7e4b8/kiali-server/templates/deployment.yaml#L67-L73) as default value in [value.yaml](https://github.com/kiali/helm-charts/blob/3aefd9f2d640132d5bac63742a2d5cf2b1b7e4b8/kiali-server/values.yaml#L73) ? In your implementation you could override the whole securityContext anyways.

**Comment by jmazzitelli** [comment]
_<tl;dr>In short, yes, we know the server helm chart deviates from some helm chart conventions, but that is done on purpose for reasons of maintainability and consistency with the operator.</tl;dr>_


> t might be a matter of taste for the naming, but in nearly any Helm chart I used, developer used something like `.Values.deployment.securityContext` or `.Values.deployment.containerSecurityContext`

If the concern here is the difference between camelCase and snake_case, there is a reason why the server helm-chart uses snake_case (against the typical helm conventions which uses camelCase). It is because we keep the naming convention of the settings so they are identical with the Kiali CR settings. This way the user of the server-helm chart can follow basically the same Kiali documentation as the operator user (e.g. [here](https://kiali.io/docs/configuration/kialis.kiali.io/)). Otherwise, we are going to have names of settings that are different depending on whether someone is using the server helm chart or the operator Kiali CR to configure the Kiali Server, and that makes documentation and support harder. In other words, we are opting for consistency here. We do not want to have to write different or special documentation for server helm chart users - the less amount of work we have to do to maintain the server helm chart the better because we don't even recommend people use the server helm chart (as our docs [state](https://kiali.io/docs/installation/installation-guide/install-with-helm/#introduction), "Although the kiali-server Helm Chart is actively maintained, it is only provided for convenience. The recommended method to install Kiali is by using the kiali-operator Helm Chart to install the Operator and then creating a Kiali CR to let the operator deploy Kiali.")

As for why we use snake_case in the first place with the Kiali CR settings, that is simply a matter of legacy - when the operator was first implemented a few years ago (at which time there wasn't even kiali helm charts) we needed to use snake_case at the time to easily implement it using the Ansible Operator SDK. It's too late to change that convention now for backward compatibility reasons.

> What about to set this [deployment.yaml](https://github.com/kiali/helm-charts/blob/3aefd9f2d640132d5bac63742a2d5cf2b1b7e4b8/kiali-server/templates/deployment.yaml#L67-L73) as default value in [value.yaml](https://github.com/kiali/helm-charts/blob/3aefd9f2d640132d5bac63742a2d5cf2b1b7e4b8/kiali-server/values.yaml#L73) ? In your implementation you could override the whole securityContext anyways.

The reason for this is because, again, we are trying to maintain consistency with the operator code. For maintenance reasons, we try to make the server helm chart templates look as close as possible to the operator templates. e.g. see the new [server helm template](https://github.com/kiali/helm-charts/pull/166/files#diff-2e81dd9315eaaa0e3ff37eed9725696f00443d93f64da7e0e8f645270608132f) compared to the [operator template](https://github.com/kiali/kiali-operator/pull/568/files#diff-bc30d1d38d9f4fd8fe0ef8affe36976a11b729129db008c0635738e23ff13746). Granted, the reason why the operator looks the way it does is because the operator has the additional feature (which the server helm chart does not) of being allowed to ignore some of these user-defined security context settings (if the kubeadmin wants to configure the operator like that, for security purposes - that is the purpose of why [these new docs](https://github.com/kiali/kiali.io/pull/579) need to be added as part of this enhancement request); but the point is, we want the templates to look as close to the same as possible because it is easier for kiali developers to maintain these files when they do.
