### ISSUE TITLE
Migrate the control plane related information from the masthead to the control plane card 

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#5525]
The masthead has a few status indicators that appear if some component is not healthy. A few of the monitored components are: the istiod deployment, istio gateways, prometheus, grafana, jaeger, etc.

Although these indicators are good, the masthead is not visible on kiosk mode making the status indicators unavailable. Thus, moving the status indicators to the control plane card in the overview page would better support kiosk and non-kiosk mode.

Alternatively, status indicators could, simply, be replicated in the control plane card (i.e., not removed from the masthead).

Epic #4435

**Comment by israel-hdez** [comment]
@jshaughn You commented [here](https://github.com/kiali/kiali/issues/4435#issuecomment-1263908830) about decorating the Overview menu item.

You mean the main menu at the left?
That would mean moving what is in the masthead to the menu, no?

I do like having these indicator available at hand. So, I wonder if rather than _moving_ maybe we should simply replicate the same information in the control plane card to support kiosk mode.

Moving from masthead to the Overview menu item sounds OK if the card would show more details. But if the card will show the same information, I'm not sure if it makes sense to do the move.

**Comment by jshaughn** [comment]
> You mean the main menu at the left?

I do think the information should be on the Control Plane card.   The nice thing about the masthead is that (in non-kiosk) it immediately reflects an infrastructure issue regardless of the Kiali page you are looking at.  Which is a good thing because the infra issue could affect any given page.  I was thinking that an indicator in the left menu may be an alternative, but actually Kiosk mode also doesn't show the left menu.  OSSMC does have a menu but that's independent of kiosk mode.  So, I think I will retract my comment because I don't see a way in kiosk mode to show some sort of global information regardless of the page you are on.   Keeping the indicator on the masthead, and replicating to the ControlPlane card seems like a good idea.  The ControlPlane card could also render a "green",  showing healthy.
