### ISSUE TITLE
Investigate the idea of Kiali working with no istiod connection

### ISSUE THREAD

**Issue by josunect** [kiali/kiali#5626]
Investigate and define how Kiali should work - in a limited way - when there is no connection with Istiod. 

At the moment there is a hard dependency with Istiod, used to retrieve data that Istio has in memory, and also the Istio configuration. 

This is an example (With anonymous auth - special case as it uses the Istio SA to access the resources)

![image](https://user-images.githubusercontent.com/49480155/201335640-b1346710-8240-40fb-83ff-910d17583c01.png)
![image](https://user-images.githubusercontent.com/49480155/201335689-d8ecf297-18d2-488d-bf18-df260fc11ab8.png)
![image](https://user-images.githubusercontent.com/49480155/201336550-d64894a5-b155-49c0-9138-54e840edaeb3.png)

**Comment by jshaughn** [comment]
Thanks @josunect for opening the issue.  This also relates to the "Anthos" issue reported in https://github.com/kiali/kiali/issues/5404.  In short, there are probably going to be deployment scenarios where the Istiod "debugz" API is unavailable to Kiali, whether it's due to the overall deployment model, or specifically shut down.  In those cases we should be able to run Kiali in a limited, bt well-defined fashion, documenting the features that will not be available.

**Comment by josunect** [comment]
I've written a document explaining a bit more the issue and identifying the failures: https://docs.google.com/document/d/1XjkodS5Uu14C_1l3-j7iNaWfLufQFycY-cKMlagIxyc/edit#heading=h.n6xytn5qv823
