### ISSUE TITLE
Support for  out-of-cluster  deployments and one kiali supports multiple istios

### ISSUE THREAD

**Issue by zengyuxing007** [kiali/kiali#5681]
kiali should be stateless, in the absence of cache.
This way we can deploy just one kiali (out of cluster) to see multiple istio meshes

**Comment by jmazzitelli** [comment]
> deploy just one kiali (out of cluster) to see multiple istio meshes

This is probably never going to happen. Kiali has always been intended (and has been implemented) to view a single mesh. And Kiali is not intended (and never has been intended) to be run outside of a cluster (i.e. there isn't any supported way to run Kiali out of a k8s cluster).

But I can also say that it is easy enough to install multiple Kialis (even in the same namespace) in order to have multiple mesh views (but again one Kiali per mesh).

**Comment by jshaughn** [comment]
Closing as out of scope.  We are working to expand Kiali support to a multi-cluster mesh, but not multiple meshes for a single Kiali.  And we are not currently looking at supporting Kiali outside of Kubernetes.

**Comment by zengyuxing007** [comment]
Many users should have more than one mesh, and deploying one Kiali per mesh feels like a waste of resources. 
Are there any benefits to One Kiali Per mesh? Or is One Kiali Support multiple mesh not technically feasible?

**Comment by jmazzitelli** [comment]
As @jshaughn says, it is out of scope for the Kiali project. We have not had many requests for Kiali to support one-Kiali-per-multiple-mesh use cases. By comparison, the Kiali user base has been very emphatic that they want better support for multi-clusters , so that is where the focus is for the Kiali project - to better support one mesh across multiple clusters.

Anything is technically feasible if you put enough time and manpower into it, but it would be difficult to update the Kiali code for it to support multiple meshes. It is more than just updating the server itself, too. The helm chart and operator would also need to be updated to support this feature as well.

**Comment by israel-hdez** [comment]
@zengyuxing007 I agree that this issue is out of scope.

Let me add that this is the position for the main maintainers as we are quite busy on adding features for single mesh. However, we are always happy to review and merge contributions. So, if you have the time and knowledge, please consider contributing the code to implement your own request.

**Comment by zengyuxing007** [comment]
> @zengyuxing007我同意这个问题超出范围。
> 
> 让我补充一点，这是主要维护者的职位，因为我们非常忙于为单个网格添加功能。但是，我们总是乐于审查和合并贡献。所以，如果你有时间和知识，请考虑贡献代码来实现你自己的请求。

@israel-hdez  

Okay, thanks for your reply~
