### ISSUE TITLE
IRC link on kiali.io is not working

### ISSUE THREAD

**Issue by ferhoyos** [kiali/kiali#5739]
Hi,

IRC link at the bottom of kiali.io page navigates to page https://kiali.io/web.libera.chat?channels=#kiali. This page does not exist.

![image](https://user-images.githubusercontent.com/122779323/213517841-dd25c1a0-6a69-41d8-af1b-454d605f7951.png)

If IRC page is no longer available the link should be deleted.

**Comment by jmazzitelli** [comment]
We should probably remove that entirely.  We don't actively participate in IRC anymore. Our user communication channels are either over github discussions, issues, or the Istio Slack channel #kiali.

**Comment by jshaughn** [comment]
@ferhoyos , This was fixed twice because you did the work without assigning yourself to the issue or adding it to the sprint.  You are forgiven and thanks for being proactive!   But, before working on an issue make sure you are assigned and that the issue has been prioritized for the sprint.  Thanks!
