### ISSUE TITLE
Support Envoy stats natively

### ISSUE THREAD

**Issue by liamawhite** [kiali/kiali#578]
Currently, Kiali only supports stats that mixer produces. As Envoy will be being scraped directly in the near future (and for mixerless deployments) Kiali should support Envoy stat labels as scraped by Prometheus.

**Comment by abonas** [comment]
@pilhuhn @lucasponce @mwringe we should move this to JIRA.
@liamawhite thank you for the notice! Do you have any information/point to docs/timeline regarding the change of Envoy being scraped directly?

**Comment by jmazzitelli** [comment]
Does this mean in the near future it is possible for the istio-* metrics to be missing/go away? That would be bad because those are the metrics that Kiali uses to build the graph visualizations.

**Comment by jotak** [comment]
Oh, I see the Envoy stats are now labelled in a "friendly" way (in 1.1.0 snapshot). That's very nice!

Ex:
`envoy_cluster_membership_healthy{app="stadium",cluster_name="BlackHoleCluster",instance="172.17.0.19:15090",job="envoy-stats",namespace="mesh-arena",pod_name="stadium-small-66888649cb-rsjk5",pod_template_hash="2244420576",version="small"}`

@liamawhite thanks for letting us know. I would like to understand what the `cluster_name` refers to, I can see three of them for every pod: `BlackHoleCluster`, `xds-grpc` and `zipkin`. I wonder if it makes sense to show the aggregate of all in Kiali or if some selection must be made.
Also, there's no reference of any workload, is it intentional? We could retrieve the workload based on pod name but it adds some cost.

We actually do already show some envoy stats but it's restricted about cluster membership as part of a service live health, it's not displayed as a timeseries.
We already have a JIRA to show timeseries about opened CB or such, iirc.

By the way, beyond cluster membership healthy versus total, do you think some stats should be particularly relevant to show?

@jmazzitelli I guess there's absolutely no impact on usual istio stats (at least I don't see any in 1.1.0-snap)

**Comment by liamawhite** [comment]
I may have misunderstood an earlier discussion with some of the telemetry team. Let me get back to you on the specifics or just how we're going to do this. I think it may be a combination of the two.
