### ISSUE TITLE
Read-only YAML editor in Istio Config even with write privileges

### ISSUE THREAD

**Issue by israel-hdez** [kiali/kiali#5836]
Given a user that does not have cluster-admin privileges and only has privileges in some namespaces. Given this user has access to Kiali and Kiali is configured to honor user privileges. Even if the user has read AND write privileges in a namespace, going to Istio Config and selecting any Istio resource there will open the YAML editor.

The editor will be in read-only mode and won't let the user change the resource, even if the user has the write privileges to do it.

**Comment by hhovsepy** [comment]
It seems the "admin" role for a "basic-user" on particular namespace it not considered, and Kiali is checking cluster roles.

**Comment by hhovsepy** [comment]
The issue comes from https://github.com/kiali/kiali/blob/master/business/istio_config.go#L1242
It return 'false' for all 3 verbs.

**Comment by hhovsepy** [comment]
For a "foo" user with "admin" role (not "cluster-admin") on a namespace (for instance `"oc adm policy add-role-to-user admin foo -n bookinfo"`) when checking `oc auth can-i create virtualservices --namespace bookinfo --as foo` it returns "no". Thus the YAML editor is read only.
@israel-hdez is your user able to create a config on particular namespace using console?
But I remember that YAML editor was saveable long time ago with "foo" user only having "admin" role on namespace.
cc @jshaughn @jmazzitelli

**Comment by israel-hdez** [comment]
> For a "foo" user with "admin" role (not "cluster-admin") on a namespace (for instance "oc adm policy add-role-to-user admin foo -n bookinfo") when checking oc auth can-i create virtualservices --namespace bookinfo --as foo it returns "no". Thus the YAML editor is read only.

In minikube, the problem with that `admin` role is that it has a list of resources. It may be the same in OpenShift. Use `oc/kubectl describe clusterrole admin`and check if it lists any Istio CRDs. If not, the `can-i` command is OK in replying with a `no` and Kiali would be OK in showing the YAML editor as read only.

In contrast, `cluster-admin` has a single `*.*` entry, which effectively matches all resources in the cluster. For testing purposes, I think it is acceptable to do `oc adm policy add-role-to-user clustesr-admin foo -n bookinfo` which would bind the role to the namespace rather than with cluster-wide effect. Then check what Kiali would do.

> @israel-hdez is your user able to create a config on particular namespace using console?

The way I was testing, is by creating the `ClusterRole` that I wrote in the new "RBAC" documentation: https://staging.kiali.io/docs/configuration/rbac/#granting-write-privileges-to-namespaces. Then, bind it to the user in a specific namespace (not cluster-wide).

By doing this, the YAML editor in Kiali is read-only, but it is possible to use the Wizards to successfully create, edit and delete those resources.

> But I remember that YAML editor was saveable long time ago with "foo" user only having "admin" role on namespace.

It depends how long ago :-)
If it was by the times when the cache was NOT enabled by default, I would agree the YAML editor was saveable. Once the cache became enabled by default, I don't know if it still worked fine or if it broke.

**Comment by hhovsepy** [comment]
@israel-hdez I see now, what was happening is, that Kiali fails to read any Istio Config details from K8s, because role verbs in your example do not contain list or get. So Kiali loads the object from registry cache, and marks it read only, because considers as cache only object.

So in your example of ClusterRole, when changing last group verbs to be:
`- apiGroups:
  - networking.istio.io
  - security.istio.io
  - extensions.istio.io
  - telemetry.istio.io
  - gateway.networking.k8s.io
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
`
So the objects can be listed as well, like described here: https://github.com/kiali/kiali-operator/blob/master/roles/default/kiali-deploy/templates/kubernetes/role.yaml
Then all works fine, YAML is editable.

**Comment by hhovsepy** [comment]
Will send a PR to kiali.io

**Comment by hhovsepy** [comment]
https://github.com/kiali/kiali.io/pull/635

**Comment by israel-hdez** [comment]
Uhm... Privilege handling is becoming weird. Let's think about it a little more, as I would prefer a consistent experience...

My thinking is around the following:
* If the wizards already allows you to create/edit/delete the Istio resources, why the YAML editor would stop you from operating on those same resources?
* If Kiali already lets you to see/read the resources, why you would need to add these `get` and `list` _read_ privileges to be able to _write/save_ in the YAML editor? Mainly, this is what doesn't make too much sense to me...

To me, the need to add these `get` and `list` verbs is more a technical glitch which should be fixed. But, perhaps, ask opinion from others  who are familiar with this.

About the changes to documentation, it is going to be VERY weird to readers to see those _read_ privileges under the _"Granting write privileges"_ section. If we are going to put this in the docs, at least add a note about why those _read_ privileges are needed for "granting write"...

**Comment by jshaughn** [comment]
If I understand correctly the _read_ permissions are needed because the _write_ permissions don't implicitly grant read.  I'm not sure people will worry about `get` and `list` when `create` is already in the list.   But, if there is no other obvious workaround then we could reword things maybe like:

Changing resources in the cluster can be a sensitive operation.  The logged-in
user will need certain privileges to make updates via Kiali.  Note that certain
_read_ privileges are required before the _write_ privileges can be applied.
 The following `ClusterRole` contains the necessary privileges:

**Comment by israel-hdez** [comment]
> If I understand correctly the _read_ permissions are needed because the _write_ permissions don't implicitly grant read.

Yes! I do understand that. But Kiali is loose on read privileges. It already shows you the YAML without having those read privileges. 

> Changing resources in the cluster can be a sensitive operation. The logged-in
user will need certain privileges to make updates via Kiali. Note that certain
read privileges are required before the write privileges can be applied.
The following ClusterRole contains the necessary privileges

Hmm... but then the bug would be on the wizards because these let you do edits without the read privileges. So, consistency is still not there.

If the fix is going to be in the docs rather than Kiali, I see no other option than being specific and telling that the YAML editor is what needs these read privileges to enable write. It would become a "feature" that you can disable edits on the YAML editor, while wizards let you edit.

**Comment by hhovsepy** [comment]
Right, there is a inconsistency between YAML editor and in wizards. 
YAML editor is loading configs from k8s api, where the role verbs are applied. So even `oc auth can-i get virtualservices --namespace bookinfo --as foo` will return 'no'. But `oc auth can-i delete virtualservices --namespace bookinfo --as foo` will return 'yes'.
On the other side, the wizard and config list are loading from registry cache, where no access is considered.
Wizard is loading only those configs which are connected to the service. The config list loads all configs from registry, even those ones which are auto generated and read only. And only when user clicks to particular config and opens YAML editor, it loads the data from k8s api to check the access and existence of that particular object.

**Comment by jshaughn** [comment]
Thanks for the details, @hhovsepy and @israel-hdez.  We definitely want consistent behavior in the wizards and YAML editor.  That means both should be read-only or writable given the same privileges.  I'd like to hear your opinions but I think the documentation fix would solve the problem, because once documented, and applied, both editing approaches would be consistent.  If the privileges remained as defined today then behavior would be inconsistent, but that could be expected because the privileges are out of compliance.   As I mentioned above, I don't think users would mind adding some read privileges when they are already granting some write privileges.

The only alternative would be to make a code change such that the YAML editor and Wizards work in the same way given today's documented privileges, and that may be a little messy.

**Comment by hhovsepy** [comment]
On k8s side itself there is inconsistency, when 'get' and 'list' privileges are not set, then user cannot list them even having 'delete' and 'patch' verbs. 
If we change Wizard to be read only, similar to YAML editor, then it is confusing, because user has 'patch' permission but cannot edit at all.
If we change YAML editor to be editable, consistent to Wizard, then this will be messy, because of cache only configs, retrieving which from k8s similarly will show access denied, and the real reason will be hidden.
If we want full consistency with k8s, then those objects will not be listed at all, as oc auth can-i get virtualservices --namespace bookinfo --as foo returns 'no', but we use registry cache for retrieving objects because of performance reasons.

So, as of all mentioned facts, it is more safe to mark in documentation that 'get', 'list', 'watch' verbs should exist in the clusterrole.

wdyt @israel-hdez ?

**Comment by israel-hdez** [comment]
> because of cache only configs, retrieving which from k8s similarly will show access denied, and the real reason will be hidden.

Are you sure of this? I don't remember seeing any _access denied_ errors, despite my test user didn't have any read privileges on any resources on the namespace.

---

IMHO and under a perspective of an end-user that won't want to know the technical details behind any Kiali page, the fix to the YAML editor is the right fix, as that will give consistency because the YAML editor will work the same way the rest of Kiali works. Under that end-user perspective, everything else looks more like a workaround.

If we change the wizards to behave the same as the YAML editor... Well... I agree it would be confusing that you cannot edit if you have `patch` permissions. But the YAML editor is behaving exactly in this confusing way, no? I know the source of the data are different, but that is just implementation details that doesn't seem to justify the behavior.

If we change the docs, we are simply moving the confusion from the Kiali App onto the Kiali docs, no? I think I'd be fully :+1: into this if you can explain how this is better than fixing the behavior of the YAML editor.

> So, as of all mentioned facts, it is more safe to mark in documentation that 'get', 'list', 'watch' verbs should exist in the clusterrole.

It depends on what you mean by "safe". If you mean that we won't have the risk to inject bugs or other unwanted behaviors, I agree. If you mean about security, I disagree as it goes against the Least privilege principle.

**Comment by israel-hdez** [comment]
> If we want full consistency with k8s, then those objects will not be listed at all, as oc auth can-i get virtualservices --namespace bookinfo --as foo returns 'no', but we use registry cache for retrieving objects because of performance reasons.

I did have this though that perhaps the whole _Istio Config_ should be hidden if you don't have those read privileges. But this would be something more drastic.

**Comment by israel-hdez** [comment]
I was thinking about this... and well, I don't wanna overthink.

If you are happy with a doc change, perhaps just do Jay's suggestion and we will be done.

**Comment by jshaughn** [comment]
I understand the issue and I'm happy with whatever you guys decide.  If Hayk is OK with a doc change then that's fine with me.  But if he is now convinced that we should resolve the inconsistency I'm fine with that as well.   In general I make these decisions based on how much effort it takes based on how much people have complained about it.  In this case we've been wondering a lot about whether people WILL complain, it's always tough to predict that but I usually err on the side of leaving work on the table.

**Comment by hhovsepy** [comment]
I will go to the docs change direction, a PR is sent: https://github.com/kiali/kiali.io/pull/635/files
