### ISSUE TITLE
Kiali-server Helm chart values file does not list components 

### ISSUE THREAD

**Issue by lisenet** [kiali/kiali#5935]
Kiali does not see `istio-ingressgateway` installed in separate kubernetes namespace. When Kiali server is deployed using Helm, the provided `values.yaml` file does not have any example for components. Unless you are familiar with Kiali operator, it is confusing, as you may think that Helm deployment does not support components. It would be useful to add a commented out section to the `values.yaml` file to address that and provide a basic example. I'm happy to raise a PR for it.

**Comment by jmazzitelli** [comment]
You could either propose a comment section in values.yaml or propose a change to [the kiali.io documentation](https://github.com/kiali/kiali.io) (which is probably what I would prefer, since this is documentation and not focused on fixing the implementation or a feature.)

For example, would something make sense to go in here? https://kiali.io/docs/installation/deployment-options/

Or here?: https://kiali.io/docs/installation/installation-guide/install-with-helm/

**Comment by jshaughn** [comment]
This has gone stale.  I'm going to close this and the pr.  I think the current docs are probably sufficient.
