### ISSUE TITLE
Missing scrapping parameters in kiali-operator helm chart

### ISSUE THREAD

**Issue by Hronom** [kiali/kiali#5949]
By default in `kiali-operator` helm chart parameter `metrics.enabled` set to `true`, this adds annotation `prometheus.io/scrape: true`. However there no annotations that describe what port and endpoint needs to be scrapped:
```
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
```

If `kiali-operator` deployed with istio sidecar - sidecar trying to scrap applications metrics from default port `80`.

This triggers errors like this:
```
	 2023-03-25T22:34:09.768729Z	error	failed scraping application metrics: error scraping http://localhost:80/metrics: Get "http://localhost:80/metrics": dial tcp [::1]:80: connect: connection refused
```

To fix it - add default annotations under `podAnnotations`:
```
  podAnnotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
```

You can also check thread in `istio.slack.com` here https://istio.slack.com/archives/C37A4KAAD/p1679928230016999

**Comment by jmazzitelli** [comment]
As I look at this, the Kiali operator is exposing Prometheus metrics via the underlying operator SDK. The way the Kiali operator uses the SDK, the port is always going to be `8080` and the path is always going to be `/path`. I don't see a way to override or customize that (definitely not within the Kiali operator set up - I'm sure there is some way to do it in the SDK but Kiali doesn't expose that - these values are therefore fixed within the Kiali operator).

Therefore, with that said, it doesn't make much sense to even define these settings in the values.yaml as suggested because the user will then think they can set those values to whatever they want and they will then expect the Kiali operator to expose the metrics over that customized port and path. This will not work, the metrics will not appear in their customized port and/or path, and the user will be left confused and think this is a bug, which it is not.

Thus, this should not be done inside values.yaml for that reason.

This should be directly placed in the operator Deployment since these values are fixed; so the change should be:

https://github.com/kiali/helm-charts/blob/master/kiali-operator/templates/deployment.yaml#L26

```yaml
      annotations:
        prometheus.io/scrape: {{ .Values.metrics.enabled | quote }}
        prometheus.io/path: /metrics <--- add this
        prometheus.io/port: "8080"  <-- add this
```

**Comment by Hronom** [comment]
@jmazzitelli agree, adjusted PR, please check

**Comment by Hronom** [comment]
@jmazzitelli thank you for guidelines! Created another PR https://github.com/kiali/kiali-operator/pull/629
