### ISSUE TITLE
Multicluster - Combine duplicated namespaces in dropdown selector

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#6007]
Namespaces that are duplicated across clusters should be combined into a single namespace name.

Related to #5932 

#5618

**Comment by leandroberetta** [comment]
Hi, I was thinking about this one, from the backend we are receiving all the namespaces from all the clusters Kiali has access (and the user):

![image](https://user-images.githubusercontent.com/1286393/230984861-2c0a28ca-635d-4190-928d-fcea6460e1fe.png)

In the namespace selector today two bookinfo namespaces appear, and when we select one, the other one is also selected (because of how it works today), and that mean we have 2 active namespaces and the info from both namespaces is shown, for example, in the workloads list page.

This issue aims to add some logic in the UI to handle this, right?. In the backend we assume we are receving namespace by cluster.

**Comment by nrfox** [comment]
> We could potentially aggregate on the frontend and still do option 2, which is I think what I prefer, but the backend currently does option 1 and no aggregation on the frontend.

Turns out that many parts of the UI assume that namespaces are only a name and frequently convert string `name` --> object `namespace`. This breaks down when a `namespace` object now has a required `cluster` field. The URL state for example only saves namespaces by their name. If we want to send cluster as a query param along with the API calls then this will require more changes on the frontend.

Going with option 1 for now.
