### ISSUE TITLE
[code] provide function to get versioned/canary istio configmap name

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#6042]
See: https://github.com/kiali/kiali/pull/6027#pullrequestreview-1388615090

We have code like this:

```
icm, err := kialiCache.GetConfigMap(configObject.IstioNamespace, configObject.ExternalServices.Istio.ConfigMapName)
```

We would like to work when using Istio revisions (e.g. canary)

We should have a function that can be used to isolate the configmap name... Something like "getIstioConfigMapName" and have it deal with the versioning/canary details.

**Comment by Xunzhuo** [comment]
xref: https://github.com/kiali/kiali/issues/6043

**Comment by jmazzitelli** [comment]
someone in discussions has asked for the ability to auto-detect canary configmap: https://github.com/kiali/kiali/discussions/6644

**Comment by yogeek** [comment]
don't know if it is the right place but I am using istio canary revisions (1.18 and 1.20 are present in the cluster at the same time, in the future it will be 1.20 and 1.22, etc) in order to allow users to choose when they want to upgrade to the latest revision.
How is it supposed to work with kiali please ? does kiali knows how to handle multiple istio revisions ?
Apparently, the `config_map_name` has to be specified in the CR but do I have to choose only 1 revision ?
Does this issue meant to cover both revisions or only one ?

**Comment by jmazzitelli** [comment]
> if it is the right place

For generation questions like this, please post a new discussion in our github Discussions - https://github.com/kiali/kiali/discussions/new?category=q-a

For details see:
