### ISSUE TITLE
Multicluster - Details page Graph section

### ISSUE THREAD

**Issue by hhovsepy** [kiali/kiali#6062]
Currently the App/Workload/Service details page's Graph section does not send cluster param to backend for querying.

RFE: But it needs to send cluster param and do queries for cluster.

![Screenshot from 2023-04-26 10-32-49](https://user-images.githubusercontent.com/604313/234518790-23c0ea55-8ffa-4bc6-98fb-830eb7810c63.png)

**Comment by jshaughn** [comment]
Node graphs will take the cluster into consideration if the `cluster` query param is provided.  I believe this is already done for Workload node graphs because they were already cluster-specific.  I think adding this for application and service nodes will also work, but we'll have to see what happens.  See Api.ts#getNodeGraphElements

**Comment by leandroberetta** [comment]
Hi @jshaughn, as you commented, the cluster is already passed when fetching the data for the mini graph, but I have one question, look the following scenario (for service or application), one of the path is lighter, at first I thought that if I'm on east cluster I should see the east path and the west path semi hidden and viceversa, but the east traffic is always like this:

![image](https://github.com/kiali/kiali/assets/1286393/566f4ae0-5f05-4894-a9f8-15a31064ef47)

I guess this needs to work as I was thinking or different?.

**Comment by jshaughn** [comment]
Hmmm, That mini-graph does not look like correct.  There are a couple of problems; it's showing the reviews app for both clusters and the wrong node is selected, that's the `reviews` app on `east`.   I can see that we do TRY to send the cluster into the graph query, but it may be undefined.  It looks like if the `cluster` URL param is not set then it's not going to be defined.

As for the unhighlighted nodes, that's standard graph behavior when a node is selected.  We unhighlight nodes and edges not in a request path of the selected node.  I don't think that's a problem, the problem is that this mini-graph should only include one `reviews` app:  `west:reviews`.

I don't have a MC setup here, maybe we could get together in the morning and investigate.

**Comment by leandroberetta** [comment]
@jshaughn thanks for the clarification, I found the issue and I'll be creating a PR soon for this. Thanks!.
