### ISSUE TITLE
Multicluster - Auto discover remote clusters

### ISSUE THREAD

**Issue by imroc** [kiali/kiali#6343]
Istiod discovers remote clusters by watching secret with label `istio/multiCluster=true`,  kiali should also support that.

I suggest add this as a sub task to #5618

**Comment by jmazzitelli** [comment]
> Istiod discovers remote clusters by watching secret with label `istio/multiCluster=true`, kiali should also support that.

This is not going to work. We already tried that when we initially started implementing multicluster support within Kiali. If we watch for secrets with that Istio label, Kiali will think those secrets are for Kiali to use - and Istio's remote cluster secrets do NOT provide the necessary permissions that Kiali needs and thus cannot be used by Kiali.

This is why Kiali looks for the label `kiali.io/multiCluster=true` on the Kiali remote secrets when [set up for multi-cluster](https://kiali.io/docs/configuration/multi-cluster/#setup). That is how Kiali knows which secrets are for it, versus which secrets are for Istio itself.

See here: https://github.com/kiali/kiali/issues/5767#issuecomment-1422522087 for where this was initially discussed several months ago and [this PR](https://github.com/kiali/kiali-operator/pull/614/files) where we purposefully moved away from the istio label.

Closing this as "won't fix".

**Comment by jmazzitelli** [comment]
If you only want a single set of remote cluster secrets, you could somehow combine both the Istio's remote cluster secret and Kiali's remote cluster secret (by combining, I mean create a single remote cluster secret that provides all permissions needed by both Istio and Kiali). This means you would need your own utility (since istioctl won't be able to do it, nor will the Kiali utility script be able to do it). But if you had a combined remote cluster secret, you could label it with `istio/multiCluster=true` and tell Kiali to look for that label (you can tell Kiali to look for that label via the Kiali CR setting documented here: https://kiali.io/docs/configuration/kialis.kiali.io/#.spec.kiali_feature_flags.clustering.autodetect_secrets.label) .. if using the server helm chart, the option is here: https://github.com/kiali/helm-charts/blob/v1.70.0/kiali-server/values.yaml#L99

But, again, if you try to set that setting to "istio/mutliCluster=true" without creating those special combined secrets, Kiali will not work - it likely won't even be able to initialize.
