### ISSUE TITLE
Multicluster - Stop remote cluster cache when cluster removed

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#6363]
Expected behavior: When a remote cluster secret is removed from Kiali's remote cluster secrets, Kiali should stop the kube cache for that cluster.

Current behavior: kube cache is not stopped and many list/watch errors are thrown if the removed cluster is inaccessible.

**Comment by jshaughn** [comment]
Current workaround:  Restart Kiali pods

**Comment by jmazzitelli** [comment]
What do you mean "When a remote cluster secret is removed from Kiali's remote cluster secrets"... do you mean someone  just deleted the actual secret resource and related resources? Or do you mean the remote secret reference is removed from the Kiali CR?

If it is the latter (removing from Kiali CR), there is nothing to do, the operator will restart the pod after reconciling the CR and removing the secret mount from the  pod.

If it is the former (just removing the secret from the cluster), Kiali will still have the secret mount point in the pod definition. I don't know how Kubernetes handles that - if you have a secret mounted to a pod's file system, and that secret is removed, what does Kubernetes do? Does it simply remove the file but keep the pod running, or does k8s automatically restart the pod?

In that case of keeping the pod running, yes, it seems Kiali would need to do something special if it sees the secret volume has been removed from the file system - but could this instead be considered an error condition? Kiali is configured for a specific remote cluster secret, but that secret is missing. That seems like an error or a misconfiguration, not something we should consider to be "normal". (note that jay's suggestion to restart the pod won't work because the pod won't start if the secret is missing - see my next sentence).

If k8s restarts the pod, that will also be a problem because [the secret is expected to exist](https://github.com/kiali/kiali-operator/blob/v1.77.0/roles/default/kiali-deploy/templates/kubernetes/deployment.yaml#L161-L165), default is [optional: false](https://kubernetes.io/docs/concepts/configuration/secret/#restriction-secret-must-exist). The pod won't restart - it will wait for the secret to exist so the volume mount can be put in place.

I don't think we want to flag remote cluster secrets as "optional" because then Kiali will start even if, for some reason, the user fails to deploy the secret. Kiali will fail to see the remote cluster and the user won't know why. We would want Kiali to pause during startup and let k8s tell the user it is waiting for the remote cluster secret to be created.

I think if a user removes a remote cluster, they should tell Kiali that via editing the Kiali CR and removing the remote cluster secret definition from the CR (or, if installing with helm, they would just remove it from the helm values). In both cases, the pod definition will be updated with the current list of volume mount points (the removed secret will no longer be mounted).

**Comment by nrfox** [comment]
> UPDATE: I just realized I forgot one thing - the default Kiali behavior is "auto detect" the secrets. In that case, there is really nothing for the user to edit in the Kiali CR, but the operator still needs to reconcile the CR because it needs to remove the old secret's volume mount.

It's been a minute since I opened this issue but I think this is what prompted it. I removed one of the "auto detected" secrets and nothing changed. I think "adding" a secret would have the same problem? I guess this issue is more about the operator watching those secrets and automatically updating the Kiali CR when a secret is added/removed but if this would require the operator having cluster scoped secret access then it's probably not worth it. How does the operator "auto detect" the secrets today?

**Comment by jmazzitelli** [comment]
This is how the operator autodetects the remote cluster secrets (it just gets the list of secrets found in the namespace where Kiali is deployed - that's actually the only namespace they can be because they need to be in Kiali's namespace for them to be mounted as volumes in the Kiali pod): https://github.com/kiali/kiali-operator/blob/v1.77.0/roles/default/kiali-deploy/tasks/main.yml#L715

And, it turns out, the operator does have those permissions. Now I remember this.  In order an operator to create a secret (which the Kiali operator does for the default signing key secret), the operator must also be given watch and list permissions, too - the operator SDK requires this so it can begin watching the secret as a dependent resource. If I remove [these permissions](https://github.com/kiali/helm-charts/blob/v1.77.0/kiali-operator/templates/clusterrole.yaml#L37-L38) like this: 

```diff
$ git diff
diff --git a/kiali-operator/templates/clusterrole.yaml b/kiali-operator/templates/clusterrole.yaml
index 961b56b..c74d020 100644
--- a/kiali-operator/templates/clusterrole.yaml
+++ b/kiali-operator/templates/clusterrole.yaml
@@ -34,8 +34,6 @@ rules:
   - secrets
   verbs:
   - create
-  - list
-  - watch
 {{- if gt (len .Values.secretReader) 0 }}
 - apiGroups: [""]
   resourceNames:
```

then this results (trying to create our signing key secret):

```
TASK [default/kiali-deploy : Create kiali-signing-key secret to store a random signing key if a secret does not already exist and we need one] ***

W1205 19:25:49.846746       7 reflector.go:424] pkg/mod/k8s.io/client-go@v0.26.2/tools/cache/reflector.go:169: failed to list /v1, Kind=Secret: secrets is forbidden: User "system:serviceaccount:kiali-operator:kiali-operator" cannot list resource "secrets" in API group "" at the cluster scope
E1205 19:25:49.846901       7 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.2/tools/cache/reflector.go:169: Failed to watch /v1, Kind=Secret: failed to list /v1, Kind=Secret: secrets is forbidden: User "system:serviceaccount:kiali-operator:kiali-operator" cannot list resource "secrets" in API group "" at the cluster scope
```

I think this is why our auto-discovery of the remote cluster secrets work. I originally did not want to rely on this "feature" but since it was required by the operator SDK I figured might as well use it for the auto-discovery of the remote cluster secrets.

If I had my choice, I would not have the operator be given these permissions and we should be on the lookout for ways to be able to remove it.

That said, I don't think we want the operator watching/getting random secrets cluster wide (which is what will happen if we add "Secret" to our watches.yaml file).

**Comment by jshaughn** [comment]
For things that don't happen often, like adding or removing a cluster, I think perhaps just documenting in kiali.io may be sufficient.

**Comment by jmazzitelli** [comment]
We have some docs already in staging - I'll flesh it out some more: https://staging.kiali.io/docs/configuration/multi-cluster/#removing-a-cluster

**Comment by jmazzitelli** [comment]
@nrfox @jshaughn see what you think in this [docs PR](https://github.com/kiali/kiali.io/pull/728) .. [netlify link is here](https://deploy-preview-728--kiali.netlify.app/docs/configuration/multi-cluster/#removing-a-cluster)

**Comment by jmazzitelli** [comment]
Here's an enhancement request to follow up on this issue: https://github.com/kiali/kiali/issues/6941
