### ISSUE TITLE
Set Istio v1.19 add-on to Kiali v1.72

### ISSUE THREAD

**Issue by jshaughn** [kiali/kiali#6436]
The Istio v1.19 release branch has been cut.  When we release v1.72 we need to sanity check it with 1.19 and set it as the add-on version.  Appropriate changes should be made to the kiali.io compat chart, as well as anything else you may think of that needs to be done.

**Comment by jmazzitelli** [comment]
upstream Istio PR: https://github.com/istio/istio/pull/46391

**Comment by nrfox** [comment]
@jmazzitelli we should also bump the istio libraries that kiali imports to 1.19 as we've had problems in the recent past not keeping those imports in sync with the istio version kiali supports.

**Comment by jmazzitelli** [comment]
@nrfox that is a bit of a chicken and egg problem. We want to release 1.72 since it has all the updates for 1.19 and ambient... but the 1.19 libraries won't be published until after 1.19 is released (with the Kiali 1.72 addon) so Kiali 1.72 can't use the 1.19 libraries.

So far as I can see, the libraries we are using in Kiali 1.72 appear to be compatible with 1.19. So we could leave it as-is and just bump up the libraries Kiali uses in our next release.  Or we could pin to some 1.19 alpha release (too late for the 1.72.0 release for that, though).

I'm inclined to say just keep it the way it is and move the next  Kiali version we release to use the 1.19 libs. If people want the latest and greatest, they can always upgrade Kiali using the Kiali standard install mechanisms and forgo the Kiali addon that ships with Istio (that is, after all, how it works today - if you want bug fixes or enhancements in Kiali, you just install it using Kiali's helm charts or operator and skip the addon yaml that ships with the Istio bundle).

**Comment by nrfox** [comment]
> I'm inclined to say just keep it the way it is and move the next Kiali version we release to use the 1.19 libs. If people want the latest and greatest, they can always upgrade Kiali using the Kiali standard install mechanisms and forgo the Kiali addon that ships with Istio (that is, after all, how it works today - if you want bug fixes or enhancements in Kiali, you just install it using Kiali's helm charts or operator and skip the addon yaml that ships with the Istio bundle).

That sounds fine for now. We can have a separate issue for bumping the istio libs in kiali post 1.19 release so there's a version of Kiali that can be used with 1.19 in case there are any issues between versions. That will probably be Kiali v1.73 or v1.74 in this case.

**Comment by jshaughn** [comment]
@jmazzitelli So, do we still need to perform the 1.72 add-on update for istio 1.19?  Or have we made that update?

**Comment by jmazzitelli** [comment]
there is nothing to do right now for 1.19.

**Comment by jshaughn** [comment]
OK, can we close this given that https://github.com/istio/istio/pull/46391 is merged?
