### ISSUE TITLE
[Multicluster] Not all reviews workloads are visible in Kiali 

### ISSUE THREAD

**Issue by matejnesuta** [kiali/kiali#6780]
There is slight chance that one of the reviews workload is not visible in Kiali. This has already happend in one of my CI runs (https://github.com/kiali/kiali/actions/runs/6640424377/job/18041166455) and due to this, the first 3 tests from `workloads_details_multicluster.feature` were failing. It is also not clear which of the workloads (reviews-v2 or reviews-v3) is going to get deployed. However, the pod itself is running, as can be seen from my terminal.

I am not sure how to reproduce this apart from re-running the `./hack/run-integration-tests.sh --test-suite frontend-multi-cluster` script. 
![Screenshot from 2023-10-25 21-54-45](https://github.com/kiali/kiali/assets/45061792/41bd1c32-cfbb-4fca-aa51-df052aeab599)
![Screenshot from 2023-10-25 21-55-13](https://github.com/kiali/kiali/assets/45061792/fb6f71ae-0d4b-4532-bb64-464f3be73558)

**Comment by leandroberetta** [comment]
Hi @matejnesuta, so, this is happening from time to time when installing the environment, there are times when the reviews-v2 is not showing up and others, when the v3 is not showing up?.

**Comment by matejnesuta** [comment]
Hello @leandroberetta 

Yes, that is right and there are also times, when the failure won't occur at all.

**Comment by leandroberetta** [comment]
Hi @matejnesuta,

The workloads are deployed, and this is not a Kiali issue, because the metrics aren't in Prometheus either. If the metrics are missing in Prometheus, Kiali won't show them of course. 

This seems to be an issue with the balancing between the two review services in cluster west, probably some configuration in Istio.

What I do to check that we do not have an issue was creating a VirtualService to split traffic evenly to both v2 and v3 workloads, after that, in Kiali we can see the following:

![image](https://github.com/kiali/kiali/assets/1286393/9fbc3638-e728-404b-bce8-5a2826f7d7f2)

I think a good thing to do is add this configuration to the script we are using when testing. Are you ok with this?. I can create a PR adding them.

**Comment by matejnesuta** [comment]
Hello @leandroberetta. 

Thank you for resolving the issue. Just one quick question. Shouldn't the traffic be split to the V1 workload as well? It is not visible on the graph. 

>I think a good thing to do is add this configuration to the script we are using when testing. Are you ok with this?. I can create a PR adding them.

Yes please, feel free to create a PR. This issue is blocking some of my Cypress automation and the PR would be very helpful.

**Comment by leandroberetta** [comment]
> Hello @leandroberetta.
> 
> Thank you for resolving the issue. Just one quick question. Shouldn't the traffic be split to the V1 workload as well? It is not visible on the graph.
> 
> > I think a good thing to do is add this configuration to the script we are using when testing. Are you ok with this?. I can create a PR adding them.
> 
> Yes please, feel free to create a PR. This issue is blocking some of my Cypress automation and the PR would be very helpful.

Yeah, v1 will be part, for this test, was ommited in the configuration.
