### ISSUE TITLE
Add labels and annotations in wizards

### ISSUE THREAD

**Issue by ferhoyos** [kiali/kiali#6806]
Currently it is not possible to add labels or annotations within the Istio object creation wizard. If you want to add any label or annotation must be done in the preview YAML editor. 

![image](https://github.com/kiali/kiali/assets/122779323/acc2f629-a080-4693-9642-025fd5b58416)

![image](https://github.com/kiali/kiali/assets/122779323/a968c770-f758-4bec-9809-f3a150e6c82f)

I think adding the possibility to add labels and/or annotations from the wizard would be useful for Kiali users. 

EDIT:
Dividing the task into two subtasks to keep it simple and smaller:

- [ ] Add Labels
- [ ] Add Annotations

**Comment by jshaughn** [comment]
First, I didn't know the Preview window was an editor :-)   Second, I'll ask @nrfox for input because he has recently been playing with adding Auth Policy.

**Comment by nrfox** [comment]
Yeah I think it'd be generally useful to have the ability to add both annotations and labels to the istio objects when you create them through Kiali. They're optional fields so perhaps they could be minimized on the form somehow to reduce visual noise.

For Auth Policy specifically, `dry-run` is enabled through an annotation so it'd be nice to have the option to add it in the form itself instead of just in "preview". The API is alpha so the annotation might eventually move to a field on the spec but like I said above the ability to add annotations/labels is still useful and IMO wouldn't add much noise to the form.
