### ISSUE TITLE
Multicluster - Document how to "remove" a cluster

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#6851]
Document how a cluster is "removed" from Kiali in a multi-cluster setup. How to add a cluster is documented by how to remove a cluster should also be documented: https://kiali.io/docs/configuration/multi-cluster/#setup.

Steps are:

1. Remove the "remote secret" from the Kiali pod.
2. Restart the Kiali pod
3. Cleanup any Kiali multi-cluster resources created in the cluster that is being removed i.e. the Service Account and Role/Rolebinding.

These steps could even by automated by the `kiali-prepare-remote-cluster.sh` script.

**Comment by jmazzitelli** [comment]
> 2. Restart the Kiali pod

My antenna go up when we say the user should "restart the pod"... that is usually the operator's job to manage the lifecycle of the server pod.

The operator [does some things with the remote cluster secrets](https://github.com/kiali/kiali-operator/blob/v1.76.0/roles/default/kiali-deploy/tasks/main.yml#L718-L736) ([mounts them](https://github.com/kiali/kiali-operator/blob/v1.76.0/roles/default/kiali-deploy/templates/openshift/deployment.yaml#L125-L129) to the pod). When removing, the operator should remove the mounts. So rather than say the user restart the pod, the user should instead edit or "touch" the Kiali CR in some way.

I'll look into this and update the script and add some docs. The script might want to edit the Kiali CR (if one exists) so the operator can be told to do its thing. If Kiali is installed some other way ([helm](https://github.com/kiali/helm-charts/blob/v1.76.0/kiali-server/templates/deployment.yaml#L130-L133)) maybe the script can do something else.

**Comment by jmazzitelli** [comment]
FYI: The script already provides [the option to delete the resources](https://github.com/kiali/kiali/blob/v1.76.0/hack/istio/multicluster/kiali-prepare-remote-cluster.sh#L432-L433). So that just needs to be documented.

**Comment by jmazzitelli** [comment]
Interestingly, our MC docs don't explain how to configure Kiali to use these remote cluster secrets that enable MC support. So we should add that. In addition, I think I can get this script to output some help text to tell the user what to do next. In short, we should tell them they need to either turn on auto-discovery of remote cluster secrets or to add the cluster secrets explicitly to the config. How they do this depends on how they want to (or have already) installed Kiali - via Operator or via helm.

Operator requires [kiali_feature_flags.clustering.autodetect_secrets](https://kiali.io/docs/configuration/kialis.kiali.io/#.spec.kiali_feature_flags.clustering.autodetect_secrets) or [kiali_feature_flags.clustering.clusters](https://kiali.io/docs/configuration/kialis.kiali.io/#.spec.kiali_feature_flags.clustering.clusters) to be touched.

For server helm installs, [analogous helm values](https://github.com/kiali/helm-charts/blob/v1.76.0/kiali-server/values.yaml#L96-L100) should be set.

**Comment by jmazzitelli** [comment]
Here's the docs PR.
* https://github.com/kiali/kiali.io/pull/718

I didn't modify the script yet. Still thinking how best to do it.
