### ISSUE TITLE
be able to auto-detect more istio things for ease-of-configuration

### ISSUE THREAD

**Issue by jmazzitelli** [kiali/kiali#7177]
### What do you want to improve?

Right now there are lots of individual configuration settings in the Kiali CR that need to be set if Istio is not installed in the default way (and by default I mean the istioctl installation method with addons installed via the addon yaml that ships with istio).

It is hard for users to know all the touch points to change if they have a non-default install such as Istio is in namespace other than istio-system or that they are using canary upgrades where the istio config map has a version number in the name.

### What is the current behavior?

The user needs to read the Kiali CR reference doc and figure out what settings need to be explicitly set so their non-default install works with Kiali. This is tedious, confusing, and error prone and often results in long discussion threads in Slack to help the person get Kiali working.

### What is the new behavior?

At minimum, we need a doc page in kiali.io that gives the details of all the things that the user might need to change. Title the doc page something like, "How to configure Kiali to work with non-default Istio installations".

But I would like to see if we could add some auto-detection features to the operator where the operator can do more to figure out what the settings should be. The operator could, for example, scan the spec.istio_namespace and look for config maps that appear to be the Isto ConfigMap (it would do this only if the config_map_name setting does not refer to an actual configmap). There could be other auto-detection mechanisms we could use (for example, look for an istiod pod in a namespace if there is no istiod pod with the default name or in the default namespace).

- [ ] https://github.com/kiali/kiali/issues/7514
- [x] https://github.com/kiali/kiali/issues/7515

**Comment by nrfox** [comment]
Yes but I'd argue that the auto-detection should not go in the operator but in the kiali server. Look at the [mesh service](https://github.com/kiali/kiali/blob/39a19d4823da0445c754d9c1015be858187d286c/business/mesh.go#L120). It's already doing a lot of this. The only missing piece is to move the UI elements to the mesh page that assume there's only a single controlplane so we can show configuration per controlplane where controlplane is defined as an "istiod workload". Kiali can list across namespaces and tie things like the configmaps to their respective istiod. Listing across namespaces works even when `accessible_namespaces != **` since in that case kiali will do a LIST per namespace that it has access to and aggregate the results.

**Comment by jmazzitelli** [comment]
That's fine by me... just SOMETHING within the Kiali ecosystem (server, operator, whatever) should be able to auto-discover things if the user has not configured those things.

**Comment by nrfox** [comment]
Actually going to re-open this and add the identity domain to the list: https://kiali.io/docs/configuration/kialis.kiali.io/#.spec.external_services.istio.istio_identity_domain

**Comment by jshaughn** [comment]
Closing this because the initial work is complete and the remaining task is fairly comprehensive, and has prerequisite work in the validation area.  The remaining task has been moved to the backlog.
