### ISSUE TITLE
Memory consumption chart for istiod container isn't getting created

### ISSUE THREAD

**Issue by jaybhamad** [kiali/kiali#7441]
### Describe the bug
 - When I use the default prometheus addon and link it with the kiali from kiai-operator I can see the cpu and memory consumption charts in the mesh page
![image](https://github.com/kiali/kiali/assets/170439760/0a863a71-45db-442c-b52c-39cae0b35662)

- But when I link it with teh prometheus as an external deployment (deployed using kube-prometheus-stack) I can see the cpu consumption chart but I couldn't see memory consumption chart
![image](https://github.com/kiali/kiali/assets/170439760/342452ed-c087-46d1-8838-cc1b3cd33b86)

- I can see the required metrics to create those charts in my prometheus UI
![image](https://github.com/kiali/kiali/assets/170439760/ad0645df-265b-4683-8695-066b2d4f2222)

Why is that happening?
### Environment

- **Kiali version:** 1.86.0
- **Istio version:** 1.22.1
- **Kubernetes impl:** prometheus-community/kube-prometheus-satck
- **Kubernetes version:** 1.29.2

**Comment by jshaughn** [comment]
Not sure, are you certain the metric has values for the requested time period?  cc @leandroberetta

**Comment by jaybhamad** [comment]
I have tried it several times but I couldn't see that chart.

**Comment by jshaughn** [comment]
OK, so it seems that migrating the control plane information to the new Mesh Page that maybe there is a problem.

**Comment by jshaughn** [comment]
As mentioned above, for a control plane's side-panel memory chart (when selecting a control plane on the Mesh page), Kiali first tries to use `container_memory_working_set_bytes`, and if that query returns no data Kiali falls back to using `process_resident_memory_bytes`.

After reading a bit,  `container_memory_working_set_bytes` seems to be the preferred metric as it better reflects active total memory usage.  But, it's a container metric for a specific pod.  We are currently aggregating all pods based on the pod prefix (like istiod.*).  This means we are not narrowing things down to the selected control plane, if there are more than one in the database (I've also seen an inactive pod if there are restarts!).  To do this correctly we'd need to narrow the query to the pods that match the control plane.  Also, because we test for `container="discovery"`, and this label doesn't seem to exist, I don't think we use this metric. @leandroberetta, can you comment on why you added that condition in https://github.com/kiali/kiali/pull/6259?

So, I feel like we are always falling back to `process_resident_memory_bytes`.

Our query against `process_resident_memory_bytes` has a similar aggregation issue, this metric actually has a label with the revision name, but we are not using it.  Note that it seems this metric does not exist for this issue report.

So, I think we need to 1) narrow our queries and 2) possibly remove the `container="discovery"` condition.

**Comment by jshaughn** [comment]
Note, the control plane CPU metrics have a similar aggregation issues.
