### ISSUE TITLE
Show certificate information per controlplane

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#7456]
### What do you want to improve?

Certificate information should be shown per controlplane instead from a single controlplane.

### What is the current behavior?

The certificates info dropdown only shows certificate information from a single controlplane. This isn't entirely accurate when there's multiple controlplanes either with revision based deployments and/or with multi-primary.

![Screenshot from 2024-06-20 11-49-24](https://github.com/kiali/kiali/assets/6226732/d0797f64-31d8-4e78-bf97-852a221b3565)

### What is the new behavior?

Certificates info is moved to the mesh page. When you click on a controlplane node the certificate information is shown for that particular controlplane.

**Comment by jmazzitelli** [comment]
@nrfox mentioned that the public cert info can be found in a configmap, rather than a secret. We should change our code to load in the data from the configmap - that would help us reduce our permissions requirements - we can remove the permission from the server to read the secrets. This would clean up some permissions to help reduce the potential for security issues.

**Comment by leandroberetta** [comment]
@jmazzitelli @nrfox 

I think using `istio-ca-root-cert` is valid when using the default CA, but when plugin a new CA, a new secret called "cacerts" needs to be created and used: https://istio.io/latest/docs/tasks/security/cert-management/plugin-ca-cert/

For this reason, I think we might need to keep reading the secret if exists to display that cert information (as it is today).

**Comment by jmazzitelli** [comment]
BTW: this would be nice to get in for 2.0 -- removing permissions for some secrets would be nice.
