### ISSUE TITLE
[kiali operator helm chart] Option to skip RBAC resource creation

### ISSUE THREAD

**Issue by rgaduput** [kiali/kiali#7460]
### What do you want to improve?
An option to skip RBAC resources (`ClusterRole`, `ClusteRoleBinding`, `ServiceAccount`).
This is useful specially when installing on cluster with not enough permissions to create cluster wide resources.

### What is the current behavior?
No way to skip to RBAC resources creation.

### What is the new behavior?
Optionally skip creation of RBAC.

**Comment by jmazzitelli** [comment]
that's what this is for:

https://github.com/kiali/helm-charts/blob/master/kiali-operator/values.yaml#L41-L45

**Comment by rgaduput** [comment]
@jmazzitelli I understand that not having the ClusterRole, ClusterRoleBinding will break the operator. The use case(atleast in mycase) is that ClusterAdmin creates these resources along with CRDs and after that we deploy the chart by disabling the resources creation through values.

**Comment by rgaduput** [comment]
> that's what this is for:
> 
> https://github.com/kiali/helm-charts/blob/master/kiali-operator/values.yaml#L41-L45

This is used inside the ClusterRole to allow the permissions of creating the ClusterRoles by operator after deployement.

**Comment by jmazzitelli** [comment]
The problem is that we can't add a "feature" to the helm charts that, when enabled, breaks the installation and expects some additional manual steps afterwards to "fix" it.

One thing you could do is use "helm template" to create the operator yamls, remove the yamls you don't want or simply apply the ones you do want. This would solve your unique use-case without introducing a setting that, when enabled, actually breaks the install.

For example, I see that you don't want the cluster role, the binding nor the service account, leaving only the deployment.

So, just do this:

```
helm template --show-only templates/deployment.yaml kiali kiali-operator | kubectl apply -f -
```

That will do what you want. If you want to create the SA but not the cluster role/bindings, then add the serviceaccount.yaml to the output:

```
helm template --show-only templates/deployment.yaml --show-only templates/serviceaccount.yaml kiali kiali-operator | kubectl apply -f -
```

**Comment by rgaduput** [comment]
Wow Ok, this is as good as maintaining my own copy of the charts locally, which I am trying to avoid :(.
Default settings does not change or break anything so not sure what's the concern here. 
By the way its normal and common approach followed by the operator charts out there.

**Comment by jmazzitelli** [comment]
see:
* https://github.com/kiali/kiali/issues/8491
