### ISSUE TITLE
k8s api token not auto refreshing for calls to fetch cacerts

### ISSUE THREAD

**Issue by msvticket** [kiali/kiali#7542]
### Describe the bug

With audit logs turned on I see that some Kubernetes API calls use a stale service account token. Especially all calls to fetch the secret cacerts use a token from when Kiali started up.

Looking at the code it seem like cacerts is fetched in https://github.com/kiali/kiali/blob/master/business/istio_certs.go, but I haven't found the root cause of the problem.

PR #7023 should be related.

### Expected Behavior

A current token is used as for other Kubernetes API calls.

### Environment

- **Kiali version:** 1.87.0
- **Istio version:** 1.22.2
- **Kubernetes impl:** EKS
- **Kubernetes version:** 1.30.2

**Comment by jmazzitelli** [comment]
If I recall correctly, that code is only used to show the istio cert details in the About box (or something like that). You can disable this -- https://kiali.io/docs/configuration/kialis.kiali.io/#.spec.kiali_feature_flags.certificates_information_indicators.enabled

**Comment by jshaughn** [comment]
@nrfox Can you take a look at this?

**Comment by nrfox** [comment]
Do you have `automountServiceAccountToken: false` on your Kiali pod spec or on your service account?

**Comment by msvticket** [comment]
> Do you have `automountServiceAccountToken: false` on your Kiali pod spec or on your service account?

No. Most other requests use a current token.

**Comment by nrfox** [comment]
@msvticket what auth strategy are you using?

**Comment by msvticket** [comment]
> @msvticket what auth strategy are you using?

anonymous

**Comment by nrfox** [comment]
Ok I think I see the issue then. In anonymous mode, the Kiali service account tokens are used but the `BearerTokenFile` is not set for the user clients: https://github.com/kiali/kiali/blob/2a0f9deda6b93369363e04ea1c381113c8b9de18/kubernetes/client_factory.go#L164-L168

This is what you want for other auth strategies but for anonymous mode since it's actually the Kiali service account token, we want to set that `BearerTokenFile` so that the token gets autorefreshed by client-go.
