### ISSUE TITLE
Latest installation script seems to be broken

### ISSUE THREAD

**Issue by SeriyBg** [kiali/kiali#761]
**Describe the bug**
I'm following the installation documentation, and I'm running the command `curl -L http://git.io/getLatestKialiKubernetes | bash`. However here is the output that I'm receiving:
```
kubectl is here: /usr/local/bin/kubectl
envsubst is here: /usr/local/opt/gettext/bin/envsubst
Will use the last Kiali release:
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
Deploying Kiali to kubernetes project istio-system
Downloading YAML via: wget -q -O - https://raw.githubusercontent.com/kiali/kiali//deploy/kubernetes/secret.yaml
error: no objects passed to create
ERROR: Failed to deploy to kubernetes. Aborting.
```

Looks like the default `VERSION_LABEL` is not set correctly to the latest version. 

**Versions used**
Kiali: Latest
Istio: 1.0.3
Kubernetes flavour and version: Kubernetes 1.10

Maybe this is the something that I have to additionally configure on my system, but in this case maybe this could be described in the documentation.
If this is confirmed as a bug or the documentation needs to be extended I can try to work on this issue.

There is a workaround for this: `export IMAGE_VERSION=latest; curl -L http://git.io/getLatestKialiKubernetes | bash`

**Comment by jmazzitelli** [comment]
This is because our last release (which happened to be our first one that we are using our automated scripts for) didn't create a github release. https://github.com/kiali/kiali/releases doesn't show 0.12.0. 

@israel-hdez remember we needed to do that in the automated scripts? See https://issues.jboss.org/browse/KIALI-2053 ... This is the reason we need it. It breaks the install script without it.

I'll manually create the release now.

BTW: I also see this:

```
readlink: illegal option -- f
usage: readlink [-n] [file ...]
```

I suspect you are running this on MacOS which doesn't have the GNU readlink and doesn't support -f. That might be something else we should think about fixing (maybe have the script see if the platform is MacOS and use greadlink instead).

**Comment by jmazzitelli** [comment]
OK, the release is created:

https://github.com/kiali/kiali/releases/tag/v0.12.0

I also pushed the docker hub tag v0.12:

https://hub.docker.com/r/kiali/kiali/tags/

@israel-hdez we need that done, too, in the automated scripts - pushing the vX.Y image to docker hub so it matches the latest x.y.z release in the x.y stream.

**Comment by jmazzitelli** [comment]
FWIW: that readlink error is not a problem under normal circumstances - that's just looking for the YAML files on your local disk. Normally, people using this won't even have them anyway (the script will download them from github). You only have them if you are running the script out of a git cloned local repo (this will be true for kiali devs, but not true for anyone else). So, its an ugly error in the output, but is really of no consequence unless you are a kiali developer on macOS.

**Comment by jmazzitelli** [comment]
FYI: I fixed that readlink error - script now uses a different method - works the same on linux and macOS now: https://github.com/kiali/kiali/pull/765

**Comment by SeriyBg** [comment]
@jmazzitelli thanx for fixing the error with readlink. What about to set the default `IMAGE_VERSION` to `latest` if it's not set manually? Or to grab the the latest existing GA version?

**Comment by jmazzitelli** [comment]
> What about to set the default `IMAGE_VERSION` to `latest` if it's not set manually? Or to grab the the latest existing GA version?

It already does this. Are you seeing this behavior broken?

See: https://github.com/kiali/kiali/blob/master/deploy/kubernetes/deploy-kiali-to-kubernetes.sh#L41
and: https://github.com/kiali/kiali/blob/master/deploy/kubernetes/deploy-kiali-to-kubernetes.sh#L69-L85

**Comment by SeriyBg** [comment]
@jmazzitelli yes, it is fixed now. So when I am able to install the lates kiali with `curl -L http://git.io/getLatestKialiKubernetes | bash `

**Comment by SeriyBg** [comment]
@jmazzitelli the issue is reproduced again. Looks like again there is no release created.

**Comment by jmazzitelli** [comment]
@SeriyBg It works for me. Make sure you use the new command syntax:

```
bash <(curl -L http://git.io/getLatestKialiKubernetes)
```

This is documented in our getting started guide here: https://www.kiali.io/gettingstarted/#_install_kiali_2

We changed this because it is required due a change recently made in the script.

For the record, here's the latest release (v0.14.0): https://github.com/kiali/kiali/releases/tag/v0.14.0

Here's my results of running the install command:

```
$ bash <(curl -L http://git.io/getLatestKialiKubernetes)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
100  8920  100  8920    0     0    872      0  0:00:10  0:00:10 --:--:--  2657
What do you want to use for the Kiali Username: admin
What do you want to use for the Kiali Passphrase: 
kubectl is here: /usr/bin/kubectl
envsubst is here: /usr/bin/envsubst
Using downloader: wget -q -O -
Will use the last Kiali release: v0.14.0
=== SETTINGS ===
IMAGE_NAME=kiali/kiali
IMAGE_VESRION=v0.14.0
VERSION_LABEL=v0.14.0
IMAGE_PULL_POLICY_TOKEN=imagePullPolicy: Always
NAMESPACE=istio-system
ISTIO_NAMESPACE=istio-system
JAEGER_URL=http://jaeger-query-istio-system.127.0.0.1.nip.io
GRAFANA_URL=http://grafana-istio-system.127.0.0.1.nip.io
VERBOSE_MODE=3
=== SETTINGS ===
Deploying Kiali to Kubernetes project istio-system
Downloading YAML via: wget -q -O - https://raw.githubusercontent.com/kiali/kiali/v0.14.0/deploy/kubernetes/secret.yaml
secret/kiali configured
Downloading YAML via: wget -q -O - https://raw.githubusercontent.com/kiali/kiali/v0.14.0/deploy/kubernetes/configmap.yaml
configmap/kiali configured
Downloading YAML via: wget -q -O - https://raw.githubusercontent.com/kiali/kiali/v0.14.0/deploy/kubernetes/serviceaccount.yaml
serviceaccount/kiali-service-account configured
Downloading YAML via: wget -q -O - https://raw.githubusercontent.com/kiali/kiali/v0.14.0/deploy/kubernetes/clusterrole.yaml
clusterrole.rbac.authorization.k8s.io/kiali configured
Downloading YAML via: wget -q -O - https://raw.githubusercontent.com/kiali/kiali/v0.14.0/deploy/kubernetes/clusterrolebinding.yaml
clusterrolebinding.rbac.authorization.k8s.io/kiali configured
Downloading YAML via: wget -q -O - https://raw.githubusercontent.com/kiali/kiali/v0.14.0/deploy/kubernetes/deployment.yaml
deployment.extensions/kiali configured
Downloading YAML via: wget -q -O - https://raw.githubusercontent.com/kiali/kiali/v0.14.0/deploy/kubernetes/service.yaml
service/kiali configured
Downloading YAML via: wget -q -O - https://raw.githubusercontent.com/kiali/kiali/v0.14.0/deploy/kubernetes/ingress.yaml
ingress.extensions/kiali configured
Downloading YAML via: wget -q -O - https://raw.githubusercontent.com/kiali/kiali/v0.14.0/deploy/kubernetes/crds.yaml
customresourcedefinition.apiextensions.k8s.io/monitoringdashboards.monitoring.kiali.io configured
```

**Comment by SeriyBg** [comment]
@jmazzitelli yes I do use the new command. However, for me, it works only when I have the value set: `export IMAGE_VERSION=latest;`
Otherwise I'm getting the error:
```
Downloading YAML via: wget -q -O - https://raw.githubusercontent.com/kiali/kiali//deploy/kubernetes/secret.yaml
error: no objects passed to apply
ERROR: Failed to deploy to Kubernetes. Aborting.
```

As you can see the forming url is incorrect as it should be: `https://raw.githubusercontent.com/kiali/kiali/master/deploy/kubernetes/secret.yaml`

**Comment by jmazzitelli** [comment]
@SeriyBg what happens when you run:

```
wget -q -O - https://api.github.com/repos/kiali/kiali/releases/latest 2> /dev/null | grep  "tag_name" | sed -e 's/.*://' -e 's/ *"//' -e 's/",//'
```

I get "v0.14.0". I wonder if your site is hitting a github rate limit and you can't get out to the github api. I've seen that before. My colleague had this happen to her - the building/network where she was at was causing github api calls to fail due to github rate limiting. See https://developer.github.com/v3/#rate-limiting

I would run that command above and see what happens?

**Comment by jmazzitelli** [comment]
@SeriyBg can you post the full output of the command you run?

**Comment by SeriyBg** [comment]
@jmazzitelli yes sure, here is the command I'm running and the output:
```
$> bash <(curl -L http://git.io/getLatestKialiKubernetes);                                                                                                                   
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  8920  100  8920    0     0   7615      0  0:00:01  0:00:01 --:--:--  7615
What do you want to use for the Kiali Username: admin
What do you want to use for the Kiali Passphrase:
kubectl is here: /usr/local/bin/kubectl
envsubst is here: /usr/local/bin/envsubst
Using downloader: wget -q -O -
Will use the last Kiali release:
=== SETTINGS ===
IMAGE_NAME=kiali/kiali
IMAGE_VESRION=
VERSION_LABEL=
IMAGE_PULL_POLICY_TOKEN=imagePullPolicy: Always
NAMESPACE=istio-system
ISTIO_NAMESPACE=istio-system
JAEGER_URL=http://jaeger-query-istio-system.127.0.0.1.nip.io
GRAFANA_URL=http://grafana-istio-system.127.0.0.1.nip.io
VERBOSE_MODE=3
=== SETTINGS ===
Deploying Kiali to Kubernetes project istio-system
Downloading YAML via: wget -q -O - https://raw.githubusercontent.com/kiali/kiali//deploy/kubernetes/secret.yaml
error: no objects passed to apply
ERROR: Failed to deploy to Kubernetes. Aborting.
```

**Comment by jmazzitelli** [comment]
@SeriyBg 

I see this in your output:

```
Will use the last Kiali release:
```

That's the problem - image version it gets back from the api call is empty. You will then see:

```
IMAGE_VESRION=
VERSION_LABEL=
```
They are now empty because of this (ignore the misspelling of IMAGE_VESRION - that's just some text in the debug message, I'll fix that later). It is failing that github API call within the script for some reason (that github api call should fill in IMAGE_VERSION env var). But as you confirmed earlier when you ran that command on its own, there is a kiali release and you can get its number (v0.14.0) from the github api. I still think there is something wrong with accessing github api. When you ran that test (you ran the command on its own) did you run it from the same machine/network where you run the actual installation script?)

The reason it works for you when you set IMAGE_VERSION to "latest" is because that causes the script to completely skip the step of going to the github API to get the version string.

You could try to download the script (save this http://git.io/getLatestKialiKubernetes script from your browser into a .bash file) and replace "2> /dev/null" on [line 171](https://github.com/kiali/kiali/blob/master/deploy/kubernetes/deploy-kiali-to-kubernetes.sh#L171) with something like "2> /tmp/github-error.txt" then run the script again and see what kind of error messages you get in that /tmp/github-error.txt file. Make sure you do this test on the same machine/network where you are seeing the failure.

In any event, that command executing on [lines 171-173](https://github.com/kiali/kiali/blob/master/deploy/kubernetes/deploy-kiali-to-kubernetes.sh#L171-L173) is failing for you. See if you can find out why that is. We have no other reports of this failing for anyone else, so I wonder if there is some local issue?

**Comment by jmazzitelli** [comment]
I'm reopening this because at minimum I want to spit out an error and exit the script if the github api returns no results (i.e. it cannot determine the latest release of kiali). Also need to fix that misspelling in the debug message  :}

**Comment by SeriyBg** [comment]
@jmazzitelli thanks. I will try to test it ASAP (but not today) and will post the results here

**Comment by pilhuhn** [comment]
@SeriyBg Any news? Can this be closed?

**Comment by SeriyBg** [comment]
@pilhuhn I guess so. For now, it seems fixed, thank you

**Comment by pilhuhn** [comment]
@SeriyBg Thanks for getting back.
