### ISSUE TITLE
Kiali federation with multiple Kubernetes flavors not able to access none OpenShift workloads/applications when running on OCP

### ISSUE THREAD

**Issue by michaelalang** [kiali/kiali#7665]
### Describe the bug

Using Kiali Federation to access multiple ServiceMesh (istio 1.20.8 and working) does not work showing (at least) applications information with the error

```
{"level":"trace","time":"2024-08-25T19:12:00Z","message":"Access to the server endpoint is not secured with credentials - letting request come in. Url: [https:///api/namespaces/ns8/apps/mockbin?rateInterval=60s&health=true&clusterName=west]"}
{"level":"error","time":"2024-08-25T19:12:00Z","message":"the server could not find the requested resource"}
{"level":"info","time":"2024-08-25T19:12:00Z","message":"Error fetching Namespaces for cluster [west]: projects.project.openshift.io is forbidden: User \"system:serviceaccount:kiali-access-ns:kiali-remote-access\" cannot list resource \"projects\" in API group \"project.openshift.io\" at the cluster scope"}
```

The error isn't ovious as vanilla Kubernetes systems do not have OpenShift specific CRD's like `Project` which seems to be not switched when running the Kiali instance handling the federation on OpenShift. 
The Kiali instance in the vanilla Kubernetes is working fine without any issues.

### Expected Behavior

Handling between various Kubernetes flavors should be consistent through federated clusters.

### What are the steps to reproduce this bug?

1. Install multi-primary on OpenShift and vanilla Kubernetes
2. Federate OCP and vanilla using OCP Kiali as federated instance
3. Select a vanilla Kubernetes resource

### Environment
*Learn about how to determine versions [here](
![kiali-multi-vendor-federation](https://github.com/user-attachments/assets/1fec30cb-6ed1-4c53-a8ed-21992e948fdf)
![kiali-multi-vendor-graph](https://github.com/user-attachments/assets/ba047fb4-cac5-4cfa-a630-f556d0a7b914)
![kiali-vanilla-application-error](https://github.com/user-attachments/assets/e4e4fc5b-1eb1-4880-a6bc-940cb910b026)).*

- **Kiali version:** 1.73.9 (but also verified with latest)
- **Istio version:** 1.20.8
- **Kubernetes impl:** OCP and Kind k8s
- **Kubernetes version:** OCP 4.14/4.16 and Kind 1.30
- **Other notable environmental factors:** multi-primary federated on OCP (CRD specifics as mentioned above)

**Comment by jmazzitelli** [comment]
```
{"level":"info","time":"2024-08-25T19:12:00Z","message":"Error fetching Namespaces
for cluster [west]: projects.project.openshift.io is forbidden: User
\"system:serviceaccount:kiali-access-ns:kiali-remote-access\" cannot list resource
\"projects\" in API group \"project.openshift.io\" at the cluster scope"}
```

I can explain some background here that might explain this.

When you install Kiali Server via the Kiali Operator, the Kiali Operator will look to see if it is running on OpenShift or not. if it is, it gives the Kiali Server permissions for OpenShift resources like Projects. See: https://github.com/kiali/kiali-operator/blob/master/roles/v1.73/kiali-deploy/templates/openshift/role-viewer.yaml#L73-L77

Of course, the permission is only going to be available to the Kiali Server on that host (where the Kiali Operator installed it) -- we call this the Kiali home cluster. That's where this Role (that is granting the Projects permission) and Service Account is, and what the Kiali client uses when it talks to the home cluster. The operator created this Role and SA on the home cluster.

BUT this is NOT the Role and SA that the client uses for the remote cluster obviously. To access the remote cluster, you must have the remote cluster secret created, and on the remote cluster you must have the Service Account and Role that Kiali will use. The remote cluster secret provides the kubeconfig that the Kiali client uses - it is how it talks to the remote cluster.

The ServiceAccount `system:serviceaccount:kiali-access-ns:kiali-remote-access` does not have the permission to see Projects on the "west" cluster. It looks like you used the Kiali script to create the remote cluster secret: https://github.com/kiali/kiali/blob/master/hack/istio/multicluster/kiali-prepare-remote-cluster.sh

So the question is - is that "west" cluster an OpenShift cluster or a vanilla k8s cluster? If it is an OpenShift cluster, you must run that script when you are connected to that OpenShift cluster so the helm chart can know to install the OpenShift specific templates for the Roles (so it gives you Projects access). If "west" is a plain vanilla cluster, then the problem lies inside the Kiali Server code somewhere - it is using the plain vanilla k8s cluster client but the Kiali Server thinks it is talking to an OpenShift cluster - hence it is asking for Projects when there isn't even a Projects API in the k8s cluster (let alone it has permissions to see it).

So that's the first question that needs to be answered - is your "west" cluster an OpenShift cluster or plain vanilla k8s cluster?

**Comment by michaelalang** [comment]
@jmazzitelli the remote Cluster is a vanilla Kubernetes and does not have the Project.openshift.io CRD at all so it's not a permission issue but a asking for a resource which isn't available at all. 
I did follow the federation guide and configuration resources are "accessible" to the home Kiali it fails on selecting the Workload/Application from the graph in details (works for an OCP federated Kiali, that might not be obvious but that's a three Cluster federation OCP <- OCP -> vanilla)
Sorry if I missed that information in the first run.

**Comment by nrfox** [comment]
This looks like just a bad assumption of the `NamespaceService`. When it first gets initialized it checks the home cluster to see if that is openshift: https://github.com/kiali/kiali/blob/d24f5bf7278922b7f07a07e5807ddcfedbbfa81d/business/namespaces.go#L58-L63

and then it assumes the rest of the clusters are also openshift: https://github.com/kiali/kiali/blob/d24f5bf7278922b7f07a07e5807ddcfedbbfa81d/business/namespaces.go#L318

A simple fix is to save this check per cluster when initializing the `NamespaceService`.

@jmazzitelli do we need to check projects at all? Can we just check namespace access for both vanilla and openshift?

**Comment by jshaughn** [comment]
I think the fix here will need backport to v1.73.  v1.89 is maybe useful for consistency in 3.0 TP1, but not required.

**Comment by jmazzitelli** [comment]
> do we need to check projects at all? Can we just check namespace access for both vanilla and openshift?

IIRC, the reason we look for Projects (as opposed to just looking for Namespace access) is because, unlike Namespaces, you a user CAN list all the projects the user can see, even if you only have GET. I don't remember the specifics, but I vaguely remember this. Getting a list of Projects didn't require the LIST permission is how I remember it.

**Comment by michaelalang** [comment]
Follow up to the issue. Faking the Project CRD into vanilla k8s makes Kiali able to access the `Application` details when browsing through the Graph on the vanilla k8s node. 
Another issue in that regards and related is that the `Mesh` Panel `Cluster` page does not list any `Network` value as Kiali seems to access the label value from the Project CR and not the Namespace CR.

```
# Empty Network in Kiali Mesh Cluster page
oc --context vanilla-k8s label namespace istio-system topology.istio.io/network=vanilla-k8s


# Working/Correct Network in Kiali Mesh Cluster page
oc --context vanilla-k8s label project istio-system  topology.istio.io/network=vanilla-k8s
```

Even though that is not a critical issue as it does not block mesh/graphing functionality but we should make the behavior equal between the various k8s flavours ...

**Comment by nrfox** [comment]
So running heterogeneous clusters will only be possible if all the clusters share the same authentication strategy. Kiali can only have one auth strategy at a time so you can't use `openshift` auth for the openshift cluster and then use `openid` for the vanilla kube cluster as an example. We can fix it so that `anonymous` mode works but the `openshift` auth strategy won't work for this setup. If the `oidc` strategy was supported on openshift clusters then this could work but multi-session auth has only been implemented for the `openshift` strategy and openshift clusters do not allow you to share kube API tokens across clusters.

**Comment by michaelalang** [comment]
@nrfox it is not related to the `auth strategy` as mentioned in my last comment, adding the `Project.openshift.io` CRD and manually creating the `Projects` accordingly works as expected and Kiali is able to access the Workloads/Appliacation resources correctly on a vanilla Kubernetes. It is related to what @jshaughn mentioned with if the Home Kiali is in OCP, it expects the Project CR's to be in all clusters ...
![kiali-vanilla](https://github.com/user-attachments/assets/09a1aef4-cff4-4d85-a485-8605e8e28674)

**Comment by nrfox** [comment]
@michaelalang yes you're right and #7710 should address that issue but only when Kiali is in `anonymous` mode like in the screenshot you posted. I just wanted to clarify that even after the fix, Kiali will only support running mixed clusters when the auth strategy is `anonymous` but it won't work for `openshift` or `openid` auth strategies.

**Comment by michaelalang** [comment]
thanks @nrfox ++ that's a really good note to write down for me :+1:

**Comment by jshaughn** [comment]
This is done for 3.0 TP and will not be backported to 2.x unless asked for.
