### ISSUE TITLE
[Multicluster] Pull the CA from the cluster and add that to the remote secret

### ISSUE THREAD

**Issue by nrfox** [kiali/kiali#7926]
### What do you want to improve?

The CA for the remote cluster can be pulled from the remote cluster and added to the remote secret automatically. The CA for the cluster should be present in the `kube-root-ca.crt` configmap which should exist in every namespace in the cluster. There's a conformance test for this so we can be pretty sure that this is reliable: https://github.com/kubernetes/kubernetes/blob/23e76432a9f2c602412d0d535fae4ac8d414d2ce/test/conformance/testdata/conformance.yaml#L1350-L1355.

This would negate the need for the `--allow-insecure` flag in the `kiali-prepare-remote-cluster` script.

**Comment by jmazzitelli** [comment]
Just so I'm clear on this.  When you say, `negate the need for the --allow-insecure`, I assume you are referring to the option `--allow-skip-tls-verify` [found here](https://github.com/kiali/kiali/blob/v2.1.0/hack/istio/multicluster/kiali-prepare-remote-cluster.sh#L439-L445)

The code block where all this CA stuff is done can be [found here](https://github.com/kiali/kiali/blob/v2.1.0/hack/istio/multicluster/kiali-prepare-remote-cluster.sh#L220-L250).

It is possible the kubeconfig explicitly declares `insecure-skip-tls-verify=true`, which the script does check (see [here](https://github.com/kiali/kiali/blob/v2.1.0/hack/istio/multicluster/kiali-prepare-remote-cluster.sh#L227)). In this case, I think it is fine for allowing insecure comm since the user themselves have that configured in their own kubeconfig.

However, if the kubeconfig does NOT define the CA bytes for whatever reason (see [here in the script](https://github.com/kiali/kiali/blob/v2.1.0/hack/istio/multicluster/kiali-prepare-remote-cluster.sh#L229) for when this is detected), then we could at that point look for this ConfigMap in the `${KIALI_CLUSTER_NAMESPACE}` namespace and pull the `ca.crt` data from it, and use that.

In addition, if the user DOES have that insecure flag set in their own kubeconfig but they tell our script NOT to allow for it (they pass in `--allow-skip-tls-verify=false`), that could be another place in the script we could change - if they user tells our script they do not want to allow skip (even though their own kubeconfig expicitly allows for it) then we could read the ca.crt ConfigMap in this instance too. That additional stuff would be done [in the code here](https://github.com/kiali/kiali/blob/v2.1.0/hack/istio/multicluster/kiali-prepare-remote-cluster.sh#L231).

Of course, we could completely ignore the kubeconfig setting and always pull the ConfigMap ca.crt (even if the user allows for insecure comm in their own kubeconfig) and just get rid of the  `--allow-skip-tls-verify` option - which was the point originally made, `This would negate the need for the --allow-insecure flag in the kiali-prepare-remote-cluster script.`

**Comment by nrfox** [comment]
> Of course, we could completely ignore the kubeconfig setting and always pull the ConfigMap ca.crt (even if the user allows for insecure comm in their own kubeconfig) and just get rid of the --allow-skip-tls-verify option - which was the point originally made, This would negate the need for the --allow-insecure flag in the kiali-prepare-remote-cluster script.

I think we should do this but maybe we should keep the `--allow-skip-tls-verify` option as an escape hatch?

**Comment by jmazzitelli** [comment]
> I think we should do this but maybe we should keep the `--allow-skip-tls-verify` option as an escape hatch?

OK, so here's what I think we can do.

1. Attempt to get the CA bytes from the user's kubeconfig. If we find it, we use it.
2. If, for whatever reason, we cannot find the CA bytes in the user's kubeconfig, we read it from the ConfigMap located in the remote cluster (that REMOTE_CLUSTER_NAMESPACE tells us where that is). If we find it, we use it.
3. If, for whatever reason, we cannot find the ConfigMap or the CA bytes in it, we abort.
4. As an escape hatch, before we even do step 1 (before we look for any CA anywhere), if the user told us `--allow-skip-tls-verify=true` then we forgo looking up any  CA bytes and in the remote secret we turn that on and do not supply any CA bytes.

**Comment by jmazzitelli** [comment]
and of course I just realized there is a bug in the PR that just got merged.

```
./hack/istio/multicluster/kiali-prepare-remote-cluster.sh --kiali-cluster-context east --remote-cluster-context west --remote-cluster-namespace istio-system --remote-cluster-name west --kiali-resource-name kiali --process-remote-resources false --allow-skip-tls-verify true
```

results in

```
./hack/istio/multicluster/kiali-prepare-remote-cluster.sh: line 256: remote_cluster_ca_bytes: unbound variable
```

We need to support that escape hatch, which right now does not work.

**Comment by jmazzitelli** [comment]
new PR that fixes the new bug: https://github.com/kiali/kiali/pull/7941

**Comment by jmazzitelli** [comment]
fixed.
