### ISSUE TITLE
Should Kiali track namespace deletion events and clear existing state?

### ISSUE THREAD

**Issue by kprabhak** [kiali/kiali#847]
After a namespace deletion event, and creation of a new namespace with the same name by a different user, Kiali still shows the service graph for the old (deleted) namespace together with the service graph for the new namespace.

I reckon this is not the desired behavior - thoughts?

**Comment by abonas** [comment]
Hi @kprabhak , thanks for opening this issue. This is an interesting use case.
Can you post an example screenshot of that duplicate graph?
What timeframe is the displayed graph configured for?
Since the graph is mostly generated from metrics stored in p8s by Istio, it sounds that since the "old namespace" metrics are still there, this is what causes this issue.
cc @jshaughn @jmazzitelli 
I think that on namespace deletion, those metrics should be deleted by Istio from p8s and that would solve the issue.

**Comment by jmazzitelli** [comment]
Just thinking briefly about this, I suspect there is nothing we can do because the Istio telemetry for both the old and new namespace will still exist in the backend telemetry storage in Prometheus. Kiali queries Prometheus and so will get this telemetry data - a mix of old and new namespaces. Because the namespaces have identical names, there is no way to distinguish between the two in Prometheus (e.g. the Prometheus labels that store the destination and source namespaces will have the same value with no way to distinguish that "this is an old namespace and this is a new namespace that happens to have the same name").

One thing you can do is tell Kiali not to graph some of the data by specifying a time range that omits the lifetime of the old namespace. But without having Istio delete or purge the telemetry data out of Prometheus, you will have this mixture of telemetry.

**Comment by abonas** [comment]
> One thing you can do is tell Kiali not to graph some of the data by specifying a time range that omits the lifetime of the old namespace. But without having Istio delete or purge the telemetry data out of Prometheus, you will have this mixture of telemetry.

@jmazzitelli that's why I was suggesting that perhaps Istio has to delete the telemetry when the namespace is deleted :)

**Comment by burmanm** [comment]
That may not be desired behavior for everyone. Reusing the same namespace names is probably not the intended use for namespace design. Otherwise they would probably include a randomized part in the internal structure like pods do.

**Comment by jotak** [comment]
Hmm... is it me who doesn't understand what we (should) have? See this task : https://issues.jboss.org/browse/KIALI-1714 ; we should already be discarding old metrics based on their "age". Or is it something that only works with openshift? (ie. looking at "Project" instead of namespaces for date info)

cc @israel-hdez

**Comment by lucasponce** [comment]
I guess that as p8s doesn't store namespace IDs, if I recreate namespace A, I will fetch metrics from old/new unless I know the exact timeframe to query.

Perhaps, good to propose in Istio telemetry to add namespace IDs.

**Comment by lucasponce** [comment]
I mean namespace IDs == UUID which is unique even if I could delete/create several ns under same name.

**Comment by jotak** [comment]
@lucasponce , the task / work I've linked above is supposed to discard old metrics, that is, restrict the query time frame to the current namespace/project creation timestamp.

**Comment by lucasponce** [comment]
Right; the task @israel-hdez implemented should fetch metrics based on namespace timestamp.
So in theory, old metrics shouldn't appear unless there is some cornercase in the logic.

**Comment by abonas** [comment]
> Right; the task @israel-hdez implemented should fetch metrics based on namespace timestamp.
> So in theory, old metrics shouldn't appear unless there is some cornercase in the logic.

The graph allows the user to select a timeframe. Does this mean that even if a user selects a "from" timestamp during the "old" metrics, it won't be displayed? Will the timeframe be adjusted in UI so users understand they can't view data older than X?

**Comment by jshaughn** [comment]
We don't query for data prior to the namespace creation time, so you will not see old traffic combined with new traffic.  But there is no way for us to remove existing time-series from Prometheus.  So, you will still get  time-series reported with 0 traffic.  I expect @kprabhak Is seeing old nodes with grey edges between them, indicating no traffic.   I'm not aware of a way to query for a time-series "create time" and so it's not possible to filter away the "old" time-series.   The best I can suggest at the moment is that you can use a Graph Hide expression to hide 0-traffic edges or nodes to clean up your graph, until such time as the old time series go away based on the retention setting.

**Comment by jshaughn** [comment]
FYI: There is an existing Jira for this topic: https://issues.jboss.org/browse/KIALI-2250

**Comment by israel-hdez** [comment]
> Or is it something that only works with openshift?

It should work both in Openshift ans Kubernetes

> Perhaps, good to propose in Istio telemetry to add namespace IDs.

We proposed this in the past. But when we say that we could filter metrics data based in creation timestamp, we didn't push forward that proposal. If wee need this, we could reconsider it.
