### ISSUE TITLE
Suddenly kiali auth is not working: Kiali secret missing

### ISSUE THREAD

**Issue by iftachsc** [kiali/kiali#894]
**General remarks**

after 49days of work kiali suddenly complains it cannot find secret kiali in its namespace.
the secret exists and just by yesterday we were working.

stdout log show kiali complains with the following:

W0306 07:26:58.124615       1 authentication.go:223] Token error: token is expired by 17h47m22s
W0306 07:26:59.828642       1 kiali.go:144] Kiali is missing a secret that contains both 'username' and 'passphrase'
W0306 07:27:09.829569       1 kiali.go:144] Kiali is missing a secret that contains both 'username' and 'passphrase'
W0306 07:27:19.830367       1 kiali.go:144] Kiali is missing a secret that contains both 'username' and 'passphrase'
W0306 07:27:29.831205       1 kiali.go:144] Kiali is missing a secret that contains both 'username' and 'passphrase'
W0306 07:27:32.708240       1 authentication.go:223] Token error: token is expired by 17h47m56s

UI looks like this:
![image](https://user-images.githubusercontent.com/28829551/53863189-2d877b80-3ff2-11e9-89d0-b3662e3f39b7.png)

i though maybe it related to the kubernetes ServiceAccount token jwt token so i deleted the kialia sa related token so it can be recreated, then delete pods and tried again on the new ones. didnthelp.

currently kiali is out of operation and its very inflecting us now because we are supposed to go prod in 2 weeks.

any help is highly appreciated.

**Versions used**
Kiali: 0.16
Istio: 1.0.3-gke.3
Kubernetes flavour and version:  1.11.7-gke.6

**To Reproduce**
i dunno

**Expected behavior**
shoudnt happen same way it didnt happen so far (1.5 monts)

**Comment by lucasponce** [comment]
Hi @iftachsc I understand that Kiali 0.16 means the latest snapshot or upstream ?
Could you show the details of the about related the commit info and we can investigate it ?
Thanks for reporting this issue.

**Comment by iftachsc** [comment]
thanks. so since i cannot login inside the only thing i can have is the image tag which is latest. i tried to get back to 0.15 but then ui shows initializtion error while logs say the same about token expiriation. i think this is related to this change 	KIALI-2380 Move kiali token to cookies (#877) which occuret 16 hours ago which is where we started to have issues. i think its not related to secret at all.

**Comment by lucasponce** [comment]
Restarting the kiali pod and accessing kiali UI from an anonymous browser (to ensure cookies are clean) helps in some way ? or does it show any different error ?

**Comment by iftachsc** [comment]
i never though kiali would be that urgent for us. but it is now. we are in the middle of load testings for going live soon. and in our current microservices arch we have requeswt depth that sometimes goes through 5 service in one request. kiali really helps us to find there 5.xx are coming from. we need it asap.

**Comment by iftachsc** [comment]
i tried incognito window and cleaning cookie but still the same. recreating new kiali secret in istio-system namespec with credentials and restarting pods didnt work. recreating k8s SA or its related secret (so token controller can create new jwt) didnt help. so i figure its not related to kubernetes at all.

**Comment by iftachsc** [comment]
ok rolled back to 0.15 and it is working again despite the stdout logs shows these:
W0306 08:16:57.945666       1 authentication.go:20] Token error: token is expired by 44h37m30s
W0306 08:17:07.004249       1 authentication.go:20] Token error: token is expired by 18h37m31s

**Comment by lucasponce** [comment]
Glad 0.15 worked for you and you are not blocked.
Note, that latest is pushed/updated on every new commit, new one is from this morning
https://hub.docker.com/r/kiali/kiali/tags
When you have some time and not in a hurry it would be good if we can investigate/reproduce your scenario.
If you can give it a try to confirm if the problem persist, we'll investigate further.
I understand that first problem happened on a long running session with more than 16h, correct ?

**Comment by iftachsc** [comment]
ill update to 0.16 again at the end of the day. and see if it happens again. sounds like if it can be related to anything it would be related to the last changes to the security part pushed 17+- hours ago.

**Comment by lucasponce** [comment]
Ok, thanks @iftachsc I think the team that worked on the tokens area will be online in some hours and they can investigate further too.
cc @jmazzitelli @israel-hdez

**Comment by iftachsc** [comment]
thank you appreciated. ill keep you updated.

**Comment by jmazzitelli** [comment]
When you say v0.16 - we don't have a 0.16 release yet. I assume you mean you are building or pulling in "latest"? There is a new deployment.yaml you have to use - you won't be able to pull in just images - you have to update the yaml for the current/latest code. This is also true for things like clusterrole.yaml, too, as changes are going into there as well (that is unrelated to the secret, but this is just a reminder to check that, too, if you are pulling in bleeding edge stuff).

The secret is now being mounted in a volume, not environment variable. This went in PR #883 - see [the deployment.yaml change](https://github.com/kiali/kiali/pull/883/files#diff-b796f97abd47659f713414f6ec48cef6) in that PR for what you'll need.

**Comment by iftachsc** [comment]
the image was with the latest tag. u r correct.
anyway we are now working properly on 0.15 and waits for 0.16 to come out.

thanks.

**Comment by garystafford** [comment]
I also ran into this issue with version 0.14 (deployed with Istio 1.1.2 Helm Chart) and 0.18 (the latest available release of kiali) on the latest GKE 1.12.6-gke.10. The version, 0.15, works as expected and finds the secret.

**Comment by jmazzitelli** [comment]
Just realize that you canNOT just change the image version and expect things to work. You HAVE to change the descriptor yaml because Kiali is looking for the secret in a different place now. See this PR for the changes that are required:
OpenShift: https://github.com/kiali/kiali/pull/883/files#diff-b796f97abd47659f713414f6ec48cef6
K8s: https://github.com/kiali/kiali/pull/883/files#diff-cbe6b632ae0a7103625b8e51b8757e7f

This means if you are installing via upstream Istio Helm charts, you canNOT just bump up the Kiali version and expect it to work because upstream Istio Helm charts have the old deployment yaml and thus not compatible with new Kiali versions.

FYI: with the new Kiali Operator, this should no longer be a problem. Because you will be using the operator version to match the kiali version you are installing - and the operator makes sure to configure the deployment properly for the version it is installing. See https://www.kiali.io/gettingstarted on how to install using the new Kiali Operator. The upstream Istio Helm charts should be upgraded soon to use the Kiali Operator.

**Comment by garystafford** [comment]
Thanks for the detailed explanation. So it sounds like there is/was a communication gap between the Istio project and the kiali project, in regards to the Helm Chart responsible for deploying Kiali, at least for the current Istio version(s).

**Comment by jmazzitelli** [comment]
No, as far as I can see, upstream Istio is fine. Here's the PR that went in upstream that took us to Kiali v0.16, and you can see the deployment.yaml changes were made in conjunction with moving up to 0.16:

https://github.com/istio/istio/commit/eb2ca5bc6eb7154695464591b63d4629695d5460#diff-94025c7c2b4beb94ee7f1a49ee588884

And here you can see the release-1.1 branch is still at 0.14 (the old way of working with secrets, so this didn't change): https://github.com/istio/istio/blob/release-1.1/install/kubernetes/helm/istio/charts/kiali/values.yaml#L7

There is a discussion in the istio PR (not merged yet) that is upgrading Kiali to Kiali 0.16 in Istio 1.1 and this issue came up:

https://github.com/istio/istio/pull/13097

So as far as I can see, the upstream Istio project looks ok.

**Comment by ricefice** [comment]
are you using anything like modheader?
