### ISSUE TITLE
Kiali installation on kubernetes without internet access

### ISSUE THREAD

**Issue by absc6** [kiali/kiali#960]
Hi Team,

I want to install Kiali on Istio 1.0.5 with K8 1.13.
k8 cluster is independent and does not use minikube or openshift and server does not have internet access.

Can you please provide steps for installation for above scenario.

Thanks

**Comment by jmazzitelli** [comment]
I will assume you are not installing Kiali with your Istio install (the istio helm charts has the ability to install Kiali - see the upstream Istio docs - you specifically need `--set kiali.enabled=true`).

We are currently developing a kubernetes operator for installing kiali that would support this. But its not done yet.

For now, what you will have to do is copy the install script along with the yaml files on your local machine and run the script (the script will use the yaml files if it finds them on the local machine).

So you want these: https://github.com/kiali/kiali/tree/v0.16/deploy/kubernetes

If you plan on using the optional Kiali dashboards, you will also need these: https://github.com/kiali/kiali/tree/v0.16/deploy/dashboards (the dashboards directory needs to be a peer to the kubernetes directory - the script requires that).

Of course, if you have no internet access, it means you can't even download the image from docker hub. So you will either somehow put the image in your docker daemon or build kiali yourself and use the make target that builds the docker image locally. That will require you to git clone this repo and run the make targets necessary to build the image. You will need to do this even when the operator is done because if you have no internet access, you cannot download the image from any public docker image repository.

**Comment by absc6** [comment]
Thanks, for the info.
Yes, we have a proxy server to download the images from docker hub.
