### ISSUE TITLE
Not seeing edges for kafka events

### ISSUE THREAD

**Issue by MathieuGi** [kiali/kiali#976]
Hello, 

I have some microservices communicating between each other using kafka events but these connections are not shown in kiali graph. Is there a way the take these events into account in kiali ?

thank you very much

**Comment by abonas** [comment]
Can you elaborate a bit more on your system?
kubernetes/openshift?
which version of Istio and Kiali?
Are sidecars injected properly?
Is any other type of communication between microservices showing?
What kind of communication are kafka events? (http/tcp/grpc etc.)
Are those events handled and reported to p8s correctly by Istio and only missing from Kiali UI?
thanks

**Comment by jmazzitelli** [comment]
I believe you need to get Istio to publish the telemetry for those kafka connections. I'm not sure Istio supports that in the telemetry (i.e. if you look in Prometheus, do you see kafka data for those connections in any timeseries?). Without publishing the telemetry, Istio won't be able to tell us anything about the kafka connections.

If there ARE kafka data in Prom, then Kiali would need to implement an enhancement to show this data.

**Comment by MathieuGi** [comment]
@abonas I'm using kubernetes 1.14 with istio 1.0.6 and kiali 0.12.0. Kafka events are using tcp and sidecars seems to be injected properly. Here is what I get in kiali UI
<img width="855" alt="Screen Shot 2019-04-04 at 13 53 55" src="https://user-images.githubusercontent.com/10846231/55553685-28951500-56e1-11e9-8f60-e7ea99fc7295.png">

@jmazzitelli That's interesting, I will take a look at these stuff and come back later if I still don't find anything

**Comment by MathieuGi** [comment]
Apparently prometheus seems to detect kafka events. When I search for : 

> istio_tcp_received_bytes_total{destination_service="kafka-broker"}

 I get 3 elements like this one for example:

> istio_tcp_received_bytes_total{connection_security_policy="unknown",destination_app="unknown",destination_principal="unknown",destination_service="kafka-broker",destination_service_name="kafka-broker",destination_service_namespace="default",destination_version="unknown",destination_workload="unknown",destination_workload_namespace="unknown",instance="172.17.0.10:42422",job="istio-mesh",reporter="source",source_app="conversation-service",source_principal="unknown",source_version="unknown",source_workload="conversation-service",source_workload_namespace="default"}

I tried some other stuffs but i'm still unable to see these kafka events in kiali

**Comment by jshaughn** [comment]
@MathieuGi The Kiali graph generates TCP topology using traffic telemetry in `istio_tcp_sent_bytes_total`, not `istio_tcp_received_bytes_total`.  It's surprising that there is only received telemetry, perhaps that is an issue with the kafka traffic handling, but it would explain why you don't see expected topology in the graph.

**Comment by MathieuGi** [comment]
I think I found why I don't see kafka's events in the kiali graph. The kafka-broker used as service for kafka is set up with clusterIP "none" so kafka is display on the graph but not the kafka-broker. As it is kafka-broker which receives the events kiali can't represent them on the graph.
I'm looking for a way to make kafka work without the clusterIP set to "none"

**Comment by abonas** [comment]
I think there might be some issues around headless services with tcp and Istio, I didn't dig deep though.
Check this:
https://github.com/istio/istio/issues/7558
https://github.com/istio/istio/issues/7495

**Comment by jotak** [comment]
I'm reopening this ticket because I'm having this issue as well. Same situation: seeing no IP on kafka browser service. Which might impact in turn the produced telemetry.

@MathieuGi , did you sort out the graph issue in Kiali?

However I think we can do something in Kiali.
The TCP metrics are actually present, and they do actually link a source workload/app with a destination service (kafka-broker), BUT the destination workload is "unknown" and I suspect this is why it's not displayed in graph?

See, it exists:
![Capture d’écran de 2020-01-17 18-12-13](https://user-images.githubusercontent.com/2153442/72631706-00676180-3955-11ea-96c4-09c385adf1c4.png)

@jshaughn I'm a bit surprised because I thought that the graph was able to show service nodes even when the workload is unknown. More importantly, the same issue exists in "service graph" mode. Maybe that's an issue only with TCP metrics but would work as intended with HTTP metrics?

**Comment by jotak** [comment]
I can try to look at it & inject some logs in graph generation, but I also take any insight that you can give graph experts :-)

**Comment by jshaughn** [comment]
@jotak Can you post the full time-series?  The screenshot above is clipped and I can't see the "reporter" or the source labels.  I'm assuming the reportr must be "source" but just to confirm as I don't immediately see why the service nodes would not show up.

**Comment by jotak** [comment]
I will post it asap, but yes it was certainly source reporting, 99% sure about that (there's no sidecar on brokers)

**Comment by jotak** [comment]
Here's the incriminated metric (and there's the same with tcp sent bytes)

`istio_tcp_received_bytes_total{connection_security_policy="unknown",destination_app="unknown",destination_principal="unknown",destination_service="my-cluster-kafka-brokers.kafka.svc.cluster.local",destination_service_name="my-cluster-kafka-brokers",destination_service_namespace="kafka",destination_version="unknown",destination_workload="unknown",destination_workload_namespace="unknown",instance="172.17.0.14:42422",job="istio-mesh",reporter="source",response_flags="-",source_app="ui",source_principal="unknown",source_version="v1",source_workload="ui",source_workload_namespace="default"}`

So, source reporter as we expected.

**Comment by jshaughn** [comment]
@jotak So I think what is happening here is that we filter out terminal service nodes unless they are useful for showing failed requests.  In other words, we want to show requests for a service that "failed to launch", but successful requests should not actually terminate at a service node, as they are expected to be handled by a workload.  We remove these because historically they have reflected bad/incomplete telemetry resulting during pod lifecycle changes.    The exception are service entries, which represent requests handled outside the mesh.

Here we have no destination workload, and so the telemetry produces a service node.  It is not a service entry.  And TCP requests don't carry status, so there are no failed requests.  We end up with a terminal service node with no request errors.  It is therefore classified as "dead" and filtered away.

So, What is is about the Kafka service that leaves the telemetry without a workload?  Also, which version of Istio are you using?

**Comment by jotak** [comment]
@jshaughn there is actually a workload for that service, it's named "my-cluster-kafka" (strimzi defaults), it apparently works fine, emitting & receiving messages as I would expect. I should add that it's deployed outside the mesh (in cluster).

![Capture d’écran de 2020-01-23 11-15-45](https://user-images.githubusercontent.com/2153442/72976277-988c9d00-3dd2-11ea-8781-a0158eeea7b5.png)

I've tried with and without service entry => in both cases kafka works (receive & send events) but telemetry is still missing the destination workload. (BTW, you said that "the exception are service entries", but it doesn't change anything for me...)

As @MathieuGi spotted and @abonas commented this is a headless service and maybe that could explain why it's handled differently in telemetry. I can open an issue in istio about that. But I wonder if we could do something in Kiali too, because the telemetry *is there* we just choose to ignore it. Do you think we could discriminate "good and bad" cases of "terminating service nodes", as you said they were historically removed on purpose?

BTW let me know if you want to reproduce with my scenario, there's a couple of steps.. working on minikube.

**Comment by jshaughn** [comment]
@jotak OK, so this must I guess have to do with headless service problems.  The headless service issues are a pretty big deal, I just spent 20 minutes going down that rat hole of issues.  I'm a little surprised the service entry approach didn't help but perhaps the SE definition wasn't quite right.  From reading about headless services it seems defining the SEs require to actually include the pod ips, not a very good thing to have to do.  I did see that there is an option for better handling of headless service/stateful sets.  Did you try enabling the option [in this PR](https://github.com/istio/istio/pull/16891/files)? 

On thing we could ask Istio is whether they could assign the destination to PassthroughCluster, or something like that, something other than unknown.

As for us trying to handle this, I'd be a little concerned to show these terminating services because of the aforementioned issues we've seen with incomplete telemetry.  But we could possibly add an option like, "show headless services" (off by default).  It may show things you don't want to see along with those that you do want to see.

**Comment by jshaughn** [comment]
@jotak I see you closed the PR around service entry handling,  I'm not sure but maybe that would have been useful.  I just don't know enough about the SE host matching.  We can wait, though, because no one else has yet to complain.

As for this issue, we should figure out a way to display headless services.

**Comment by jotak** [comment]
@jshaughn well, the two are related: if we put a service entry in front of headless services, then we can display it. Now what I'm unsure is if it is "hijacking" what service entry is, or if it makes sense anyway for Istio too (not just for Kiali)

**Comment by jshaughn** [comment]
> But it's worth noting that it doesn't make any difference for Istio (with default policies)

I think this is important.  It may only be true with global.outboundTrafficPolicy.mode=ALLOW_ANY (default).  If it's changed to REGISTRY_ONLY then I wonder if the Kafka requests succeed.  Do you know?  Something tells me that the headless service is handled differently than an external host because otherwise I would expect telemetry to show PassthroughCluster as the destination service (with ALLOW_ANY).  Of course there could be a telemetry issue and if REGISTRY_ONLY rejects the Kafka requests then I think there would be a definite case for a telemetry problem.

Excluding Istio from the equation, Kiali today can report these requests if we don't run the DeadNode appender.  We could add a display option (or possibly just a config setting) that could alter the appender and not filter these headless service nodes.

**Comment by jotak** [comment]
I would like to have the option of bypassing the dead node appender. However we must take care to not overcomplicate the UX for more standard use cases.

What about having the dead node appender not removing the node, but flagging it so that on UI side we can give the option to display it _only if there's one at least_ ? So that in the standard case, where there's no dead node, we don't show this option as it could look cryptic for most users.

**Comment by jotak** [comment]
Or actually maybe as you say, as a config setting, it would be fine as well

**Comment by jshaughn** [comment]
Part of Epic: #2197

**Comment by iainduncani** [comment]
We run Elasticsearch as a headless service and see exactly the same as described here: telematary data available in Prometheus but with some fields `"unkown"` and the cluster works even with `global.outboundTrafficPolicy.mode=REGISTRY_ONLY` but the connection not appearing on Kiali.

**Comment by jotak** [comment]
@iainduncani which version of Istio do you use?
At the moment, if you need a workaround you could define a Service Entry for ES, which should make Kiali showing these connections.
And we're still thinking about a solution for this partial telemetry.

**Comment by iainduncani** [comment]
@jotak we are on version 1.4.6 of Istio at the moment.  Thanks for the tip with the workaround, I think we can live with it for now not appearing in Kiali and wait for the fix to come in.
